### ISSUE TITLE
Move innerHTML etc to Element

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#100]
<a href="https://github.com/arv"><img src="https://avatars.githubusercontent.com/u/45845?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arv](https://github.com/arv)**
_Thursday Oct 31, 2013 at 16:46 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/290_

---

innerHTML, outerHTML and inserAdjacentHTML were moved to Element.

http://domparsing.spec.whatwg.org/#extensions-to-the-element-interface

**Comment by TimvdLippe** [comment]
This has been fixed with https://github.com/webcomponents/custom-elements/blob/master/src/Patch/Element.js
