### ISSUE TITLE
[BUG] Webcomponentjs breaks Symbol.iterator

### ISSUE THREAD

**Issue by ruphin** [webcomponents/webcomponentsjs#1000]
After loading `webcomponents-bundle.js` the native `Symbol.iterator` is broken. This bug is introduced in version 2.1.0.

Minimal reproduction: https://codepen.io/ruphin/pen/XPzYBr?editors=1000

**Comment by TimvdLippe** [comment]
I think this is the same issue as #998

**Comment by yuanyan** [comment]
The some issue for me.

Should detect first.

**Comment by tirithen** [comment]
Also seeing this issue

**Comment by ruphin** [comment]
It is probably the same issue as #998 - but your analysis that the problem is with `reflect-metadata` is certainly wrong @TimvdLippe. 

Take a look at my reproduction. It doesn't load any code other than webcomponentsjs straight from npm. The problem is certainly with webcomponentsjs.

**Comment by ruphin** [comment]
The problem was introduced in [this commit](https://github.com/webcomponents/webcomponentsjs/commit/e5c5de331958093ae5dfe00e2d616f5fa0220cf7#diff-a1352760113112ec3b38ee51f9dc1892) 

The polyfill library `polyfill-library` that you are using does not conditionally polyfill. This library has separate `detect.js` files that check if the polyfill should be loaded. The main polyfills do not perform any checks and force execute the polyfill, overriding the native implementation.

You cannot use this polyfill the way it is used now.

**Comment by ruphin** [comment]
I will take a look at it today

**Comment by ruphin** [comment]
The architecture of `polyfill-library` makes it pretty unusable in a browser directly. `detect.js` is nothing but a line of javascript that returns a boolean that indicates if the polyfill should be loaded or not. The only way we can use it is by inlining the polyfill in our own files.

I am looking into using the core-js polyfills for Symbol

**Comment by ruphin** [comment]
Core-js is somewhat awkward to use to polyfill a single item.

Most promising right now seems to use this: https://github.com/es-shims/get-own-property-symbols
The `polyfill-library` polyfill for Symbol is based on that, but the original does include checks to use the native versions when available.
