### ISSUE TITLE
Static Code Analysis Findings

### ISSUE THREAD

**Issue by codeanalysis9876** [webcomponents/webcomponentsjs#1002]
Cross-Site Request   Forgery - At Line: 16 of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi.js
--
JavaScript Hijacking - At Line: 16 of   File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi.js
Cross-Site Request Forgery - At Line: 16   of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-ce.js
JavaScript Hijacking - At Line: 16 of   File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-ce.js
Cross-Site Request Forgery - At Line: 19   of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd.js
JavaScript Hijacking - At Line: 19 of   File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd.js
Cross-Site Request Forgery - At Line: 102   of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js
Cross-Site Request Forgery - At Line: 103   of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js
Cross-Site Request Forgery - At Line: 19   of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js
JavaScript Hijacking: Vulnerable   Framework - At Line: 102 of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js
JavaScript Hijacking: Vulnerable   Framework - At Line: 103 of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js
JavaScript Hijacking - At Line: 19 of   File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js
Insecure Randomness - At Line: 28 of   File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-lite.js
Cross-Site Request Forgery - At Line: 47   of File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-lite.js
JavaScript Hijacking - At Line: 47 of   File:   frontend/src/static/bower_components/webcomponentsjs/webcomponents-lite.js

**Comment by TimvdLippe** [comment]
We no longer publish to Bower, so you probably ran the analysis on an old version.
