### ISSUE TITLE
Can't load component on IE11 nor Edge

### ISSUE THREAD

**Issue by lemoustachiste** [webcomponents/webcomponentsjs#1003]
Hi, 

I have a webcomponent written with Polymer 3. When using `polymer serve` and I can load it seamlessly in IE11 and Edge.

I made a build of the component with `rollup`, and then a basic HTML as follows:
```html
  <script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
  <script type="module" src="node_modules/my-component/dist/build.js"></script>
```

In that case I manage to load the component in FF, Chrome and Safari, but Edge and IE11 remain blank.

IE11 does not produce an error, but does not nothing.
Edge mentions an error:
```
  SCRIPT5022: Expected identifier, String or Number
```

When I click on the error, this is what I can see:
<img width="859" alt="screen shot 2018-09-12 at 18 42 47" src="https://user-images.githubusercontent.com/12797962/45440742-66870900-b6bd-11e8-8161-3b0482468ad8.png">

I tried using `polymer build` but that only produced different errors. I also tried targetting IE11 in my rollup babel config, but that prevented loading in Chrome and didn't change IE11's behaviour.

This is my first time dealing with webcomponents and I am not sure what to do from there. Is this an issue (an actual bug) with this library, Polymer, or the way I build the component?

Thanks for any help that could take me back on the happy path

**Comment by lemoustachiste** [comment]
I have managed to fix the problem on MS Edge, which was due to untranspiled code coming from Polymer.

However IE11 just fails silently.

**Comment by TimvdLippe** [comment]
Sadly it is not possible for us to debug your issue without a reproduction case like a JSBin. This issue is likely related to serving untranspiled code to IE11. Note that `polymer serve` is only intended for development purposes. In your production environment, you should serve the build output as generated by `polymer build`.

If you are still unsure how to proceed, feel free to ask other Polymer developers in [The Polymer Slack](http://polymer-slack.herokuapp.com/) who will be happy to help you out!

**Comment by lemoustachiste** [comment]
Yeah I figured IE11 but forgot to come back to this issue. It was missing the `es5-to-es6` adapter script.

thanks

**Comment by hellokatili** [comment]
@lemoustachiste I have the same issue. Which es5-to-es6 adapter script do you mean?

**Comment by lemoustachiste** [comment]
@hellokatili I think that should be this one:
`<script src="../node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>`

**Comment by hellokatili** [comment]
@lemoustachiste I updated the `polymer.json` so that the script is included and loaded. But the app still does not load. Do you have any idea what is missing? I've got no errors in the console.

**Comment by hellokatili** [comment]
@lemoustachiste Or do you know which webcomponentsjs version you used?

**Comment by hellokatili** [comment]
It works when I remove the `fragments` array from `polymer.json`...
