### ISSUE TITLE
new Comment/Text/DocumentFragment constructors doesn't work

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#101]
<a href="https://github.com/jmesserly"><img src="https://avatars.githubusercontent.com/u/1081711?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jmesserly](https://github.com/jmesserly)**
_Friday Nov 01, 2013 at 21:54 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/293_

---

this works in normal JS, hits an "assertion failed" with polyfill:

``` js
document.body.appendChild(new Comment('hello world'));
```

see also http://dom.spec.whatwg.org/#comment

**Comment by TimvdLippe** [comment]
This has been fixed: http://jsbin.com/mosakol/edit?html,console,output
