### ISSUE TITLE
:host styling does not seem to work on Firefox 62

### ISSUE THREAD

**Issue by gotcha** [webcomponents/webcomponentsjs#1010]
With the code below, the `Debug` text is displayed as red text on blue background in Chrome or Safari.

However, it is displayed as black test on blue background in Firefox 62.0 on MacOS.

A I missing something ?

```
<html>
    <head>
        <script type="text/javascript" src="https://unpkg.com/@webcomponents/webcomponentsjs@2.1.3/webcomponents-bundle.js"></script>
        <script type="text/javascript" >
        window.onload = function() {
        class MyDebug extends HTMLElement {
        constructor() {
            super()

            let shadowRoot = this.attachShadow({mode: "open"})

            shadowRoot.innerHTML = `
                <style>
                     :host { color: red; }
                     p { background-color: blue }
                </style>
                <p>Debug</p>
            `
          }
        }
        window.customElements.define('my-debug', MyDebug)
        }
        </script>
    </head>
    <body>
        <my-debug></my-debug>
    </body>
</html>
```

**Comment by web-padawan** [comment]
It is not expected to be working that way. See the docs here for usage example:
https://github.com/webcomponents/shadycss#usage

**Comment by TimvdLippe** [comment]
@web-padawan is correct. This is a working in example in Firefox and Chrome: http://jsbin.com/dehimeqipo/edit?html,output

**Comment by gotcha** [comment]
@web-padawan @TimvdLippe Thanks for your answers.

I had read through all this but failed to understand that only :host styling would be broken.

As the rest of the styling of my component was applied, I did not think that the ShadyCSS dance was needed.

In other words, it might be useful to state more explicitely which parts of styling do not work without ShadyCSS.

**Comment by TimvdLippe** [comment]
In your specific example it worked out like this, as `:host` is something specific to shadow dom and older browsers do not understand that. Since the `p` selector is a regular selector, you were seeing the blue background. If you used any other features of shadow dom styling (like `::slotted`), you would have seen the same result. E.g. shadow dom styling not working at all, tainting your whole website.

**Comment by TimvdLippe** [comment]
@gotcha Thank you for the write up! It is very much appreciated to have another point of view of someone new to web components. Feel free to open a PR which clarifies the wording such that you would have instantly understood what to do :smile:

**Comment by gotcha** [comment]
Done ! #1011
