### ISSUE TITLE
Support customized built-in elements 

### ISSUE THREAD

**Issue by asbachb** [webcomponents/webcomponentsjs#1027]
Specification: https://html.spec.whatwg.org/multipage/custom-elements.html#customized-built-in-element
Validation indicator: https://jsbin.com/saxatutave/1/edit?html,console,output

Works on Chromium Version 69.0.3497.100
Does not work on Firefox 62.0.2

**Comment by web-padawan** [comment]
See webcomponents/custom-elements#88

**Comment by TimvdLippe** [comment]
Closing this as duplicate of https://github.com/webcomponents/custom-elements/issues/13 which the above linked PR is subjected to fix.
