### ISSUE TITLE
Should define launchpad browsers to reduce wct startup time

### ISSUE THREAD

**Issue by attilapuskas** [webcomponents/webcomponentsjs#1037]
_This is rather a feature request and not a bug ticket._

Without using a LAUNCHPAD_BROWSERS env parameter or a defined "browsers" in the wct.conf.json the startup time of the _wct_ is really slow. (already discussed the reason for example [here](https://github.com/Polymer/web-component-tester/issues/169), the config is mentioned [here](https://github.com/bitovi/launchpad#environment-variables-impacting-local-browsers-detection) & [there](https://github.com/Polymer/tools/tree/master/packages/web-component-tester#configuration))

I think it would be a quite a huge performance improvement to configure the relevant browsers in the already existing wct.conf.json files for all webcomponents/* repositories.

**Comment by azakus** [comment]
wct detects which browsers you have available. Hardcoding `LAUNCHPAD_BROWSERS` would make that not work correctly, or try to launch Safari on a Windows machine, etc.
