### ISSUE TITLE
addEventListener always adds events in capturing phase whenever any options object is used (IE11 and Edge)

### ISSUE THREAD

**Issue by cjwainwright** [webcomponents/webcomponentsjs#1038]
When calling `addEventListener` and passing an options object as the final argument, the event is always added in the capturing phase in IE11 and Edge.

A simple reproduction is here:
https://jsbin.com/catufuwuze/1/edit?html,console,output

Click on the inner element and notice the order of the events logged and the event phase.

In IE and Edge you can see the events are incorrectly called from outside in, and in the capturing phase.
![image](https://user-images.githubusercontent.com/1623948/47222916-de78db00-d3af-11e8-8d19-72edc705847f.png)

In Chrome the events are correctly called from the inside out and in the bubbling phase:
![image](https://user-images.githubusercontent.com/1623948/47222852-b0939680-d3af-11e8-8137-530d391ece7a.png)

Note, this importantly also affects adding event handlers directly with e.g. `element.onmousedown`, as this seems to call `addEventListener` method with an empty options object.

It works correctly if no options object is passed.

**Comment by cjwainwright** [comment]
This issue is in version 2.1.3

**Comment by TimvdLippe** [comment]
This should be fixed in https://github.com/webcomponents/shadydom/commit/5621b9f3264fd2f276ca926c4713dbdcbb328441 Please reopen if it is still an issue.
