### ISSUE TITLE
Contenteditable elements do not trigger MutationObserver

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#104]
<a href="https://github.com/azakus"><img src="https://avatars.githubusercontent.com/u/46725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [azakus](https://github.com/azakus)**
_Wednesday Feb 05, 2014 at 00:05 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/374_

----

Example: http://jsfiddle.net/x8dKv/
[Mailing list link](https://groups.google.com/forum/#!msg/polymer-dev/LHdtRVXXVsA/v1sGoiTYWUkJ)

I assume this is fallout from reimplementing MutationObservers internally.
Perhaps we could listen for "input" events and schedule a Mutation that way.

**Comment by garlicnation** [comment]
Captured this in #231.
