### ISSUE TITLE
Problem with HTML Import on Ios 12

### ISSUE THREAD

**Issue by jokamax** [webcomponents/webcomponentsjs#1040]
Hi,

I have a problem with the new ios : ios 12 and HTML Import
(OK for other Ios version and system/browser).
I use webcomponentsjs v1.2.7

This is my code : 

Html : 
`<link href="/static/creaentry.html" rel="import">`

Detection : 
```
(function() {
  if ("registerElement" in document
      && "import" in document.createElement("link")
      && "content" in document.createElement("template")) {
    //console.log("IMPORT - plateforme OK");
  } else {
    // polyfill the platform!
    var e = document.createElement("script");
    e.src = $("#baseUrl").val() + "/modext/webcomponents/webcomponents-hi.js";
    document.body.appendChild(e);
  }
})();
```

Use : 
```
var link = document.querySelector('link[href$="' + filename + '"]');
var err_mess = "";
if(isEmpty(link)) {
     // OK - Link not empty. Next
}
var content = link.import;
if(isEmpty(content)) {
     // throw ERROR
}
```

On IOS12 and only IOS 12 (I think) : link.import is empty or undefined.

Can you help me ?

**Comment by TimvdLippe** [comment]
There could be many reasons for this and I fear it is hard for us to debug this issue. In any case, I would recommend upgrading to ES modules instead, as HTML imports are deprecated.
