### ISSUE TITLE
Consider using code gen

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#105]
<a href="https://github.com/arv"><img src="https://avatars.githubusercontent.com/u/45845?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arv](https://github.com/arv)**
_Friday Feb 21, 2014 at 19:36 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/379_

----

Most of the wrappers are created using reflection. However, every webidl method and attribute that takes or returns a wrapper requires manual code.

One option would be to generate the code for these at build time by reading the webidl file.

**Comment by garlicnation** [comment]
Closing this as stale. Might be worth revisiting in the future.
