### ISSUE TITLE
How to utilize web component in react?

### ISSUE THREAD

**Issue by PrasannaBrabourame** [webcomponents/webcomponentsjs#1051]
How to utilize web component in react?

**Comment by web-padawan** [comment]
We have an example using Create React App 2.0: https://github.com/vaadin/base-starter-react

There are few things requiring extra steps:

1. You need to configure build properly (especially, tweak Babel to transpile dependencies, as in React ecosystem it's not yet widely adopted).
2. React doesn't play well with object and array properties and custom events, see https://custom-elements-everywhere.com/#react

**Comment by TimvdLippe** [comment]
Closing per the above comment (amazing explanation by @web-padawan again :smile: )
