### ISSUE TITLE
Lighthouse says 'Does not use passive listeners to improve scrolling performance' for webcomponents-lite.js 

### ISSUE THREAD

**Issue by grvsooryen** [webcomponents/webcomponentsjs#1052]
I am working on lighthouse best practices of the website and while conducting the audit tests, I get the following error. 
![image](https://user-images.githubusercontent.com/16348876/49087742-cda86880-f27d-11e8-877f-55b5e8ab190d.png)

The version is 1.0.17

**Comment by TimvdLippe** [comment]
Could you post the full stacktrace? It is unclear to me what line is throwing this exception.

**Comment by grvsooryen** [comment]
In best practices I am not getting the trace option. I just shows line number 74 of version 1.0.17. Here is complete best practice overview
![image](https://user-images.githubusercontent.com/16348876/49089029-a3a47580-f280-11e8-9303-008399d01ad3.png)

I have already use passive mode in polymer: `Polymer.setPassiveTouchGestures(true)` but it doesn't work: https://github.com/Polymer/polymer/issues/4847

**Comment by TimvdLippe** [comment]
Could you update version 2.x.x and see if that resolves it? It is quite hard for us to debug this issue without a reproduction case.

**Comment by azakus** [comment]
This shows up as webcomponents because it patches all event listeners for Shadow DOM scoping. This is likely a Polymer issue with setPassiveTouchGestures, or a touch listener in your own code.
