### ISSUE TITLE
webcomponents-loader.js required folders and files are not included after a polymer build

### ISSUE THREAD

**Issue by Fausto-theXS** [webcomponents/webcomponentsjs#1053]
It's so trivial that I should be missing something

I installed and saved it in the package.json
`npm i -S @webcomponents/webcomponentsjs
`

And the index.html uses it
`<script src="@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
`

Then I build the project from the terminal
`polymer build
`

But, the production folder 
`./build/default/node_modules/@webcomponents/webcomponentsjs
`

Does not includes the required folders and files for webcomponents-loader.js
Like bundles and entrypoints 
That folder only has the webcomponents-loader.js

What am I missing?

Thanks in advance

**Comment by TimvdLippe** [comment]
You have to specify the `extraDependencies`: https://polymer-library.polymer-project.org/3.0/docs/tools/polymer-json#extradependencies

**Comment by Fausto-theXS** [comment]
Thanks a lot!!

I knew it was trivial, one of those hard to find though ... for me.
