### ISSUE TITLE
WebComponents.waitFor() runs twice for async/no-polyfill cases

### ISSUE THREAD

**Issue by zerodevx** [webcomponents/webcomponentsjs#1056]
Hello! According to the README, we are promised that

>The WebComponents.waitFor function takes a callback function as an argument, and will **EVALUATE** that callback **AFTER** the polyfill bundle has been loaded. (emphasis added)

`webcomponents-loader` is designed to handle 4 cases, namely:
1. sync and polyfills needed;
2. sync and no polyfills needed;
3. async and polyfills needed;
4. and async and no polyfills needed.

For case (4), the callback function is actually run twice. This happens for the latest Chrome and FF (v71 and v64 respectively) - FF doesn't require polyfills now that HTMLImports is deprecated. So something like:

```html
<script defer src="https://unpkg.com/@webcomponents/webcomponentsjs@2.2.0/webcomponents-loader.js"></script>

<script type="module">
  WebComponents.waitFor(() => {
    // We want to batch code that requires CE polyfill here so that 
    // polyfillWrapFlushCallback() upgrades all CEs together.
    // But cb actually runs twice for fully speced browsers.
    ...
  });
</script>
```

actually runs the callback twice for compliant browsers.

Here is a super minimal repro: https://jsbin.com/decoreqapo/edit?html,console

Looking deeper into the code, I thought there might be some issues with the implementation. Let me try to be as coherent as I can.

**1. Race condition introduced by runWhenLoadedFns()**

Referencing:

https://github.com/webcomponents/webcomponentsjs/blob/81beb06a05fa3f9c6cc92012b32abb723ad8edb2/webcomponents-loader.js#L77-L91

the `whenLoadedFns` array is cleared **after** its Promise resolves. 

https://github.com/webcomponents/webcomponentsjs/blob/81beb06a05fa3f9c6cc92012b32abb723ad8edb2/webcomponents-loader.js#L81

What probably should happen is it should be cleared **before**, so that if this method is called again before its Promise resolves, evaluation of the functions array wouldn't be repeated. Perhaps this method could be refactored into something like:

```js
  function runWhenLoadedFns() {
    allowUpgrades = false;
    var fnsMap = whenLoadedFns.map(function(fn) {
      return fn instanceof Function ? fn() : fn;
    });
    whenLoadedFns = []; //let GC handle this (ref: https://jsperf.com/array-destroy)
    return Promise.all(fnsMap).then(function() {
      allowUpgrades = true;
      flushFn && flushFn();
    }).catch(function(err) {
      console.error(err);
    });
  }
```

Which leads me to the next issue:

**2. runWhenLoadedFns() is called twice**

TBH I'm not sure if this is intended by design or not. Based on current implementation, for compliant browsers where no polyfills are needed, this block runs.

https://github.com/webcomponents/webcomponentsjs/blob/81beb06a05fa3f9c6cc92012b32abb723ad8edb2/webcomponents-loader.js#L172-L184

The `polyfillsLoaded` flag is asserted right after the browser passes all feature-detection tests. Therefore, referencing `waitFor()` function definition, 

https://github.com/webcomponents/webcomponentsjs/blob/81beb06a05fa3f9c6cc92012b32abb723ad8edb2/webcomponents-loader.js#L95-L103

the flag is `true` and hence `runWhenLoadedFns()` is immediately run when the `WebComponents.waitFor(() => {...})` script is declared. 

However, `runWhenLoadedFns()` is called again via the `ready()` method upon `DOMContentLoaded` event, and before its first call resolves, here:

https://github.com/webcomponents/webcomponentsjs/blob/81beb06a05fa3f9c6cc92012b32abb723ad8edb2/webcomponents-loader.js#L179-L182

This is essentially why the `waitFor()` callback gets evaluated twice for spec-compliant browsers when used asynchronously.

**3. Flow for handling no-polyfill cases seems incorrect**

The current implementation handles no-polyfill cases like this:
* sync - wait for DCL event, run `waitFor()` cbs, then fire WCR.
* async - just fire WCR.

This seems wrong - firstly, async cases would typically have `waitFor()` defined, while sync cases wouldn't, so the implementation got that backwards. Secondly, if we are by design setting `polyfillsLoaded` to true right after the browser passes feature tests over here:

https://github.com/webcomponents/webcomponentsjs/blob/81beb06a05fa3f9c6cc92012b32abb723ad8edb2/webcomponents-loader.js#L173

then there isn't a need to handle anything special except fire the WCR event to indicate that the CEs have been defined.

My apologies that this post got a bit longer than intended - just hoping to seek some clarifications. Thanks!

**Comment by TimvdLippe** [comment]
This is a very detailed bug report, thanks! I can reproduce the issue and it is indeed racy, because sometimes it just works fine. Do you mind opening a PR and adding an appropriate regression test with it?
