### ISSUE TITLE
TypeError: Invalid calling object when manipulating document

### ISSUE THREAD

**Issue by jarrodek** [webcomponents/webcomponentsjs#1057]
The issues can be reproduced with version 1.3.0. I didn't try versions 2.x.x as I am still working on previous version.

When the `webcomponents-loader.js` or `webcomponents-lite.js` library is loaded the following code throws an error in Edge (others seems to work just fine, IE not tested).

```javascript
const doc = document.implementation.createDocument('', '', null);
const main = doc.createElement('child-element');
doc.appendChild(main);
```
The error:

```
TypeError: Invalid calling object
   at isConnected.get (http://127.0.0.1:8081/components/webcomponentsjs/webcomponents-lite.js:157:174)
   at J (http://127.0.0.1:8081/components/webcomponentsjs/webcomponents-lite.js:164:723)
   at Anonymous function (http://127.0.0.1:8081/components/webcomponentsjs/webcomponents-lite.js:183:373)
   at load (http://127.0.0.1:8081/components/api-example-generator/demo/issue.html:39:7)
```

See the following gist for full example: https://gist.github.com/jarrodek/aba67f64ed8df89cccfe8a509b58f0d1#file-webcomponentsjs-error-html

This can be avoided by slightly changing the implementation but in my case it means a lot of additional work.

```javascript
const doc = document.implementation.createDocument('', 'child-element', null);
const main = doc.createElement('other-child');
doc.documentElement.appendChild(main);
```

**Comment by TimvdLippe** [comment]
Still reproducible with 2.x.x: https://jsbin.com/nuxupurolu/edit?html,console,output Custom elements polyfill seems to be the culprit, as only the `sd` bundle works just fine.

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/custom-elements#181
