### ISSUE TITLE
Loader is not loading ShadyCSS on time (or not at all?)

### ISSUE THREAD

**Issue by tpluscode** [webcomponents/webcomponentsjs#1060]
Please check this snippet, running [here](https://stackblitz.com/edit/js-izsvsg?file=index.html)

```html
<script src="./node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>

<script>
WebComponents.waitFor(function () {
  document.write(`ShadyCSS is ${window.ShadyCSS}`)
});
</script>
```

## Actual

It writes `ShadyCSS is undefined`.

## Expected

ShadyCSS should be ready when loader does its thing.

## Workaround

Use `webcomponents-bundle.js` instead.

**Comment by TimvdLippe** [comment]
ShadyCSS is not loaded on browsers that do not need it. E.g. it will not be there on Safari, Chrome and Firefox. Which browser are you using?

**Comment by tpluscode** [comment]
Indeed, Safari and Chrome.

Here's the twist though: ShadyCSS is indeed needed to get apply-shim working in lit-html. 

In my case I have lit-elements and Polymer elements. Effectively Polymer does load the apply-shim eventually but there is this one line in lit https://github.com/Polymer/lit-html/blob/master/src/lib/shady-render.ts#L45 which effectively disable CSS mixin support if ShadyCSS is not present at the very beginning.

Yes, I know that CSS mixins are deprecated and will go away but until there is a workable alternative, I'd like to keep using them.

**Comment by TimvdLippe** [comment]
If you want to use CSS mixins, you would need to force include ShadyCSS for these browsers. Paging @justinfagnani for his 2 cents.

**Comment by azakus** [comment]
ApplyShim is not loaded with webcomponentsjs, but separately from `@webcomponents/shadycss/apply-shim.min.js`
