### ISSUE TITLE
is `Node.isConnected` defined in any of these polyfills?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#1065]
Is [`Node.isConnected`](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected#Browser_compatibility) covered in any of these polyfills?

I've got custom elements that check `isConnected`, and want to know if that works with the polyfilled custom-elements.

**Comment by TimvdLippe** [comment]
Yes it is with ShadyDOM: https://github.com/webcomponents/shadydom/blob/e3471cf4461328e0e97afb4d2e5743e7d3d9d934/src/patches/Node.js#L160-L184

**Comment by trusktr** [comment]
Nice, thanks!

**Comment by trusktr** [comment]
@TimvdLippe 

On these lines,

https://github.com/webcomponents/shadydom/blob/e3471cf4461328e0e97afb4d2e5743e7d3d9d934/src/patches/Node.js#L162-L164

shouldn't it be

```js
    if (nativeIsConnected) {
      return nativeIsConnected.call(this);
    }
```

?
