### ISSUE TITLE
[HTMLImports] WrongDocumentError in IE11 if document.domain has been changed

### ISSUE THREAD

**Issue by Tronil** [webcomponents/webcomponentsjs#1068]
If document.domain has been changed we get a WrongDocumentError in IE11 when attempting to import a component. It seems that this is caused by the Document returned from document.implementation.createHTMLDocument having a different domain.

I have tracked down one issue to the template polyfill, but the same technique may be used in other webcomponents polyfills.

We have added this hack to get it to work for now:
```
    var capturedCreateHTMLDocument = DOMImplementation.prototype.createHTMLDocument;
        DOMImplementation.prototype.createHTMLDocument = function() {
            var newDocument = capturedCreateHTMLDocument.apply(this, arguments);
            if (newDocument.domain !== document.domain)
            {
                newDocument.domain = document.domain;
            }
            return newDocument;
        };
```
However, this still assumes that the document.domain will not be changed *after* createHTMLDocument is called. There probably needs to be a check on the domain whenever elements are created or added to the DOM for it to be robust.

**Comment by azakus** [comment]
Unfortunately, HTML Imports is deprecated, and will be removed from Chrome at some point. We suggest you transition to ES Modules, which are supported natively in Chrome, Safari, Firefox, and the new Edge browser.
