### ISSUE TITLE
HTMLElement.getRootNode() not available in IE11

### ISSUE THREAD

**Issue by SetTrend** [webcomponents/webcomponentsjs#1072]
The `HTMLElement.getRootNode()` function and, consequentially, the `HTMLElement.getRootNode().host` property don't seem available through webcomponentsjs in IE11.

Would you mind adding support for this functionality?

The TypeScript declaration for this function would be:

```ts
function getRootNode() : Node {return ... ;}
```

Where `Node` can be [ShadowRoot, Document, HTMLDocument, SVGDocument, or similar](/whatwg/dom/issues/739#issuecomment-474647270).

**Comment by CITguy** [comment]
The `shadydom` polyfill patches [`Node.getRootNode()`](https://github.com/webcomponents/polyfills/blob/master/packages/shadydom/src/patches/Node.js#L473-L503).  

I've been using the polyfills with IE11 for quite a while now with no problem.

Are your polyfills loading successfully?

**Comment by azakus** [comment]
`getRootNode()` is implemented.

If you're still having issues, please file an issue at https://github.com/webcomponents/polyfills
