### ISSUE TITLE
webcomponentsjs has issues with lit-html on IE11

### ISSUE THREAD

**Issue by SetTrend** [webcomponents/webcomponentsjs#1073]
# Description
Using `webcomponentsjs` along with [`lit-html`](https://github.com/Polymer/lit-html) results in a syntax error on IE11.

# Steps to Reproduce

1. Write this code

```ts
import "@webcomponents/webcomponentsjs/webcomponents-bundle";
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js';
```

2. See this output...

![image](https://user-images.githubusercontent.com/9283914/54633832-40ce2880-4a81-11e9-9a2e-9c788725dd49.png)

1. Write this code

```ts
import "@webcomponents/webcomponentsjs/webcomponents-bundle";
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js';
import "lit-html"
```

2. See this output...

![image](https://user-images.githubusercontent.com/9283914/54633951-78d56b80-4a81-11e9-814d-e980b01c14f7.png)

## Reason For This Error

The syntax error is raised by the `const` in file `node_modules\@webcomponents\webcomponentsjs\custom-elements-es5-adapter.js`:

```js
(function(){if(void 0===window.Reflect||void 0===window.customElements||window.customElements.hasOwnProperty('polyfillWrapFlushCallback'))return;const a=HTMLElement; ...
```

Or, rather, it's based in the fact that `lit-html` renders the preceding `if` condition `false`.

## Expected Results

`webcomponentsjs` and `lit-html` should co-exist smoothly in IE11.

## Additional information

I need my website to run in Chrome, Firefox and IE11. So I require the ES5-shim for Chrome/Firefox.

I'm not sure whether this is a `webcomponentsjs` or a `lit-html` issue, so I'm creating the same issue in both repositories.

## Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x] IE 11

/ref: /Polymer/lit-html/issues/873

**Comment by web-padawan** [comment]
You should NOT load `custom-elements-es5-adapter` in IE11. It is only needed for browser supporting Custom Elements natively, when you transpile to ES5. You can read more about that script here:
https://github.com/webcomponents/custom-elements#es5-vs-es2015

**Comment by SetTrend** [comment]
I know, but the same page is supposed to *load* in Chrome, too. So I *need* this shim.

I'm including the file in my TypeScript files, so it's bundled with my sources.

Couldn't you implement a run-time switch that's disabling the shim when run on IE 11?

**Comment by SetTrend** [comment]
It seems like `lit-html` mimics a browser that's capable of natively dealing with custom elements.

It causes the above if statement in `webcomponentsjs` to yield `false`.

If I understand it right, you're all part of the Polymer group. Wouldn't you want to have a small discussion amongst the teams to puzzle out a solution?

**Comment by justinfagnani** [comment]
We don't need two issues on the same topic with the same comments. Closing in favor of https://github.com/Polymer/lit-html/issues/873
