### ISSUE TITLE
Will html import be supported  still,  in the future？

### ISSUE THREAD

**Issue by Marksteinsong** [webcomponents/webcomponentsjs#1078]
I  just  saw  it  below from my Chrome bowser:

[Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.

**Comment by web-padawan** [comment]
See https://github.com/webcomponents/html-imports/issues/89#issuecomment-445160693

In short: nothing will explode, as long as you use `webcomponentsjs` 1.x

**Comment by azakus** [comment]
As @web-padawan said, webcomponents 1.x will continue to work for HTML Imports.
However, HTML Imports as a platform feature is being removed from Chrome at some point in the future, and we suggest moving to ES Modules, which are native in Chrome, Safari, Firefox, and in the new Edge.
