### ISSUE TITLE
document.evaluate broken by loading polymer.js

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#108]
<a href="https://github.com/dhubler"><img src="https://avatars.githubusercontent.com/u/8318?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dhubler](https://github.com/dhubler)**
_Friday Apr 18, 2014 at 21:03 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/422_

----

Just loading polymer.js library will break document.evaluate function, which is xpath parser.  

Full details:
  http://stackoverflow.com/questions/23161195/polymer-breaks-document-evaluate-xpath

Failed example code:
  http://jsbin.com/jadir/2/edit?html,console,output

Workaround:
  unwrap select dom elements before passing in function

**Comment by garlicnation** [comment]
Works as of June 23, 2016.
