### ISSUE TITLE
support for ShadowRoot/Document activeElement

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#110]
<a href="https://github.com/sigmundch"><img src="https://avatars.githubusercontent.com/u/2049220?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sigmundch](https://github.com/sigmundch)**
_Monday Jul 28, 2014 at 23:27 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/478_

----

It seems we don't have a polyfill for [document.activeElement][1]. Not sure if that was intentional.

Here is a simple example:
```html
<!-- <script src="ShadowDOM.min.js"></script> -->
<div></div>
<script>
document.addEventListener('click', function() {
  console.log(document.activeElement);
});

var div = document.body.querySelector('div');
var root = div.createShadowRoot();
root.innerHTML = '<input id="a"></input>';
</script>
```

This program should print `<div>` when clicking on the input element `#a` (this works with the native implementation in Chrome 37). When using the polyfill, the code prints the input element instead.

This came up in the context of [a bug reported by a Dart user][2].

[1]: http://www.w3.org/TR/shadow-dom/#active-element
[2]: https://code.google.com/p/dart/issues/detail?id=20165

**Comment by bicknellr** [comment]
Working on this in #457.
