### ISSUE TITLE
performance for newer browsers 

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#111]
<a href="https://github.com/jmesserly"><img src="https://avatars.githubusercontent.com/u/1081711?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jmesserly](https://github.com/jmesserly)**
_Thursday Aug 21, 2014 at 18:59 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/493_

---

The idea behind this bug is to take advantage of native features on the latest browsers:
- override DOM Accessors (IE, FF, transpiler needed on Safari)
- use native MutationObservers (IE11+, all others)

this won't be as easy to use as current codebase (due to transpiler & more restricted browser set)
currently I'm experimenting in a fork/branch: https://github.com/jmesserly/ShadowDOM/tree/patching

**Comment by garlicnation** [comment]
This is much lower priority with the shift towards ShadyDOM.

**Comment by jmesserly** [comment]
yeah, also it's not an issue if you use platform-lite. I'd be happy with closing this too.

for the record, I also had a branch from webcomponentsjs (more recent than the old link above): https://github.com/jmesserly/webcomponentsjs/tree/faster_shadowdom
