### ISSUE TITLE
new querySelector logic broken if no <content> element

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#112]
<a href="https://github.com/jakemac53"><img src="https://avatars.githubusercontent.com/u/984921?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jakemac53](https://github.com/jakemac53)**
_Tuesday Aug 26, 2014 at 20:55 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/495_

---

https://github.com/Polymer/ShadowDOM/commit/14bc904433b71dd8c6de0091c2fa4fccdb66f960 skips some tests which are exposing real errors. Specifically, if you do not have a content element in  your polymer elements template, but somebody does supply content for your element, then they can no longer query for those elements (see the querySelectorAll test). While these elements will not be rendered they should still be queryable.

**Comment by nazar-pc** [comment]
I did partial fix for this issue in #624 (and unlocked some previously skipped tests).
My guess is that no one will ever work on this for v0, so PR in its current form actually makes sense.
