### ISSUE TITLE
querySelector with '/deep/' issue

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#118]
<a href="https://github.com/ebidel"><img src="https://avatars.githubusercontent.com/u/238208?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ebidel](https://github.com/ebidel)**
_Sunday Nov 16, 2014 at 21:19 GMT_
_Originally opened as https://github.com/Polymer/ShadowDOM/issues/520_

---

_From @jakemac53 on November 14, 2014 17:13_

This is the smallest repro I could get: http://jsbin.com/hukiqacosu/1/edit?html,output.

In chrome it will find the element, in firefox under the polyfill it will not.

Original report here: http://dartbug.com/21314

_Copied from original issue: Polymer/webcomponentsjs#54_

**Comment by antitoxic** [comment]
Guys, this is still an issue for me with the latest 0.5.2 version.  :(

And I'm trying to use external plugin (Packery) which allows me to pass in only a selector so I don't have control of the logic afterwards.

**Comment by jmesserly** [comment]
yeah, I don't think this issue was fixed. indeed http://jsbin.com/zicijuwumi/1/edit?html,output still shows different behavior in Chrome vs Firefox

**Comment by antitoxic** [comment]
Also I have built it from source (0.5.3 beta) and the problem is still there. 

I initially hit this problem when using Packery with Draggabilly (desandro's layout scripts) and tried to pass selector to Draggabilly in order to be used as a handle for the dragging (`handle: '.content /deep/ .handle'`). Didn't work for elements in the shadow dowm. It did work for elements in the "LightDom"

**Comment by johnstonmatt** [comment]
I have (I think) this one too, I have IE 10 support, but not safari. I am using 0.5.4 and my querySelectors at page load return null on safari but not on any other browsers.

**Comment by eeid26** [comment]
Try this workaround for the original example reported. 
http://jsbin.com/muyoxiwera/10/edit

**Comment by dylanb** [comment]
I think I have found a different version of this problem - please tell me if it is the same or different. The following HTML file works in Chrome but not in Firefox. Clicking the button should set the focus into the shadow DOM.

```html
<!DOCTYPE html>
<html>
	<head>
		<script src="bower_components/webcomponentsjs/webcomponents.js"></script>
	<head>
	<body>
		<link rel="import" href="bower_components/polymer/polymer.html">
		<polymer-element name="aria-menu">
			<template id="ariamenu">
				<div role="menu" tabindex="-1"><content></content></div>
				<style>
				*:focus {
					outline: 2px dotted black;
				}
				</style>
			</template>
			<script>
			(function () {
				Polymer({
					focus: function () {
						console.log(this.shadowRoot.querySelector('div'));
						this.shadowRoot.querySelector('div').focus();;
					}
				});
			}());
			</script>
		</polymer-element>
		<button id="popup">focus</button>
		<div id="myPopupContainer">
		    <aria-menu>My Content</aria-menu>
		</div>
		<script>
			popup.addEventListener('click', function (e) {
				myPopupContainer.querySelector('aria-menu').focus();
			}, false);
		</script>
	</body>
</html>
```

**Comment by eeid26** [comment]
@dylanb your issue is not the same issue.

```javascript
        // this would fix your sample
        wrap(myPopupContainer).querySelector('aria-menu').focus();
        
        // or this 
        document.getElementById("myPopupContainer").querySelector('aria-menu').focus();
```

**Comment by dylanb** [comment]
I know that the second workaround works, but is this expected behavior or a bug? I didn't find any documentation for this on the web site.

**Comment by eeid26** [comment]
its not a bug. I am not sure where would you find information on how webcomponents work and how it wraps the dom elements. The code is fully documented if you need to know more.
So in your example, you happened to access the dom element without the wrapper. 
In browsers that support shadow dom, there are no wrappers.

**Comment by TimvdLippe** [comment]
`/deep/` has been deprecated and we have removed it from our polyfill. Therefore this issue no longer exists.
