### ISSUE TITLE
getting errors for my webcomponents in FF where there are none in Chrome

### ISSUE THREAD

**Issue by Pomax** [webcomponents/webcomponentsjs#128]
So I thought I'd try to do something "serious" with polymer's webcomponents, and wrote http://pomax.github.io/mjscoring.js, a single page app for tracking mahjong scoring during a game, where all of the functional elements are implemented as web components. This works fine in Chrome, but Firefox dies quite a bit on things that should, for all intents and purposes, work just fine from what I can tell.

On load, FF will immediately throw a "TypeError: this.bonus is undefined on line 15" for https://github.com/Pomax/mjscoring.js/blob/gh-pages/elements/mj-player.html#L48 despite the fact that the `this.bonus` involved gets set up in the `domReady` lifecycle function. Chrome happily does this, Firefox apparently silently fails to make that binding work.

Am I missing something completely elementary here (like a single library import missing in index.html, found at https://github.com/Pomax/mjscoring.js/blob/gh-pages/index.html) or is this an actual systemic issue with Polymer and a thing people will always run into?

All my elements are relatively short (Except for the chinese classical rules element, which is mostly a .js library refactored as element) and live in https://github.com/Pomax/mjscoring.js/tree/gh-pages/elements, with https://github.com/Pomax/mjscoring.js/blob/gh-pages/elements/mj-game.html being the topmost web component inside of which everything else is loaded.

note: I don't vulcanize the elements, but from what I understand whether the elements are vulcanized or not should not change their in-browser behaviour, so I just have no idea why things are working fine in Chrome, but are broken enough in Firefox to be unusable...

**Comment by garlicnation** [comment]
@Pomax it looks like your application is working in FF and Safari now. I'm closing this issue since it seems resolved.

**Comment by Pomax** [comment]
ah, didn't even realise this was still open. I redid the application in the mean time as a React app (which feels a surprisingly amount like web components, since it's also about the compositioning)
