### ISSUE TITLE
Breaking Twitter Bootstrap Dropdown in Safari

### ISSUE THREAD

**Issue by reggi** [webcomponents/webcomponentsjs#130]
I have the following scripts on the page:

``` html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.1/webcomponents.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/polymer/0.5.1/polymer.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
```

I'm using the [default navbar](http://getbootstrap.com/components/#navbar) from the [Twitter Bootstrap](http://getbootstrap.com) docs. When the [dropdown](http://getbootstrap.com/components/#dropdowns) is clicked Safari throws this error:

``` javascript
[Error] TypeError: undefined is not a function (evaluating 'a.getAttribute(b)')
    (anonymous function) (jquery.min.js, line 2)
```

The error only occurs when `webcomponents.min.js` is being included.

Here's an [example in jsbin](http://jsbin.com/sigiwaceye/1)

>  **_Remember_**: it only throws the error in Safari / iOS.

**Comment by warnerandy** [comment]
there is an assertion error on safari that shows up in webcomponentsjs around the shadowdom polyfill. This seems to be breaking the bootstrap js. using webomponentsjs-lite fixes the problem (as long as you arent using shadowdom)
