### ISSUE TITLE
Add LICENCE file

### ISSUE THREAD

**Issue by triblondon** [webcomponents/webcomponentsjs#137]
This repo is missing a licence declaration.  I'd like to reuse some of the polyfills in the [polyfill service](https://cdn.polyfill.io) but won't be able to unless you confirm that the code is licensed under terms that permit reuse.

This file also links to the licence, which 404s:
https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md

**Comment by addyosmani** [comment]
Thanks for catching this. We currently include LICENSE information as part of a banner https://github.com/webcomponents/webcomponentsjs/blob/master/banner.txt prepended to files as necessary. We could improve on this with a separate LICENSE file in the repo - @jmesserly thoughts?
