### ISSUE TITLE
Don't use set & get keywords

### ISSUE THREAD

**Issue by niutech** [webcomponents/webcomponentsjs#139]
The [Paper Elements Sampler](http://www.polymer-project.org/components/paper-elements/demo.html) doesn't work in QupZilla (based on QtWebKit) on Ubuntu 12.04 LTS due to many parse errors in webcomponents.js, namely setters and getters using `set` and `get` keywords. Could you rewrite your code, so that the polyfill works?

**Comment by addyosmani** [comment]
+1 on what @ebidel wrote above. There is a minimal baseline expected by these polyfills which must be met in order for them to function correctly. If operating in a non-ES5 environment, I suggest attempting to use an ES5 polyfill set prior to loading webcomponents.js and see how far you can get with it.
