### ISSUE TITLE
`polyfill-next-selector` and `polyfill-rule` shadow DOM selectors don't work in latest Firefox

### ISSUE THREAD

**Issue by JoshMock** [webcomponents/webcomponentsjs#140]
In Firefox 34.0.5, neither the `polyfill-next-selector` nor the `polyfill-rule` CSS selectors work at all when applying CSS rules to elements in a shadow DOM.

The following JSFiddle uses webcomponents.js 0.5.2 and follows the rules as documented on [polymer-project.org](https://www.polymer-project.org/docs/polymer/styling.html#at-polyfill-rule).

To see the extent of the issue, open this in latest Firefox and latest Chrome to see the difference. http://jsfiddle.net/JoshMock/h0azk9sg/8/

**Comment by sorvell** [comment]
Yes, this should be documented. The style shimming must be done manually.
When Polymer is involved, it is done automatically. Here's a version of the
fiddle above that should work:

http://jsfiddle.net/apobfgkr/

Note specifically the line to shim the styles:

  WebComponents.ShadowCSS.shimStyling(template.content, name);

Hope that helps.

**Comment by JoshMock** [comment]
Awesome! Thanks, @sorvell.

Is there a way I can help contribute back to the documentation with that information? If it's noted anywhere it wasn't immediately clear or obvious.

**Comment by addyosmani** [comment]
At the moment we maintain high-level documentation around the polyfills on webcomponents.org, with source comments being the other place where notes like this could potentially be added. Do we have a preference on where this specific note should go?

**Comment by tjsavage** [comment]
@addyosmani It seems like there may be a handful of these type of patches that will solve common issues that are run into with the polyfills. Maybe could add a section to the README for "Common Pitfalls"?

**Comment by addyosmani** [comment]
> Maybe could add a section to the README for "Common Pitfalls"?

:100:
