### ISSUE TITLE
Uncaught ReferenceError: Window is not defined

### ISSUE THREAD

**Issue by hedcet** [webcomponents/webcomponentsjs#142]
i am currently using meteorjs + polymer + cordova to build android application
when i run it in android device as cordova app cause an error

I20141230-13:23:05.908(5.5) (android:http://meteor.local/polymer/bower_components/webcomponentsjs/webcomponents.min.js:11) Uncaught ReferenceError: Window is not defined

but it working perfectly in android browser

**Comment by lorensr** [comment]
+1, appears that webcomponents might break meteor websites in iOS cordova as well:

```
[Error] Deprecated attempt to access property 'userAgent' on a non-Navigator object.
	global code (webcomponents.js, line 6290)
```

**Comment by andrescabana86** [comment]
+1, using angularjs polymer. In browser works perfectly.

In emulator or device cause this error

'''
01-07 12:44:25.160: E/Web Console(17402): Uncaught ReferenceError: Window is not defined at file:///android_asset/www/lib/webcomponentsjs/webcomponents.js:1285
'''

**Comment by addyosmani** [comment]
I've been able to confirm the above breaks. Trying to dig down into the cause of the issue.

**Comment by andrescabana86** [comment]
Could you solve the problem? Im very happy with polymer smile:

**Comment by andrescabana86** [comment]
any news?? polymer is spectacular!

**Comment by abigoroth** [comment]
having the same problem on android 4.2.2, the weird issue is my friend can compile and run into it flawlessly.

**Comment by andrescabana86** [comment]
news?????? :D

**Comment by andrescabana86** [comment]
any news please???

**Comment by HedCET** [comment]
I don't know why polymer not work in my MIUI redme note (android 4.2.2)

https://github.com/HedCET/torrentz.meteor.com this made full in polymer & it working in 4.4.2 note2 & lollipop nexux4

**Comment by addyosmani** [comment]
@andrescabana86 We're aware of the issue and are hoping to get to it when time allows. We'll close this issue when that's been completed.

**Comment by fullhdpixel** [comment]
Im having the same issue using the package https://github.com/numtel/meteor-webcomponent

**Comment by HedCET** [comment]
@fullhdpixel some errors solve with start iron:router after polmer-ready event & load webcomponent.js at head tag

**Comment by andrescabana86** [comment]
thank @HedCET. Same to me on Android 4.4.2 it always show a blank page.

**Comment by sharmamo** [comment]
+1 I am seeing a very similar symptom. In the emulator it works fine, but unfortunately in the actual device it shows a blank page and the error of the window not being defined. Is there a work around meanwhile this is being worked?

**Comment by bambattajb** [comment]
I was trying to use Polymer inside a Meteor.js app and I was having all of these issues as well. After being bounced around a few places online to help with the problem, I decided I would try using Crosswalk. After factoring Crosswalk into CordovaLib (at least in Meteor) from what I am able to tell right now, everything in Polymer appears to work great. 

The Meteor resource I followed is below. I found the process very simple.
https://meteor.hackpad.com/Building-Meteor-app-with-Crosswalk-kHKh4DzGxFQ

Perhaps using Crosswalk will solve some of these other issues with other environments as well?

Note, tesed in Android 4.2.2 (HTC 310), 4.3 (Galaxy S3) and 4.4 (Galaxy Tab)

**Comment by andrescabana86** [comment]
Muy env is Córdova and polymer. Hoy can i use crosswalk to solve this issue?

**Comment by jwdunn1** [comment]
Not sure if this helps, but I recently learned that "window" is an object, while "Window" is a native function [note the upper case]. I found that the Android browser throws the "Window is not defined" error for a library I'm building. While on my desktop, in Chrome, Firefox, both Window and window are defined.

**Comment by antoinerl** [comment]
Hello, any news on that issue ?

**Comment by antoinerl** [comment]
I found two things I hope it will help : 
- I use myWebView.setWebChromeClient(new WebChromeClient()); It works well with Polymer
- and webSettings.setDomStorageEnabled(true); if you want to use localStorage or sessionStorage

**Comment by kashesandr** [comment]
I have the same issue on android web browser.
Any updates?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
