### ISSUE TITLE
ShadowDOM wrapper error

### ISSUE THREAD

**Issue by alx5962** [webcomponents/webcomponentsjs#143]
In Internet Explorer 9, an error from ShadowDOM/wrappers.js is generated:

  function setWrapper(impl, wrapper) {
    wrapper.**impl4cf1e782hg** = impl;
    impl.**wrapper8e3dd93a60** = wrapper;
  }

Unable to define property « **wrapper8e3dd93a60** » as impl is undefined.
So does it means IE9 is not supported or is it just a bug?

**Comment by addyosmani** [comment]
There are limitations on how much of the polyfills reliably function in IE9 (IE10 is the baseline we test against and support). Would it be possible for you to supply a minimal test case of what was breaking?

**Comment by alx5962** [comment]
I had this problem mostly with core-selector (from Polymer).
So just run the core-selector demo in IE9 and you'll be able to repeat this error:
https://www.polymer-project.org/components/core-selector/demo.html
