### ISSUE TITLE
the Node.normalize does not remove the empty text nodes using the polyfill

### ISSUE THREAD

**Issue by eeid26** [webcomponents/webcomponentsjs#145]
Hi,

I am not sure if I missed something or not ?   

I ran the following code with webcomponents.js (version: 0.5.1-1 ) and I did not get the correct results by calling the polyfill normalize. I had to use unwrap to get the correct results.

        var div = document.createElement("div");
        div.appendChild(document.createTextNode(""));
        div.appendChild(document.createTextNode(""));
        div.appendChild(document.createTextNode(""));
        var childDiv = document.createElement("div");
        childDiv.appendChild(document.createTextNode(""));
        childDiv.appendChild(document.createTextNode(""));
        div.appendChild(childDiv);

        console.log("parentDiv before normalize:",div.childNodes.length);
        console.log("childDiv before normalize:",childDiv.childNodes.length);

        // calling the polyfill normalize will not remove the empty textNodes
        //div.normalize();
        //console.log("parentDiv after polyfill normalize:",div.childNodes.length);
        //console.log("childDiv after polyfill normalize:",childDiv.childNodes.length);

        unwrap(div).normalize();
        // the parentDiv should have 1 child and the childDiv should be 0
        console.log("parentDiv after unwrap normalize:",div.childNodes.length);
        console.log("childDiv after unwrap normalize:",childDiv.childNodes.length);

Thank you

**Comment by eeid26** [comment]
This is really a bug and not a a question

**Comment by azakus** [comment]
Ah, there's actually an exception being thrown. Fixing.

**Comment by eeid26** [comment]
Thank you
