### ISSUE TITLE
webcomponents + ember + ipad = browser hang

### ISSUE THREAD

**Issue by ralphcrisostomo** [webcomponents/webcomponentsjs#149]
browser hang when viewing on iPad.  I found out what causing the crash and it is something to do with Ember (1.8.1) Resolver and webcomponents.

**Comment by addyosmani** [comment]
Do you have a reduced test case you can share? We don't actively test for Ember compatibility.

**Comment by addyosmani** [comment]
Hey @ralphcrisostomo. As it's been a month since this issue was opened and you haven't had a chance to post back a repro test case, I'm going to go ahead and close this up. If you are able to get a repro together we would be happy to investigate further.
