### ISSUE TITLE
Bower repository for lite version

### ISSUE THREAD

**Issue by gdcohan** [webcomponents/webcomponentsjs#150]
I want to pull in the lite version without Shadow DOM through Bower. Is it possible for a separate Bower package to be set up to enable this?

Thanks!

**Comment by azakus** [comment]
The lite versions are included in the releases:  https://github.com/webcomponents/webcomponentsjs/tree/0.5.2

**Comment by gdcohan** [comment]
the problem I'm running into is that the main entry of the release points to the full version, and my app relies on those entries to know what to pull in.

**Comment by azakus** [comment]
What tool are you using? There should be a way to manually specify the file you want to serve.

**Comment by gdcohan** [comment]
Ya--I can manually edit the main entry of the bower file, I was just hoping to see if there was an easier way to do it so that I don't have to re-update that entry every time I update the dependency. Thanks for the help, though!

**Comment by addyosmani** [comment]
One option is that we expand main to include both the webcomponents.js full-fat build and webcomponents-lite.js (main can be an array). This solves this use-case but will pull in both entries for everyone. Do we want that?

**Comment by gdcohan** [comment]
I can't speak to other use cases, but I don't think that'd be that helpful in my own case--it seems like in the normal case that would just include both versions (which seems like the worst of both worlds)

**Comment by TimvdLippe** [comment]
We have shipped https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-hi-ce.js for this use-case 🎉
