### ISSUE TITLE
Fix up sourcemaps

### ISSUE THREAD

**Issue by nevir** [webcomponents/webcomponentsjs#152]
Main goal is to get sourcemaps to work for the imports polyfill (but really all of them).

**Comment by garlicnation** [comment]
@nevir Does https://github.com/webcomponents/webcomponentsjs/issues/11 feel like it is related? I think there's a large class of devtools-related issues that could be fixed by this.

**Comment by garlicnation** [comment]
For inline/external scripts:
script should have a reasonable name
parsing errors are useful
console.log works as expected - no horrible ```data://utf8wke;qjre;kwlqhjr``` nonsense.
Breakpoints - ideally they work everywhere you can see the source.

**Comment by azakus** [comment]
We should give a look at using `Blob` instead of data urls. The generated urls are much shorter, and don't require any calls to `encodeURIComponent`.

**Comment by garlicnation** [comment]
I think "parsing errors are useful" is mutually exclusive with the other features, unfortunately.

Unless we manually eval() the scripts, we can't get a nice, debuggable name out of them.

**Comment by TimvdLippe** [comment]
This should be fixed with #858
