### ISSUE TITLE
IE 9: MutationObserver doesn't get childList mutation events when observed element not in DOM when using webcomponents-lite.js

### ISSUE THREAD

**Issue by lazd** [webcomponents/webcomponentsjs#161]
### Steps to reproduce
1. Visit http://jsfiddle.net/lazd/3799ertb/16/ in IE 9
2. Click 'Add new item with JS'
3. Note the log entires for mutations observed and that the last item is the only selected item
4. Click 'Remove/Add list to DOM'
5. Click 'Add new item with JS'
6. Click 'Remove/Add list to DOM'
### Expected

Only the last item is selected.

The following log output should be present:

```
* Just initialized, selecting only the last element
  Deselecting all but Item 3
  Deselecting Item 2
* Adding a new selected item programmatically
- Mutation: Got a new childList, selecting only the last element
  Deselecting all but Item from JS
  Deselecting Item 3
- Mutation: selected attribute removed from item, doing nothing
* Removing from DOM
* Adding a new selected item programmatically
- Mutation: Got a new childList, selecting only the last element
  Deselecting all but Item from JS
  Deselecting Item from JS
- Mutation: selected attribute removed from item, doing nothing
* Adding to DOM
```
### Actual

All 'Item from JS' items are selected.

The following log output is present:

```
* Just initialized, selecting only the last element
  Deselecting all but Item 3
  Deselecting Item 2
* Adding a new selected item programatically
- Mutation: Got a new childList, selecting only the last element
  Deselecting all but Item from JS
  Deselecting Item 3
- Mutation: selected attribute removed from item, doing nothing
* Removing from DOM
* Adding a new selected item programmatically
* Adding to DOM
```
### Additional information

This affects `webcomponents-lite.js` 0.5.3-rc as well as 0.5.2, and the Fiddle us linking against `webcomponents.js` from 0.5.3-rc.

The issue is not present in:
- Chrome 39.0.2171.95 (64-bit)
- Firefox 34.0.5
- Safari 7.0.6 (9537.78.2)

**Comment by jmesserly** [comment]
this polyfill doesn't officially support IE9, but you may have luck debugging through the code here:
https://github.com/webcomponents/webcomponentsjs/blob/master/src/MutationObserver/MutationObserver.js#L421

Transient observers are the things attached to nodes when they are disconnected from the DOM tree. That code is supposed to be registering the event listener to listen for those DOM Mutation Events. 

Have not looked into it, but I'm not sure if this can be fixed. If the browser doesn't deliver events for disconnected trees there isn't much we can do (without resorting to ShadowDOM polyfill style tricks).

IE 11+ has native MutationObservers, though.

**Comment by jmesserly** [comment]
another spot to look: https://github.com/webcomponents/webcomponentsjs/blob/master/src/MutationObserver/MutationObserver.js#L527, and see if the browser is even delivering an event there

**Comment by lazd** [comment]
A quick update: I tried version 0.5.2 of webcomponents.js and the problem is NOT present there, see [revision 17 of the fiddle that links 0.5.2](http://jsfiddle.net/lazd/3799ertb/17/). I will investigate further and see if I can track down what changed.

**Comment by lazd** [comment]
Ok, it seems that the `webcomponents-lite.js` distribution suffers from the problem in both 0.5.2 and 0.5.3-rc. When including `webcomponents.js` 0.5.2, the issue described is not present. :white_check_mark: 

That said, 0.5.3-rc doesn't run in IE 9, will file a separate issue for that.

**Comment by jmesserly** [comment]
yeah so webcomponents.js includes ShadowDOM polyfill, which has includes its own MutationObserver polyfill included. ShadowDOM intercepts *all* DOM reads/writes, so it can be much more precise in how it polyfills MutationObservers. By contrast -lite.js tries to build new MutationObserver on old Mutation Events, which is a lot more performant, but more tricky to pull off.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
