### ISSUE TITLE
Availability in NuGet

### ISSUE THREAD

**Issue by adityapurwa** [webcomponents/webcomponentsjs#166]
I dont see webcomponentjs on NuGet, it would be great if you also host it there.

**Comment by rstellar** [comment]
@adityapurwa I'm trying to find a way to point NuGet directly to a Git repository. I'm new to the .NET world, but in Node/NPM this would be pretty trivial. Do you have a doc reference?

**Comment by adityapurwa** [comment]
Yes, in NPM, it is very straightforward. I was about to try Polymer. The Polymer package itself is available at NuGet gallery. Polymer depends on WebComponent, I have to use NuGet and Bower side by side for now (which I need to configure to store these files in one common folder).

 

I think http://docs.nuget.org/ contains complete information about NuGet.

I think git repository integration is not possible yet. So, the best option for now is to create an automation to build the project, prepare it for NuGet, and push it to the NuGet server. This http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package page contains the command needed to publish NuGet package.

**Comment by addyosmani** [comment]
We currently focus on publishing releases to both Bower (where the majority of our users consume it) and NPM, however don't have support for NuGet in our pipeline. If another member of the community would like to take on creating/updating a NuGet package in the interim, that would be welcomed :)

**Comment by adityapurwa** [comment]
If I have the permission, I will try to manage the NuGet release for webcomponentjs.

**Comment by addyosmani** [comment]
cc @azakus for a second opinion. I'm otherwise fine with ^ :)

**Comment by addyosmani** [comment]
Closing as “fine with a community member managing NuGet releases”. Atm, we’re focused on Bower and npm ones.
