### ISSUE TITLE
webcomponents-lite.js "release" version refers to itself as webcomponents.js

### ISSUE THREAD

**Issue by JEAxero** [webcomponents/webcomponentsjs#168]
The latest versions of webcomponents lite in the "releases" directory that I've seen (at least v0.5.3 and v0.5.4) refer to file being loaded as webcomponents.js instead of webcomponents-lite.js. Here is line 15 from v0.5.4's webcomponent-lite.js:

  var file = "webcomponents.js";

It's also worth noting that this seems to have been fixed in webcomponents-lite.js in the "master" branch on line 17. However, the v0.5.4 and "master" versions of webcomponents-lite are quite different. The "master" version is streamlined to 78 lines and seems to define the modules to be included in webcomponents-lite.js. However, the v0.5.3 and v0.5.4 versions are ~1,750 lines and not modularized.

**Comment by rojaro** [comment]
Something seems very broken in the build process of the latest releases.

i.e. package contents of 0.5.2 (npm install webcomponents.js@0.5.2)
```
-rw-r--r--  1 root     root      30473 Dec 15 20:37 CustomElements.js
-rw-r--r--  1 root     root      14665 Dec 15 20:37 CustomElements.min.js
-rw-r--r--  1 root     root      34740 Dec 15 20:37 HTMLImports.js
-rw-r--r--  1 root     root      17904 Dec 15 20:37 HTMLImports.min.js
-rw-r--r--  1 root     root       1456 Dec 11 21:45 README.md
-rw-r--r--  1 root     root     150577 Dec 15 20:37 ShadowDOM.js
-rw-r--r--  1 root     root      68147 Dec 15 20:37 ShadowDOM.min.js
-rw-r--r--  1 root     root        248 Dec 11 21:45 bower.json
-rw-r--r--  1 root     root        974 Dec 11 21:45 build.log
-rw-r--r--  1 root     root       2561 Jan 28 14:42 package.json
-rw-r--r--  1 root     root      55089 Dec 15 20:37 webcomponents-lite.js
-rw-r--r--  1 root     root      28179 Dec 15 20:37 webcomponents-lite.min.js
-rw-r--r--  1 root     root     232233 Jan 28 14:42 webcomponents.js
-rw-r--r--  1 root     root     105184 Dec 15 20:37 webcomponents.min.js
```
vs. package contents of 0.5.4 (npm install webcomponents.js@0.5.4)
```
-rwxr-xr-x  1 root     root      791 Jan 28 11:22 .autoclave-build.sh
-rw-r--r--  1 root     root       18 Dec  1 17:31 .npmignore
-rw-r--r--  1 root     root     2507 Dec  1 17:31 CONTRIBUTING.md
-rw-r--r--  1 root     root     1456 Dec  1 17:31 README.md
-rw-r--r--  1 root     root      564 Dec  1 17:31 banner.txt
-rw-r--r--  1 root     root      249 Jan 28 11:22 bower.json
-rw-r--r--  1 root     root     3724 Dec  1 17:31 gulpfile.js
-rw-r--r--  1 root     root     2562 Jan 28 14:36 package.json
drwxr-sr-x 10 root     root     4096 Jan 28 14:36 src
drwxr-sr-x 11 root     root     4096 Jan 28 14:36 tests
-rw-r--r--  1 root     root     2349 Dec  1 17:31 webcomponents-lite.js
-rw-r--r--  1 root     root     2773 Jan 28 14:36 webcomponents.js
drwxr-sr-x  2 root     root     4096 Dec  1 17:31 workbench
```

**Comment by addyosmani** [comment]
> It's also worth noting that this seems to have been fixed in webcomponents-lite.js in the "master" branch on line 17

Can you confirm that everything works as expected for you with the master version of webcomponents-lite?

**Comment by JEAxero** [comment]
I'd been running some tests with the packaged downloads of v0.5.3 and v0.5.4. But I'll try to pull the master version and see if that works once I finish catching up with the post-blizzard cleanup here near Boston.

**Comment by JEAxero** [comment]
Just ran a very, very quick test and the version of webcomponents-lite.js pulled from the "master" does not seem to work. Note that I didn't pull the master and run through the build steps with gulp. (Will try to find time to do that later.)

I grabbed the .zip generated from the master and replaced my v0.5.3 copy of "webcomponents-lite.min.js" with the master's "webcomponents-lite.js" and updated the reference in my app. After I did this, the simple custom element that I built (that used to work) stopped working. (I.e., none of its content rendered on the page.)

**Comment by Jeff17Robbins** [comment]
I tried this:
```Batchfile
git clone https://github.com/webcomponents/webcomponentsjs.git
npm install
gulp build 
```
yet, in my dist\webcomponents-lite.js file, I see:
```Javascript
/**
 * @license
 * Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
 */
// @version 0.5.4-5494dfa
window.WebComponents = window.WebComponents || {};

(function(scope) {
  var flags = scope.flags || {};
  var file = "webcomponents.js";
```

Shouldn't that be:
```Javscript
var file = "webcomponents-lite.js"
```

**Comment by JEAxero** [comment]
Just duplicated the results of Jeff17Robbins comment above. Same result when going through the build process.

**Comment by addyosmani** [comment]
cc @azakus who may have insight into what is going on with the builds atm. Afaik, 0.5.2 didn't have these issues but 0.5.3 and 0.5.4 appear to.
