### ISSUE TITLE
"Trust Encapsulation" Like with iframes

### ISSUE THREAD

**Issue by trisys3** [webcomponents/webcomponentsjs#170]
I have a similar issue to [this StackOverflow question](http://stackoverflow.com/questions/14338817/can-a-shadow-dom-secure-my-elements#), except we need to support IE10 and above (conveniently the cutoff point for Polymer). According to the currently only answer, the team working on web components is working on a flag that would allow the shadow root to opt into support for this issue. Are there any plans to implement something similar in Polymer's Shadow DOM?

**Comment by jmesserly** [comment]
hi @trisys3, I don't think we have any plans to implement support in the polyfill, at least not until something is written in the specification for Shadow DOM. Maybe @dglazkov has thoughts, but I haven't seen any updates to https://www.w3.org/Bugs/Public/show_bug.cgi?id=20144 in a while.

**Comment by trisys3** [comment]
OK, thanks for the quick reply. To be honest, I wasn't expecting much, but I figured I would at least try. Do you know about anything else that has similar functionality that's more established, besides `<iframe>`s?

**Comment by jmesserly** [comment]
iframes are the only thing I know of with the right security properties enforced by the browser (polyfilling the "private shadow root" feature would probably need to be based on iframes for that reason). That said, there are some ahead-of-time compiler approaches, like https://developers.google.com/caja/, that aim to enforce iframe-like properties without (as much) runtime performance penalty.

**Comment by trisys3** [comment]
Being based on iframes would involve embedding a whole extra document for each shadow root. This would involve immense performance penalties, and that's not even considering nested roots. How would you get around that?

**Comment by jmesserly** [comment]
> How would you get around that, if you explicitly based it on <iframe>s?

we couldn't

> How does Caja do it, without being based on <iframe>s?

I'm by no means an expert on Caja. Just have heard of it. You can read more at:
https://developers.google.com/caja/
https://code.google.com/p/google-caja/wiki/GettingStarted?tm=6
http://en.wikipedia.org/wiki/Caja_project

I think the idea is to use whole-program analysis. So it must see all HTML and JS code, and transpile it.

**Comment by jmesserly** [comment]
by the way, i'm going to close this because this feature isn't yet specified in Shadow DOM, and the polyfill tries to track the specification. But we can definitely reopen if/when it's specified.

(but as you point out, the polyfill for this probably won't have great performance)

**Comment by trisys3** [comment]
Yeah, sorry, I should have closed it yesterday when you guys said it wasn't feasible. I will wait with bated breath for this to become available, though not for my company to allow me to include it in the application. They'll wait for better browser support, etc.
