### ISSUE TITLE
Firefox 35 doesn't define Element.prototype.createShadowRoot

### ISSUE THREAD

**Issue by pennyfx** [webcomponents/webcomponentsjs#173]
createShadowRoot is not defined in Firefox 35 and throws 'originalCreateShadowRoot is undefined'. 

https://github.com/webcomponents/webcomponentsjs/blob/0.5.4/webcomponents-lite.js#L1365

**Comment by jmesserly** [comment]
hi @pennyfx webcomponents-lite does not include ShadowDOM polyfill, and Firefox does not yet implement ShadowDOM, so this is not expected to work. Use webcomponents.js if you need `createShadowRoot`. let me know if that works for you. Cheers!

**Comment by pennyfx** [comment]
I don't need to use it.  The issue is that you guys are not checking to see if createShadowRoot defined before calling it on line 1367.

https://github.com/webcomponents/webcomponentsjs/blob/0.5.4/webcomponents-lite.js#L1367

**Comment by pennyfx** [comment]
Please check to see if Element.prototype.createShadowRoot exists before rewriting it.  Otherwise downstream libraries won't be able to feature detect on it.

**Comment by jmesserly** [comment]
hi, can you explain who's calling createShadowRoot? you're linking to the `var root = ...` line:
```js
  var originalCreateShadowRoot = Element.prototype.createShadowRoot;
  Element.prototype.createShadowRoot = function() {
    var root = originalCreateShadowRoot.call(this);
    CustomElements.watchShadow(this);
    return root;
  };
```

to get there, someone had to call createShadowRoot already. who? a jsbin to illustrate the problem you're seeing would be very helpful. or at least a full stack trace. Thanks!

**Comment by jmesserly** [comment]
Ah, I think I get what you're saying. Yeah, the point about feature detection is good. I was confused by Firefox 35 in the bug title, it made it sound like a much more specific problem you were hitting :) 

A workaround for feature testing Shadow DOM is  `window.ShadowRoot`.

I'm guessing the fix for this is really simple, but let me double check the ordering when we're in webcomponents.js

**Comment by jmesserly** [comment]
ah, I see #174 too, going to dupe this against that one (also taking a look)

**Comment by jmesserly** [comment]
fyi, landed the fix. thanks for filing this!

**Comment by pennyfx** [comment]
Awesome, thanks.

-----Original Message-----
