### ISSUE TITLE
Compiled "lite" build without Shadow DOM still defines createShadowRoot

### ISSUE THREAD

**Issue by csuwildcat** [webcomponents/webcomponentsjs#174]
The latest compiled build of the no-Shadow-DOM "lite" version still defines `createShadowRoot`, here is the block: https://github.com/webcomponents/webcomponentsjs/blob/0.5.4/webcomponents-lite.js#L1365-L1370.

This causes downstream code using the presence of the `createShadowRoot` method for feature detection, to fail.

**Comment by pennyfx** [comment]
+1

**Comment by addyosmani** [comment]
@jmesserly @garlicnation is there a technical reason why we still define `createShadowRoot` as part of this build? Looking through the CE polyfills I noticed a few references to shadow roots, but was unsure if they were completely necessary.

**Comment by csuwildcat** [comment]
@addyosmani I'm not sure it's a possibility that this can be left in - it's a landmine that explodes if touched.

**Comment by addyosmani** [comment]
@csuwildcat Roger. @jmesserly appears to be on the case. Hoping we can drop our refs to `createShadowRoot` from lite builds to avoid the need to use workarounds for feature detection.

**Comment by jmesserly** [comment]
fyi, I'm looking at this now. I think it's legacy from the old layout. Right now I'm running through builds and testing that both webcomponents.js and webcomponents-lite.js work as expected after patch

**Comment by csuwildcat** [comment]
Works! Can you tag a new release?

**Comment by addyosmani** [comment]
We usually bump the polyfills in sync with new releases of Polymer, though we should probably move to independent release cycles at some point given this project is now separate. 

@azakus will be the one to make a call on tagging/publishing new releases.
