### ISSUE TITLE
Error calling installProperties on a flash <embed> object in Firefox

### ISSUE THREAD

**Issue by rictic** [webcomponents/webcomponentsjs#181]
Here's a minimal reproduction of the bug:

```html
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <script src="http://www.polymer-project.org/components/webcomponentsjs/webcomponents.js"></script>
    <embed src="http://www.youtube.com/v/dQw4w9WgXcQ" type="application/x-shockwave-flash" pluginspage="https://www.macromedia.com/go/getflashplayer">
```

In Firefox, with Flash installed and running when the page initializes, we get

```Error: Error enumerating properties on scriptable plugin object```

This error originates in installProperty, where we call getOwnPropertyNames on the prototype of unwrapped elements. In Firefox with Flash enabled, the prototype obtained by calling getPrototypeOf on a flash <embed> element is `NPObject JS wrapper class { }`. This NP Object will throw the above error when getOwnPropertyNames is called on it.

You can reproduce the specific code that lead to this error by running the following in the FF console:

```javascript
   Object.getOwnPropertyNames(Object.getPrototypeOf(unwrap(document.querySelector('embed'))))
```

**Comment by garlicnation** [comment]
Here's the bug report from 2010:

https://bugzilla.mozilla.org/show_bug.cgi?id=545565

I'm thinking that we just have to avoid wrapping the embed object in firefox, but I'm unsure of the consequences of this.

**Comment by jmesserly** [comment]
@garlicnation ... easiest fix would be to hard code the properties of `<embed>` from the spec https://html.spec.whatwg.org/multipage/embedded-content.html#the-embed-element

(that way we aren't breaking any invariants about whether APIs return wrapped or unwrapped nodes)

**Comment by garlicnation** [comment]
Some notes from poking at the embed object in ff:
```
> node
< <embed pluginspage="https://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" src="http://www.youtube.com/v/dQw4w9WgXcQ">
> node.constructor
< function ()
> node.constructor.name
< "HTMLEmbedElement"
> node.__proto__
< NPObject JS wrapper class {  }
> node.prototype
< undefined
> typeof node
"function"
```

**Comment by garlicnation** [comment]
This bug was actually recently re-introduced in http://hg.mozilla.org/mozilla-central/diff/5a8e7d35dd45/dom/plugins/base/nsJSNPRuntime.cpp late last year.
