### ISSUE TITLE
Conflict between Google Polymer and Highcharts library

### ISSUE THREAD

**Issue by hcho112** [webcomponents/webcomponentsjs#186]
In IE, if I use Polymer and Highcharts together, it does not display things properly. Detailed descriptions are already posted on stackoverflow:

http://stackoverflow.com/questions/28205698/conflict-between-google-polymer-and-highcharts-library

The live demo is available on jsfildde:

http://jsfiddle.net/epavak4y/2/

The example codes used on jsfiddle is copy of highchart demo. (Noticed that Issue only occurs on IE. Tested with IE11)

**Comment by hcho112** [comment]
Here are the response from Highcharts Support team:

-------------------------------------------------------------------------

For some reason IE is not able to calculate the bounding box of text elements in this case. The problem arises on this line: https://github.com/highslide-software/highcharts.com/blob/master/js/parts/SvgRenderer.js#L616 .

An error is thrown on element.getBBox(), and the message is "Invalid calling object". You can debug this by adding a console.log(e.message) inside the catch statement.

Why this happens is another case. The element is an SVG text element, and other browsers have no problem with it. You could take this back to the Polymer developers so they can take it further.

For the records, I have tried rendering Highcharts to hidden or disconnected nodes, but that too works well, so it is not the reason why the elements don't have a bounding box: http://jsfiddle.net/highcharts/721to3sj/

----------------------------------------------------------------------------------------------------------------------------

**Comment by jmesserly** [comment]
this is strange... your example is working for me on Win 8.1 IE 11. Not sure why I'm seeing something different than you are. but http://jsfiddle.net/epavak4y/2/ displays the chart for me

**Comment by jmesserly** [comment]
the other link http://jsfiddle.net/highcharts/721to3sj/ also works

**Comment by hcho112** [comment]
Thank you for your e-mail.

The image example I have posted on stackoverflow is actual image of my
code. (I should have uploaded image of demo to avoid confusion.. my
apologies)

Here are the issued output.
Tested in Windows 8.1 IE 11.

[image: Inline image 1]

Noticed that orientation of chart labels and hover panel is corrupted.

Compare to IE, In Chrome:

[image: Inline image 3]

Noticed that label is properly oriented along with hover panel display
nicely.

As you saw in these two images, they are identical codes.

Furthermore, I only used legit libraries that are well used among many web
developers.

I do understand that Chrome supports HTML import natively and
webcomponents.js isn't really get executed.

Only thing I could think of is that webcomponents.js is doing something..


Thank you for reviewing the issue

**Comment by hcho112** [comment]
It's been a while since I made my last comment and no sign of review.. has current issue been reviewed..?

**Comment by addyosmani** [comment]
Both examples are working here, tested in Windows 8 with IE11:

http://jsfiddle.net/epavak4y/2/ 
http://jsfiddle.net/highcharts/721to3sj/ 

I will say: given that there's a lot of library code involved here, we may not be able to debug this further without a reduced test case that demonstrates what is breaking. My tests aren't (currently) showing any exceptions otherwise.

**Comment by karanahuja007** [comment]
Hi,
I am also facing the same problem.
I have tried Polymer with Dev Express, High-Charts, (X-Tag + Webcomponent.js)
But didn't get success.
Although chart is working in Firefox and Chrome.
Issue is only in IE 10, 11
Do we have any resolution to this problem?

**Comment by talee** [comment]
@addyosmani - I've reproduced this with Google Charts in IE 11 and created a tiny code example at http://embed.plnkr.co/ae6dHPlCUfcOSBDlqHyL/preview.  The code for the chart is taken straight from the Google developers site Material design line chart example.

Expected (screenshot):
![screen shot 2015-05-23 at 9 16 15 am](https://cloud.githubusercontent.com/assets/6241941/7784886/6a8875a6-012c-11e5-926c-c6be505f4de3.png)

Actual (screenshot):
![screen shot 2015-05-23 at 9 20 16 am](https://cloud.githubusercontent.com/assets/6241941/7784910/fb37b3f0-012c-11e5-8859-3b3ea5c9591c.png)

Exact same error.  Traces to a SVG text node calling getBBox() resulting in "Invalid calling object".
Line of code that throws the error (screenshot):
![screen shot 2015-05-23 at 9 19 25 am](https://cloud.githubusercontent.com/assets/6241941/7784906/e4c587a0-012c-11e5-86cd-5b2705cd954f.png)

The code loaded by Google's autoloader I think is https://www.google.com/uds/api/visualization/1.1/9543863e4f7c29aa0bc62c0051a89a8a/dygraph,webfontloader,format+en,default+en,ui+en,line+en.I.js.  Possibly it's using the same libraries.

**Comment by talee** [comment]
Looking at [Microsoft's documentation](https://msdn.microsoft.com/library/gg622930(v=vs.85).aspx), it may be related to calling a cached instance.  Selecting the node via $0 in the console and calling getBBox() on the fresh instance results in no error.  Possibly a polyfill is causing a stale reference.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
