### ISSUE TITLE
unresolved.js adds an inline-style tag to the DOM, breaking CSP.

### ISSUE THREAD

**Issue by scriptsrc** [webcomponents/webcomponentsjs#188]
unresolved.js adds an inline-style tag to the DOM, breaking CSP.

This is also an issue in the 0.10.1 version of web_components in the dart repository:
https://pub.dartlang.org/packages/web_components

https://github.com/webcomponents/webcomponentsjs/blob/e49de932c97ec336c6e1b106319a582e07d7385d/src/WebComponents/unresolved.js#L22

```
var style = document.createElement('style');
style.textContent = ''
  + 'body {'
  + 'transition: opacity ease-in 0.2s;'
  + ' } \n'
  + 'body[unresolved] {'
  + 'opacity: 0; display: block; overflow: hidden; position: relative;'
  + ' } \n'
  ;
var head = document.querySelector('head');
head.insertBefore(style, head.firstChild);
```

**Comment by vossad01** [comment]
Is this considered a bug?  I had hoped `webcomponents.js` would work with CSP [because Polymer indicates it runs under CSP](https://www.polymer-project.org/resources/faq.html#csp); though that seems currently not to be the case.

If webcomponetjs's intentions are to maintain support CSP, I may be able to temporarily relax our requirements.  Otherwise, we will need to forgo webcomponents and Polymer.

**Comment by ephaee** [comment]
What are those styles supposed to do?
When does the body element have an unresolved attribute?

**Comment by monkeysecurity** [comment]
Hmm. I opened this a while ago.  I am no longer familiar with the context.  Not sure if it's still an issue, or what those styles do.

**Comment by ephaee** [comment]
These CSS selecotrs target ```body``` and ```body[unresolved]```. I am not sure how body ever can have the attribute unresolved. What does this script solve? 
This does not make sence IMO and I would love if webcomponents polyfill would not insert a ```<style>``` element. Actually I think this script should be removed completely:  
https://github.com/webcomponents/webcomponentsjs/blob/master/src/WebComponents/unresolved.js

**Comment by ebidel** [comment]
body[unresoved] is a polyfill feature to mimic custom elements `:unresolved` pseudo element and is useful for controlling visual FOUC while elements upgrade. See https://github.com/webcomponents/webcomponentsjs/issues/230#issue-60288516r

For CSP environments that do not want to use `style-src 'self' 'unsafe-inline'`, we should probably have a way to turn this off or inject it using `<link rel="stylesheet" href">`

@azakus @garlicnation thoughts?

**Comment by morrisonlevi** [comment]
Bump. This appears to have been forgotten. I would like to use CSP with web components. Since it has been 2.5 years since this was last discussed maybe a viable alternative can be found?

**Comment by BAGELreflex** [comment]
Bump again.

Why would this not just apply a class to the created element, instead of doing a `var style = document.createElement("style");`? This is causing issues with production environments and implementing proper CSP.

**Comment by TimvdLippe** [comment]
Opened a tracking issue to remove `:unresolved` as a whole: #1020
