### ISSUE TITLE
Add browser support matrix to the README

### ISSUE THREAD

**Issue by nsisodiya** [webcomponents/webcomponentsjs#189]
It will be great if somebody can add list of browsers (min version) supported by webcomponent.js

**Comment by addyosmani** [comment]
Sure. We'll get this added soon

**Comment by addyosmani** [comment]
@garlicnation I'd like to go ahead and add a browser support matrix to the readme. Folks ask about this regularly and the old one (https://www.polymer-project.org/resources/compatibility.html) could be made more clear.

Shall we say the last two versions of all modern browsers? We can add notes around the odd exception (e.g where IE9 support may still be possible with the CE polyfill).

**Comment by zenorocha** [comment]
Duplicated #65

**Comment by addyosmani** [comment]
Closing as dupe. Thanks @zenorocha
