### ISSUE TITLE
ShadowDOM CSS-Selector Polyfill (::shadow) doesn't work.

### ISSUE THREAD

**Issue by silentHoo** [webcomponents/webcomponentsjs#193]
I've tested this on `Android 5.0.1 WebView` (which is Chromium 40), `Android 4.4.4` (which is Chromium 33) and `Chrome 40` for Desktop.

When I use `this.shadowRoot.querySelectorAll('paper-slider::shadow paper-progress::shadow #progressContainer')` in my custom Polymer element I'll get:

**`Android 5.0.1` + `Chrome 40`**: The `progressContainer` elements.
**Android 4.4.4**: `Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': 'paper-slider::shadow paper-progress::shadow #progressContainer' is not a valid selector.` from the `0.5.4` `webcomponents.js:2433`.

When I use `document.querySelectorAll('* /deep/ #progressContainer')` I'll get a a list with the elements but that will always select **all** elements in the whole document.

Is this a bug or does the given selector not work under the polyfill in this way?

**Comment by addyosmani** [comment]
So that we're testing for the correct behaviour you're seeing, could you supply us with a reduced test case (ideally on jsbin or jsfiddle) please?

**Comment by silentHoo** [comment]
Here's the jsfiddle for that: http://jsfiddle.net/f62v4vwz/

**Comment by TimvdLippe** [comment]
`::shadow` has been removed from the specification https://www.chromestatus.com/features/6750456638341120
