### ISSUE TITLE
Fix breaking unit test suite

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponentsjs#194]
Using recent versions of web-component-tester, I haven't been able to get our unit tests passing over the last few releases. I'd be interested in someone else from the team verifying this is the case for them too.

This will help with the CI explorations @garlicnation is looking at atm, but also help us ensure the stability of our builds when looking at new PRs.

**Comment by addyosmani** [comment]
Verified failing tests:

* Document: document.registerElement attachedCallback, detachedCallback 
* Document: document.registerElement get reference, upgrade, rewrap 

These are failing in Chrome, FF and Safari for me. Untested in IE.

**Comment by garlicnation** [comment]
I've been working on getting karma running the wct tests. I'm going to work now on fixing these regressions and hopefully identifying where they were introduced.

**Comment by addyosmani** [comment]
Thanks @garlicnation! That's going to help a ton when verifying how safe new patches are.

**Comment by TimvdLippe** [comment]
Should be fixed now.
