### ISSUE TITLE
Firefox error on webcomponents.js with angularJS ng-repeat-start

### ISSUE THREAD

**Issue by pienikrz** [webcomponents/webcomponentsjs#195]
I put problematic code to http://jsbin.com/pimiji/1/edit?html,js,console,output and error description on http://stackoverflow.com/questions/28466622/polymer-with-angularjs-ng-repeat-start-ng-repeat-end-firefox-issue

**Comment by TimvdLippe** [comment]
This appears to be resolved now: http://jsbin.com/viharix/edit?html,js,console,output
