### ISSUE TITLE
IE 9 HTMLImport external CSS file problem

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#203]
I have a mini test site in a folder below root:

viz3\
viz3\js
viz3\css
viz3\components

My test page is in viz3\import-page.html

``` html
<html lang='en'>

<head>
    <meta charset='UTF-8'>
    <title>import test</title>
    <script type='text/javascript' src='js/webcomponents-lite.js'></script>
    <link rel='import' href='components/test-file.html' />
    <script>
    var XFooPrototype = Object.create(HTMLElement.prototype);
    XFooPrototype.createdCallback = function () {
        this.textContent = "I'm an x-foo!";
    };
    var XFoo = document.registerElement('x-foo', {
        prototype: XFooPrototype
    });
    </script>
</head>

<body>
    <x-foo></x-foo>
</body>

</html>
```

webcomponents-lite.js version 0.5.3 is in viz3\js\webcomponents-lite.js

An HTML Import file (with a single external CSS file link in it) is in viz3\components\test-file.html

``` html
<link href="../css/test.css" media="all" rel="stylesheet" type="text/css" />
```

And finally a single rule to color the text of x-foo red in viz3\css\test.css

``` html
x-foo { color: red; }
```

This test works on Chrome and on IE 11.  But it fails on IE 9.  The problem seems related to how the HTMLImport polyfill is patching in the link.  Here's the network log in IE 9 showing the apparent glitch:

**IE 9** -- note the initial (aborted) attempt to GET test.css from the wrong location

| URL | method | result |
| --- | --- | --- |
| /viz3/import-page.html | GET | 200 |
| /viz3/js/webcomponents-lite.js | GET | 200 |
| /viz3/components/test-file.html | GET | 200 |
| /css/test.css | (Aborted) |  |
| /viz3/css/test.css | (Aborted) |  |
| /viz3/css/test.css | GET | 200 |

**IE 11**

| URL | method | result |
| --- | --- | --- |
| /viz3/import-page.html | GET | 200 |
| /viz3/js/webcomponents-lite.js | GET | 200 |
| /viz3/components/test-file.html | GET | 200 |
| /viz3/css/test.css | GET | 200 |

IE 9 -- note the text is black, not red
![image](https://cloud.githubusercontent.com/assets/2102919/6202040/e69c43a6-b49d-11e4-9ce4-e1a34a6751d7.png)

IE 11 -- note the text is red, as expected
![image](https://cloud.githubusercontent.com/assets/2102919/6202041/ef1a01bc-b49d-11e4-8fa7-81aec877217d.png)

**Comment by Jeff17Robbins** [comment]
Problem reproduced using webcomponents-lite.js version 0.5.4.

*loaded* (line 978) calls *makeDocument*.  On IE 9, the assignment to doc.body.innerHTML causes the erroneous load (by the browser, not by the polyfill) using the wrong path.

```javascript
doc.body.innerHTML = resource; 
```



When *loaded* calls *parse.parseNext()*, that works its way to *parseLink*, and this assignment:

```javascript
linkElt.href = linkElt.href;
```

which causes the abort and correct load, by the browser.  But apparently too late or not a good thing for IE 9, since the css rule doesn't work.


line 978
```javascript
    loaded: function(url, elt, resource, err, redirectedUrl) {
      flags.load && console.log("loaded", url, elt);
      elt.__resource = resource;
      elt.__error = err;
      if (isImportLink(elt)) {
        var doc = this.documents[url];
        if (doc === undefined) {
          doc = err ? null : makeDocument(resource, redirectedUrl || url);
          if (doc) {
            doc.__importLink = elt;
            this.bootDocument(doc);
          }
          this.documents[url] = doc;
        }
        elt.import = doc;
      }
      parser.parseNext();
```

line 1013
```javascript
  function makeDocument(resource, url) {
    var doc = document.implementation.createHTMLDocument(IMPORT_LINK_TYPE);
    doc._URL = url;
    var base = doc.createElement("base");
    base.setAttribute("href", url);
    if (!doc.baseURI) {
      Object.defineProperty(doc, "baseURI", {
        value: url
      });
    }
    var meta = doc.createElement("meta");
    meta.setAttribute("charset", "utf-8");
    doc.head.appendChild(meta);
    doc.head.appendChild(base);
    doc.body.innerHTML = resource;
```


line 812
```javascript
    parseLink: function(linkElt) {
      if (nodeIsImport(linkElt)) {
        this.parseImport(linkElt);
      } else {
        linkElt.href = linkElt.href;
```

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
