### ISSUE TITLE
[ShadowCSS] Wrong handling of prefix attributes ([attr^=value])

### ISSUE THREAD

**Issue by vicb** [webcomponents/webcomponentsjs#207]
If a style contains an `[attr^=value]` selector, the "^" will be removed in the output.

This happens because `scopeCssText()` calls `convertShadowDOMSelectors()` which replaces all `shadowDOMSelectorsRe` with a space. `/\^/g` is the 2nd regexp in this array.

Side question: what are the `^` and `^^` selectors ?

**Comment by jmesserly** [comment]
> Side question: what are the `^` and `^^` selectors ?

they were the "cat and hat" selectors: https://github.com/FrontenderMagazine/the-cat-and-the-hat-css-selectors/blob/master/eng.md, older names for ::shadow and /deep/.

**Comment by vicb** [comment]
"they **were**" does it mean that they are deprecated ?

**Comment by jmesserly** [comment]
yes

**Comment by vicb** [comment]
Ok, thanks for the explanations.

Do that mean that they should be removed from the `shadowDOMSelectorsRe` as a simple fix or do we want to keep them ?
