### ISSUE TITLE
webcomponents-lite bower package

### ISSUE THREAD

**Issue by adidahiya** [webcomponents/webcomponentsjs#218]
Any chance you will publish a separate bower package that points to `webcomponents-lite.js` in its main entry instead of `webcomponents.js`? I'd like to pull in the lite version via bower & wiredep but don't want to use [overrides](https://github.com/taptapship/wiredep#bower-overrides).

If this is not a possibility, then I will probably publish a `webcomponents-lite` package myself.

**Comment by addyosmani** [comment]
Is there a reason wiredep `overrides` aren't feasible here? It's catered to pretty much exactly what you're trying to achieve. 

We typically try to just maintain a single primary package for both the individual and compiled full/lite polyfill builds. I don't believe the maintenance overhead of managing another separate package in the release pipeline is quite yet justified here, but interested in @garlicnation's thoughts.

**Comment by addyosmani** [comment]
@garlicnation IIRC you discussed this idea during the team sync today. Should we a lite package be made available for Bower users in the short term?

**Comment by adidahiya** [comment]
wiredep overrides work well at the app-level (top level), but not so much at the library level because you have to re-declare the override when you use that library. Also overrides can lead to a diamond dependency problem, which we wish to avoid.

**Comment by addyosmani** [comment]
In our team sync today we decided to go ahead with a webcomponents-lite bower package, pending a few discussions on release process. @garlicnation is leading this up.

**Comment by adidahiya** [comment]
sounds good. thanks for the update :+1:

**Comment by garlicnation** [comment]
bower install webcomponents/webcomponents-lite now gives just the built polyfill.
