### ISSUE TITLE
Polymer.import callback gets called even when path to HTML file is invalid

### ISSUE THREAD

**Issue by akutamruta** [webcomponents/webcomponentsjs#219]
Polymer.import(['/path to html file'], function callback () {
   console.log('hello from loaded import');
});

If the path mentioned in invalid, then there is an error loading the HTML import. In this case the callback should not be called. In the above example, "hello from loaded import" will get printed on the console when path is invalid

**Comment by IntranetFactory** [comment]
I'm not sure if the change is ok - in the original version the callback gets the errorImports and can handle the error condition. With your change the callback is not called for errors and therefore won't be able to react on errors any longer.

**Comment by akutamruta** [comment]
Makes sense. I agree that the callback should be responsible for handling the error condition. I will make the change in polymer.js. Thanks :)

**Comment by addyosmani** [comment]
Thanks @akutamruta. Agree we should try to ensure the callback continues to get the `errorImports` included before landing this.

**Comment by garlicnation** [comment]
This is working as intended. In your callback you can check the argument's errorImports and loadedImports arguments to determine if the import loaded successfully.
