### ISSUE TITLE
HTMLDocument.prototype.__proto__ === Document.prototype

### ISSUE THREAD

**Issue by j03m** [webcomponents/webcomponentsjs#224]
After webcomponents.js is evaluated this is no longer true. If you have document extensions that occur after this evaluations, they won't show up in HTMLDocument. Surmountable, but highly unexpected.

**Comment by garlicnation** [comment]
This isn't true for me in FF, Safari, and chrome. Are you experiencing the issue in IE, or can you provide a minimal reproduction?

Note that in cases where we mess with the prototype chain, you should always be able to find the original prototype by walking __proto__ repeatedly. For example, all Polymer elements still have  `HTMLElement` in their prototype chain.

**Comment by jmesserly** [comment]
could be an issue with ShadowDOM polyfill?
https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/Document.js#L299

I think the comment is that HTMLDocument shouldn't really exist (per spec), which seems to match: https://html.spec.whatwg.org/multipage/dom.html#the-document-object

anyway, I think it wouldn't be a big deal to add a fake HTMLDocument to the chain, if you wanted. 
So we could accept a patch along the lines of:

```diff
-registerWrapper(window.HTMLDocument, Document);
+// emulate non-standard HTMLDocument
+function HTMLDocument(node) {
+    Document.call(this, node);
+}
+HTMLDocument.prototype = Object.create(Document.prototype);
+registerWrapper(window.HTMLDocument, HTMLDocument);
```

... assuming it passes tests :)

Note, nothing can fix: `document instanceof Document`, as it's impossible to fix the `document` accessor. You need something like `ShadowDOMPolyfill.wrap(document) instanceof Document` to get the wrapped one.
