### ISSUE TITLE
document.createTreeWalker always throws exception 

### ISSUE THREAD

**Issue by eeid26** [webcomponents/webcomponentsjs#229]
see example
http://jsbin.com/wawuxuxibu/2/edit

the error is
TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.

PR to resolve this issue
https://github.com/webcomponents/webcomponentsjs/pull/227

**Comment by jmesserly** [comment]
yeah, this was originally just skipped on the theory it's not a super common API. But still good to have these things added

**Comment by jmesserly** [comment]
should be fixed now
