### ISSUE TITLE
unresolved.js broken

### ISSUE THREAD

**Issue by IntranetFactory** [webcomponents/webcomponentsjs#230]
`<body unresolved>` was used to avoid FOUC when using the polyfill (https://www.polymer-project.org/docs/polymer/styling.html#fouc-prevention)

unresolved.js adds the required style for FOUC to head, but the unresolved attribute is never removed.

In the past Polymer removed the unresolved attribute, but Polymer 0.8 doesn't remove it any longer.

Not sure if this is the right solution but when adding `removeAttribute' after line 230
https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/base.js#L230

```
  rootDocument.dispatchEvent(evt);
  document.body.removeAttribute('unresolved');
```

FOUC seems to work as before.

**Comment by garlicnation** [comment]
This should be solved by either the library using webcomponentsjs, or the user. By not removing the unresolved attribute in the polyfill, we give time for a library to setup bindings, rendering, etc without a FOUC,
