### ISSUE TITLE
content doesn't refresh when attribute change

### ISSUE THREAD

**Issue by pienikrz** [webcomponents/webcomponentsjs#241]
I have a simple component

```
<polymer-element name="test-component">
    <template>
        <content select="div[order='1']"></content>
        <content select="div[order='2']"></content>
        <content select="div[order='3']"></content>
        <content select="div[order='4']"></content>
        <content select="div[order='5']"></content>
        <content select="div[order='6']"></content>
    </template>
    <script>
    Polymer('test-component', {
    });
    </script>
</polymer-element>
```

which I use on a simple page:

```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <script src="webcomponents/webcomponents.js"></script>
        <script src="polymer/polymer.js"></script>
        <link href="test-component.html" rel="import">
    </head>
    <style>
    </style>
    <body>
        <test-component>
            <div order="1" onclick="this.setAttribute('order', '4');"> Div 1</div>
            <div order="2"> Div 2</div>
            <div order="3"> Div 3</div>
            <div order="4"> Div 4</div>
            <div order="5"> Div 5</div>
            <div order="6"> Div 6</div>
        </test-component>
    </body>
</html>
```

When I click on first div, it's order attribute change to "4" in all browser but only in Chrome the output is changing from:

```
Div 1
Div 2
Div 3
Div 4
Div 5
Div 6
```

to

```
Div 2
Div 3
Div 1
Div 4
Div 5
Div 6
```

**Comment by adko-pl** [comment]
I have the same problem, @addyosmani  any estimates when this will be fixed?

**Comment by jmesserly** [comment]
fwiw, the code that's supposed to handle this:
https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/ShadowRenderer.js#L611
used from: https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/Element.js#L92

maybe it's failing to match that selector?
https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/ShadowRenderer.js#L487

**Comment by jmesserly** [comment]
hmm, when I ran that query on your selector, it seemed to work.
What might be happening: onclick="this.setAttribute('order', '4');" is giving you an unwrapped ShadowDOM node. That won't work, and we can't fix it in polyfill. Try onclick="ShadowDOMPolyfill.wrap(this).setAttribute('order', '4');"

**Comment by pienikrz** [comment]
@jmesserly Thanks for response. ShadowDOMPolyfill.wrap(this).setAttribute('order', '4'); work almost perfectly. Problems start when I try to embed test-component inside another polymer component. Example:

html page

	<!DOCTYPE html>
	<html>
		<head>
			<meta http-equiv="content-type" content="text/html;charset=utf-8">
			<script src="webcomponents/webcomponents.js"></script>
			<script src="polymer/polymer.js"></script>
			<link href="outer-test-component.html" rel="import">
			<link href="test-component.html" rel="import">
		</head>
		<body>
			Nested component doesn't work:
			<outer-test-component></outer-test-component>
			</br>
			Component set directly in html page work fine:
			<test-component>
				<div order="1" onclick="wrap(this).setAttribute('order', '4');"> Div 1</div>
				<div order="2"> Div 2</div>
				<div order="3"> Div 3</div>
				<div order="4"> Div 4</div>
				<div order="5"> Div 5</div>
				<div order="6"> Div 6</div>
			</test-component>
		</body>
	</html>

outer-test-component

	<polymer-element name="outer-test-component" noscript>
		<template>
			<test-component>
				<div order="1" onclick="wrap(this).setAttribute('order', '4');"> Div 1</div>
				<div order="2"> Div 2</div>
				<div order="3"> Div 3</div>
				<div order="4"> Div 4</div>
				<div order="5"> Div 5</div>
				<div order="6"> Div 6</div>
			</test-component>
		</template>
	</polymer-element>

Any idea why this code doesn't work ?

**Comment by jmesserly** [comment]
Hmm, not sure. Maybe have the event handler call a method, and put a breakpoint in it so you can debug and see what's happening, e.g. what happens when stepping into setAttribute? Or maybe try:
https://www.polymer-project.org/0.5/docs/polymer/polymer.html#declarative-event-mapping

Since one works and one doesn't, that's really helpful, because it means side-by-side stepping can see what is different about the two cases, in other words, why does one of them go off the rails?

**Comment by TimvdLippe** [comment]
`<content>` has been replaced with `<slot>` and the polyfill should work with updating the `slot` and `name` attributes.
