### ISSUE TITLE
webcomponents.js and qtip2.js cause HTML select element to malfunction

### ISSUE THREAD

**Issue by trevorhreed** [webcomponents/webcomponentsjs#248]
See [jsfiddle](http://jsfiddle.net/y61w1Ltm/)

When webcomponents.js and qtip2.js are on the same page, they cause HTML Select elements to malfunction, requiring a user to double-click in order open the select list. (Confirmed in IE 11)

**Comment by addyosmani** [comment]
I’ve confirmed this is an issue in at least Firefox.

Some quick notes. ShadowDOM (used in webcomponents.js) by it’s nature tries to add scoping to both the CSS and DOM. This means that technologies assuming a giant global scope (like jQuery) may not work out of the box with ShadowDOM and our shimming and some existing libraries may not just work with the polyfills today.

Could you let us know if using webcomponents-lite (just Custom Elements and Imports) has the same issue? http://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.4/webcomponents-lite.min.js

**Comment by trevorhreed** [comment]
Using webcomponents-lite seems to alleviate the problem.

**Comment by addyosmani** [comment]
Awesome. I'll make sure that we better document the limitations of the polyfills when it comes to third party libraries in the README.
