### ISSUE TITLE
webcomponents.js/CustomElements no longer works w/ commonjs require

### ISSUE THREAD

**Issue by brianleroux** [webcomponents/webcomponentsjs#249]
just updating and found the src tree has changed so code that once looked like this...

```javascript
// no longer works =.(
import CustomElements from 'webcomponents.js/CustomElements' 
```

thats ok, I can import the whole thing and just pull that one part but now it's throwing a script error :fearful: 

https://github.com/brianleroux/date-today

**Comment by garlicnation** [comment]
Does webcomponents.js/src/CustomElements work?

**Comment by brianleroux** [comment]
@garlicnation alas no, throws here

![screen shot 2015-03-18 at 4 53 42 pm](https://cloud.githubusercontent.com/assets/990/6721846/006ffdc2-cd8f-11e4-9103-08024b60e0f9.png)

**Comment by brianleroux** [comment]
(sorry too quick on the draw there)

I am compiling/concating w/ browserify and babeljs (which I recognize is not the designated path)

**Comment by addyosmani** [comment]
It’s unclear to me atm whether this is breaking on the line in your screenshot or there’s some additional info available independent of your babel setup. 

Can you clarify?

**Comment by garlicnation** [comment]
The pre-built sources you're looking for are in the tagged releases, such as https://github.com/webcomponents/webcomponentsjs/releases/tag/v0.6.0 .
