### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by nazar-pc** [webcomponents/webcomponentsjs#252]
0.6.0 is out, but no release notes this time because Polymer 0.6.0 was not released.
Maybe, you can start separating release notes for these 2 projects since they are separate now and was quite odd to see whats new in polyfills in Polymer repo?

**Comment by addyosmani** [comment]
I agree it makes sense to separate out the release notes for the polyfills. @garlicnation would you be opposed to us publishing the release notes in this repo for changes?

We could simply cross-reference or cross-post.

**Comment by garlicnation** [comment]
@addyosmani, I agree! Let's publish release notes here as well.

**Comment by addyosmani** [comment]
:tada:

**Comment by nazar-pc** [comment]
Thanks!

**Comment by addyosmani** [comment]
Re-opening just to remind us to get this done. We'll strive to get the notes published to webcomponents.org and cross-post wherever necessary.

**Comment by addyosmani** [comment]
@tjsavage Just to check-in. Are you authoring the release notes for this atm, or are @garlicnation or I taking care of that? :)

**Comment by tjsavage** [comment]
Release notes for this polyfill release are now published here: http://webcomponents.org/articles/polyfills-0-6-0/

We'll continue publishing the release notes for webcomponents.js separately from Polymer going forward.
