### ISSUE TITLE
Safari fails to load imported script when type is specified.

### ISSUE THREAD

**Issue by muymoo** [webcomponents/webcomponentsjs#273]
Example project here: https://github.com/muymoo/html-imports-safari-bug
Originally found on SO: http://stackoverflow.com/questions/29291578/difficulty-using-html-import-for-javascript-dependencies-with-polymer-on-firefox

Safari fails to load a file with a `<script>` tag with a type

 `<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>`

but works when the type is removed

`<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>`

`_` is not available in the former case.

Is this expected?

**Comment by azakus** [comment]
Should add another line for "application/javascript" here: https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/parser.js#L38
