### ISSUE TITLE
Release 0.6.0 does not conform to its own release notes

### ISSUE THREAD

**Issue by cobalamin** [webcomponents/webcomponentsjs#275]
See https://github.com/webcomponents/webcomponentsjs/issues/180#issuecomment-89485977

The release at https://github.com/webcomponents/webcomponentsjs/releases/tag/v0.6.0 does not include everything noted in its release notes. I'm still getting "flags.log.split no longer throws an error". The release points to commit https://github.com/webcomponents/webcomponentsjs/commit/af3bdd38cc9374623d3ec961b003bb0b5d2a26a7 , which does not include the changes made in https://github.com/webcomponents/webcomponentsjs/commit/bc7afc1f1fc8811247eaaa1eb0309c46f2360e47 .

**Comment by dtracers** [comment]
I am glad I am not the only person who saw this.  I thought I was going crazy.

**Comment by addyosmani** [comment]
The release notes have been updated to point to the changelog between 0.5.5 and 0.6.0. Can you verify if you're still seeing issues?

https://github.com/webcomponents/webcomponentsjs/releases

**Comment by cobalamin** [comment]
I `bower install`ed `0.6.0` again and it seems to include the change I pointed out as missing now. Seems to be fixed to me.
