### ISSUE TITLE
ShadowDOM.js causing unclosed img tags in XHTML

### ISSUE THREAD

**Issue by shaunnetherby** [webcomponents/webcomponentsjs#278]
If I create an XHTML document and create and add img tags via JavaScript the resulting documents img tag is unclosed if I have ShadowDOM.js imported.  

Here is a jsfiddle to demonstrate the unclosed img tag with ShadowDOM.js included: http://jsfiddle.net/L2xr59gg/5/ 
Here is a jsfiddle to demonstrate the closed img tag when only webcomponentjs-lite is included: http://jsfiddle.net/L2xr59gg/4/

**Comment by azakus** [comment]
Looks like innerHTML and outerHTML don't check the doctype. Should be a pretty simple fix.

**Comment by azakus** [comment]
Actually, HTML and XHTML share a namespaceURI, so your example is not actually making an XHTML document, but rather an HTML4 document.

You would need a DTD to make a real XHTML document

**Comment by shaunnetherby** [comment]
Good point.  I was trying to strip my example down and I think I lost some stuff.  Here is an example with a doctype.  This may be a different bug because now ShadowDOM.js fails on the third argument of createDocument.

Working with a doctype:
http://jsfiddle.net/L2xr59gg/9/

ShadowDOM.js failing on 3rd argument of createDocument:
http://jsfiddle.net/L2xr59gg/8/
