### ISSUE TITLE
(parent) document.baseURI changed to baseURI of child document in FF (HTMLImports)

### ISSUE THREAD

**Issue by DestyNova** [webcomponents/webcomponentsjs#287]
When loading a child document with the HTMLImports polyfill in Firefox (38.0a2), the parent document baseURI is changed. This should not happen, and doesn't seem to be the case in Chrome.

I've set up an example testcase [here](http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/). The following is printed to the console in Firefox:

```
"Creating link object..." test-import.js:2:4
"document._currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/child/embed.html" embed.html.js:2:6
"document.currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/" embed.html.js:3:6
"HTMLImportsLoaded event triggered." test-import.js:10:8
"document.baseURI (should be .../index.html): http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/child/embed.html" test-import.js:20:8
GET 
http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/test.png [0ms]
GET 
http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/child/test.png [HTTP/1.1 200 OK 10ms]
```

(I have no idea what's going on with the second last GET request at the end... this may be related to the strange behaviour in Chrome.)

This is what Chrome prints:

```
document._currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/child/embed.html
embed.html:10 document.currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/child/embed.html
test-import.js:10 HTMLImportsLoaded event triggered.
(program):2 document._currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/
(program):3 document.currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/
(program):2 document._currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/
(program):3 document.currentScript.ownerDocument.baseURI: http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/
test-import.js:20 document.baseURI (should be .../index.html): http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/
http://computing.dcu.ie/~omacfh/html-imports/testcase-shouldnt-change-baseURI/test.png Failed to load resource: the server responded with a status of 404 (Not Found)
```

This seems to be the opposite scenario -- the parent baseURI is unchanged, but the imported child document's baseURI is not set appropriately and so it loads things from the wrong place. Do I need to load the shadow DOM library as well?

**Comment by DestyNova** [comment]
I tested with "webcomponents.min.js" instead, which I believe includes the Shadow DOM code, and the behaviour seems to be the same in both browsers.

**Comment by DestyNova** [comment]
Digging a little deeper, in src/HTMLImports/importer.js:132 a base tag is created and added to the new document. When the imported document is added to the page, the presence of the base tag changes the baseURI for the whole document, which breaks relative links.

Unfortunately it seems that there can only be one baseURI for the entire document. I can't see a workaround right now except disabling the base tag creation and changing every link in the child document to be absolute.
If anyone has insight into a better solution or workaround, I'd really appreciate it.

**Comment by azakus** [comment]
Why are you inserting the entire document of the import into your main document? Just clone the parts you would need, such as stylesheets or the children of `<body>` in the import.

**Comment by DestyNova** [comment]
Hi Azakus, that's interesting. I didn't do it like this because the documentation for HTML Imports didn't suggest that such a thing was necessary. If I restore the base element creation code, will the children of the imported body still have their relative links resolved properly, without altering the importing document baseURI?

**Comment by DestyNova** [comment]
Ok, I eventually got it working by only cloning the children of the imported head and body (skipping any base tags in the head, as this causes the parent document baseURI to change as described above) and appending them to the containing div.
However, without the base tag, none of the relative src/href attributes in the child document was correct. I solved this by walking through all cloned nodes before adding them to the parent document, like this:

```
     function replaceRelativeUrls(node, baseURI) {
       var basePath = getBasePath(baseURI),
           all = node.querySelectorAll('*');
       for(var i = 0; i < all.length; i++) {
         // replace src attribs
         if(all[i].hasAttribute('src')) {
           var relativeSrc = all[i].getAttribute('src');
           if(!relativeSrc.startsWith('http') && !relativeSrc.startsWith('//')) {
             all[i].src = basePath + relativeSrc;
           }
         }
         // replace href attribs
         if(all[i].hasAttribute('href')) {
           var relativeHref = all[i].getAttribute('href');
           if(!relativeHref.startsWith('http') && !relativeHref.startsWith('//')) {
             all[i].href = basePath + relativeHref;
           }
         }
       }
     }

     function getBasePath(baseURI) {
       if(baseURI === undefined || baseURI == null || baseURI == '')
         return "";
       else
         return baseURI.substr(0, baseURI.lastIndexOf('/') + 1);
     }
```

This all feels terribly hacky, but it seems to work for now at least. Thanks, azakus, for the advice. If you have any suggestions for how to do this better, I'd appreciate it.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
