### ISSUE TITLE
webcomponents.js breaks IE touch events

### ISSUE THREAD

**Issue by miguelmota** [webcomponents/webcomponentsjs#290]
Here I have a [JSFiddle](http://jsfiddle.net/xL78aq4u/) that includes hammer.js and webcomponent.js. None of the touch events (ie tap), get fired in Internet Explorer 11 when webcomponents.js is included.

[Issue on Hammer.js](https://github.com/hammerjs/hammer.js/issues/753)

**Comment by addyosmani** [comment]
Can you try this http://jsfiddle.net/u5rp3uxv/? I've switched it over to using webcomponents-lite, our build that doesn't include the Shadow DOM polyfills. This appears to be working fine in IE11.

**Comment by miguelmota** [comment]
@addyosmani Yes that works, thanks!
