### ISSUE TITLE
Exception in HTML import polyfill when importing a non-existent URL

### ISSUE THREAD

**Issue by plequang** [webcomponents/webcomponentsjs#292]
Hi,

We are importing dynamically HTML templates in our app, by adding `<link rel="import">` elements when needed.
This works fine except if we add an html import to a resource that does not exists, the polyfill fails with an exception. This exception prevent the "error" event to be raised on the import link, and we need this event to display an error message in such a situation.

I've created a simple jsbin to demonstrate the issue http://jsbin.com/hocasebaje/1.
When you click on the button, it tries to import a non existent html file.
The exception occurs in `_forDocumentTree` function, which tries to process a `null` document.
Note that with jsbin, there is also an assertion that fails in webcomponentsjs but I do not have this error when I run the same code locally.

I've not observed this behavior with a statically added import in the head section of the document.

I've tested with firefox so far, will try to test with safari.

**Comment by addyosmani** [comment]
I just tested your bin using the latest version of the polyfills and the `error` event is being fired correctly, displaying the oops message for both Firefox and Safari. Is there a particular exception being thrown for you?

**Comment by plequang** [comment]
That's really strange.
I've tested again with the jsbin, and the event is fire correctly and there is no exception.
But If I test the exact same code locally, or here http://plequang.github.io/test.html, I get the exception.
See below the screenshot of firebug :
![2015-04-24 22_45_43-cosmoz 3](https://cloud.githubusercontent.com/assets/5500311/7328217/f041df4e-ead3-11e4-96b8-ff67f621ffb0.png)

**Comment by TimvdLippe** [comment]
This has been fixed: http://jsbin.com/zoconor/edit?html,console,output
