### ISSUE TITLE
Version 0.6.1 isn't on npm

### ISSUE THREAD

**Issue by krampstudio** [webcomponents/webcomponentsjs#293]
Hi, it seems the last version hasn't been yet publish on npm. 
An `npm info webcomponents.js` shows me `0.6.0` as the latest version.

**Comment by addyosmani** [comment]
@garlicnation when we cut the 0.6.1 release, did we use one of Dan's scripts or did we manually roll it? For bumping the npm package we should just need to publish the tag IIRC.

**Comment by azakus** [comment]
Published.

**Comment by addyosmani** [comment]
Thanks @azakus!
