### ISSUE TITLE
[Chrome Browser Bug] CustomElement Inside Template Tag not working

### ISSUE THREAD

**Issue by nsisodiya** [webcomponents/webcomponentsjs#296]
@addyosmani  & other,
I am using customElement inside template tag, and it is not working in Chrome. However it is working fine in Firefox browser. (very strange)

**Comment by nsisodiya** [comment]
this works fine in Firefox   http://nsisodiya.js.org/WcBug296/
but In  Chrome it failed to work propertly. Please open it chrome & firefox to see difference.

**Comment by nsisodiya** [comment]
Source Code - https://github.com/nsisodiya/WcBug296

**Comment by jmesserly** [comment]
you're missing importNode, which brings the custom element into the main document:
```js
this.appendChild(templateNode.content.cloneNode(true));
```
should be
```js
this.appendChild(document.importNode(templateNode.content, true));
```
example: https://github.com/Polymer/polymer/blob/e4f64ff770b8c0673c65102a882e6cb37c38b1e8/test/html/polymer-import.html#L33

**Comment by nsisodiya** [comment]
Let me try the changes.
But how it is working well in Firefox ?

**Comment by nsisodiya** [comment]
Yup, is now working now.
Why do not you update cloneNode function so that both syntax starts working.
```js
Node.prototype.cloneNode = function(deep){
    return document.importNode(this, deep);
}
```

**Comment by jmesserly** [comment]
> But how it is working well in Firefox ?

Firefox does not have native support for Custom Elements. Some things are difficult to impossible to polyfill with perfect accuracy. The Custom Elements polyfill does not implement a separate registry for `<template>` content document.

> Why do not you update cloneNode function so that both syntax starts working.

Chrome is showing the correct specified behavior, which is implemented in Blink engine C++ code, not by the polyfill. So we can't really (and don't want to) change the cloneNode behavior in Chrome.
