### ISSUE TITLE
Assertion Failure when using removeChild()

### ISSUE THREAD

**Issue by bdkjones** [webcomponents/webcomponentsjs#297]
I have a `<link>` element named `oldLink` that is a child node of `<head>`. When I do the following:

```
oldLink.parentNode.removeChild(oldLink);
```

I get this result in my console:

![screen shot 2015-04-28 at 23 53 30](https://cloud.githubusercontent.com/assets/926566/7385913/4fedee48-ee02-11e4-9c5c-cd953514e085.png)

Removing webcomponents.js from the page solves the problem, as does switching to the `lite` version. 

### Affected Browsers

I have confirmed this in these browsers:

Safari 8.0.5 on OS 10.10.3
Firefox 37.0.2 on OS 10.10.3

The following browser is **not** affected and the call to `removeChild()` succeeds when using the full library:

Chrome 42.0.2311.90

I have not tested any other browsers.

### Version

I am using webcomponents.js 0.6.1. The same issue manifests in 0.5.5, so it does not look like a regression. 

### Better Error Messages

It might be a good idea to write more descriptive error messages than "Assertion failure". It might **seem** obvious to you guys that if you want to understand the assertion, you just go look at the source code for the library. But that is not helpful for outsiders. And a vague message like "Assertion failure" gives us nothing to Google to see how other folks have solved this problem. A more descriptive message of exactly **what** assertion failed would be much better.

**Comment by bdkjones** [comment]
I should also clarify: 

This is happening on a dead-simple test page. There is no jQuery (or any other JS library) involved. The page is this:

```
<!doctype html>
<html>
	<head>
		<script src="bower_components/webcomponentsjs/webcomponents.js"></script>
		<link rel='stylesheet' href='styles.min.css'>
		<link rel='import' href='import.html'>
	</head>
	<body >
		<h1>Lorem ipsum</h1>
	</body>
</html>
```

My script is targeting the first `<link>` element and attempting to remove it. It is removed successfully when webcomponentsjs is not included.

**Comment by bdkjones** [comment]
The issue does *not* occur when using `webcomponents-lite.js`. In this case, the element is removed successfully.

**Comment by bdkjones** [comment]
The issue does *not* occur in Chrome 42.0.2311.90. (However, I'm not sure if that's because Chrome has native support for HTML imports so that the polyfill is not being used in that browser.)

**Comment by bdkjones** [comment]
The issue **does** occur in Firefox 37.0.2. Again, switching to the `lite` version solves the problem in this browser as well.

**Comment by jmesserly** [comment]
oldLink is not a wrapped Shadow DOM Polyfill node. This can happen if you got it directly via the `document` property, which we cannot polyfill:
```js
// won't work! this is bypassing the polyfill
var oldLink = document.head.lastChild;
// assertion that catches the bug:
oldLink.parentNode.removechild(oldLink);
```
Instead use:
```js
// By calling a method, in this case querySelector, the polyfill can kick in (yay!)
var oldLink = document.querySelector('head').lastChild;
// no more assert
oldLink.parentNode.removechild(oldLink);
```

Unfortunately, there is no possible way to fix `document` or `document.head` in current browsers, as much as I would like to. Sadly that's the nature of polyfills :\

**Comment by jmesserly** [comment]
Oh, also, you can explicitly call `ShadowDOMPolyfill.wrap`, for example:
```js
oldLink = ShadowDOMPolyfill.wrap(oldLink)
```

**Comment by bdkjones** [comment]
Thanks!

The way I'm obtaining the `<link>` element is by starting from a `stylesheet` object, like this:

```
var styleSheetList = startDoc.styleSheets;
// Assume 'styleSheetList' has length 2
var sheet = styleSheetList[1];
var oldLink = sheet.ownerNode;
```

Is this the same issue? Also: the code I'm writing cannot assume that `webcomponents.js` is on the page. This code must be able to handle pages with and without webcomponents. In other words, I'm simply looking to make my code compatible with your project.

**Comment by bdkjones** [comment]
I have to work from the `stylesheet` object---that's the only way I have to access the `<link>` node. 

However, if I explicitly call `ShadowDOMPolyfill.wrap(oldLink)`, do I need to first check if this element has already been wrapped somehow? Or is it safe to call `.wrap()` on a node that has potentially already been wrapped?

**Comment by jmesserly** [comment]
> Is this the same issue? 

yeah, any combination of field accesses (including `[0]`), unfortunately. If there's a method call somewhere along the line we can kick in the polyfill :)

> do I need to first check if this element has already been wrapped somehow?

ah, yeah, there's wrapIfNeeded for that. BTW, I forgot to mention, there's actually just `window.wrap` which is equivalent to wrapIfNeeded:
https://github.com/webcomponents/webcomponentsjs/blob/4c5f21610c6cea02c74beaa3a25cd8075807ce31/src/WebComponents/shadowdom.js#L21

so maybe a workaround like:
```js
if (window.wrap) oldLink = window.wrap(oldLink);
```

**Comment by bdkjones** [comment]
Perfect. Just tested that and it solves the problem. Thanks for the quick help!
