### ISSUE TITLE
Cannot call getBBox() on wrapped SVGTextElement in Internet Explorer 11: Invalid calling object

### ISSUE THREAD

**Issue by talee** [webcomponents/webcomponentsjs#317]
webcomponents.js v0.7.1
Creating a more specific ticket of issue #186 as it's not related to any charting libraries.
Created a tiny code example at http://embed.plnkr.co/XvdXdq/preview:
    
      var svgNode = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
      var textNode = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      textNode.textContent = 'Hello world';
      textNode.setAttribute('y', 12);
      svgNode.appendChild(textNode);
      document.body.appendChild(svgNode);
      console.log(textNode.getBBox());

textNode.getBBox() throws a "Invalid calling object" in Internet Explorer 11, possibly due to cached pointer issue described in [Microsoft documentation](https://msdn.microsoft.com/library/gg622930(v=vs.85).aspx).  This essentially blocks much of SVG rendering with web components in IE.

Screenshot:
![screen shot 2015-05-23 at 3 31 34 pm](https://cloud.githubusercontent.com/assets/6241941/7785935/d7e06c10-0160-11e5-8007-b62fe5f5001a.png)

**Comment by talee** [comment]
Got more traction on this. I think there's an issue with the wrapper.js code during the registering of a super class's instance properties on to a GeneratedWrapper (constructor).  If an instance property is a method, instead of being ignored, it is being added as a getter/setter.

**Comment by jmesserly** [comment]
thanks again for tracking this down!

**Comment by talee** [comment]
No probs. Glad we got it resolved. Would this be built/merged into the Polymer dependent version as well (0.6.x tag)?

**Comment by jmesserly** [comment]
that'd be a question for @azakus maybe? I'm not super familiar with the release process.

**Comment by azakus** [comment]
We're all focused on I/O related things right now.
Probably next week before we make another release.
