### ISSUE TITLE
Opera errors thrown

### ISSUE THREAD

**Issue by smiffy6969** [webcomponents/webcomponentsjs#324]
Hi,

I have been looking to use webcompoennts.js for polyfilling lack of support in browser etc etc... I have been doing some testing on various browsers and for some reason I cannot get webcomponents.js to work with opera latest version.

"About Opera
Version information
Version 12.16 
Build 1860 
Platform Linux 
System x86_64, 3.16.0-31-lowlatency"

Now my reasons for wanting to use this by itself instead of framework a or b is immaterial at this point, suffice to say I am wanting to just patch up the 'not yet implemented' function sso I may build web components manually through html imports.

I have installed webcomponents.js using bower (V 0.7.2) although the actual latest release here is listed as 0.6.1, anyway, I rolled with it and can get good working web components implementation over IE9+ chrome and FF (without shadow dom).... This is great, then I start up opera and get this crap...

```
Uncaught exception: TypeError: Cannot convert 'constructor' to object Error thrown at line 341, column 10 in <anonymous function>(name) in http://localhost/localhost.paul/www/paul/framework/bower_components/webcomponentsjs/webcomponents.js:
    constructor.prototype[name] = function() {
called from line 340, column 8 in <anonymous function>(constructor) in http://localhost/localhost.paul/www/paul/framework/bower_components/webcomponentsjs/webcomponents.js:
    names.forEach(function(name) {
called from line 339, column 6 in forwardMethodsToWrapper(constructors, names) in http://localhost/localhost.paul/www/paul/framework/bower_components/webcomponentsjs/webcomponents.js:
    constructors.forEach(function(constructor) {
called from line 4216, column 4 in <anonymous function>(scope) in http://localhost/localhost.paul/www/paul/framework/bower_components/webcomponentsjs/webcomponents.js:
```

You get the idea.....

I have tried the minified version only to get a slightly different error, looks like hte imports are faling to load with an error about 'matches' being thrown.

I then went on to try the individual polyfills, I get similar errors for html import polyfill.

I thought maybe the issues was the version, so I rolled back to 0.6.1 as stated here as the latest release, I now get a different error in opera.

The end result is that no matter what concoction I try, opera always throws it's dummy way out the pram complaining about everything fro sun spots to solar flares, so my question is this.... Has anyone actually tested this on Opera?

Whilst I admit opera is at best, around 1.5% market share, knowing this issues exists stops me from migrating my JS from a commercial standpoint, and I so want to use web components, but on my grounds.

And please do not offer polymer or x-tags or any other framework as an answer, I have opera issues with imports that contain style tags in x-tags killing the custom element registration which is bizzare and polymer seem to drop support for things without even a second thought to the knock on (template if's).

I am not a fan of opera here.... just wanting to not alienate anyone on purpose (which I have a commercial incentive not to do).

regards

Paul

**Comment by jmesserly** [comment]
Hi Paul, thanks for writing this up. It looks like you're using Opera 12 (released 14 June 2012 according to Wiki). The latest stable version (just downloaded) reports Opera 29.0.1795.60. As far as I can tell, every functionality test is passing on latest Opera[1][2]. In general, we only support recent versions for auto-updating browsers. That said, we've accepted patches for older browsers, e.g. IE9 and older Firefoxes.

[1] you probably don't even need to include webcomponents.js to latest Opera. It looks like it has webcomponents support built in. e.g. http://caniuse.com/#feat=shadowdom

[2] one CustomElement test expects an exception thrown if an invalid custom element name is passed, Opera doesn't throw the exception. Chrome fails it too. Not a super important test, I think it's an issue with the polyfill being ahead of the implementation in Blink.

**Comment by smiffy6969** [comment]
Thanks for that... looks like the evergreen version of opera changed from opera to opera-stable (not sure when) so if you want to install opera you need to opt for opera-stable instead of opera..... genius!

So the version I had, was the older series, but still reports as the latest version (in that series)... why oh why does it not tell you there is a newer version.... total genius.

Thanks for taking the effort to reply to this, I hate opera to be honest, this just confirms that fact top me as different series of browsers or not, the version I had should not have said latest when it quite simply wasn't.

I was totally aware that it should support things natively, which is why I was confused when it didn't, and even more confused when it threw a wobbly on the webcomponents.js file even being added as a resource. The support for opera generally follows chrome I know being webkit based, although they do plan on switching to blink (may have happened by now for all I know).

Anyhow, thanks for taking the time to reply.

regards

Paul

**Comment by jmesserly** [comment]
No problem, glad you found a solution!
