### ISSUE TITLE
[CustomElements] `attributeChangedCallback` should not be invoked synchronously from other lifecycle callbacks

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#325]
Currently, calling `setAttribute` in the context of a lifecycle callback such as `createdCallback` causes the `attributeChanged` callback to be called synchronously.

Per http://w3c.github.io/webcomponents/spec/custom/#enqueuing-and-invoking-callbacks, the callback should be "enqueued" rather than called synchronously.  This results in different timing behavior between native and polyfill.

The following illustrates this timing difference:
http://jsbin.com/qahiduraje/1/edit?html,console,output

Running on Chrome results in 

```
"created start"
"created end"
"attribute changed"
```

Running on polyfill results in

```
"created start"
"attribute changed"
"created end"
```

The `setAttribute` implementation should ideally detect when it is being called from the context of another lifecycle callback, and in that case call the callback async; if not, call synchronously to maintain the approximation of "nanotask" timing.

**Comment by dogoku** [comment]
Any news on this issue?

**Comment by TimvdLippe** [comment]
This issue has been fixed: http://jsbin.com/zepasa/2/edit?html,console,output (working in Firefox with polyfill and Chrome)
