### ISSUE TITLE
[ShadowDOM] The `change` event should be stopped from bubbling

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#326]
Per the ShadowDOM spec, the `change` event should be stopped from bubbling through the shadow boundary: http://www.w3.org/TR/shadow-dom/#events-that-are-always-stopped

Typing then pressing enter has different behavior on Chrome vs. polyfill (change is caught outside the shadow root on polyfill, and not on native SD):
http://jsbin.com/rigifokuja/1/edit?html,console,output

The `change` event is [included in a blacklist in `eventMustBeStopped`](https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/events.js#L105) per that section of the spec, but it appears to only affect `event.path` calculation, not actual stopping of propagation.

Not sure if supporting this is feasible in the polyfill.

**Comment by TimvdLippe** [comment]
This appears to be fixed now: http://jsbin.com/tuhemejina/1/edit?html,console,output
