### ISSUE TITLE
:host attribute selector polyfill doesn't render correctly in Safari 7+

### ISSUE THREAD

**Issue by derekolson** [webcomponents/webcomponentsjs#332]
Having multiple elements with host attribute styles like :host([type="error"]) don't get rendered properly. It looks like the first element style registered on the page overrides any other similar host attribute styles on the page in Safari. 

See this JSBin: http://jsbin.com/locidoxira/1/edit

Renders correctly in Chrome 43 and Firefox 38, but not in Safari 7+

**Comment by TimvdLippe** [comment]
This should be fixed in shadycss, as we run our tests on Safari 9+, even with native implementation.
