### ISSUE TITLE
Full polyfill throws on Safari 8 preventing apps from loading

### ISSUE THREAD

**Issue by ebidel** [webcomponents/webcomponentsjs#344]
chromestatus.com:

<img width="1147" alt="screen shot 2015-07-10 at 7 26 11 pm" src="https://cloud.githubusercontent.com/assets/238208/8631925/df17adbe-2739-11e5-8c7d-17f8ba68878b.png">

pp.org

<img width="1151" alt="screen shot 2015-07-10 at 7 30 17 pm" src="https://cloud.githubusercontent.com/assets/238208/8631937/283b3e52-273a-11e5-9c89-cb1a198178ec.png">

webcomponents-lite does not throw. I assume it's somewhere in the full shadow dom polyfill.

**Comment by ebidel** [comment]
Can no longer repo. I'll reopen if I see anything weird.

**Comment by ansorg** [comment]
I see this in Safari 9 OS X and iOS9 beta on polymer-project.org 
And my own polymer-5 based webapp is now broken in iOS 9 due to this error
