### ISSUE TITLE
Wrong execution order in IE and FF with imports containing scripts

### ISSUE THREAD

**Issue by nippur72** [webcomponents/webcomponentsjs#347]
In IE11 and FF scripts contained in html imports are executed with wrong order, e.g.:

```HTML
   <link rel="import" href="file1.html">     
   <script src="file2.js"></script>
```
- in IE and FF: first executed is `file2` and then `file1` (**wrong**)
- in Chrome: first executed is `file1` and then `file2` (**correct**)

Is this supposed to be so, or it's a bug?

**Comment by sorvell** [comment]
This is true of HTML imports and scripts in the main document only and is a limitation of the HTMLImports polyfill. The polyfill provides an event which can be used to emulate the order of the native implementation in Chrome. Code loaded in the main document that depends on content in HTMLImports can listen for the `HTMLImportsLoaded` event. For example,

```
addEventListener('HTMLImportsLoaded', function() {
  // do stuff that depends on HTMLImports content
});
```

**Comment by nippur72** [comment]
I think we should add this to the "Known Issues" list in the `README.md`
