### ISSUE TITLE
webcomponents.js not working on Safari 9

### ISSUE THREAD

**Issue by fabiospada** [webcomponents/webcomponentsjs#348]
Tested on iOS 9 Beta 3 and OS X 10.11 Beta 3 with Safari 9.0

Here's the log using webcomponents.js v0.7.6
![untitled](https://cloud.githubusercontent.com/assets/6159065/8678270/e978d946-2a53-11e5-832e-5f484c945bc4.jpg)

webcomponents-lite.js seems to work fine

**Comment by azakus** [comment]
Oh good, Safari decided to break the spec again. Thanks for the heads up.

**Comment by azakus** [comment]
Hmm, can't reproduce with Webkit Nightly 186801. Guess I'll have to find a real Safari 9 beta to try.

**Comment by ebidel** [comment]
I saw this in https://github.com/webcomponents/webcomponentsjs/issues/344 as well but couldn't repo after a few hours

**Comment by fabiospada** [comment]
I found out that on OS X 10.11 Beta 2 works, maybe it's a bug in the version of WebKit used in the Beta 3?

Here's the version of each browser:

OS X 10.11 Beta 2
- Safari version: 9.0 (11601.1.35.2)
- WebKit version: 601.1.35

OS X 10.11 Beta 3
- Safari version: 9.0 (11601.1.37.1)
- WebKit version: 601.1.37

**Comment by azakus** [comment]
Looks like `SVGElement.prototype.ownerSVGElement` is no longer configurable in ios 9.

**Comment by fabiospada** [comment]
In the latest beta of iOS 9 and OS X 10.11 (beta 4) this bug seems to have been fixed.

Now is working.
