### ISSUE TITLE
[Shadow DOM] innerText is undefined in Firefox and IE

### ISSUE THREAD

**Issue by dnbard** [webcomponents/webcomponentsjs#356]
```html
<div id="shadow">1</div>

<script>
  //self.document is the root of Shadow DOM
  self.document.querySelector('#shadow').innerText = "Hello, World";
</script>
```

The component are added to document as Custom Element, wrapped in Shadow DOM.
It will work in Chrome but not in the Firefox or IE.
If I use `innerHTML` instead then it is going to be working everywhere.

If I try to access the `innerText` directly via the console then Browser will tell that this property is undefined.

**Comment by dnbard** [comment]
Had the Firefox that doesn't support WebComponents. 
With latest version (39) this bug is reproducible only on IE11.

**Comment by dnbard** [comment]
Heh, looks like Firefox should not have this property at all =)

**Comment by jmesserly** [comment]
oops, I just saw this. It sounds like you figured it out. But yeah, sounds like you want the [Node.textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) property. (I think innerText was an IE specific extension)
