### ISSUE TITLE
Cannot set id to HTMLImports in <script>

### ISSUE THREAD

**Issue by noopole** [webcomponents/webcomponentsjs#371]
&lt;script src="scripts/wc/HTMLImports.js" id="HTMLImports"></script>

will fail because of the id set to "HTMLImports": error line 610, flags is undefined.

It works with any other id.

**Comment by ebidel** [comment]
This is likely because the browser puts DOM ids on the JS global scope. The HTML Imports polyfill creates a global var, "HTMLImports", so there's a collusion. Please use another id.
