### ISSUE TITLE
Template polyfill innerHTML does not support <templates> in content

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#374]
Repro: http://jsbin.com/tiyepur/edit?html,console,output

**Comment by jmesserly** [comment]
FWIW, ShadowDOM handles this by intercepting the "content" getter:
https://github.com/webcomponents/webcomponentsjs/blob/51c337b2327ef63ee50ee1b69f50dc19966f1483/src/ShadowDOM/wrappers/HTMLTemplateElement.js#L66

But I guess that's not possible in -lite, so would need to walk the resulting DOM and fix up template contents. The latter approach is similar to what TemplateBinding does:
https://github.com/Polymer/TemplateBinding/blob/b46180bf156f68f5ac27af607def24be1ce57d0c/src/TemplateBinding.js#L216

**Comment by kevinpschaaf** [comment]
Yeah, the lite polyfill already has a `bootstrap` function that finds & upgrades templates, just needs to do this in the innerHTML case also. 

https://github.com/webcomponents/webcomponentsjs/pull/376

Solves repro: http://jsbin.com/vawecuwoto/1/edit?html,console
