### ISSUE TITLE
Imported javascript object is not visible in 'main' file, only in another import 

### ISSUE THREAD

**Issue by bushuyev** [webcomponents/webcomponentsjs#381]
Imported javascript object is not visible in 'main' file, only in another import  in IE11 and FF. In chrome it's visible everywhere.  

The plnkr:
http://plnkr.co/edit/oqzWxrZup6Ei3iduJsS7?p=preview (http://embed.plnkr.co/oqzWxrZup6Ei3iduJsS7/preview)

in produces following console output:
chrome: 

(index):11 index, MyClass=[object Object]
import2.html:2 import2, MyClass=[object Object]

firefox (and same in IE):
ReferenceError: MyClass is not defined oqzWxrZup6Ei3iduJsS7:11:8
import2, MyClass=[object Object]

**Comment by noopole** [comment]
The HTML Imports are asynchronous, so you should attach an onload event handler on the import element before performing the test :
    `function test()
    {
        console.log('index, MyClass='+MyClass);
    }`
` </script>`
` <link rel="import" href="import2.html" onload=test()>`

**Comment by bushuyev** [comment]
Oh, yes, asynchronousness again. Thank you for clarifying!
