### ISSUE TITLE
`attachedCallback` goes into infinite loop

### ISSUE THREAD

**Issue by nazar-pc** [webcomponents/webcomponentsjs#388]
Basically `this.parentNode.appendChild(this)` should not cause triggering `attachedCallback` (it doesn't in Chromium with native support).
Otherwise simple trick (using Polymer) causes infinite loop:

``` coffeescript
Polymer(
    'is' : 'my-element'
    attached : ->
        document.body.parentNode.appendChild(@)
)
```

**Comment by azakus** [comment]
Why would you want to append an attached element in the first place?

**Comment by nazar-pc** [comment]
I have modal dialog element. When it is opened I'm applying blur effect to `<body>`, so, I'm moving element after `<body>` right from the beginning to avoid blurring of modal content.
[Here is source code](https://github.com/nazar-pc/CleverStyle-CMS/tree/master/includes/html/CleverStyle%20Widgets/cs-section-modal)
Basically relevant part is:
```coffeescript
...
	attached : ->
...
		body.parentNode.appendChild(@)
...
```

Well, it is indeed possible to check current parent, position of element among other parent children and so on, but I like elegant solutions and this particular works fine under native Shadow DOM.
The only thing I worry about PR is that, probably, there are some other cases when similar fixes as for `appendChild()` should be made.

**Comment by TimvdLippe** [comment]
Closing this as it was part of v0. If you are still encountering this issue in v1, please open a new issue which includes a reproduction case in JSBin.
