### ISSUE TITLE
attributeChangedCallback not triggered with changes made to dataset

### ISSUE THREAD

**Issue by dougellison** [webcomponents/webcomponentsjs#391]
In IE11 / Firefox 38.0.5 (using the polyfill) attributeChangedCallback does not get triggered with changes made to dataset.

A JSFiddle is here: https://jsfiddle.net/twmsnojt/1/  showing the behavior.

Normally when

```
var element = document.querySelector('some-element');
element.dataset.test = 1;  
```

Adds an attribute called 

```
data-test='1' 
```

to the selected element.  In Chrome this triggers the attributeChangedCallback.  Additionally if using a MutationObserver (instead of the attributeChangedCallback) modifying the dataset triggers in all browsers.

**Comment by sylvainlb** [comment]
I still have the same issue with Firefox 49.
Using setAttribute("data-xxx") does the trick, but it should be at least documented.

**Comment by mortenson** [comment]
I'm not seeing the `attributeChangedCallback` get fired in Firefox when changing any attribute, not just dataset attributes. Anyone else?

**Comment by sylvainlb** [comment]
@mortenson I have it working fine, as long as I use setAttribute to trigger the event. Do you have a code example of what doesn't work?

**Comment by mortenson** [comment]
@sylvainlb No code example - I wasn't testing `setAttribute`, I was using the Firefox inspector to change the attribute value in the DOM, which works in Safari/Chrome but not in Firefox. This is an edge case, I just use it to manually test and demo components, so my comment can be ignored. Sorry for the noise. :)

**Comment by AndyOGo** [comment]
I observed the same, changing any attribute in Firefox's inspector does not trigger `attributeChangedCallback`. It only works if I script `setAttribute('foo', 'bar')` manually. I consider this a bug in Firefox's inspector dev tools.

**Comment by AndyOGo** [comment]
And I filed an issue regarding changing attributes in Firefox's inspector:
https://bugzilla.mozilla.org/show_bug.cgi?id=1449489

**Comment by AndyOGo** [comment]
And a separate ticket for us: https://github.com/axa-ch/patterns-library/issues/374

**Comment by TimvdLippe** [comment]
This appears to be resolved: http://jsbin.com/bigafog/edit?html,console,output
