### ISSUE TITLE
webcomponents should not add inline style to head

### ISSUE THREAD

**Issue by ephaee** [webcomponents/webcomponentsjs#399]
These CSS selecotrs target body and body[unresolved]. I am not sure how body ever can have the attribute unresolved. What does this script solve? 
This does not make sence IMO and I would love if webcomponents polyfill would not insert a ```<style>```element. Actually I think this script should be removed completely:

https://github.com/webcomponents/webcomponentsjs/blob/master/src/WebComponents/unresolved.js

![screen shot 2015-09-16 at 15 36 15](https://cloud.githubusercontent.com/assets/5112286/9906058/ba9a24f6-5c88-11e5-8681-0d132e3cf8f7.png)

**Comment by thisconnect** [comment]
I guess it is ok for the component itself, but wrong to add it to the host document head

**Comment by kapouer** [comment]
Related to https://github.com/webcomponents/webcomponentsjs/issues/188

**Comment by ebidel** [comment]
Closing in favor of #188
