### ISSUE TITLE
polyfill breaks in safari for windows

### ISSUE THREAD

**Issue by isaldarriaga** [webcomponents/webcomponentsjs#401]
safari for windows v5.1.7 (latest version available for the platform):

ERROR: Methods with parameters having the same name as the method makes the parser break. 
--------------------------
Additional errors are thrown in both regular and lite versions of the polyfill after the previous error is fixed.

webcomponents-lite.js

CODE:

elt.dispatchEvent(new CustomEvent("load", ...

ERROR: 

ReferenceError: Can't find variable: CustomEvent

--------------------------
webcomponents.js:

CODE:

[ Node, Window ].forEach(function(constructor) ...

ERROR: 

ReferenceError: Can't find variable: Window
--------------------------

**Comment by azakus** [comment]
Safari for windows is extremely old (newest version is 9), and is supported by neither Apple, nor Polymer.

**Comment by isaldarriaga** [comment]
ok. so this is out of the compatibility matrix. I'm going to close this one.
