### ISSUE TITLE
HTMLImports not working as expected in Firefox (works in Chrome & Safari). Plunkr provided.

### ISSUE THREAD

**Issue by kenkouot** [webcomponents/webcomponentsjs#402]
Greetings,

I'm running into an issue where HTML imports is behaving differently in FF than in Chrome & Safari. In this naive plunkr example, the alert fires in both Chrome and Safari, but fails to fire at all in FF. Quick checking for the feature support in FF using `'import' in document.createElement('link')` returns true, but the script inside the imported document does not seem to be invoked at all.

Plunkr link: http://plnkr.co/edit/o5ueTfA0wSfDlpgFrUDY
I'm using webcomponents.js 0.7.12.

**Comment by ebidel** [comment]
Sounds like you have the web components flag on in `about:config`. Try turning that off.

**Comment by kenkouot** [comment]
Ended up being a bug with Ember and Firefox. Setting the `tagName` on a component to a custom element was getting totally fudged, will file an issue with Ember and close this one. Thanks.
