### ISSUE TITLE
Safari error message: Refused to get unsafe header "Location"

### ISSUE THREAD

**Issue by tdesc** [webcomponents/webcomponentsjs#407]
Hello,
I'm trying to load polymer library with webcomponents-lite.min.js from CDN 
and get an error in Safari: <b>Refused to get unsafe header "Location"</b>
  
```
<link rel="import" href="https://cdn.rawgit.com/tdesc/polymer-cdn/1.1.4/lib//paper-button/paper-button.html">
```

Any help will be very appreciate

**Comment by azogheb** [comment]
:heavy_plus_sign: :one: on this issue

**Comment by bzeffren** [comment]
+1

**Comment by themerius** [comment]
+1

**Comment by azakus** [comment]
This is just a console log inside of a try/catch: https://github.com/webcomponents/webcomponentsjs/blob/7911bb7827474999b46aec95606b6a246bb5d745/src/HTMLImports/xhr.js#L35-L44

It should not affect the runtime of your application.

**Comment by azakus** [comment]
Oh now I remember, that was merged not too long ago.
WebComoponents 0.7.16+ has this message fixed.

**Comment by strann** [comment]
@azakus I'm still seeing this error in Safari 9.1.2 using webcomponents-lite (0.7.22)

This line is causing the error:

```js
var locationHeader = request.getResponseHeader("Location");
```
https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/xhr.js#L36

**Comment by mford516** [comment]
@strann +1 I am now seeing this in Safari as well in 9.1.2. However it does not exist in Safari 10.0 on the Sierra Beta.

**Comment by mford516** [comment]
@azakus Any update on this issue?

**Comment by crswll** [comment]
I'm running 0.7.22 and still seeing this in Safari 10.

**Comment by AmitM30** [comment]
Any resolutions ? I am too trying to load Polymer from CDN

**Comment by solutionboxing** [comment]
So any solutions???
