### ISSUE TITLE
hi guy My i really want to get this polymer thin can some one help me out im using windows 8.1

### ISSUE THREAD

**Issue by rowellfortune** [webcomponents/webcomponentsjs#409]

**Comment by cdata** [comment]
Please follow the guide at this URL: https://www.polymer-project.org/1.0/docs/start/getting-the-code.html

**Comment by TimvdLippe** [comment]
The guide has now been moved to https://www.polymer-project.org/2.0/start/

**Comment by rowellfortune** [comment]
Thanks
