### ISSUE TITLE
WebGL context tests failing on iOS9

### ISSUE THREAD

**Issue by markhats** [webcomponents/webcomponentsjs#414]
The WebGL ```texImage2D``` and ```texSubImage2D``` tests are failing on iOS9 (Safari). They are fine on iOS8. 

```
TypeError: gl.createTexture is not a function. 
(In 'gl.createTexture()', 'gl.createTexture' is undefined
(http://localhost:8081/webcomponentsjs/src/ShadowDOM/wrappers/events.js:242)
onerror@http://localhost:8081/webcomponentsjs/tests/tools/mocha/mocha.js:5738:19
```
```
TypeError: gl.createTexture is not a function. 
(In 'gl.createTexture()', 'gl.createTexture' is undefined
(http://localhost:8081/webcomponentsjs/src/ShadowDOM/wrappers/events.js:242)
onerror@http://localhost:8081/webcomponentsjs/tests/tools/mocha/mocha.js:5738:19
```

Essentially any function of a WebGL context seems to be undefined e.g. ```getParameter```, ```getExtension``` etc.

**Comment by dmmn** [comment]
Hi guys, is there any news on this one?
It's a big blocker on my current project.
Thanks.

**Comment by markhats** [comment]
me too.

**Comment by azakus** [comment]
Looks like Safari 9 has a new prototype chain for WebGL.
WebGLRenderingContext -> WebGLRenderingContextBase -> CanvasRenderingContextPrototype

**Comment by dmmn** [comment]
Thank you for that! :)
