### ISSUE TITLE
WebComponentsReady explanation difficult to understand

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#420]
The [site landing page](https://github.com/WebComponents/webcomponentsjs#webcomponentsready) has this to say about <b>WebComponentsReady</b>:

```
The criteria for this event to fire is all Custom Elements with definitions 
registered by the time HTML Imports available at load time have loaded 
have upgraded.
```

Despite several re-readings, I cannot understand this sentence.  

It seems to be saying something like "WebComponentsReady is fired when all <i>relevant</i> Custom Elements have upgraded", but defining <i>relevant</i> is tricky?  

The current definition of <i>relevant</i> in the sentence

```
...with definitions registered by the time HTML Imports available at load time have loaded...
```

is the part of the sentence I am having trouble understanding.

**Comment by ebidel** [comment]
Yea, this is very confusing! @addyosmani do you want to help update?

**Comment by csuwildcat** [comment]
It should probably read: "This even fires when the element upgrade process is completed for all Custom Elements whose definitions were registered before the load of HTML Imports."

Thoughts?

**Comment by webwizart** [comment]
@csuwildcat does it mean that when you don't use HTML Imports you don't really need the event?

**Comment by TimvdLippe** [comment]
This has now been clarified: https://github.com/webcomponents/webcomponentsjs#webcomponentsready-event Feel free to reopen if anything is still unclear.
