### ISSUE TITLE
Scoped CSS not working in Safari/Firefox (fine in Chrome)

### ISSUE THREAD

**Issue by sebdeckers** [webcomponents/webcomponentsjs#422]
When using the polyfill, CSS defined with `<style>` inside a shadow root is leaking to the light dom. Am I doing something wrong or is this a bug / unsupported feature?

Code:

``` html
<body>
  <style>h1 { color: deepskyblue; }</style>
  <h1>light (body)</h1>
</body>
```

``` js
const main = document.createElement('main')
main.innerHTML = '<h1>light (main)</h1>'
const root = main.createShadowRoot()
root.innerHTML = '<h1>shadow (main)</h1>' +
  '<style>h1 { color: orange; }</style>'
document.body.appendChild(main)
```

Demo:
https://jsbin.com/buqeviluha/1/edit?html,js,output

Expected (Chrome 46):
![Fine in Chrome](http://i.imgur.com/8DI4abJ.png)

Result (Safari 9):
![Broken in Safari](http://i.imgur.com/24jk1rP.png)

**Comment by cbas** [comment]
Found a workaround: Manually calling the ShadowCSS shim after creating the shadow root.

```js
WebComponents.ShadowCSS.shimStyling(root, main.tagName)
```

I suppose this should be invoked automatically somewhere. Any ideas?

**Comment by ebidel** [comment]
IIRC, the polyfill doesn't shim styles for you automatically. Polymer does.

**Comment by cbas** [comment]
@ebidel Thanks for the reply!

Is there a list of known issues & considerations when using webcomponents.js without Polymer?

I'm trying to use raw webcomponents; sticking as close to the standard as possible. Guess I'll have to facilitate the shim a little bit though.

**Comment by ebidel** [comment]
Not many. The styling stuff is the only one I can think of right now.
Mostly, things just work :)

You won't have dom scoping is you're using the -lite.js version. That uses
shady dom and I think Polymer also does the css shiming for that version.

**Comment by kewisch** [comment]
In Firefox sounds like [bug 992249](https://bugzilla.mozilla.org/show_bug.cgi?id=992249). I have the webcomponents flag enabled, which probably causes the shadow dom shim to not be loaded, but that also means that content styling does not work.

Therefore, `WebComponents.ShadowCSS` is undefined. Would there be a way to force the shadow dom to be loaded so far that the css rewriting works?

**Comment by kewisch** [comment]
Ah I found out how by using `?wc-shadow=1` or equivalent before loading. This still doesn't make a css rule like `.header > content::content > h1` work, as it gets translated into `scope .header > content > h1`, but I can work around that by specifying two selectors.

You might consider fixing the `content::content` issue by removing it from the selector for that specific tag before closing this issue.

**Comment by lukasoppermann** [comment]
I am having this problem as well, css is leaking in and out from the shadow Dom.

I am using the `components.js` file. It happens in Firefox, but not in chrome. Is there a fix for it?

**Comment by Slaals** [comment]
Anything new about this issue?

https://jsfiddle.net/rkez144z/1/

If you try this on Firefox the style affects the shadow DOM, it's not the case in Chrome with its native support of ShadowDOM.

**Comment by trusktr** [comment]
> IIRC, the polyfill doesn't shim styles for you automatically.

Why not? It's an expected default feature of ShadowDOM, and it should work without having to call polyfill-specific APIs.
