### ISSUE TITLE
google-map not working correctly when using full webcomponents

### ISSUE THREAD

**Issue by kungufli** [webcomponents/webcomponentsjs#426]
The full version of webcomponents (0.7.15) seems to breaks some click events on the `google-map` component (you can't zoom, drag the map or click on markers) in Firefox, Safari and IE. The problem is triggered only when the `signed-in=true` attribute is set on the map. It works normally in Chrome and Edge, or if you use the lite version of webcomponents or if the `signed-in=true` attribute is not set.
Here is a reference jsbin that trigger the bug (to open with Firefox, Safari or IE) https://jsbin.com/buweluwoye/edit?html,output 

Issue originally opened at https://github.com/GoogleWebComponents/google-map/issues/218.

**Comment by TimvdLippe** [comment]
This appears to be fixed in the original JSBin.
