### ISSUE TITLE
How do i just use it?

### ISSUE THREAD

**Issue by MatsSvensson** [webcomponents/webcomponentsjs#427]
BowserNPmNodejsYadaYada....

I want to just use this as plain ol java-script.
That is, manually copy the file(s) with my own fleshy fingers, to a directory and include a reference or two in my html.

You know, like its way back in the swinging 2013's or something.

Can i do that?
How do i do that?

What file(s) goes where?

Has anyone of you kids seen my glasses?

**Comment by azakus** [comment]
You can download the latest release as a zip: https://github.com/webcomponents/webcomponentsjs/archive/v0.7.15.zip.

There are a bunch of files in there, but there are 2 "all in one" options:
- webcomponents.js is everything all-in-one
- webcomponents-lite.js is everything minus the ShadowDOM polyfill

The `*.min.js` files are minified versions with uglify.js

Just put your `<scripts src="webcomponents.js">` line as the first script and you should be all set.

**Comment by ebidel** [comment]
Also info: http://webcomponents.org/polyfills/

**Comment by MatsSvensson** [comment]
Yes, that would be a good place to put that information in the furture.
Maybe under "Installation & usage"?
