### ISSUE TITLE
HTMLImports.whenReady should not include `async` imports

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#431]
HTMLImports.whenReady should not block on async `<link rel="import" async>` imports, to mach the native non-blocking behavior of HTML imports.

Solution may simply invlove adding `:not([async])` here: https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/base.js#L117

**Comment by kevinpschaaf** [comment]
Is this something you could look at?

**Comment by TimvdLippe** [comment]
This was fixed in https://github.com/webcomponents/webcomponentsjs/commit/ca23b7e2f7044e4f56f2d9a9bd19b7e0738d7a40
