### ISSUE TITLE
Double upgrade of custom elements in cloned document fragments

### ISSUE THREAD

**Issue by csuwildcat** [webcomponents/webcomponentsjs#438]
When cloning a document fragment containing custom elements, it appears the custom elements inside the cloned fragment are double upgraded.

Here's a reduced test case to illustrate the issue: http://jsbin.com/cowonugidu/edit?html,js,output

**Comment by ebidel** [comment]
I see `I should only appear once.` twice in Chrome (native custom elements), without loading the polyfill.

**Comment by csuwildcat** [comment]
It looks like the issue is probably the `wrapDomMethodToForceUpgrade` wraper function. This function wraps `cloneNode`, but doesn't account for the fact that JS DOM properties/flags of cloned elements are not copied, even when you pass the second arg to invoke a `deep` clone. The `deep` option clones the subtree and attributes of the cloned node, but not JS DOM properties/flags. Because all JS DOM props/flags are dropped, which includes the `__upgraded__` flag I see being checked everywhere, it makes the element appear as though it has not been handled, even when it has.

**Comment by azakus** [comment]
`document.createElement` is synchronous, so the createdCallback runs right before it is appended to the document fragment, and you end up with `<x-foo><div>I should only appear once</div></x-foo>`.

Then x-bar clones the document framgent.
This creates a new x-foo because the node has been cloned, not moved. This x-foo then does it's upgrade, creates the div, and is done. If you check the document fragment and did a compairsion, the fragment's x-foo and the main document's x-foo are different nodes.

**Comment by csuwildcat** [comment]
@ebidel that can't possibly be expected behavior - how would one ever clone a custom element that has already had its content and DOM properties upgraded?

**Comment by justinfagnani** [comment]
As you said above, cloneNode doesn't clone JS properties, so createdCallback has to be called on clones to initialize them.

**Comment by csuwildcat** [comment]
@azakus I realize `createElement` is sync, that's not the issue. The issue is that when an element that has been upgraded is added to a document fragment, a clone should be of the upgraded element, IMO. If this is as-spec'd, I suppose one can never reliably clone a custom element that has been upgraded, or they will face a situation where content or the setting of JS DOM props is duplicated. Does that make sense?

**Comment by csuwildcat** [comment]
@justinfagnani if that's the case, you simply cannot use document fragments as a way to 'cache' bits of DOM that include custom elements for later generation, which is a _major_ bummer.

**Comment by justinfagnani** [comment]
How would setting JS properties be duplicated? `cloneNode` doesn't clone them, or shadow roots. In your example you're modifying the child content, which is cloned, in `createdCallback`. That's an anti-pattern. Child content is owned by a nodes host, not by the node. If you instead do:

```
var fooProto = Object.create(HTMLElement.prototype,  {
  createdCallback: {
    value: function(){
      var div = document.createElement('div');
      div.textContent = 'I should only appear once.';
      var root = this.createShadowRoot();
      root.appendChild(div);
    }
  }
});
```

Then the message will only appear once.

**Comment by azakus** [comment]
@csuwildcat Yep, cloneNode starts a clean slate for all the nodes. That is in the DOM spec: https://dom.spec.whatwg.org/#concept-node-clone.

You *can* use a template's content document though, as it is not a custom element registry document.

**Comment by azakus** [comment]
Example using template's document for fragment creation: http://jsbin.com/fakeme/edit?html,js,output

**Comment by justinfagnani** [comment]
And example using shadow root instead of light children: http://jsbin.com/qeremozuqi/edit?html,js,output

**Comment by csuwildcat** [comment]
@azakus I was just about to type that out to make sure I understood what you meant - thanks, I will use that route. Is this issue/alternative documented clearly anywhere? I feel like this is significant dragon for folks who may not be used to the WC realm ;)

**Comment by csuwildcat** [comment]
@justinfagnani I knew Shadow DOM would work for this, but my use-case constraint requires only light-DOM reliance, so I'll go with @azakus's suggestion. Thank you, this was very helpful!

**Comment by kapouer** [comment]
@csuwildcat this is very puzzling indeed.
There's a discrepancy between chrome and webcomponents.js here.
Using @azakus way to create a clean fragment,
```
var fragment = document.createElement('template').content
.ownerDocument.createDocumentFragment();
frag.appendChild(contentDoc.createElement('x-foo'));
console.log(frag.childNodes[0].outerHTML);
console.log(frag.cloneNode(true).childNodes[0].outerHTML);
```
webcomponents.js runs "upgradeAll" on cloneNode - fine, but it seems it it using
the `document` register, not the `frag.ownerDocument`register, which leads to an
unexpected upgrade.

Test on chrome without webcomponent.js: http://jsbin.com/mawibezune/1/edit?html,js,console,output
And somewhere else with webcomponent.js: http://jsbin.com/kowipukaba/1/edit?html,js,console,output
i believe the expected result is to see three empty <x-foo> tags in console.

**Comment by csuwildcat** [comment]
I actually ended up sidestepping the issue entirely by simply keeping the template's string representation around, adding a dummy node to the target, then setting its outerHTML to the fragment. This allows for correct operation, and is a dramatic reduction in code complexity. You can see what I settled on in X-Tag's source: https://github.com/x-tag/core/blob/master/src/core.js#L333

**Comment by kapouer** [comment]
So after reading [creating-and-passing-registries](http://w3c.github.io/webcomponents/spec/custom/#creating-and-passing-registries) i came to the conclusion that most of the time, a custom element will be upgraded, except when it is owned by a template's content document - which clearly is supposed to have a new (empty) registry.
So ```
var doc = createElement('template').content;
doc.appendChild(doc.createElement('x-foo'));
doc.cloneNode(true);
```
shouldn't upgrade anything, because the cloned node is still owned by a document that has an empty registry.

**Comment by justinfagnani** [comment]
@kapouer I think you have a different issue than this. This issue was with fragments created from the main document, and had the same behavior in polyfill vs native, and was actually working as intended. Your issue sounds like it could be a bug in the custom elements polyfill.
