### ISSUE TITLE
Interact .draggable and webcomponentsjs conflict in IE

### ISSUE THREAD

**Issue by radiart** [webcomponents/webcomponentsjs#441]
Hi I have problem when using webcomponentsjs with Interact https://github.com/taye/interact.js draggable function under IE 10 and 11

``		.draggable({
		  // enable inertial throwing
		  inertia: true,
		  // keep the element within the area of it's parent
		  restrict: {
			restriction: "parent",
			endOnly: true,
			elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
		  }, ``

I getting such error:

``SCRIPT5078: Cannot redefine non-configurable property 'defaultPrevented'
File: webcomponents-lite.js, Line: 1039, Column: 7``

...any ideas?

**Comment by radiart** [comment]
Try run this on IE: https://jsfiddle.net/ynxuy50g/1/ and drag the green div

**Comment by radiart** [comment]
console.trace()
   at eval code (eval code:1:1)
   at eval code (eval code:29:29)
   at Event.prototype.preventDefault (https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.16/webcomponents-lite.js:1039:7)
   at Interaction.prototype.checkAndPreventDefault (https://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.6/interact.js:3140:17)
   at Interaction.prototype.pointerMove (https://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.6/interact.js:1929:21)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.6/interact.js:3348:17)

**Comment by radiart** [comment]
Story in Interact repo: https://github.com/taye/interact.js/issues/310

**Comment by azakus** [comment]
Interesting. Looks like IE has a working `defaultPrevented` for PointerEvents, but not Event or CustomEvent.

**Comment by liraniom** [comment]
I had the same issue:
After i was putting configureable:true inside the newly defined defaultPrevented object ,the problem disappeared.
```
Event.prototype.preventDefault = function() {
        if (!this.cancelable) return;
        unsafeUnwrap(this).preventDefault();
        Object.defineProperty(this, "defaultPrevented", {
          configurable: true,
          get: function() {
            return true;
          }
        });
      };
```

Can you please include it in your future releases? 

Thanks.
