### ISSUE TITLE
Misdetection of native HTMLImports on Firefox for Android

### ISSUE THREAD

**Issue by KitaitiMakoto** [webcomponents/webcomponentsjs#452]
Hi,

Now detection of native HTMLImports is done here: https://github.com/webcomponents/webcomponentsjs/blob/fedfe0210aa853a9531bd976f6d161d585cc22fb/src/HTMLImports/base.js#L28
But on Firefox for Android which, `IMPORT_LINK_TYPE in document.createElement('link')` is `true` although it doesn't support HTMLImports natively, because `document.createElement('link').import` is `null` object.

Could you implement more proper detection?

My environment is:
Device: Nexus 7 2013
OS: Android 6.0
Browser: Firefox for Android 42.0.1

Thank you.

**Comment by prantlf** [comment]
I observe the same behaviour in the desktop Firefox, if I set 'dom.webcomponents.enabled' to `true` in about:config.  The `import` property exists and is `null`.  Resetting the 'dom.webcomponents.enabled' to the default `false` helps.

Firefox [wasn't planing to implement HTML Imports last year](https://hacks.mozilla.org/2014/12/mozilla-and-web-components/).  The [task in their bugzilla](https://hg.mozilla.org/integration/mozilla-inbound/rev/89716e3f169d) was set to "FIXED", bug I don't know how to test test it.  The 'dom.webcomponents.enabled' alone is no way - it even breaks the webcomponents polyfill.

**Comment by ebidel** [comment]
Please turn the flash off. Their implementation is incomplete. Checking for
the .import property is the right feature detect.

**Comment by KitaitiMakoto** [comment]
I see. Thank you for the reply and sorry for bothering you.

**Comment by prantlf** [comment]
I've had Flash blocked and turning it off makes no change.  (I'm not sure about the connection to the imports.)

Anyway, the 'dom.webcomponents.enabled' appears to be useless for the typical webcomponents use case and it should stay at its default `false`.
