### ISSUE TITLE
Release notes / Changelog

### ISSUE THREAD

**Issue by warpech** [webcomponents/webcomponentsjs#453]
Would it be possible to publish a very short information about changes in each release? 

Currently it is not aparent from the [GitHub Releases](https://github.com/webcomponents/webcomponentsjs/releases) pages what are the consequences of upgrading. It doesn't look as if every git tag is intended as a stable release.

<img width="1019" alt="screenshot 2015-11-23 12 45 26" src="https://cloud.githubusercontent.com/assets/566463/11335814/1a0988d2-91e0-11e5-8c7a-85b1cda0f515.png">

**Comment by addyosmani** [comment]
Added a short set of release notes for v0.7.18 to https://github.com/webcomponents/webcomponentsjs/releases/tag/v0.7.18. Feel free to edit/improve @azakus :)

**Comment by warpech** [comment]
Brilliant, thanks!

**Comment by azakus** [comment]
LGTM, thanks @addyosmani :+1:

**Comment by addyosmani** [comment]
Pleasure! :candy:

**Comment by abdonrd** [comment]
@azakus Please, don't forget the changelog.

<img width="1013" alt="screen shot 2017-10-19 at 09 54 14" src="https://user-images.githubusercontent.com/1007051/31760001-7f2e8dd2-b4b3-11e7-80ef-83a0b2cd8c8d.png">
