### ISSUE TITLE
[Custom Element] Creating with `innerHTML` property not supported

### ISSUE THREAD

**Issue by smalluban** [webcomponents/webcomponentsjs#459]
Custom Element polyfill support `createElement` and `createElementNS`:

``` javascript
document.register('my-element', ...);
document.createElement('my-element'); // Will trigger createdCallback
```

But setting `innerHTML` property of element not attached to document will not trigger `createdCallback`:

``` javascript
const el = document.createElement('div');
el.innerHTML = '<my-element></my-elemement>'; // Will NOT triger createdCallback
```

Native implementation in Chrome support above feature.

`innerHTML` property of `Element.prototype` should be watched as it is already computed property and when is set, polyfill should travers created tree.

**Comment by Sendoushi** [comment]
I have the exact same issue... One year after.
