### ISSUE TITLE
stylesheet links being ignored

### ISSUE THREAD

**Issue by paulie4** [webcomponents/webcomponentsjs#460]
The changes in https://github.com/webcomponents/webcomponentsjs/commit/c2d7ca1726112868c7d4105233815b8d28806e89 are causing ```<link rel="stylesheet" type="text/css" ...>``` tags, which are valid, to be ignored, but I think that change was just meant to ignore stylesheets with non-standard types, so can we add ```'link[rel=stylesheet][type="text/css"]'``` and ```'style[type="text/css"]'``` to the list of importsSelectors so they aren't ignored anymore?

**Comment by Echogene** [comment]
It seems like this has already been reported in issue #400.  I am also experiencing this issue.
