### ISSUE TITLE
<template> shim in Template.js mishandles HTML Comments

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#467]
This code (https://github.com/webcomponents/webcomponentsjs/blob/master/src/Template/Template.js) implements a special innerHTML for many of the polyfilled browsers. 

``` javascript
          Object.defineProperty(template, 'innerHTML', {
            get: function() {
              var o = '';
              for (var e = this.content.firstChild; e; e = e.nextSibling) {
                o += e.outerHTML || escapeData(e.data);
              }
              return o;
            },
```

The line **o += e.outerHTML || escapeData(e.data);** only works correctly on Elements or Text.  escapeData() garbles Comments.

Whereas native Chrome's `<template>`'s .innerHTML supports Comments.  So a <template> with Comments can be correctly retrieved as a string on Chrome, but not via this shim.

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/template#5
