### ISSUE TITLE
ShadowDom -> Can features/elements be polyfilled?

### ISSUE THREAD

**Issue by jogibear9988** [webcomponents/webcomponentsjs#468]
I've a question:

If all the browsers support natively "shadowdom", can i then polyfill features so that they are also available in webcomponents? For example I  want to polyfill "&lt;menu&gt;", i can i polyfill it so that also browsers with shadowdom, can use the element in components?

**Comment by notwaldorf** [comment]
I'm not sure what you mean about polyfilling `<menu>` -- you can't create a one-word custom element (it's prevented by the spec, and thus also the polyfill), so I don't think that would be possible
