### ISSUE TITLE
MutationObserver has no support for observing style changes

### ISSUE THREAD

**Issue by ryanwhite04** [webcomponents/webcomponentsjs#477]
This would just be a nice feature to include.
You can currently observer inline styles by observing the style attribute on an element, but it doesn't monitor changes to style sheets.
Similar to http://xml3d.org/xml3d/specification/styleobserver/
I'm going to try and add support for the style extensions to the mutation observers according to the above specifications, unless someone else wants to.

**Comment by TimvdLippe** [comment]
Since we no longer have this polyfill, I am closing this issue.
