### ISSUE TITLE
Code in main document exectued after one in import even when placed above it

### ISSUE THREAD

**Issue by bushuyev** [webcomponents/webcomponentsjs#479]
Could you please have a look at
http://stackoverflow.com/questions/34857939/order-of-javascript-execution-when-loading-html-import

Could it be that js code in main document somehow exectued after import even when placed above it?

**Comment by ebidel** [comment]
Let's keep it on SO: http://stackoverflow.com/questions/34857939/order-of-javascript-execution-when-loading-html-import#comment57592550_34857939

**Comment by bushuyev** [comment]
https://github.com/PolymerElements/polymer-starter-kit/issues/669
