### ISSUE TITLE
Assertion failed with jquery.autosize.js

### ISSUE THREAD

**Issue by mathieulegrand** [webcomponents/webcomponentsjs#48]
I get an `Error: Assertion failed` with both Safari 8.0 and Firefox 32.0.3. The call stack is as follow:

```
[Error] Error: Assertion failed
	assert (webcomponents.js, line 113)
	assertIsNodeWrapper (webcomponents.js, line 1566)
	insertBefore (webcomponents.js, line 1779)
	appendChild (webcomponents.js, line 1776)
	buildFragment (jquery.js, line 5126)
	domManip (jquery.js, line 5363)
	append (jquery.js, line 5194)
	autosize (jquery.autosize.js, line 54)
	initContent (channel.js, line 373)
	fire (jquery.js, line 3073)
	fireWith (jquery.js, line 3185)
	ready (jquery.js, line 3391)
	completed (jquery.js, line 3407)
```

The assertion in https://github.com/Polymer/webcomponentsjs/blob/master/src/ShadowDOM/wrappers/Node.js#L30 fails following the `append`  triggered by https://github.com/jackmoore/autosize/blob/master/jquery.autosize.js#L54

**Comment by kof** [comment]
Can someone explain why this issue happens?

**Comment by kof** [comment]
I don't see how this issue has been resolved ...

**Comment by garlicnation** [comment]
@kof webcomponentsjs needs to be loaded before jquery.

**Comment by kof** [comment]
yeah I got it, but why does this happen, its not always that easy to change the order ... maybe there is another way ...

**Comment by garlicnation** [comment]
Webcomponentsjs(specifically, the Shadow DOM polyfill) needs to wrap every element in the DOM in order to work properly. When it doesn't run until after jquery, jquery ends up with references to un-wrapped objects that don't behave as expected in the presence of the polyfill.

**Comment by kof** [comment]
I see, thanks!
