### ISSUE TITLE
Document CSP Compatibility

### ISSUE THREAD

**Issue by indolering** [webcomponents/webcomponentsjs#484]
WebComponents.js is setting off `eval()` and inline style related Content Security Policy errors.  It looks like there is support for [detecting runtimes with `eval` locked down](https://github.com/webcomponents/webcomponentsjs/blob/43b5dfa32f3b368cbd3d14295049dcbcb233171f/src/ShadowDOM/wrappers.js), [a ticket](https://github.com/webcomponents/webcomponentsjs/issues/188) discussing externalizing problematic styling, and there are CSP related unit tests, but it's not clear if running without `eval` is supported and if there are any tradeoffs.  Documentation with a sample CSP policy would be helpful.

**Comment by TimvdLippe** [comment]
We have removed all usages of `eval()`. We are tracking the other CSP issues in #188.
