### ISSUE TITLE
Use of Function Triggers CSP Errors

### ISSUE THREAD

**Issue by indolering** [webcomponents/webcomponentsjs#485]
It appears as if [some code](https://github.com/webcomponents/webcomponentsjs/blob/43b5dfa32f3b368cbd3d14295049dcbcb233171f/src/ShadowDOM/wrappers.js#L161) uses `Function` but includes a fallback:

``` JavaScript
  // The name of the implementation property is intentionally hard to
  // remember. Unfortunately, browsers are slower doing obj[expr] than
  // obj.foo so we resort to repeat this ugly name. This ugly name is never
  // used outside of this file though.

  function getGetter(name) {
    return hasEval && isIdentifierName(name) ?
        new Function('return this.__impl4cf1e782hg__.' + name) :
        function() { return this.__impl4cf1e782hg__[name]; };
  }
```

While the fallback code works, it still generates bogus reports and it seems like a premature optimization ... wouldn't the JIT cache the lookup?  An author of a [book on JS optimizations](http://archive.oreilly.com/pub/a/server-administration/excerpts/even-faster-websites/writing-efficient-javascript.html) mentions that it was a problem in Safari 4 but [this JS perf](https://jsperf.com/dot-notation-vs-bracket-notation/7) doesn't show any real-world differences.

But perhaps there are performance issues that aren't captured in these simple tests....

**Comment by indolering** [comment]
Cross-referencing #484 and #188.

**Comment by TimvdLippe** [comment]
We have removed all usages of `Function()`. We are tracking the other CSP compatibility issues in #188.
