### ISSUE TITLE
google-map-marker loses infowindow and/or click event on update

### ISSUE THREAD

**Issue by northeastintegration** [webcomponents/webcomponentsjs#486]
Hello All --

Using google-map v1.1.10 against git://github.com/GoogleWebComponents/google-map.git#*

I build up my markers like so:
```
<template>
   <site-data sites="{{sites}}"> </site-data>
   <google-map fit-to-markers >
      <template is="dom-repeat" items="{{sites}}">
        <template is="dom-repeat" items="{{item}}">
          <google-map-marker latitude={{item.latitude}}
                             longitude={{item.longitude}}
                             title="{{item.project_name}}"
                             >
            <h1>{{item.project_name}}</h1>
            <p style="margin: 0;">Location: <b>{{item.town}}, {{item.country}}</b></p>
            <p style="margin: 0;">Tech Description: <b>{{item.tech_desc}}</b></p>
          </google-map-marker>
        </template>
      </template>
    </google-map>
</template>
```

Upon initial loading of the webapp, things work really well. I can click on a marker and the infowindow shows the content. However, if I change any values in my sites array, I seem to lose the infowindow and/or the click event. I have to refresh the browser to get back to my initial condition.

Also, The marker locations will update perfectly if I change lat/long and hovering shows tooltip aka. title, appropriately as well. 

I've also added a click event which calls a console.log to validate that it functions.. It works well until a value is changed in the {{sites}} binding, so it seem I am losing click events when the google-map updates itself?

There are no scripts in this element.

If I can provide more information, please let me know. 

Thanks in Advance,
Scott

**Comment by ebidel** [comment]
This issue tracker is for the polyfills.
