### ISSUE TITLE
Firefox hang with webcomponents while the developer tools are opened

### ISSUE THREAD

**Issue by kao98** [webcomponents/webcomponentsjs#493]
As discussed in the issue #75 
Firefox hang when using webcomponents.js while the developers tools are opened.
No problem when using webcomponents-lite.js.
No problem without the developer tools.
I'm using Firefox developer edition (46.0a2)

This is reproducible with the following simple code:

``` html
<!-- index.html -->
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="webcomponents.js"></script>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>
```

Yes. That's it. You actually don't need to do anything. Inserting the script webcomponents.js make firefox hang for a few seconds if the developer tools are opened.

To be sure, simply import an HTML component that just `alert('something');`. 

It seems to be an issue with Firefox not with Webcomponents. But I've opened this issue to be linked with #75 as shadowmint said to do.

**Comment by noopole** [comment]
It's not only a problem of Firefox dev' tools, because even witout them, a `<link>.import` remains `undefined`. Which is quite annoying.

(While it works as expected with the *-lite* version.)

**Comment by notwaldorf** [comment]
I just tried it out (http://jsbin.com/pasogaf/edit?html,output) on the latest Firefox, and it didn't look like it hung, so I'm going to close this (since it's a very old issue to begin with)
