### ISSUE TITLE
Creating a TreeWalker throws 'Error: Assertion failed' in Safari and Firefox

### ISSUE THREAD

**Issue by joriskdzaack** [webcomponents/webcomponentsjs#494]
In a project I want to both use the webcomponents polyfills (the full webcomponents.js) and a TreeWalker for iterating through all my text nodes. Every time `document.createTreeWalker` gets called I get an error saying _Error: Assertion failed_ in every browser but Chrome. (Did not check any IE yet.)

The trace of the error in Firefox Developer Edition is the following:

> assert() webcomponents.js:116
> unwrap() webcomponents.js:309
> Document.prototype.createTreeWalker() webcomponents.js:4193
> forwardMethodsToWrapper/</</constructor.prototype[name]() webcomponents.js:350
> readyStateChange() tooltips.html:25
> invoke() webcomponents.js:1092
> dispatchAtTarget() webcomponents.js:1041
> dispatchEvent() webcomponents.js:1019
> dispatchOriginalEvent() webcomponents.js:975

[Here](http://jsbin.com/yanoqebube/edit?html,console) is a minmal sample document which allows me to reproduce the error: 

```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Tree Walker</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="http://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.21/webcomponents.js"></script>
    </head>
    <body>
        <main role="main" class="main" itemscope itemprop="mainContentOfPage">
            <p>Objectively maintain technically sound e-commerce before intermandated bandwidth. Completely transform fully researched functionalities for superior applications. Efficiently parallel task emerging processes with cost effective mindshare. Energistically deliver end-to-end e-markets for multifunctional opportunities. Holisticly seize premier architectures for effective catalysts for change.</p>
        </main>

        <script>
            var _filterNodes = function _filterNodes (node) {
              return NodeFilter.FILTER_ACCEPT;
            };

            document.addEventListener('readystatechange', function readyStateChange() {
              if (document.readyState === 'complete') {
                var textNodes = [];
                var treeWalker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, _filterNodes, false);

                while (treeWalker.nextNode()) {
                  var currentNode = treeWalker.currentNode;
                  textNodes.push(currentNode);
                }

               console.log(textNodes);
              }
            }, false);
        </script>
    </body>
</html>
```

Thanks! 

(Browsers used:

* Chrome 48.0.2564.116
* Chrome  50.0.2655.0 canary
* Safari  8.0.8
* Firefox 44.0.2
* Firefox 46.0a2)

**Comment by eeid26** [comment]
try to change your code 
```javascript
document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, _filterNodes, false);
```
to
```javascript
document.createTreeWalker(wrap(document.body), NodeFilter.SHOW_TEXT, _filterNodes, false);
``` 

Maybe the code in webcomponents should have used unwrapIfNeeded(root) in
      return new TreeWalkerWrapper(originalCreateTreeWalker.call(unwrap(this), unwrap(root), whatToShow, newFilter, expandEntityReferences));

Most tests used wrapped div tags

**Comment by joriskdzaack** [comment]
@eeid26 Thank you very much! This bypasses the problem.
