### ISSUE TITLE
IE >= 10 breaks when in strict mode

### ISSUE THREAD

**Issue by dudabone** [webcomponents/webcomponentsjs#496]
Hi,

There seems to be an issue when importing webcomponents-lite.js from a file that declares "use strict" (getting "Variable undefined in strict mode"). Looks like this is coming from the following line (1066 in v0.7.21): 

`  if (needsTemplate) {
    HTMLTemplateElement = TemplateImpl;
  }`

My assumption is that the issue can be fixed if TemplateImpl will be assigned to "window.HTMLTemplateElement" instead?

**Comment by MadaraUchiha** [comment]
I see the same problem with PhantomJS 2

**Comment by MadaraUchiha** [comment]
Hey, sorry for pestering, how long should it take for this fix to be tagged and released? Our build is currently breaking and the only workaround is to patch the library inhouse, which sucks a lot.
