### ISSUE TITLE
nested `template` disappears when stamped but not distributed by shadow host

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#498]
### Description

When `template` is inserted to shadow host, but not distributed, then it it is not available in document tree.
#### Live Demo

http://jsbin.com/fecofo/4/edit?html,js,console,output
#### Steps to Reproduce
1. Create `my-element` witch shadow dom, and content distribution
2. Append `my-element` to `document.body`
3. Create `template` with another `<template>` inside.
4. Stamp parent `template` contents into `<my-element>`
#### Expected Results

`<template>` element is available in document tree (light DOM), for example to be selected with `querySelector`, or removed.
#### Actual Results

parent `template`'s content is stamped without nested `template` element
### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [x] IE 11

I didn't check, but I suspect, other polyfilled browsers are also affected
- [x] Edge
- [x] Safari 9
- [x] Safari 8 
### Versions
- webcomponents.js: 0.7.21
### Other comments

When the parent/host element, does not have shadow tree, stamping works as expected.

**Comment by warpech** [comment]
Also reproducible in Edge and Safari

**Comment by azakus** [comment]
Looks like this is a bug in `querySelector`.
`myEl.children[1].localName === 'template'`

**Comment by warpech** [comment]
Yes, nested `template` appears correctly in polyfill's DOM element references like `firstElementChild`, `nextElementSibling`, `children`, etc. 

It is skipped in polyfill's `querySelector` and `querySelectorAll`, which means the bug might be there.

**Comment by warpech** [comment]
I just checked that in addition to `querySelector` and `querySelectorAll`, the bug is also reproducible in polyfill's `getElementsByTagName` and `getElementById`.

**Comment by tomalec** [comment]
This issue have also a big impact on custom elements use:

```html
<div>my markup</div>
<vendor-element>
  <template>my template</template>
</vendor-element>
```

Then as I am not aware of `vendor-element` code, as vendor is the owner, my dom selector `.querySelector('template')` may suddenly stop working, once vendor will decide to put shadow root there.

http://jsbin.com/letipid/edit?html,console,output

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/yimohew/2/edit?html,console,output
