### ISSUE TITLE
Sample of creation and insertion of a web component with plain Javascript

### ISSUE THREAD

**Issue by krisnye** [webcomponents/webcomponentsjs#5]
Some frameworks need to interface with web components via javascript.  A sample that demonstrates how to do that, and verifies that it works with this shim would be very useful.

**Comment by ssorallen** [comment]
@ebidel wrote an article covering how to use web components with vanilla JS: http://www.html5rocks.com/en/tutorials/webcomponents/customelements/

Does that give an example like you were looking for?
