### ISSUE TITLE
Update to reflect the revised Custom Element spec

### ISSUE THREAD

**Issue by jmalonzo** [webcomponents/webcomponentsjs#502]
Just wondering if there are/will be plans  to update to the latest Custom Element spec? 

Thanks.
- https://w3c.github.io/webcomponents/spec/custom/

**Comment by kellengreen** [comment]
I too am curious about this.

**Comment by notwaldorf** [comment]
This work is being done in a new webcomponents/custom-elements repo, and it's being used in the `v1` branch of this polyfill
