### ISSUE TITLE
Injection at Top of Head Renders X-UA-Compatible Unusable

### ISSUE THREAD

**Issue by JD-Robbs** [webcomponents/webcomponentsjs#503]
I noticed that the script injects the necessary code (e.g. CSS fallbacks) at the very top of the header - i.e. right below `<head>`.

This means that it injects itself above `<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />`.  However, this meta tag needs to be the **very first** within the head - otherwise, IE (even IE11) won't render in `edge` mode and you'll get issues with `querySelectorAll` being unavailable.

Therefore, webcomponentsjs should check for the presence of this particular tag and, if it is present, inject all necessary code below it.

**Comment by TimvdLippe** [comment]
This should now be fixed: https://github.com/webcomponents/shadycss/blob/b5cd362a76a587403c5cb3aa59fa3899c45fdf45/src/style-util.js#L126-L146
