### ISSUE TITLE
Just importing MutationObservers/Weakmap Polyfills?

### ISSUE THREAD

**Issue by Vheissu** [webcomponents/webcomponentsjs#505]
I like to keep my applications nice and light. Previously I was using the Polymer MutationObservers repository to get the polyfill that I need. However, because it is deprecated I want to move to this repo. I don't want to include all of the polyfills and would like to just include the MutationObservers and WeakMap polyfills. Is there a way I can do this?

At present I am including the entire repo in my application like so:

```
System.import('webcomponents/webcomponentsjs')
```

**I would ideally like to just be able to use it like this:**

```
System.import('webcomponents/webcomponentsjs/WeakMap')
System.import('webcomponents/webcomponentsjs/MutationObserver')
```

Is this at all possible?

**Comment by azakus** [comment]
MutationObserver includes WeakMap, so `MutationObserver.js` should be all you need.

**Comment by Vheissu** [comment]
@azakus What would this look like from an import perspective using an ES6 or System import?

**Comment by azakus** [comment]
The script is an IIFE, so you should just be able to include it with `import './webcomponentsjs/MutationObserver.js'` or the like.

I'm not sure how `System.import` works, but I'm sure a path to that file should just work.

**Comment by Vheissu** [comment]
@azakus Thanks for the clarification. This works:

```
SystemJS.import('webcomponents/webcomponentsjs/MutationObserver')
```
