### ISSUE TITLE
Webcomponent polyfill rewrites url(#id) to relative URL

### ISSUE THREAD

**Issue by Torins** [webcomponents/webcomponentsjs#509]
Hey,

Webcomponents polyfill seems to rewrite any and all url(..) it finds inside CSS, but this poses a problem when using inline SVG.

I've got this example Polymer element:

&lt;dom-module id="x-circle"&gt;

&lt;template&gt;
  &lt;style&gt;
    #circle {
      fill: url(#grad);
    }
  &lt;/style&gt;
   &lt;svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 70 70"&gt;
                &lt;defs&gt;
                    &lt;linearGradient id="grad" x1="0%" y1="100%" x2="100%" y2="0%"&gt;
                        &lt;stop offset="0%" style="stop-color:red" /&gt;
                        &lt;stop offset="100%" style="stop-color:blue" /&gt;
                    &lt;/linearGradient&gt;
                &lt;/defs&gt;
                &lt;circle id="circle" cx="35" cy="35" r="25""/&gt;
            &lt;/svg&gt;
&lt;/template&gt;

&lt;script&gt;
  (function(){
    Polymer({
      is: 'x-circle'
    });
  })();

&lt;/script&gt;
&lt;/dom-module&gt;

On Chrome, where the polyfill isn't used, everything works fine and the gradient is applied to the circle.
On Firefox, the fill attribute's value gets rewritten and to an absolute URL and it doesn't work. 
If I manually edit it in FireBug back to "url(#grad)" it shows properly.

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/rugeron/edit?html,output
