### ISSUE TITLE
Styles of HTMLElement only working when setting position to 'absolute'

### ISSUE THREAD

**Issue by sixtyjs** [webcomponents/webcomponentsjs#517]
When I register and attach an Element to the DOM with any style like width, height, and background-color the element never displays until I set the position to absolute. Also, only setting the styles when element is attached will display color but renders the rest of the inner contents. Trying to inherit from the base HTMLElement to create something great but this is a bad hic-cup for the workflow. Thoughts?

Ex. Change the position of the testStyle to absolute;

var testStyle = 'width:200px;height:200px;background-color:yellow;position:relative;';

```
function A() {}
A.prototype = Object.create(HTMLElement.prototype);

A.prototype.createdCallback = function() {
    console.log('created');

    this.shadow = this.createShadowRoot();
    this.shadow.innerHTML = '<div>firsttext<span>spantext</span>endtext</div>';
    this.shadow.style = testStyle;
};

A.prototype.attachedCallback = function() {
    console.log('attached');
    this.style = testStyle;
    this.style.width = '200px';
    this.style.height = '200px';
    this.style.background = 'blue';
};

A.prototype.detachedCallback = function() {
    console.log('detached');
};

A.prototype.attributeChangedCallback = function() {
    console.log('attr changed');
};

document.registerElement('a-a', {
    prototype: Object.create(A.prototype)
});


var aa = document.createElement('aa');
document.body.appendChild(document.createElement('a-a'));
```

**Comment by notwaldorf** [comment]
You need to set the host's `display` attribute (like `display: block`), which is essentially what `position: absolute` does. By default, a custom element's `host` is `display:inline`, which has dubious styling abilities.
Here's an updated version of your example: http://jsbin.com/podaze/1/edit?html,console,output
