### ISSUE TITLE
Changes arity of Document.createElement

### ISSUE THREAD

**Issue by jasmith79** [webcomponents/webcomponentsjs#523]
I recently had some code break when using the polyfill because it wrapped `Document.createElement` with a decorator that curried the native function, expecting the arity to be 0 (Firefox, Safari, IE, Edge) or 1 (Chrome, Opera).

Changing the signature of built in functions is probably a bad idea, can we use the `arguments` psuedo array? I'll be happy to file a PR if there's interest in changing this.

Related [SO](http://stackoverflow.com/questions/36653913/document-createelement-arity/36654075#36654075) question.

**Comment by TimvdLippe** [comment]
This now all have 1 reported: http://jsbin.com/sujecig/edit?html,console,output
