### ISSUE TITLE
extending native elements: SVG

### ISSUE THREAD

**Issue by azakus** [webcomponents/webcomponentsjs#524]
_From @bradjohnwoods on March 5, 2016 0:47_

Currently you can't extend SVG elements, I was told this was because of a namespace issue?
- Polymer: v1.2.0
- webcomponents: v0.7.21 

_Copied from original issue: Polymer/polymer#3495_

**Comment by azakus** [comment]
FWIW, this is mostly due to the feeling that extending SVG elements will be used too little to justify the engineering effort. We're open to hearing your use-case though.

**Comment by chrisprice** [comment]
A friendly use-case ping for @azakus :smiley:

**Comment by TimvdLippe** [comment]
Closing this as duplicate of https://github.com/webcomponents/custom-elements/issues/13
