### ISSUE TITLE
Need help with shadow dom

### ISSUE THREAD

**Issue by ibnbd** [webcomponents/webcomponentsjs#526]
Hello there @azakus,

I am looking for a solution where I can replace iFrame with shadow dom. Is this possible to call shadow dom on host HTML file and create a DOM within a DIV and push HTML contents on it. Which won't affect host css style. If yes can  you please give an example. Thank You very much.

**Comment by zoechi** [comment]
GitHub issues are for bug reports and features requests. For support questions mailing lists or StackOverflow are usually a better place.

Yes, styles added to custom elements' shadow DOM doesn't affect other elements. See also the https://github.com/webcomponents/webcomponentsjs/blob/master/README.md for more details.

**Comment by notwaldorf** [comment]
Closing as this seems to have been answered! (thanks @zoechi 🍰)
