### ISSUE TITLE
Deferred load of webcomponentsjs will fail if DOM contains an element with id="wrap"

### ISSUE THREAD

**Issue by zerodevx** [webcomponents/webcomponentsjs#529]
Hello,

I'm doing feature detection and will only load the webcomponents polyfill iff

``` js
registerElement' in document && 'import' in document.createElement('link') && 'content' in document.createElement('template')
```

is false. However, if the existing DOM contains an element with `id="wrap"`, 

``` html
<div id="wrap"></div>
```

webcomponents will **fail to load**. 

Repro: http://jsbin.com/viwolohigo/edit?html,console,output

Not sure if it's documented anywhere, but it should be.

**Comment by ebidel** [comment]
Looks like this is colliding with `wrap()`. Oh how I wish DOM ids didn't make directly to JS vars.

@azakus @garlicnation what do you suggest?

**Comment by uqleadegroot** [comment]
+1
We have a third party app we are inserting components into and don't have control of the HTML

**Comment by TimvdLippe** [comment]
The original JSBin is now working as intended.
