### ISSUE TITLE
Using @import statement for WebComponents.js

### ISSUE THREAD

**Issue by 4leem** [webcomponents/webcomponentsjs#530]
I would like to understand how to use WebComponents.js in ES6 using @import statement. I have installed the package from [npm](https://www.npmjs.com/package/webcomponents.js) . I wouldn't be adding the polyfill in the HTML script tag, instead wanted to use within the JS(where I have additional code for React Components).

**Comment by TimvdLippe** [comment]
You can now inline the polyfill per https://github.com/webcomponents/webcomponentsjs#inlining
