### ISSUE TITLE
Polyfill does not seem to work in firefox if webcomponents flag is turned on

### ISSUE THREAD

**Issue by mattrunyon** [webcomponents/webcomponentsjs#534]
In Firefox, if the dom.webcomponents.enabled flag in about:config is set to true, then the polyfills do not seem to work. Turning this flag to false remedied the issue (the default state is false).

Would it be possible to make the polyfill work with this flag enabled still? Or should it be something to alert the user of if it is active?

**Comment by ebidel** [comment]
FF's has an old prototype implementation of Custom elements / shadow dom. I'm not sure we should make it work with that. When they have an updated v1 implementation, the polyfill will of course be made to work with it.
