### ISSUE TITLE
V0&V1: HTML Imports polyfill does not execute onload for empty resources

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#535]
Once importing an empty resource (`text/html 200 Ok ""`), Html Imports polyfill does not execute `onload` callback.

``` js
var link = document.createElement('link');
link.rel = "import";
link.href = 'empty-200.html';
link.onload = function processImportedDocument() {
    alert('This should work!');
};
document.head.appendChild(link);
```

Fails in FF, IE & Safari; works fine with Chrome. Same code works fine when imported html file contains any character.

Live example at http://tomalec.github.io/webcomponentsjs-empty-HTML-Imports-bug/

PR is waiting at https://github.com/webcomponents/webcomponentsjs/pull/536

**Comment by tomalec** [comment]
Can I email personally @tjsavage   ... https://youtu.be/dFxMzUUWLeM?t=24m31s ? ;)

**Comment by tomalec** [comment]
I've made a PR that asserts it in webcomponents/html-imports, maybe this one could be merged https://github.com/webcomponents/html-imports/pull/4

**Comment by notwaldorf** [comment]
@tomalec The `html-imports` PR seems to have been merged, so I'm going to tentatively close this issue, but please re-open it if I shouldn't have! :)
