### ISSUE TITLE
Update polyfill to Custom Elements v1

### ISSUE THREAD

**Issue by supermoos** [webcomponents/webcomponentsjs#540]
Seems like the specs W3C for custom elements changed. There's now a `CustomElementRegistry` on the `Window` object, this enables a fiddle like this to work: https://jsfiddle.net/6rk9oz8f/2/
Ref: https://www.w3.org/TR/custom-elements/#dom-customelementsregistry
Ref example: https://www.w3.org/TR/custom-elements/#custom-elements-autonomous-example

Will the polyfill be updated to comply?

https://jsfiddle.net/hasan3ysf/qzzs6yg0/ - this is the current working solution in Chrome, it's annoying though that you can't directly instantiate a `new SaveBtn()` class but have to assign to a variable first.

**Comment by ebidel** [comment]
Yes, the polyfill will be updated to the new spec. Work is being done in https://github.com/webcomponents/webcomponentsjs/tree/v1.

**Comment by supermoos** [comment]
Any word on a timeline for this?

**Comment by tclzcja** [comment]
Any update on this one? Thank you!

**Comment by aaronshaf** [comment]
What is the difference between tree/v1 and https://github.com/webcomponents/custom-elements ?

**Comment by notwaldorf** [comment]
Hiya! The `v1` branch is being updated to work with `v1`, and #657 is the tracking meta-issue for all items left in porting the polyfill 🎉 

@aaronshaf `tree/v1` was lagging, but has since been updated to use the `custom-elements` repo
