### ISSUE TITLE
Memory Leak in IE11

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#542]
_From @ankurp on May 26, 2016 14:31_

Noticing a lot of memory leak in IE11 and it most likely is due to the order in which node elements are appended to the DOM. Can someone look into this.

_Copied from original issue: webcomponents/webcomponents-lite#7_

**Comment by tjsavage** [comment]
Do you happen to have a repro case that demonstrates this memory leak?

**Comment by tjsavage** [comment]
_From @ankurp on May 31, 2016 13:43_

```html
<!DOCTYPE html>
<html>
  <head>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <base href="https://polygit.org/polymer+:master/components/">
    <script src="webcomponentsjs/webcomponents-lite.js"></script>
    <link href="polymer/polymer.html" rel="import">

    <script>

      // After every second, the memory will increase by ~3 MByte. GC is kicking in sometimes but it will not collect everything.
      setTimeout(function() {
        location.reload();
      }, 1000);

    </script>

  </head>


  <body spellcheck="false">

    <!-- Define a custom element -->
    <dom-module id="simple-element">
      <template>
        <div>Custom Element</div>
      </template>

      <script>
        Polymer({ is: 'simple-element' });
      </script>
    </dom-module>


    <!-- An empty element will also leak! -->
    <dom-module id="even-simpler-element"></dom-module>

  </body>
</html>
```

**Comment by tjsavage** [comment]
_From @ankurp on May 31, 2016 14:6_

@tjsavage Here is also a repo which you can clone and serve with a static server to see the issue in IE11. The page refreshes every second and you can see the memory increase continuously https://github.com/ankurp/polymer-webcomponent-IE-memory-leak

**Comment by tjsavage** [comment]
Got it, thank you. I'm going to move this to the main webcomponents/webcomponentsjs repo to make sure it gets attention. (Will close issues here as well)

**Comment by ankurp** [comment]
We should close this one in favor of this Issue as it has more detail and history https://github.com/webcomponents/webcomponentsjs/issues/541
