### ISSUE TITLE
native-shim HTMLElement prototype is the old function?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#546]
I see the line

``` js
  HTMLElement.prototype = Object.create(origHTMLElement);
```

But should it be

``` js
  HTMLElement.prototype = Object.create(origHTMLElement.prototype);
```

? If the prototype is the `origHTMLElement`, that would mean that the `origHTMLElement.*` static properties will be HTMLElement instance properties?

**Comment by justinfagnani** [comment]
I think I just fixed this, though I admittedly don't have tests for the shim.

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/custom-elements#51
