### ISSUE TITLE
Custom Elements v1: error using polyfill on browser with native window.customElements

### ISSUE THREAD

**Issue by ebidel** [webcomponents/webcomponentsjs#548]
![screen shot 2016-06-01 at 1 44 05 pm](https://cloud.githubusercontent.com/assets/238208/15725100/13b804a8-27ff-11e6-925a-596239ea8696.png)

**Comment by ebidel** [comment]
@justinfagnani her's a repo: http://jsbin.com/tawuzuhuri/edit?html,output

Works in Canary, but not in Chromium with the CE flag turned on.

**Comment by ebidel** [comment]
@justinfagnani any word on this? Still seeing in on the latest v1 branch.

**Comment by justinfagnani** [comment]
Should be fixed now

**Comment by justinfagnani** [comment]
At least, when I paste the new version into that jsbin on Canary, and change the code to load the polyfill, it works fine.

**Comment by ebidel** [comment]
LGTM
