### ISSUE TITLE
Custom Elements v1: element should not be upgraded until it's in document

### ISSUE THREAD

**Issue by ebidel** [webcomponents/webcomponentsjs#549]
Spec: 

> Note that upgrades only apply to elements in the document tree. (Formally, elements in a shadow-including document.) An element that is not inserted into a document will stay un-upgraded. 

This test currently fails under the polyfill:

```
window.customElements.define('better-button', BetterButton);

var b = document.createElement('better-button');
console.assert(!(b instanceof BetterButton), 'Element should not be upgraded when not in document');
```

**Comment by justinfagnani** [comment]
This is working as intended, and not an upgrade scenario. `better-button` is defined before `b` is created, so it's created in it's upgraded state (there's an official term in the spec I have to go look up), and this does not perform an upgrade.

**Comment by ebidel** [comment]
I see now. Confusing because it's an edge case (as highlighted in the spec section). I'm also mixing things with the v0 (`registerElement`) behavior where created elements would get their prototype, after they're registered and before they're added to the DOM.
