### ISSUE TITLE
Webcomponentsjs makes prototype.js fail in IE

### ISSUE THREAD

**Issue by ostap0207** [webcomponents/webcomponentsjs#562]
prototype.js extends global Event object with custom methods e.g. `Event.observe`

At the same time webcomponentsjs does the following:

``` javascript
  if (!window.Event || isIE && typeof window.Event !== "function") {
    var origEvent = window.Event;
    window.Event = function(inType, params) {
      params = params || {};
      var e = document.createEvent("Event");
      e.initEvent(inType, Boolean(params.bubbles), Boolean(params.cancelable));
      return e;
    };
    window.Event.prototype = origEvent.prototype;
  }
```

Which overrides global `Event` and copies prototype from original Event object. But own properties of `Event`, such as `Event.observe` in this case, are not being copied.

This makes prototype.js not useable in IE.

**Comment by ostap0207** [comment]
Possible solution is to copy all properties from `origEvent` as well.

**Comment by alexfromgalax87** [comment]
i still get error with "observe" method from prototype after adding the fix above

**Comment by ostap0207** [comment]
The final fix was to add:
```javascript
 var origPropertyNames = Object.getOwnPropertyNames(origEvent);
 for (var i = 0; i < origPropertyNames.length; i++) {
   window.Event[origPropertyNames[i]] = origEvent[origPropertyNames[i]];
 }
```

after
```javascript
 window.Event.prototype = origEvent.prototype;
```

**Comment by notwaldorf** [comment]
This looks resolved? Tentatively closing, but please reopen if that's not the case
