### ISSUE TITLE
Static properties/methods ignored for `element.constructor`

### ISSUE THREAD

**Issue by zanona** [webcomponents/webcomponentsjs#563]
Currently I can't seem to be able to retrieve an element constructor static methods or properties when having the following:

``` js
document.registerElement('x-foo', class extends HTMLElement {
  static staticMethod() { return true; }
  instanceMethod() { return true; }
});
```

so when creating an element with the below, the response is unexpectedly `undefined` 

``` js
document.createElement('x-foo').constructor.staticMethod // <== undefined
document.createElement('x-foo').constructor().instanceMethod // <== function () { return true; }
```

How can I still use static methods using webcomponentsjs?

Apparently the same happens when using Object.prototype instead classes.

**Comment by zanona** [comment]
Hey guys, would you have any comments on this? the constructor object seem to be greatly changed and non-compliant when using webcomponents.js

Also, `Object.getPrototypeOf(document.body)` returns about 40 errors, just try it on your console here in github.

**Comment by anaran** [comment]
@zanona which browser and version are you using?

**Comment by zanona** [comment]
Hey @anaran thanks for the reply.

The issue happens on the below browsers while not returning the static method at all:

- Safari 9.1
- Firefox 45
- Edge 13

The snippet I am using to test is:

```js
document.registerElement('x-foo', class extends HTMLElement {
  static staticMethod() { return true; }
  instanceMethod() { return true; }
});

var foo = document.createElement('x-foo');

document.body.innerHTML = ''
    + '<pre>' 
    + 'x-foo staticMethod is: ' + foo.constructor.staticMethod
    + '</pre>'
```

Available at https://jsfiddle.net/3tugtdyc/2/

Actually Chrome is the only one not returning __`undefined`__ as the static method, but then it's the only one that discards webcomponents.js altogether.

**Comment by treshugart** [comment]
I've just come across this, as well. I ended up putting up a [PR](https://github.com/skatejs/skatejs/pull/653) into [SkateJS](https://github.com/skatejs/skatejs). It probably wouldn't be too much effort to port this over instead of doing it there.

Some things I noticed:

- This works in Blink's v0 implementation in Chrome 39 and above
- This is reproducible in Chrome 38 and below, in native

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/lagepeg/edit?html,console,output
