### ISSUE TITLE
 http://customelements.io/ seems empty in firefox nightly

### ISSUE THREAD

**Issue by anaran** [webcomponents/webcomponentsjs#570]
@Nevraeka suggested to move https://github.com/webcomponents/webcomponents.github.io/issues/321 here.

I still see this in Firefox 50.0a1 (2016-06-16)

css rule for body[unresolved] in
https://customelements.io/assets/vendor/webcomponentsjs/webcomponents-lite.js
matches.

Disabling the inline rules in firefox devtools makes the body visible and search functionality works.

I do have
dom.webcomponents.enabled: true
set in firefox nightly.

**Comment by ebidel** [comment]
You'll want to turn off `dom.webcomponents.enabled: true`. Generally, FF's early implementation of shadow dom and custom elements is old and causes issues like this.
