### ISSUE TITLE
[v1] HTMLElement shim broke code outside the library

### ISSUE THREAD

**Issue by edoardocavazza** [webcomponents/webcomponentsjs#576]
If I want to instantiate a class with HTMLElement prototype (NOT a custom element)
```js
class MyClass extends HTMLElement {}
new MyClass();
```
I get an error because no custom element definition has been found. I think that the shim should return the default behavior if the scope is not a custom element.

**Comment by justinfagnani** [comment]
This behavior is inline with the spec, see https://html.spec.whatwg.org/multipage/dom.html#html-element-constructors step 3.
