### ISSUE TITLE
document.querySelectorAll and element.querySelectorAll do not return an iterable NodeList 

### ISSUE THREAD

**Issue by salientgreen** [webcomponents/webcomponentsjs#577]
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Steps to reproduce:**

Windows 10
Firefox 47.0.1

var div_list = document.querySelectorAll('div'); // should return a NodeList
console.log(div_list);
var div_array = [...div_list]; // converts NodeList to Array

**Actual results:**

Object { 0=t}
TypeError: div_list is not iterable

**Expected results:**

An iterable NodeList should be returned by document.querySelectorAll that can be converted to an array using the spread operator as shown here: 
https://developer.mozilla.org/en-US/docs/Web/API/NodeList?redirectlocale=en-US&redirectslug=DOM%2FNodeList#Converting_a_NodeList_to_an_Array

var div_list = document.querySelectorAll('div'); // returns NodeList

console.log(div_list);

[div.wrapper]
    0: div.wrapper
    length: 1
    **proto**: NodeList

var div_array = [...div_list]; // converts NodeList to Array

console.log(div_array);

[div.wrapper]
    0: div.wrapper
    length: 1
    **proto**: Array

**Comment by pdesjardins90** [comment]
Still does this in v1

**Comment by pdesjardins90** [comment]
I can confirm that this is still there as of october 2017

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/lidexab/edit?html,console,output
