### ISSUE TITLE
Template.js shouldn't modify `Node.prototype.cloneNode`

### ISSUE THREAD

**Issue by mhkeller** [webcomponents/webcomponentsjs#578]
Template.js overwrites the `cloneNode` method of `Node.prototype` on [line 216](https://github.com/webcomponents/webcomponentsjs/blob/bffb86c750039b54ca9d3d3df5c46426cb4ab570/src/Template/Template.js#L216) of Template.js.

This causes problems with libraries that use native `Node.cloneNode`. 

This should be fixed to either create a new prototype method or replace `Node.prototype.cloneNode` with `nativeCloneNode` when this script is finished.

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/template#4
