### ISSUE TITLE
Safari 9.1.1 : NotSupportedError: DOM 9: The implementation did not support the requested type of object or operation.

### ISSUE THREAD

**Issue by imanzano** [webcomponents/webcomponentsjs#579]
I got this error and the load fails.

NotSupportedError: DOM Exception 9: The implementation did not support the requested type of object or operation.
p - webcomponentsjs.min.js:628
dispatchEvent
dispatchEvent- webcomponentsjs.min.js:988
(anonymous function)- webcomponentsjs.min.js:245
(anonymous function)- webcomponentsjs.min.js:4498:206

Only happen in Safari. Chrome work well.

Any idea ? workaround ?

thanks!

**Comment by notwaldorf** [comment]
Closing, as this is an old issue and doesn't have any repro steps. The polyfill works in Safari, so this is probably related to a particular bug in your setup. Please re-open if you have more details
