### ISSUE TITLE
Dynamically created <script>s do not fire 'load' event inside an HTML import

### ISSUE THREAD

**Issue by matthewp** [webcomponents/webcomponentsjs#581]
NOTE: See comments below, was able to reduce this down.

**Comment by matthewp** [comment]
Note that the bug only occurs when the script was cloned from a `<template>`, if you create the script with `document.createElement` or `document._currentScript.ownerDocument.createElement` it will fire the load event.

**Comment by matthewp** [comment]
Ok, I was able to reduce this down to the below, so I think this is not a webcomponentsjs bug but rather a browser bug. This works in Chrome but not in Safari or Firefox. I would expect it to work. 

Before I close the issue, any advice on how I should approach reporting this, since I am not sure it's a bug or not...

```html
<!doctype html>
<html>
<head>
<title>Test</title>
</head>
<body>
<script>
(function(){
  var doc = document.implementation.createHTMLDocument('Test');
  doc.body.innerHTML = '<template><scr' + 'ipt></scr' + 'ipt></template>';
  var template = doc.querySelector('template');
  var frag = document.importNode(template.content, true);
  var script = frag.querySelector('script');
  script.src = './foo.js';
  script.addEventListener('load', function(){
    console.log('loaded');
  });
  document.body.appendChild(script);
})();
</script>
</body>
</html>
```

**Comment by matthewp** [comment]
Going to close this issue and report in Firefox.

**Comment by matthewp** [comment]
I filed against firefox here: https://bugzilla.mozilla.org/show_bug.cgi?id=1288080

**Comment by matthewp** [comment]
This is a bug in the polyfill. The problem is that when you set .innerHTML on the new document it causes scripts within that document not to run. The firefox bug explains the issue.

**Comment by notwaldorf** [comment]
cc-ing @valdrinkoshi as an FYI for `v1`

**Comment by fadfood** [comment]
Is this issue solved? I can't load scripts dynamically in custom elements

**Comment by tomalec** [comment]
This may hit Chrome in 66 as well https://bugs.chromium.org/p/chromium/issues/detail?id=572693#c16

**Comment by TimvdLippe** [comment]
As HTML Imports have been removed in v2, I am closing this issue.
