### ISSUE TITLE
V1 Pollyfill Release?

### ISSUE THREAD

**Issue by RevillWeb** [webcomponents/webcomponentsjs#582]
Hi,

I've been playing with the V1 branch working with Custom Elements and from my limited testing it appears to be working :) I was wondering if you know when you were planning on releasing this (i.e. merging it into master).

Thanks for the incredible work, us web component nuts literally couldn't survive without this :)

**Comment by treshugart** [comment]
@justinfagnani we're actively using it from the v1 branch. Is there anything I can do to help with this?

**Comment by RevillWeb** [comment]
My main reason for the question is that I'm planning on writing some tutorials and training material to encourage more web component usage. It would be nicer to not have to explain that a separate branch and file is required for the newer API - and in general would be easier for most users of the pollyfills.

Assuming that V1 would eventually become part of the main webcomponentsjs release on master I was just wondering if you had any idea when this would be :)

Thanks again.

**Comment by RevillWeb** [comment]
On a similar note, are then plans to update the Shadow DOM polyfills to polyfill the V1 API?

**Comment by treshugart** [comment]
Hey @RevillWeb I can't speak for the polyfill here, but until that's updated to v1, you can try https://github.com/skatejs/named-slots/. It's not a complete polyfill, but it might work for your use case.

**Comment by RevillWeb** [comment]
Hi @treshugart thanks for the link, looks pretty good I will give it a go. Would be great to get an update regarding the polyfill too :)

**Comment by lukasoppermann** [comment]
Any news on this?

**Comment by justinfagnani** [comment]
We just split out custom elements into it's own repo. `bower install webcomponents/custom-elements` should work, and we're on npm now: https://www.npmjs.com/package/@webcomponents/custom-elements
