### ISSUE TITLE
use document._documentURI instead document._URL

### ISSUE THREAD

**Issue by zanona** [webcomponents/webcomponentsjs#585]
Browser version: Safari 9.1.1

When importing a document, it's possible to access its URL through `document.documentURI`, however when using the polyfill this becomes `document._URL`.

Can we honour nomenclature and keep it `document._documentURI` just as it's done for `_currentScript`?

This would certainly help users to understand the conventions.

**Comment by TimvdLippe** [comment]
I don't think we expose either properties, so I suppose this issue has been resolved.
