### ISSUE TITLE
Custom Element v1 error on chrome

### ISSUE THREAD

**Issue by warnerandy** [webcomponents/webcomponentsjs#586]
I am seeing this error on occasion at page load. I'm only using the custom elements v1 polyfill in this scenario.

<img width="841" alt="screen shot 2016-08-03 at 12 30 41 pm" src="https://cloud.githubusercontent.com/assets/44771/17377260/314f1c56-5976-11e6-9af8-7e0136858724.png">

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/custom-elements#50
