### ISSUE TITLE
ETA for WebComponents V1?

### ISSUE THREAD

**Issue by idibidiart** [webcomponents/webcomponentsjs#590]
Hi

It was mentioned here https://developers.google.com/web/fundamentals/primers/shadowdom/ that you're updating this to V1 of WebComponents spec.

What's the ETA on that? :-)

👍

**Comment by DimitryDushkin** [comment]
https://developers.google.com/web/fundamentals/primers/shadowdom/ is misleading about possibility of current use.

**Comment by treshugart** [comment]
Until it's released, maybe give https://github.com/skatejs/web-components a try.

**Comment by ebidel** [comment]
Let's use https://github.com/webcomponents/webcomponentsjs/issues/582. Marking as a dupe.
