### ISSUE TITLE
[Spec] clarification on global configuration 

### ISSUE THREAD

**Issue by idibidiart** [webcomponents/webcomponentsjs#592]
I had this conversation with one of the members of Facebook's React team about using Shadow DOM for creating truly reusable React components, and he mentioned that they have a problem with the spec:

> dibidiart commented 17 days ago
> @gaearon
> 
> What is Facebook's position on using Shadow DOM for CSS encapsulation? Have you seen Maples.js? https://github.com/Wildhoney/Maple.js/
> 
> Would you consider moving to this approach at some point? Or why not now? :-)
>  @gaearon
>  
> gaearon commented 17 days ago
> We are currently not planning to use Shadow DOM actively because it’s not supported by many our target browsers and requires "global configuration." We may revisit this choice in the future.
> 

The link to "global configuration" issue: https://facebook.github.io/react/contributing/design-principles.html#configuration

Can you clarify what Dan is referring to and whether or not it is a general problem for reuse that is due to the WebComponents spec itself?

**Comment by ebidel** [comment]
The Shadow DOM API itself has no notion of "global configuration". In fact, the whole API is meant to dictate local behavior for DOM trees.

He might be referring to the global intrusiveness that the full shadow dom polyfill has? It basically patches all DOM nodes to mimic the scoping behavior of SD. Shady DOM (polymer's lighter-weight, less correct, but faster) "polyfill" does not perform the same patching.

**Comment by idibidiart** [comment]
Thanks for the info about the existence of another polyfill, namely, Shady DOM. Will check it out.

I think he's referring to document.registerElement() which (I've just started looking at it, so this could be my misconception) seems to associate a specific custom element tag e.g. x-foo, to a custom element constructor e.g. XFoo. So if you had two component libraries registering "x-foo" with different prototypes (or extending different elements) what would happen in that case? How does SD encapsulation come into play?

**Comment by ebidel** [comment]
So `document.registerElement()` is custom elements v0, which is another spec, but unrelated to shadow dom.

You don't have to save the return val of d.registerElement. Just drop it on the floor. Or, if it's undesirable that the constructor ends up on the global `window` object, put it in a namespace (`var myapp = {}; myapp.XFoo = document.registerElement('x-foo');`).

> So if you had two component libraries registering "x-foo" with different prototypes (or extending different elements) what would happen in that case? 

This is true. The tag name "x-foo" can only be registered once. It's just how HTML works! However, in practice this has never been an issue in the apps I've built. It's also unrelated to shadow dom and part of the custom elements spec.

Can you register a react component twice? A jquery plugin? Usually the answer is no :)

**Comment by idibidiart** [comment]
For some insane reason, I was thinking that using two different shadow roots we could encapsulate two different versions of "x-foo". I assumed SD is like having iframes without the clunkiness and baggage. With iframes "document" and "window" are specific to the iframe, and so is the linked CSS and scripts. 

Anyway, as a web dev, I'll need to do my homework and understand the Web Components the associated set of specs (SD, CE, and whatever else) now that major browser vendors are moving forward on that front :-)

**Comment by idibidiart** [comment]
Re-opening in case you have any feedback about how React achieves reuse with JSX vs how Web Components does reuse (by extending the global DOM with new custom element types)  ... There might be something to learn from how React does reuse, and React might have something to learn from how Web Components does CSS isolation. At the very least, the Facebook React team and Web Components team should be talking about the future of resuable components on the web.

**Comment by Garbee** [comment]
React is quite different from Web Components integration. React is using VDOM to provide *state* to components, not isolation. While Shadow DOM is our normal old DOM, just encapsulated for *isolation between components* needs.

React is just enforcing a solid structure, however it is still functioning under global scope when it comes to styling and scripting when it is executed in-client. For example, your custom CSS can still target anything that comes out of react and modify how it looks. When using Shadow DOM, your CSS can't touch a components inner-styling.

I'd ask for clarification on what they mean by global configuration. As far as their other concern, it is purely down to browser support not being wide enough and polyfills can slow things down for users who need it. For React's needs, that is a massive drawback that they can't reconcile.

**Comment by treshugart** [comment]
@idibidiart FWIW SkateJS uses a virtual DOM, supports JSX and can have non colliding names (as well as stateless functions - reuse without registration), all built on top of the specs.

**Comment by idibidiart** [comment]
@garbee I know what React does. I just hadn't really thought much about Web Components. MapleJS and SkateJS are proof that you could effectively use Shadow DOM for CSS isolation which is what I was suggesting to them. I still think the confusion around global configuration that they have has to do with custom elements (registering is a global config), not the Shadow DOM. I'll double check that and get back with an answer.

**Comment by idibidiart** [comment]
@skatejs looks like it's similar to MapleJS using the Virtual DOM library instead of React? That model is what I was suggesting to them, but someone it got confused (I think) with custom elements.

**Comment by treshugart** [comment]
@idibidiart it uses [incremental-dom](https://github.com/google/incremental-dom)

**Comment by justinfagnani** [comment]
I think the "global configuration" referenced above, probably refers to an assumption that React would need to globally use Shadow DOM, or globally not use it, via some kind of `React.configure()` API. I think this discussion is out of scope for the polyfills though.
