### ISSUE TITLE
Why was attachedCallback renamed to connectedCallback

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#598]
and `detachedCallback` renamed to `disconnectedCallback`?

**Comment by treshugart** [comment]
There's some prior art in the W3C web components issues https://github.com/w3c/webcomponents/issues/362. I think there's some they reference from there and there were a couple PRs, but that should give you the gist.

**Comment by ebidel** [comment]
Going to close this as this was a spec change. The link to the discussion is sufficient.
