### ISSUE TITLE
[v1] No upgrade function

### ISSUE THREAD

**Issue by argelius** [webcomponents/webcomponentsjs#599]
In the v0 version of the polyfill there was a `CustomElements.upgrade(el)` function that would force the upgrade of an element.

This was very useful to get the same behavior on both native custom elements in Chrome and browsers using the polyfill. With v1 you can not access properties on the element directly after it has been created.

Does the v1 polyfill have a way to force upgrade an element?

**Comment by justinfagnani** [comment]
We're going to investigate making more of the polyfill synchronous, which might get rid of the need for something like `upgrade()`. I'd prefer that, as I'd rather add as little API that's specific to the polyfill as possible.

**Comment by argelius** [comment]
@justinfagnani Yes, not having to force element upgrade at all would of course be even better :)

Thanks for looking into this.

**Comment by justinfagnani** [comment]
I don't think we want to add new API on-top of the spec. This will make it difficult to not load the polyfill. Please reopen in the new repo if you have a specific use case where this type of operation is needed: https://github.com/webcomponents/custom-elements
