### ISSUE TITLE
IE can't reload webcomponents.js on a framed page

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/webcomponentsjs#6]
One common method to force a framed page (on the same domain) to reload is to invoke `contentWindow.location.reload()`. This method fails in IE if the framed page loads webcomponents.js.

To repro:
1. Copy http://jsbin.com/ruceci/edit somewhere. This framing page just tries to frame another page. You'll need both it and the framed page to be on the same domain to avoid security constraints.
2. Update the URL in the iframe so that it points to a target page on the same domain. It doesn't matter what the target page does, as long as it loads webcomponents.js. It doesn't need to load polymer.html.
3. Open the framing page and click the Reload button.

On IE, this causes an exception to be thrown in HTMLElement.js, line 247:

```
  registerWrapper(OriginalHTMLElement, HTMLElement,
                  document.createElement('b'));
```

When the exception is thrown, OriginalHTMLElement is undefined.

This problem is not seen in Chrome, Firefox, and Safari.

**Comment by garlicnation** [comment]
I've confirmed that this is still happening. document.createElementNS is undefined in Element.js in an iframe.

@sorvell It seems like we're somehow bashing over this function on document in the iframe's context. I have a minimal repro locally.

**Comment by garlicnation** [comment]
Fixed in IE's March 10th patch.

**Comment by renatotrev** [comment]
I'm able to reproduce the same issue above using the release v0.7.15.

**Comment by misterbrownlee** [comment]
lurk mode: engaged

**Comment by aayush-nitb** [comment]
I am facing same issue in IE 11.0.10240.17022 using webcomponents v0.7.22.
![image](https://cloud.githubusercontent.com/assets/1482529/17924997/b412528c-6a08-11e6-9e5b-c0f8f58b8e16.png)

**Comment by proxyLaw** [comment]
Well basically from I can see the methods(createElement) are not yet there on reload, so a simple wait would be enough.
Not sure how it will be implemented with all IIFE's, though the most naive fix would be wrapping it with another IIFE(tested on IE11; using webcomponents v0.7.22)

```
(function init() {
    if (!document.createElement) {
        return setTimeout(init, 16);
    }
    (function() {
        window.WebComponents = window.WebComponents || {
        ...
```

**Comment by proxyLaw** [comment]
A naive fix would be inserting something like this on top of the webcomponents.js.
Tested on IE11; chrome 52; FF 48 with Polymer(1.6.1) and a simple component
webcomponents v0.7.22.
```
if (!document.createElement) {
    document.createElement = document.constructor.prototype.createElement;
    document.createElementNS = document.constructor.prototype.createElementNS;
    document.importNode = document.constructor.prototype.importNode;
}
```

**Comment by MagmaRules** [comment]
I'm running 0.17 in my project and ran into this problem. Updating to 0.22/0.23 did not fix the problem. Adding the fix from @proxyLaw solves the problem for now.
