### ISSUE TITLE
[v1] Defining observedAttributes with no attributeChangedCallback fails

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/webcomponentsjs#602]
According to https://github.com/w3c/webcomponents/issues/555, it should be possible to define a class with `observedAttributes` and no `attributeChangedCallback`.

```
customElements.define("x-x", class extends HTMLElement {
  static get observedAttributes() { console.log("does this happen?"); }
});
```

The expected behavior is, "nothing should be logged to the console (and no error thrown)."

Actual behavior of the v1 polyfill is to try to invoke the missing `attributeChangedCallback`.

**Comment by justinfagnani** [comment]
This should be fixed now.
