### ISSUE TITLE
How to import v1 into ES6 module?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#603]
I think the following will do, but I've gotten some errors in Meteor and I'm not sure if it's Meteor's fault or not, but I think the following should work:

Depend on v1 branch from github in package.json:

```json
{
  "dependencies": {
    "webcomponents.js": "webcomponents/webcomponentsjs#v1"
  }
}
```

then in my ES6 module code:

```js
import 'webcomponents.js/src/CustomElements/v1/native-shim'
import 'webcomponents.js/src/CustomElements/v1/CustomElements'
```

Is that what I should do? I'm not looking to build anything manually, I'm simply looking to install and use.

**Comment by treshugart** [comment]
@trusktr you also need to make sure you have the `Map` and `MutationObserver` polyfills if you need them.

**Comment by justinfagnani** [comment]
The polyfill shouldn't be a dependency of any modules, since it's polyfilling global behaviors. It should be included (or not) as a `<script>` tag in the main page. If it's a dependency of a module, it'll be pulled in even when not needed.

**Comment by trusktr** [comment]
> If it's a dependency of a module, it'll be pulled in even when not needed.

Not necessarily true. Doesn't a good polyfill do feature detection first? For example, the WebReflection v1 polyfill [doesn't mess with the globals if they already exist](https://github.com/WebReflection/document-register-element/blob/v1/src/document-register-element.js#L243), and the recommended usage is with `import 'document-register-element'`, while your polyfills don't seem to do any checking like that.

Wouldn't it be okay to import polyfills that *do* do those checks? It would mean that the first polyfill to be imported wins, but if the user really wants a specific polyfill then the user could still manually include a script tag before the module code and so the polyfills would be no-ops.

**Comment by trusktr** [comment]
@treshugart 

> Map and MutationObserver

I'm targetting recent enough environments, so those exist natively.

Well anyways,

```js
import 'webcomponents.js/src/CustomElements/v1/native-shim'
import 'webcomponents.js/src/CustomElements/v1/CustomElements'
```

isn't working for me in Meteor's ES6 module environment, with an error

```
While computing assigned variables:
node_modules/webcomponents.js/src/CustomElements/v1/native-shim.js: Unexpected token (30:17)
```

**Comment by trusktr** [comment]
Made a bug report in Meteor: https://github.com/meteor/meteor/issues/7738

**Comment by justinfagnani** [comment]
Yes, the polyfill feature detects and doesn't apply itself if custom elements are already available, but then you've added a ~3k dependency to you module for no reason. If one module does that, and another loads a different polyfill, then you might load ~10k for no reason on Chrome.

The polyfill is an extension to the _environment_, it's not scoped, and it should be applied to the whole environment at the top-level of the app. It's an _implicit_ dependency of code that uses the Custom Element APIs.

**Comment by trusktr** [comment]
> but then you've added a ~3k dependency to you module for no reason.

But, that is also an extra step. If a user can simple `import Something from 'my-library'` and they are good to go, that can be seen as an advantage.

What are the steps (f.e. the series of shell commands) that you'd explicitly list for someone to get started using the v1 polyfill right now?

**Comment by justinfagnani** [comment]
All I can say is that including polyfills has lead to no end of headaches for us, and we are slowly backing them out where we have them, even if it's a breaking change. Including the Web Animations polyfill with the neon-* elements was a big mistake, and a big breaking change now to fix it. Only the application has enough knowledge its environment to correctly choose which polyfills to load. A web component should not load it's own Promise polyfill, or WeakMap polyfill likewise.

Regarding instructions on using the polyfill, we'll definitely add those before merging into master, and they'll be different when we're actually distributing the new polyfill. For now it's something like:

```bash
$ git clone https://github.com/webcomponents/webcomponentsjs.git
$ npm i
$ gulp build
$ bower link
$ cd ../my-project
$ bower link webcomponentsjs
```

and in index.html:

```html
<html>
  <head>
    <!-- polyfills -->
    <script src="/bower_components/webcomponentsjs/dist/CustomElementsV1.min.js"></script>
    <!-- Web Animations, Promise, WeakMap, etc., as necessary -->
  </head>
</html>
```

If you're developing a reusable element, only include the polyfill in tests, not in your element's HTML or JS.

**Comment by Nitin-Prabhakar** [comment]
Hey guys,

I have been trying to follow Eric Bidelman's primer documentation on the v1 specs.
My problem is, I havent been able to polyfill my browsers as much as I try.

here is what I did

- cd bower_components

- git clone https://github.com/webcomponents/webcomponentsjs.git

- cd webcomponentsjs

- git checkout v1

- npm install

- gulp build

- include the component in my index.html

```html
<script src="bower_components/webcomponentsjs/dist/webcomponents.js"></script>
```

and , I can not use customELements nor can I do attachShadow

**Comment by ebidel** [comment]
The script should be:

<script
src="/bower_components/webcomponentsjs/dist/CustomElementsV1.min.js"></script>

I don't believe the shadow dom polyfill is ready as of yet.

**Comment by Nitin-Prabhakar** [comment]
Ah ok. TYSM Eric! :) 
Is there a ballpark for when shadowDoMv1 will be ready

**Comment by OliverJAsh** [comment]
After reading https://medium.com/dev-channel/the-case-for-custom-elements-part-1-65d807b4b439#.dw606rus9 and https://developers.google.com/web/fundamentals/primers/shadowdom/ I thought I would had a give at writing a simple web component using shadow DOM in latest stable Chrome.

My understanding is the latest versions of Custom Elements nor Shadow DOM are available in Chrome stable (52 as of writing), so a polyfill is needed.

But sadly it looks like the polyfill isn't ready to use 😢 

Thanks for all your work, can't wait to start using this (v1).

**Comment by ebidel** [comment]
Unfortunately, the v1 polyfills are now behind what Chrome is shipping natively. Chrome 53 is shipping native Shadow DOM v1. Chrome 54 will be shipping native Custom elements v1 9https://www.chromestatus.com/features/4696261944934400). 

I'll ask around about the shadow dom v1 polyfill progress.

**Comment by justinfagnani** [comment]
The custom elements polyfill has moved to https://github.com/webcomponents/custom-elements

I still would very, very strongly recommend against importing any global polyfill like Custom Elements directly into JavaScript.

As for Shadow DOM. I don't know of any plans to update the full polyfill. We've separated out Polymer's "Shady DOM" shim into it's own library though: https://github.com/webcomponents/shadydom

**Comment by trusktr** [comment]
@justinfagnani 

Thanks for showing those steps. I don't have bower, I was able to do the following:

```sh
npm install @webcomponents/custom-elements --save
npm link -s node_modules/@webcomponents/custom-elements/src/native-shim.js /path/to/served/folder/native-shim.js
npm link -s node_modules/@webcomponents/custom-elements/src/custom-elements.js /path/to/served/folder/custom-elements.js
```

```html
<script src="/path/to/served/folder/native-shim.js"></script>
<script src="/path/to/served/folder/custom-elements.js"></script>
<script>
  customElements.define('my-el', class MyEl extends HTMLElement { /* ... */ })
</script>
```

This also works (in app code for example):

```js
import '@webcomponents/custom-elements/src/native-shim'
import '@webcomponents/custom-elements/src/custom-elements'

customElements.define('my-el', class MyEl extends HTMLElement { /* ... */ })
```

By the way, when is native-shim required?
