### ISSUE TITLE
[v1]Issue with used constructor.

### ISSUE THREAD

**Issue by tosandeepgarg** [webcomponents/webcomponentsjs#604]
Hi,

I am trying to use single extended class for registering my custom element. But getting error at runtime. Following is the code snippet.
        window["customElements"].define("my-tag1", MyTag);
        window["customElements"].define("my-tag2", MyTag);
        window["customElements"].define("my-tag3", MyTag);

On chrome i am getting following error.
NotSupportedError: CustomElementRegistry.define failed for 'my-tag2'. The constructor is already used.

**Comment by justinfagnani** [comment]
This is correct per the spec.

The reason you can't define more than one tag with the same constructor function is that when using constructors to create elements, like in `new MyTag()`, the browser has to look up the correct tag to use. If there's isn't a one-to-one mapping, it couldn't do this.

This simplest workaround is to make trivial subclasses for each tagname:

```
window["customElements"].define("my-tag1", class extends MyTag {});
window["customElements"].define("my-tag2", class extends MyTag {});
window["customElements"].define("my-tag3", class extends MyTag {});
```
