### ISSUE TITLE
[bug] breaks Meteor

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#608]
I was trying to use v1 in Meteor but it fails. Not sure who's fault it is. The only two lines of code are:

```js
import 'webcomponents.js/src/CustomElements/v1/native-shim'
import 'webcomponents.js/src/CustomElements/v1/CustomElements'
```

which results in a [familiar yet unhelpful error](https://github.com/meteor/meteor/issues/5551):

```js
   While computing assigned variables:
   node_modules/webcomponents.js/src/CustomElements/v1/native-shim.js: Unexpected token (30:17)
```

Reproduction:

```sh
git clone git@github.com:trusktr/meteor --branch issue-7738 --single-branch
cd meteor
./run-dev.sh
```

Note, I'm getting the webcomponents.js package from GitHub (see package.json).

**Comment by trusktr** [comment]
Opened issue in Meteor: https://github.com/meteor/meteor/issues/7738

**Comment by justinfagnani** [comment]
The shim can only be loaded in browsers that support `new.target` - it's a syntax error in those that don't. This is why it's a separate file. It'll have to be conditionally loaded, either with server-side browser sniffing, or maybe a client-side `document.write`.

**Comment by trusktr** [comment]
The error was because there was a [comma instead of a colon](https://github.com/webcomponents/custom-elements/issues/5), causing invalid syntax, which has since been fixed.

**Comment by justinfagnani** [comment]
The shim still will throw a syntax error in browsers that don't support `new.target`
