### ISSUE TITLE
CustomElements - document.importNode/adoptNode does not upgrade custom elements

### ISSUE THREAD

**Issue by TeaSeaLancs** [webcomponents/webcomponentsjs#61]
Using document.importNode/adoptNode on a page using the custom elements polyfill (eg: Firefox, IE) does not perform upgrading of custom elements. Performing the same function on browsers with a native implementation (ie: Chrome) triggers the upgrade instantly.

Note: I've not tried this with a proper Polymer element, this is simply when using only the custom elements polyfill.

An example of this issue can be seen at http://jsfiddle.net/0hj3u6p4/4/

On Chrome, the output shows both "mod-copy1" and "mod-copy2". On other browsers, it only shows "mod-copy2".

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/zekedux/edit?html,console,output
