### ISSUE TITLE
Continuous Integration Seems to be  Broken

### ISSUE THREAD

**Issue by snuggs** [webcomponents/webcomponentsjs#611]
Please see https://travis-ci.org/webcomponents/webcomponentsjs/builds/157020858

![capture d ecran 2016-09-02 a 03 34 48](https://cloud.githubusercontent.com/assets/38223/18196210/0c4aae0c-70be-11e6-90b9-dafdbb2dd63b.png)

**Comment by snuggs** [comment]
Blocked in https://github.com/webcomponents/webcomponentsjs/pull/610

**Comment by snuggs** [comment]
@azakus @sorvell **crickets**

**Comment by notwaldorf** [comment]
The master branch looks better now that in the screenshot, in the sense that almost 800 tests are being ran, and less than 5 fail: https://travis-ci.org/webcomponents/webcomponentsjs/builds/177827630
 
Good news: the `v1` branch has a happy CI. Bad news: it's very unlikely we'll spend effort trying to fix the `v0` branch more than it is already fixed, so I'm going to close this issue for now.
