### ISSUE TITLE
CustomElementsV1 gulp task broken?

### ISSUE THREAD

**Issue by rubenhazelaar** [webcomponents/webcomponentsjs#612]
I want to use the minified version so I pulled in the library through a git clone. Went through the following build sequence:

```
git clone https://github.com/webcomponents/webcomponentsjs
cd webcomponentjs
git checkout v1
gulp CustomElementsV1
```

However the task does not seem to finish or produce a minified file as the task describes in the gulpfile.js. Perhaps a bug?

**Comment by justinfagnani** [comment]
looks like you're missing an `npm install` after the `git checkout v1`

**Comment by justinfagnani** [comment]
Custom Elements has moved to: https://github.com/webcomponents/custom-elements

**Comment by rubenhazelaar** [comment]
Ah yes did the npm install as well, but forgot to mention it. I will test it (from the new repo) and will create an issue there is the problem persists.
