### ISSUE TITLE
::content > * doesn't work

### ISSUE THREAD

**Issue by zanona** [webcomponents/webcomponentsjs#613]
On Safari 9.1, the `::content > *` selector doesn’t work. While `::content > tag` does.

**Comment by ebidel** [comment]
This may be because the v0 web components polyfills do not fix up the styles. That's at the Polymer level atm. The v1 polyfills will include the style shimming that Polymer currently does for you.

work in chrome but not safari: http://jsbin.com/gejizudajo/edit?html,output

**Comment by zanona** [comment]
@ebidel thanks! Looking forward to see it brought to the polyfill.

**Comment by ebidel** [comment]
Here's the repo: https://github.com/webcomponents/shadycss
