### ISSUE TITLE
webcomponents-lite failing on Safari 9.1.3

### ISSUE THREAD

**Issue by slundberg** [webcomponents/webcomponentsjs#616]
When I try and extend HTMLElement using webcomponents-lite I run into an assertion

`TypeError: Super expression must either be null or a function, not object`

In the non-lite version HTMLElement is a function. Any reason for this difference? And is the assertion added by webpack/babel justified? If so then webcomponents-lite is broken on Safari.

**Comment by ebidel** [comment]
Please post a jsbin that repros the issue.

**Comment by slundberg** [comment]
I moved on to just use custom-elements by itself. It may have been a version specific issue with Babel/webpack because on JSbin it does not give the same error.
