### ISSUE TITLE
V1: Remove webcomponents.js or webcomponents-lite.js and update README

### ISSUE THREAD

**Issue by kito99** [webcomponents/webcomponentsjs#619]
The current version of webcomponents.js is out-of-date, and from what I can tell webcomponents-lite.js actually includes Shadow DOM v1 support, so perhaps one of these two files should be removed and the README should be updated.

**Comment by ebidel** [comment]
We're still working on refactoring polyfills and updating instructions. Right now, https://github.com/webcomponents/webcomponentsjs/blob/v1/webcomponents-lite.js is the one you should be using, but we're not providing a built version yet. Not sure what will happen to webcomponents.js, but we're also thinking about moving to a model where you load individual polyfills where they are needed.

**Comment by warnerandy** [comment]
it would be nice to have a feature by feature loading method. I've gotten in trouble a few times (thanks safario) with the old shadow dom polyfill breaking even when i wasnt using it in any elements. Luckily wc-lite excluded that code :)

**Comment by notwaldorf** [comment]
This is being tracked in https://github.com/webcomponents/webcomponentsjs/issues/657
