### ISSUE TITLE
WebComponents.JS blocks page render for ~15s on Android

### ISSUE THREAD

**Issue by mattisfrommars** [webcomponents/webcomponentsjs#62]
Hi, unfortunately I don't have many devices to get more data- and I'm unsure how to help troubleshoot this issue. Any help on fixing or diagnosing the below greatly appreciated!

I'm creating an app for a specific device running android 4.4, and when including webcomponents.js page rendering speed drops _dramatically_ here's a screenshot of an example timeline view

![image](https://cloud.githubusercontent.com/assets/1679485/5110084/a427ecc0-700d-11e4-82b6-4d3be3ec5b24.png)

As you can see, purely evaluating the javascript triggers a recalculate style, layout and 6  GC events. What is happening here? Is the bug hardware or software related?

If there's any further information I could provide that would help diagnose the issue, or additional steps I could take- please advise me on the best course.

Thanks!

**Comment by gabrielmancini** [comment]
@mattisfrommars i had same issue here.... what you do?

**Comment by jakemac53** [comment]
The best solution for large lists is to use something like the core-list-dart element from the core_elements package. This now supports horizontal/grid layouts as well so that should help.
