### ISSUE TITLE
V1: CustomElements folder doesn't exist

### ISSUE THREAD

**Issue by ccapndave** [webcomponents/webcomponentsjs#621]
When trying to `gulp build` in the latest branch of V1 gulp fails with:

```
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src/CustomElements/build.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at readJSON (/Users/dave/Projects/forks/webcomponentsjs/gulpfile.js:70:17)
    at readManifest (/Users/dave/Projects/forks/webcomponentsjs/gulpfile.js:101:15)
    at /Users/dave/Projects/forks/webcomponentsjs/gulpfile.js:107:32
    at Array.forEach (native)
    at readManifest (/Users/dave/Projects/forks/webcomponentsjs/gulpfile.js:103:9)
    at /Users/dave/Projects/forks/webcomponentsjs/gulpfile.js:40:16
    at defineBuildTask (/Users/dave/Projects/forks/webcomponentsjs/gulpfile.js:66:5)
```

This is because `src/WebComponents/build.json` and `src/WebComponents/build-lite.json` both refer to `../CustomElements/build.json` which doesn't exist.

**Comment by a-tarasyuk** [comment]
`CustomElements` has moved to https://github.com/webcomponents/custom-elements

**Comment by tomalec** [comment]
but it's still required by build and `webcomponents.js` https://github.com/webcomponents/webcomponentsjs/blob/v1/webcomponents.js#L82

**Comment by tomalec** [comment]
fix is available at: https://github.com/webcomponents/webcomponentsjs/pull/622

**Comment by daKmoR** [comment]
get the same error...
does anyone has a build v1 version?

**Comment by daKmoR** [comment]
ok, some failed search and a few hours of hacking around later...
I manually created a build. If anyone is interested here it is... 
https://gist.github.com/daKmoR/6251ae09e7da25d274603346c906b598

**Comment by daKmoR** [comment]
nice :) looking forward to it :) if there is any testing to be done or anything I can help - just let me know :)

**Comment by notwaldorf** [comment]
Going to prematurely closing since I'm in a triaging spree. This will be fixed by https://github.com/webcomponents/webcomponentsjs/pull/661
