### ISSUE TITLE
V1: instanceof operator isn't working for non-patched nodes.

### ISSUE THREAD

**Issue by blasten** [webcomponents/webcomponentsjs#623]
Using the v1, the following assertion fails:

``` js
assert.isTrue(document.documentElement instenceof HTMLElement);
```

/cc @justinfagnani

**Comment by blasten** [comment]
I also found that `HTMLElement.ELEMENT_NODE` is `undefined`.

**Comment by justinfagnani** [comment]
The first issue is more or less unsolvable. Any element that has HTMLElement as its direct prototype can't be patched to make `instanceof` work.

The second issue is fixable and important. We need to copy statics down.

**Comment by shannonmoeller** [comment]
In case it's useful to others, my team came up with a workaround. It's far from perfect, but it worked well enough for our needs:

```js
const div = document.createElement('div');

console.log((/^HTML\w*Element/).test(div.constructor.name));
```

Further, all of our custom element use a specific prefix, so we could extend the regex to:

```js
/^(HTML|Foo)\w*Element/
```

**Comment by justinfagnani** [comment]
For your custom elements, `instanceof` should work fine. The issue here is that the polyfilled `HTMLElement`'s prototype isn't on the prototype chain of the built-in elements, but your custom element's prototype is fine.

Another option, which should be fine in basically all cases, is `el.nodeType === Node.ELEMENT_NODE`.

**Comment by blasten** [comment]
thanks for the reply @justinfagnani

**Comment by notwaldorf** [comment]
This sounds like a CustomElements polyfill issue so I'm moving it there, sorrynotsorry.

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/custom-elements#48
