### ISSUE TITLE
iOS 10 compatibility

### ISSUE THREAD

**Issue by lucasdupin** [webcomponents/webcomponentsjs#628]
Hi all,
I'm using webcomponents for a project and noticed that an error is being thrown on the latest iOS version: 10.0.1

![0](https://cloud.githubusercontent.com/assets/88702/18841302/1a9dafe8-83c6-11e6-8417-67c2d65f817e.png)

And digging into the source, I could figure out that `scope.wrappers.Window` is null:

![unnamed](https://cloud.githubusercontent.com/assets/88702/18841356/47aa379a-83c6-11e6-89d7-8d7aa6c318d1.png)

And the reason why is because it can't be registered:

![unnamed-1](https://cloud.githubusercontent.com/assets/88702/18841365/54281c80-83c6-11e6-9288-6559255a5c9a.png)

Whenever `getDrescriptor` gets called with the `window` object and property it doesn't support, it returns `null` instead of a dummy descriptor. 

The reason why it's happening is because `Object.getOwnPropertyDescriptor` is not throwing an exception, but only returning `undefined`.

You can go ahead and try this on the *iOS 10.0.1 Safari* console:

```javascript
Object.getOwnPropertyDescriptor(window, 'location____')
```

My current fix involves checking if a return value is valid before returning:

Line 212:
```javascript

    function getDescriptor(source, name) {
      try {
        var desc = Object.getOwnPropertyDescriptor(source, name);
        if (desc) return desc;
      } catch (ex) {
        // Just return a dummy descriptor
      }
      return dummyDescriptor;
    }

```

Let me know what you guys think. I can create a pull request with this change.

**Comment by ArturKlajnerok** [comment]
It's already being discussed in : https://github.com/webcomponents/webcomponentsjs/issues/617, https://github.com/webcomponents/webcomponentsjs/pull/618
