### ISSUE TITLE
Polyfill affecting NodeList liveness in Edge

### ISSUE THREAD

**Issue by peterjosling** [webcomponents/webcomponentsjs#630]
I've got some code using an IE-specific hack to set innerHTML on an SVG element. The hack works fine in Chrome (always), but breaks in Edge when the full webcomponents.js is included. (Code words fine with -lite). JSbin [here](http://jsbin.com/qemomaqihi/1/edit?html,js,console). In Chrome/Safari, the loop body executes once. In Edge, it loops infinitely.

As far as I'm aware, the `children` NodeList should be live, as it's active in the DOM - and that's how it behaves in all browsers including Edge when webcomponents.js is not included.

**Comment by CITguy** [comment]
`childNodes` is a _read-only_ property. Its length doesn't change, so you never reach your exit condition for your `while` loop. 

Try iterating over `div.children` instead.

```javascript
var children = div.children;
for (var i = 0; i < children.length; i++) {
    svg.appendChild(children[i]);
}
```

**Comment by peterjosling** [comment]
The code works fine in all of Chrome, Safari and Edge without webcomponents.js installed — is it not specified behaviour?

The actual code in question isn't owned by my team so we weren't able to modify it. We instead decided to remove webcomponents.js entirely as we didn't need it any longer.

**Comment by e111077** [comment]
@notwaldorf (I'm not a part of the org so I can't tag) this is a `source:hooli` bug.

**Comment by TimvdLippe** [comment]
This is an issue in ShadyDOM still: http://jsbin.com/muyivurufe/1/edit?html,js,console

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadydom#259

**Comment by morewry** [comment]
Is https://github.com/webcomponents/shadydom/pull/226 related?
