### ISSUE TITLE
webcomponents-lite.js does not work in IE while using ES6 (Babel)

### ISSUE THREAD

**Issue by 4leem** [webcomponents/webcomponentsjs#631]
webcomponents-lite.js does not work in IE (v11 and v10) while **extending the HTMLElement in ES6 format**, transpiled through Babel. 

Sample Code:

```
    class SuperBtn extends HTMLElement {
        constructor() {
            super();
        }
        createdCallback() {
            this.innerHTML = "Invoke Ultron!";
            this.addEventListener('click', () => alert(this.textContent + ' has been clicked'));
        }
    }

    var MySuperBtn = document.registerElement("super-button", SuperBtn);
```

The _inherits method (after babel) throws an Error - 

> "Super expression must either be null or a function, not object"

The above code works fine when we use webcomponents.js but not webcomponents-lite.js. The HTMLElement is returned as object while using webcomponents-lite.js, and it returns function when we use webcomponents.js

**Comment by priley86** [comment]
For anyone running into this issue, it can be temporarily resolved with the following shim...

https://github.com/patternfly-webcomponents/patternfly-webcomponents/blob/master/src/customElementShim.js

Reference [here](https://github.com/babel/babel/issues/1548#issuecomment-102472288)

**Comment by TimvdLippe** [comment]
We are now testing the `babel` transpilation in `custom-elements` [here](https://github.com/webcomponents/custom-elements/blob/master/tests/js/babel.js) so I assume this has been resolved.
