### ISSUE TITLE
<template> polyfill not working when template root element is <tr>

### ISSUE THREAD

**Issue by herrernst** [webcomponents/webcomponentsjs#632]
Hi,
I was looking for just a polyfill for the HTML5 `<template>` tag. I've tried to use yours but it doesn't give the expected result when the `<template>` element contains a `<tr>`. There is an example adopted from [MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/template) here: 
https://codepen.io/superlupo/pen/qapgZY
This works in Chrome and Firefox, but not in IE (11). I suspect this is because the HTML parser throws away the `<tr>` and `<td>` when they are not inside of a `<table>`; so the template then is basically empty. I reproduced this also with another polyfill. Can you think of any way to work around that? If this is a general restriction on all `<template>` polyfills, then maybe this should be noted.
Thanks

**Comment by motss** [comment]
@herrernst  Facing the same issue and totes no idea why everything is stripped off in IE11. 
My way to work around IE11: https://jsbin.com/huqezujotu/edit?html,output

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/template#3
