### ISSUE TITLE
Issue with webcomponents createdCallback call order

### ISSUE THREAD

**Issue by medialwerk** [webcomponents/webcomponentsjs#634]
Hello,

If I add inner HTML at the createdCallback with other nested webcomponents, the polyfill works in a different way as the nativ implementation does. 
## Environment

**Nativ implementation means here:**
- Firefox 49.0.1  (dom.webcomponents.enabled == true)
- Chrome 53.0.2785.143 (64-bit)

**webcomponents.js version:**
- 0.7.22
## A simple example for clarification

**parent_web_component.coffee**

``` coffeescript
class ParentWebComponent extends HTMLElement

  createdCallback: ->
    console.log 'createdCallback of parent web component'
    @innerHTML = require('./parent_web_component.jade')()
    console.log 'inner html of parent web component set'
```

**parent_web_component.jade**

``` jade
.parent-web-component--container
  child-web-component
```

**child_web_component.coffee**

``` coffeescript
class ChildWebComponent extends HTMLElement

  createdCallback: ->
    console.log 'createdCallback of child web component'
```
### Native implementation:
1. createdCallback of parent web component
2. createdCallback of child web component
3. inner html of parent web component set
### Webcomponents.js:
1. createdCallback of parent web component
2. inner html of parent web component set
3. createdCallback of child web component

It's a bad thing if i rely on the api of the child web-component at the created callback.

Thanks!

**Comment by TimvdLippe** [comment]
Closing per above comment.
