### ISSUE TITLE
In Chromium, slotchange doesn't fire when replacing a one TextNode with another TextNode (by setting innerHTML on the host)

### ISSUE THREAD

**Issue by micahscopes** [webcomponents/webcomponentsjs#641]
It'd be nice if there was a polyfill for this for current and older versions of Chrome/Chromium.

See here for discussion: https://github.com/w3c/webcomponents/issues/592
And the example: https://jsbin.com/xivunad/edit?html,js,console,output

**Comment by notwaldorf** [comment]
This sounds like it's an older-versions-of-Chrome `v1` bug -- since Chrome is evergreen and updates fairly quickly, I don't think this is worth it.

/cc @azakus for objections to closing this

**Comment by micahscopes** [comment]
Sounds good to me, looks like the bug has been fixed.
