### ISSUE TITLE
Support for v1 spec -- constructor() problem?

### ISSUE THREAD

**Issue by johnthad** [webcomponents/webcomponentsjs#645]
I've created a small custom elements template that can be seen at https://github.com/johnthad/wc-template or https://jsfiddle.net/JThaddeus/Lm16jnyu/

When run in Chrome 54 it naturally works--I see the `WC-TEMPLATE` in the console. However, though I've added the webcomponents.min.js polyfill, the web component fails in other browsers. When running the JSFiddle, I see in the console `TypeError: window.customElements is undefined` in Firefox 49.0.2 and `TypeError: undefined is not an object (evaluating 'window.customElements.define')` in Safari 10.0.1. 

Is the web components v1 spec supported yet? I see in the `README.md` that "Custom element's constructor property is unreliable." Is that the problem am seeing? When loading the page locally with Edge (running Windows 10 under Parallels), I get a JavaScript error at `class extends HTMLElement`, so maybe is an issue with ES6?

**Comment by pixelhandler** [comment]
@johnthad I had the same issue; this is my project: https://customelements.io/pixelhandler/alert-box-web-components/ Here is a branch with the polyfill, https://github.com/pixelhandler/alert-box-web-components/tree/polyfill

**Comment by johnthad** [comment]
@pixelhandler Yes. Chrome works, but both Firefox and Safari complain about script.js at line 14: When I load this in Firefox, I see 

    TypeError: link.import is null
       let templates = link.import.querySelectorAll('template');

in the console. In Safari the error is `TypeError: undefined is not an object (evaluating 'link.import.querySelectorAll')`.

So what's your hunch? Is the v1 spec not yet supported by the polyfill? Or is the problem something else, like HTML Imports?

**Comment by pixelhandler** [comment]
@johnthad Yeah I think there is an issue, well more then one. I experimented with v1 polyfills and got closer but still had issues with HTML Import. I tried these bower deps…

```js
  "devDependencies": {
     "shadydom": "webcomponents/shadydom",
     "shadycss": "webcomponents/shadycss",
     "custom-elements": "^1.0.3",
     "webcomponentsjs": "^0.7.22"
  }
```

**Comment by johnthad** [comment]
Ah! I missed this the first time I went looking: [#540 - Update polyfill to Custom Elements v1](https://github.com/webcomponents/webcomponentsjs/issues/540). We must wait...
