### ISSUE TITLE
Current npm release 0.7.22 has not the latest dom.js included

### ISSUE THREAD

**Issue by medialwerk** [webcomponents/webcomponentsjs#646]
Hi,

i received a lot of "Uncaught TypeError: Object #<Performance> has no method \'now\'" errors on my production environment. After that i found this issue "https://github.com/webcomponents/webcomponentsjs/issues/539" and checkt the "node_modules/webcomponents.js/webcomponents-lite.js" file. The polyfill within the npm module differs from the one in the current dom.js file. Could it be, that the bundle is outdated?

Current "dom.js":
```
  if (!(window.performance && window.performance.now)) {
```

Current "node_modules/webcomponents.js/webcomponents-lite.js":

```
  if (!window.performance) {
```

Thanks! :-)

**Comment by ebidel** [comment]
Yea, looks like the last release was April 15 and that patch landed in June

@azakus, are you able to do a release?

**Comment by azakus** [comment]
Released v0.7.23

**Comment by ebidel** [comment]
Thanks!

**Comment by medialwerk** [comment]
Thanks too! :-)
