### ISSUE TITLE
Shadow Root gets replaced instead of appended, when empty Document Fragment is added while Event is being dispatched

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#648]
### Description
When I add Shadow DOM, trigger event, append empty `DocumentFragment` to the `.shadowRoot`, then append something again asynchronously - Shadow DOM is replaced by the thing I tried to append.

It seems to me related to timing problem.

I have marked in comments lines which seems to cause the race condition.

#### Live Demo
old: http://jsbin.com/fewuju/4/edit?html,console,output
new V0: http://jsbin.com/hacodob/2/edit?html,console,output
V1 works: http://jsbin.com/butoxup/3/edit?html,console,output
https://tomalec.github.io/webcomponentsjs-issues-648/

#### Steps to Reproduce

1. Create `div` shadow host `<div id="shadow-host">Am I green?</div>`
2. Append Shadow DOM to shadow host:
   ```js
   // V0
   var shadowRoot = shadowHost.createShadowRoot();
   shadowRoot.innerHTML = '<div style="background: green;"><content></content></div>';
   ```
3. Dispatch event on shadow host:
   ```js
   shadowHost.dispatchEvent(new CustomEvent("stamping"));
   ```
4. Append empty `DocumentFragment` into shadow root:
   ```js
   var emptyDocFragment = document.createDocumentFragment();
   shadowHost.shadowRoot.appendChild(emptyDocFragment);
   ```
5. Asynchronously append something into shadow root:
   ```js
   setTimeout(function(){
        shadowHost.shadowRoot.appendChild(document.createTextNode('and followed by shadow content?'));
   });
   ```

#### Expected Results
Shadow DOM with distributed content should be rendered:
```
A I green? // on green background
and followed by shadow content?
```

#### Actual Results
Only the last part is rendered:
```
and followed by shadow content?
```

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8
- [x] IE 11

### Versions
- webcomponents: v0.7.23

### Notes
It makes it impossible to lazy load `dom-bind` to anything with Shadow DOM https://github.com/Polymer/polymer/issues/4144

**Comment by johnthad** [comment]
FWIW, the shadow-host example works for me in Chrome 54 and Firefox 49, but not in Safari 10.

**Comment by tomalec** [comment]
I think it's some kind of a chase, so it may or may not appear. 

On my Firefox 49.0.1 it does not work

**Comment by warpech** [comment]
For me this works in Chrome 54/Mac. 

Firefox 49.0.2 and Safari 10.0.1 both fail to render anything. There are some security errors visible in the browser console. Is this the same what you see, @tomalec?

![screen shot 2016-11-14 at 17 02 10](https://cloud.githubusercontent.com/assets/566463/20271774/2463cbd8-aa8c-11e6-8529-c6aee80404c0.png)
<img width="1440" alt="screen shot 2016-11-14 at 17 00 46" src="https://cloud.githubusercontent.com/assets/566463/20271778/26b96a96-aa8c-11e6-80be-84f7cb039350.png">

**Comment by tomalec** [comment]
I have removed MutationObserver dependency from this bug, and updated the OP

**Comment by tomalec** [comment]
> There are some security errors visible in the browser console. Is this the same what you see, @tomalec?

I think it's something related to jsbin itself.
At https://tomalec.github.io/webcomponentsjs-issues-648/ you can see bare example, without such error.

**Comment by tomalec** [comment]
The only workaround I have found is to add something to the document fragment, for example zero width space:
```js
emptyDocFragment.appendChild(document.createTextNode("\u200B"));
```

**Comment by tomalec** [comment]
I have discovered that the "erased" effect is in fact replacing entire shadow root with the element I try to append at the end (updated OP and title).

**Comment by tomalec** [comment]
@notwaldorf It's also an issue in V1 http://jsbin.com/butoxup/1/edit?html,console,output

**Comment by tomalec** [comment]
Sorry, my bad (jsbin failed to save) it actually works fine in V1 http://jsbin.com/butoxup/3/edit?html,console,output

**Comment by TimvdLippe** [comment]
Thanks for the investigation @tomalec and sorry for not responding sooner. Given that this bug does not appear with v1, I am closing this issue.
