### ISSUE TITLE
[htmlimports-lite] issues with imported html that loads a script

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/webcomponentsjs#650]
I'm importing an element which depends on `neon-animation` to load a web animations script.
If the import is done in `components/[my_element]/demo/index.html`, the htmlimport polyfill has issues in resolving the path for scripts, while this is not the case if i do the import in `components/[my_element]/index.html`
e.g. see the logs in Safari Technology Preview for `index.html` and `demo/index.html` after you install the deps and serve the content of this repo https://github.com/valdrinkoshi/htmlimports-lite-test

@sorvell FYI

**Comment by cdata** [comment]
/cc @justinfagnani 

This blocking `app-storage` elements like `firebase/polymerfire` and `polymerelements/app-pouchdb`.

**Comment by e111077** [comment]
Testing things with scripts in Polymer 2 and hunting down script imports is killing me

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/html-imports#10
