### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by Roba1993** [webcomponents/webcomponentsjs#651]
Hi all,

I'm actually developing a webcomponent-loader for webpack.

The goal is to allow loading of a .html webcomponent file with javascript (`Import 'my-webcomponent.html';`). The benefit would be, that the extra loading call for the webcomponent isn't needed and everything is compressed with webpack.

I' actually able to load the .html file with my loader and minimize the content etc.

The tricky part is now, to preload this content into an link tag as document and execute the included javascript of the webcomponent. Provides the webcomponentjs polyfill any functionality which creates the link element and loads the content into it?

Thanks,
Robert

**Comment by TimvdLippe** [comment]
We have no plans to do this for webcomponents, but it might be possible to just use the `polymer-webpack-loader` with any custom element definition. https://github.com/webpack-contrib/polymer-webpack-loader
