### ISSUE TITLE
Running v0 and v1 side by side

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#653]
Are there any plans to support both APIs side by side as Chrome does?

It would be really great to have such "hybrid" step available, to make migration from v0 to v1 less painful for vanilla web components.

**Comment by tomalec** [comment]
Seems that @WebReflection did the great job to support V1 on top of V0. 
https://www.webreflection.co.uk/blog/2016/08/21/custom-elements-v1#a-graceful-migration
Now, it's the time to test it :)

**Comment by tomalec** [comment]
Does anybody know how to achieve such hybrid step for Shadow DOM?

**Comment by TimvdLippe** [comment]
We offer no hybrid support. I think you should be fine with loading both, although that is detrimental for performance.

**Comment by WebReflection** [comment]
> Does anybody know how to achieve such hybrid step for Shadow DOM?

@tomalec it's limited, but it works down to IE9: https://github.com/WebReflection/attachshadow#attachshadow
