### ISSUE TITLE
HTML Imports polyfill incompatible with Safari's native v1 custom elements

### ISSUE THREAD

**Issue by sorvell** [webcomponents/webcomponentsjs#656]
The polyfill mirrors Chrome's native implementation by placing imported dom into disconnected documents. However, v1 custom elements do not customize in these documents. Chrome makes a special exception for HTML Imports and customizes custom elements in them. Therefore, the current approach the polyfill takes results ing custom elements not customizing in imported documents.

To fix this, the polyfill could become less correct by avoiding the use of documents. Instead it could inject hidden dom in the main document. This is the same approach that `polymer build` takes when bundling HTML Imports.

**Comment by sorvell** [comment]
Experimental branch to address this issue: https://github.com/webcomponents/webcomponentsjs/tree/htmlimports-lite.

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/html-imports#9
