### ISSUE TITLE
Standardize package name

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponentsjs#66]
Nowadays, this polyfill is hosted both on Bower and npm with different names.

1. `bower install webcomponentsjs`
2. `npm install webcomponents.js`

I'm personally in favor of `webcomponents.js` 'cause that separating dot makes it easier to read. But I know that the latest Polymer release introduced the `webcomponentsjs` dependency to hundreds of Bower users. So maybe we should just rename the npm package since it haven't been used by many people yet.

**Comment by garlicnation** [comment]
This has been fixed for some time.

**Comment by zenorocha** [comment]
@garlicnation so why does `bower.json` & `package.json` name differ?

https://github.com/webcomponents/webcomponentsjs/blob/master/bower.json#L2
https://github.com/webcomponents/webcomponentsjs/blob/master/package.json#L2

**Comment by Gheoan** [comment]
Package name still differs between bower and npm. I want to add a shortcut for this package on [`jspm`'s registry](https://github.com/jspm/registry) and I am not sure which name to pick.

**Comment by justinfagnani** [comment]
99% of our users are probably using the Bower name, if that matters.

This would be more important if these were normal dependencies, and not polyfills. As polyfills they should only be imported a the top-level of a package hierarchy, and never be a transitive dependency, so it's not quite as hard to change the name if a package switches from one package manager to another.
