### ISSUE TITLE
Alert user if browser doesn't support polyfill

### ISSUE THREAD

**Issue by pensierinmusica** [webcomponents/webcomponentsjs#662]
Hi,

I think there should be a visible alert for the user when the browser does not support the webcomponentsjs polyfill.

Something that says "Your browser is outdated. Please update your browser to properly view this website" (through a pop-up, a modal, or some banner).

Or at least have some callback that the developer can use to alert the user.

Any chance this could be implemented?

Thanks!

**Comment by notwaldorf** [comment]
I think an alert/banner is pretty visually intrusive, and very confusing to the user --what's a polyfill? Why is this site using a polyfill? Why do I, as a user of this website, care about what this website is using? I just want to buy a cat.

This also sounds to me like it's not the polyfill's job, but the website's decision -- you as the dev are responsible for choosing the polyfills, and knowing where they're applicable.

Closing, as this is not something the polyfill should do, but cc'ing @azakus for a second opinion

**Comment by pensierinmusica** [comment]
Hi @notwaldorf I personally completely disagree. Having the polyfill fail and not giving any signal leads to the worst possible experience for the user. Since the website will be broken and the user doesn't know what to do.

Even if you don't want to show any alert, which I agree should be a developer choice, still the polyfill should offer a custom event or a callback that the developer can use when the polyfill fails to load properly.

Something like:

```js
webComponentsJs.on('fail', function () {
  // Let the developer decide what to do
});

// or

webComponentsJsFail = function () {
  // Let the developer decide what to do
});
```

Can we please re-open this thread? Thanks!

**Comment by Garbee** [comment]
I think pivoting this to providing a generic callback on failure is far more reasonable than a built in alert to the user. It also allows developers to collect hits on failures via analytics to see if maybe they need to rethink what they're doing.

**Comment by pensierinmusica** [comment]
Yep, completely agree. Please @notwaldorf and @azakus can we re-open this issue? Thx!

**Comment by Garbee** [comment]
Give them some time please. It is the weekend and they have a lot of different projects to handle. :wink:
