### ISSUE TITLE
Unable to Gulp v1

### ISSUE THREAD

**Issue by CodeBush91** [webcomponents/webcomponentsjs#666]
Doesn't look like this has been raised yet, It appears that we are unable to run gulp on the v1 branch, this appears to be related to some changes made towards the end of last year during a cleanup. During this commit there were a lots of files/folders being removed but I don't think the updates in the gulpfile.js was made completely, build.json is now build-lite.json and HTMLImports is now html-imports. Locally I have had  these changes along with removing audit to get it to work and changing the hard-coded structure paths, if I manage to solve that then I will create a pull request, however in the meantime if anyone else wants to fix it they can.

**Comment by notwaldorf** [comment]
Hi! Please follow the branch `gulp-all-the-things`, since that's actually fixing gulp. Going to close this issue, since it's being tracked by https://github.com/webcomponents/webcomponentsjs/issues/657
