### ISSUE TITLE
Content security policy rule of Shopify CMS blocks script load in the FireFox

### ISSUE THREAD

**Issue by fuerte656** [webcomponents/webcomponentsjs#670]
Hello there,

I am developing a plugin for Shopify CMS. This plugin uses webcomponents.js to load Polymer scripts via:
`script.src = "data:text/javascript;charset=utf-8," + encodeURIComponent(scriptContent);` [line 307](https://github.com/webcomponents/webcomponentsjs/blob/0d285e7df994f99341e45bf2b603a1fdb485baae/src/HTMLImports/parser.js#L307)

In FireFox I get the following errors:

    Content Security Policy: The page’s settings blocked the loading of a resource at data:text/javascript;charset=utf-8,/**script code*/(“script-src https://domainurl https://* 'unsafe-inline' 'unsafe-eval'”)

Here is an original Content security policy header (I can't change this header on the server, because Shopify is a hosted platform and I don't have any control on it):

```
    Content-Security-Policy:
    default-src 'self' https://*;
    child-src 'self' https://* blob: data:; 
    connect-src 'self' https://* wss://*;
    font-src 'self' https://* blob: data:;
    img-src 'self' https://* blob: data:; 
    media-src'self' https://* blob: data:;
    object-src 'self' https://* blob: data:;
    script-src 'self' https://* 'unsafe-inline' 'unsafe-eval';
    style-src 'self' https://* 'unsafe-inline';
```
The  ` script-src 'self' https://* 'unsafe-inline' 'unsafe-eval';`  rule prevents loading js through script tags with DataURI.

I have found that I can load js in a script tag without a DataURI. In particular, this comment says that DataURI is not necessary:  

` // NOTE: execute scripts by injecting them and watching for the load/error
  // event. Inline scripts are handled via dataURL's because browsers tend to
  // provide correct parsing errors in this case. If this has any compatibility
  // issues, we can switch to injecting the inline script with textContent.
  parseScript: function(scriptElt) {....` [line 226](https://github.com/webcomponents/webcomponentsjs/blob/0d285e7df994f99341e45bf2b603a1fdb485baae/src/HTMLImports/parser.js#L226)

At this moment, I have modified your script to use textContent instead of the DataURI, but I am worried that I have to use my own branch of webcomponents.js. I wonder whether you consider making this behavior as a standard feature? Or at least make it configurable? 

[my question on stackoverflow](http://stackoverflow.com/questions/42017052/content-security-policy-webcomponent-can-i-override-http-header-by-meta-tag)

Best regards
Alex

**Comment by sz332** [comment]
although not suitable for this case, but if you have control over nginx, then add the following:

instead of 

script-src 'self' https://* 'unsafe-inline' 'unsafe-eval';

use

script-src 'self' https://* 'unsafe-inline' 'unsafe-eval' data:;

**Comment by fuerte656** [comment]
No, I haven't any control of server side. We produce cms plugin and give this plugin to our customers. I have created a patch that changes the code of webcomponentsjs, and I applying this patch before a build process.

**Comment by sz332** [comment]
Yes, basically the question is whether this function could be changed, or made configurable in webcomponents so you don't have to patch it.

**Comment by TimvdLippe** [comment]
The HTML Imports polyfill no longer exists in version 1 of this polyfill. Therefore, this issue should be resolved. Note that we are tracking the other CSP compatibility issues in #188.
