### ISSUE TITLE
0.7.24

### ISSUE THREAD

**Issue by JulienNexonia** [webcomponents/webcomponentsjs#672]
Hi guys,
I am unable to get the last version of webcomponentsjs.

`bower webcomponentsjs#^0.7.24              ENORESTARGET No version found that was able to satisfy ^0.7.24
Additional error details:
Available versions: 0.5.0, 0.5.1, 0.5.1-1, 0.5.2, 0.5.3, 0.5.3-rc, 0.5.3-rc2, 0.5.4, 0.5.5, 0.5.5-rc1, 0.6.0, 0.4.2, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.10, 0.7.11, 0.7.12, 0.7.13, 0.7.14, 0.7.15, 0.7.16, 0.7.17, 0.7.18, 0.7.19, 0.7.2, 0.7.20, 0.7.21, 0.7.22, 0.7.23, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9
`

**Comment by elion** [comment]
+1
npm publish

**Comment by SerkanSipahi** [comment]
+1
please publish !

**Comment by azakus** [comment]
Sorry about that, published now.
