### ISSUE TITLE
JS error with hashed webcomponents-lite.js file names

### ISSUE THREAD

**Issue by marybeshaw** [webcomponents/webcomponentsjs#673]
We ran into a JS error using Polymer 2 with webcomponentsjs #v1.  When we add a hash the webcomponents-lite.js file name, the querySelector statement can't find the script tag.

HTML:
`<script src="https://edge.fscdn.org/assets/components/webcomponentsjs/webcomponents-lite-388f0ed9715fa5c200615ae26ba24747_raw.js"></script>
`

Problem JS:
```
var file = 'webcomponents-lite.js';
var script = document.querySelector('script[src*="' + file + '"]');
...
var src = script.getAttribute('src'); // JS ERROR! script is undefined
```

One suggested fix would be to remove the ".js" from file.  This works with files that have extensions in the name:

`document.querySelector('script[src*="webcomponents-lite"]')`

I am happy to make a PR with this fix if you'd like.

**Comment by notwaldorf** [comment]
There is a very sizeable [PR](https://github.com/webcomponents/webcomponentsjs/pull/661) currently in flight for the v1 polyfills, so i wouldn't do anything until that lands (and you can check that you can still repro the problem)

**Comment by marybeshaw** [comment]
Oh, how interesting!  I took a look, and it will have the same problem with webcomponents-loader.js so I'll keep an eye on it. Thanks!

**Comment by gechols** [comment]
Any update on this? It seems like this is still happening.

**Comment by TimvdLippe** [comment]
You can now inline the polyfill to get around this: https://github.com/webcomponents/webcomponentsjs#inlining
