### ISSUE TITLE
instanceof Function fails when running in multiple frames

### ISSUE THREAD

**Issue by JamesXNelson** [webcomponents/webcomponentsjs#675]
Heya, my apologies if this is already opened; I searched but found nothing...

So, I'm building my custom elements inside of a window that runs in an iframe for isolation from the global window, and when using chrome / native implementation of custom elements V1, all is well, everything works fine.

In the polyfill, there are a bunch of `instanceof Function` checks which fail, because my functions were defined in a different window scope.  While I understand this is the "more standard" way of checking types, instanceof is generally frowned upon for this very reason, especially for native types that can get by using `typeof`.  

Unless there is a real, known issue with defining custom elements that have functions created from other frames, please consider using typeof instead of instanceof.

PS -> I am already building my own copy of the library, and am able to export V1 to ES5 syntax, and create my component "classes" by using Reflect.construct to handle the issues around extending HTMLElement without using `class`.

PPS -> I am doing this because I am assembling these components via GWT, and binding compiled java methods onto the components, and I really, really don't want to do something ugly like:

    function rebase(f) {
      return f.apply(this, arguments);
    }

just to pass an instanceof check.

**Comment by JamesXNelson** [comment]
Hrrrgh.  I notice the problem is actually in the custom-elements module.  Not sure if I should move this there, or just leave it here.

My apologies for not digging deeper before filing...

**Comment by bicknellr** [comment]
Hi @JamesXNelson, this was brought up in webcomponents/custom-elements#64 so I'm going to close this one. Feel free to drop any suggestions there.
