### ISSUE TITLE
I have not ability to get true ownerDocument for inner webcomponent

### ISSUE THREAD

**Issue by gorshkov-leonid** [webcomponents/webcomponentsjs#676]
I used GoogleMaps webcomponent inside GeographicalView webcomponent. 
In GeographicalView declared template `<template>...geoview content...<template>`.
In GoogleMaps declared template `<template>...google maps content...<template>`

When I try to get template in GoogleMaps via `document._currentScript.ownerDocument.querySelector('template').
 In chrome I got template of GoogleMaps. But In IE result different: was got template of GeographicalView.

![chrome](https://cloud.githubusercontent.com/assets/2270831/22821282/d3e75858-ef93-11e6-9e5c-8a8fb7472193.png)
![ie](https://cloud.githubusercontent.com/assets/2270831/22821283/d401b784-ef93-11e6-9514-fd0541a356fd.png)

Sample: https://github.com/gorshkov-leonid/webcomponenets_get_inner_document
Used version of webcomponenets JS: commit b93c3571eac3026902fffc6598d882a6741a58df from v1 branch with fix of loader for es5.

I know that work in progress, and priority of this issue is lower then development of v1, but In my mind this functionality is important. Could you include this issue to v1 development scope?

**Comment by valdrinkoshi** [comment]
`webcomponentsjs#v1` is using `html-imports` polyfill, which appends the imports in the main document to leverage the native implementation of Custom Elements. You can use the method `HTMLImports.importForElement()`, please see the [README.md](https://github.com/webcomponents/html-imports#linkimport-is-not-a-document) for more info.

**Comment by gorshkov-leonid** [comment]
@valdrinkoshi thank you. This code will be work In chrome that is not used polyfill same as IE?

**Comment by valdrinkoshi** [comment]
the `html-imports` works both with native HTMLImports or polyfilled case. `HTMLImports.importForElement(element)` will return you the import document of that element (aka the `link.import` document containing that element) 👌

**Comment by gorshkov-leonid** [comment]
I am not sure, I see error in console `HTMLImports.importForElement is not a function`
I used loader and was loaded loaded webcomponents-none.js only.

**Comment by valdrinkoshi** [comment]
oh ok, that's because the loader won't load the `html-imports` polyfill in chrome since there is native supports (less stuff to load on your page!)
It should probably stub also the `importForElement` method.
For now, I'd suggest to have something like this:
```js
const ownerDoc = HTMLImports.importForElement ? 
   HTMLImports.importForElement(el) : el.ownerDocument;

**Comment by gorshkov-leonid** [comment]
:ok_hand: it is reasonable workaround, thanks again

**Comment by gorshkov-leonid** [comment]
hmmm, 
Early in IE and FF I saw: 
```
Inner component: id of selected template outer-template 
Outer component: id of selected template outer-template
```
Appeared result in IE and FF after WA:
```
Inner component: id of selected template inner-template
Outer component: id of selected template inner-template
````
Expected result as in chrome:
```
Inner component: id of selected template inner-template 
Outer component: id of selected template outer-template
```

**Comment by valdrinkoshi** [comment]
Uhm, could you share the example?
Here a similar scenario with `paper-menu-button` (outer component), which imports `iron-dropdown` (inner component) https://github.com/PolymerElements/paper-menu-button/blob/2.0-preview/paper-menu-button.html#L14
From the logs you can see that the values returned by `importForElement` are the expected ones
http://output.jsbin.com/jobolo/1/

Ps: I noticed you were using `document._currentScript`. In the new `html-imports` that doesn't exist anymore, you can use the native `document.currentScript` 👌

**Comment by gorshkov-leonid** [comment]
Yes, I have tryed to use document.currentScript only, result has been same. I do not know how to share example -in github the polyfills was additionally compiled to es5 via 'es2015' preset. Example can be ran via npm install & npm run serve. So I will try to use it in jsbin...

**Comment by valdrinkoshi** [comment]
If you share a GitHub repo is fine as well. Beware that some polymer elements haven't been ported to 2.0 yet...

**Comment by gorshkov-leonid** [comment]
Now I'm just playing with web components, though tried polymer 2.0-preview in chrome before. Well, this issue is not critical for me, because exact selector can be used looks like '#${my-specific-web-component-name}-template'

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
