### ISSUE TITLE
component initialization is different in chrome and firefox

### ISSUE THREAD

**Issue by everdimension** [webcomponents/webcomponentsjs#684]
If you call a component's method just after it has been added to the DOM (for instance, with innerHTML) it works in chrome but throws a `TypeError` in firefox.

Here's a minimal fiddle reproducing the bug: https://jsfiddle.net/everdimension/6tap4jdy/
If you postpone calling method to the next tick then it works in firefox, too.

I'm not sure whether this is the library's fault or ff's.

**Comment by bicknellr** [comment]
(0.7.24 is used in the repro.)

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/cexanar/edit?html,console,output

**Comment by everdimension** [comment]
@TimvdLippe "_appears_"? How does it "appear" to be fixed if the FF still crashes in the repro demo I linked to?
