### ISSUE TITLE
v1 branch - Safari 9

### ISSUE THREAD

**Issue by deini** [webcomponents/webcomponentsjs#685]
In v1 branch, I believe that using the babel preset `babili` breaks Safari 9 support as to my knowledge `babili` will output ES2015. 

Is adding `es2015` preset an option? 

I can help out with the fix, just want to confirm its actually a problem and I'm not going crazy.

**Comment by notwaldorf** [comment]
We will actually be using the closure compiler instead. @azakus has a branch out already, and we should be merging his fix today or tomorrow.

**Comment by azakus** [comment]
Should be fixed with #698
