### ISSUE TITLE
webcomponents-lite.js

### ISSUE THREAD

**Issue by nbagley** [webcomponents/webcomponentsjs#692]
Re: v0.7.24 (using Polymer v1.8.0)

@robdodson I've built a standard tree-view that makes use of nesting components for "branch" and "leaf" nodes as follows:

tree (tree component)
--leaf (leaf component)
--leaf
-+branch (branch component)
----leaf
----etc

All of this is working just fine... in Chrome. In other browsers, we are having an issue with errors getting thrown when passing arrays and objects through properties. We're getting the following errors:

Safari: The component renders and functions as normal, but throws this error: "TypeError: undefined is not an object (evaluating 'node.__importParsed')", line 1705

Firefox: Similarly, the component renders and functions as normal, but throws this error: "TypeError: node is undefined", line 1705

IE: Complete failure. No render of the component. Throws this error: "Unable to get property '__importParsed' of undefined or null reference", line 1705

You can clearly see the pattern: There's an undefined value getting passed through when it's it's expecting an object. Line 1705 of webcomponents-lite.js (and it's surrounding method is as follows:

isParsed: function(node) {
  return node.__importParsed;
}

Which if you follow it up the stack, you see that it's called on line 1853:

1852 owner = n.ownerDocument;
1853 parsed = parser.isParsed(owner);

It's making the assumption that the ownerDocument can be found on the node passed. What's interesting is that the breakdown is that it's reading the value of one of my properties (which is an object of values) that's being passed to a sub-component (a leaf in my tree) and at this point, it sees it as an object, not a node, so naturally, there isn't a property of "ownerDocument" in it. At this point it's literally passing the following:

1853 parser.isParsed(undefined);

Which when it hits line 1705, it blows up:
1705 return node.__importParsed; // can not get property on undefined

The solution is much more simple than my longwinded explanation:
1705 return node && node.__importParsed; //check for value before checking for property

This small change allows for things to render in all browsers and completely clears all errors. I've been looking for the reason by it's only in a certain scenario that it's not parsing a node, but rather the direct value of a property, but I haven't come to a conclusion on why yet.

I'm open to any and all suggestions and if you need more or any samples of my component, please let me know. Thanks!

--
Nathan

**Comment by robdodson** [comment]
I don't have assigning powers... but I'm assigning this to @azakus 😄

**Comment by azakus** [comment]
Hmm, do you have a small example you could provide?
This codepath is coming from a MutationObserver, and the object here should be a `Node`, and all nodes should have `ownerDocument`.

> What's interesting is that the breakdown is that it's reading the value of one of my properties (which is an object of values) that's being passed to a sub-component (a leaf in my tree) and at this point, it sees it as an object, not a node, so naturally, there isn't a property of "ownerDocument" in it.

I'm particularly interested in how this setup works for you. Do you override a DOM accessor such as `children` or `parentNode`?

**Comment by nbagley** [comment]
You are amazing... and I am a complete idiot for not even thinking about that. Silly me added a `children` property to my component and it overrides the default `children` property. So I just went through and changed everything to `items` to test and see if that fixed things and, lo and behold, all errors are gone.

Memo to self: Never ever use `children` as a property. Rookie mistake.

I'm not sure if anything should be done about that, but I will tell you that the check to make sure that whatever is being passed has an `ownerDocument` solved my issue and things loaded on without errors. Granted the only reason I did add a `children` property was because in Chrome there is absolutely no issue with overriding that property. So technically, it's a polyfill issue, though some might view it as somewhat of an edge-case.

If you want more details about the recreation of this issue, please let me know.

Much thanks, @azakus, @robdodson
