### ISSUE TITLE
v1 - CSS variables not working on chrome's iPhone emulator

### ISSUE THREAD

**Issue by jehna** [webcomponents/webcomponentsjs#703]
# Description:

CSS variables are not working in the `v1` branch on desktop Chrome's iPhone emulator

# How to reproduce:

1. Create a simple Polymer component
2. Set any CSS property with a CSS variable
3. Open the page with with Chrome
4. Open dev tools
5. Set mode to mobile device emulator
6. Set device to any iPhone
7. Reload page

## Result:

CSS property set with CSS variable does not work

## Expected result:

The CSS property should work, as iOS and Chrome supports CSS variables

# Demo

http://jsbin.com/sixecuvuxo/1/edit?output

**Comment by azakus** [comment]
Looks like the useragent string is set to iOS 9.1, which has some bugs in the CSS Variables implementation: https://github.com/webcomponents/shadycss/blob/master/src/style-settings.js#L15-L17. This then interacts poorly with the checks for native ShadowDOM, as we do not support native ShadowDOM and CSS Variables polyfill.

I suggest using the iOS simulator or an iOS device when testing, as there are plenty of differences in the runtimes that are not simulated with the developer inspector.

**Comment by TimvdLippe** [comment]
This now appears to be working in iPhone emulation mode: http://jsbin.com/xazawom/edit?html,output
