### ISSUE TITLE
v1 branch - caret disappears from <input> elements in Firefox

### ISSUE THREAD

**Issue by patrickarlt** [webcomponents/webcomponentsjs#713]
I originally reported this in https://github.com/webcomponents/shadydom/issues/61 but it looks like the same issue is occurring on the v1 branch here and since it looks like 1.0.0 is getting an final release soon and I wanted to give it more visibility.

When the ShadowDOM polyfill is loaded in Firefox all `<input>` elements loose their caret when focused.

![screen shot 2016-12-05 at 11 28 42 am](https://cloud.githubusercontent.com/assets/378557/20899428/47c07708-badf-11e6-816b-5be1b9600a62.png)

http://jsbin.com/nowuvug/1/edit?html,output

This seems to occur in FF 50 in my original issue and FF 51 which is the latest.

I really would like to adopt the v1 specs and polyfills but I would be really hesitant to do with this bug.

**Comment by notwaldorf** [comment]
Thanks for the report! I've pinged back the other thread -- unfortunately this looks like a shadyDOM bug, so it has to be fixed there, not here -- webcomponentsjs just assembles all the polyfills together.

**Comment by patrickarlt** [comment]
@notwaldorf Thanks! I'm going to close issue out since it should be tracked on webcomponents/shadydom#61.

Can't wait to start using the first stable release of this.

**Comment by patrickarlt** [comment]
Thanks @notwaldorf! I'll close this issue out. Really looking forward to the v1 release of this.
