### ISSUE TITLE
polyfill registerElement on browsers that support customElements.define

### ISSUE THREAD

**Issue by jogibear9988** [webcomponents/webcomponentsjs#714]
is that possible?

**Comment by notwaldorf** [comment]
It's not likely this is a thing we can do easily -- it's not just the syntax that has changed from Custom Elements v0 to v1 -- it's the timing of some of the callbacks, and the structure of elements (`content` vs `slot`). As a result, mixing and matching v0 and v1 on the same page becomes really confusing: you need to know which spec an element was written for if you want to use it correctly, and that isn't a thing we really want to encourage.

**Comment by jogibear9988** [comment]
thanks for info
