### ISSUE TITLE
Edge returning errors when using webcomponentjs v1.0.0-rc.4

### ISSUE THREAD

**Issue by tjmonsi** [webcomponents/webcomponentsjs#715]
Microsoft edge is returning a lot of errors
Object doesn't support property or method 'registerElement'
Object doesn't support property or method '_getExtendedPrototype'
Object doesn't support property or method '_prepIs'

![image](https://cloud.githubusercontent.com/assets/2645718/23710921/4b85ca46-0459-11e7-97f9-2ae2efba97b0.png)

It might be related to: #699

**Comment by azakus** [comment]
It looks like you're using Polymer v1.x? If so, you must use Webcomponents v0.
Webcomponents v1 only supports Polymer 2.x
