### ISSUE TITLE
WebComponentsReady does not fire

### ISSUE THREAD

**Issue by oravecz** [webcomponents/webcomponentsjs#734]
I'm on Chrome Version 52.0.2743.116 (64-bit) on OSX 10.11.6 (15G1217).

I tried to use the `webcomponents-loader`, and it correctly identified the `webcomponents-sd-ce.js` file and loaded it. However, the `WebComponentsReady` custom event did not fire. I did a search in the `webcomponents-sd-ce.js` file, but did not find this event being triggered.

From the source code, it looks like the event is raised in the `webcomponents-loader` only when there are no polyfills loaded. This made me assume that the event is fired from one of the other polyfills, but I could not find mention of this event in the source code.

Since this is a core function, I would assume that many other people would of complained about it before myself; but I do not see it in the code, and the simplest example does not trigger the event.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>No Event</title>

    <script src="bower_components/webcomponentsjs/webcomponents-es5-loader.js"></script>
</head>

<script>
    window.addEventListener( "WebComponentsReady", function ( event ) {
        console.log('WebComponentsReady')
    } )
</script>

<body>
</body>
</html>
```

**Comment by valdrinkoshi** [comment]
This happens also when we force ShadyDOM and customElements polyfill in chrome57
http://jsbin.com/coyesaq/1/edit?html,console,output
