### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by moebiusmania** [webcomponents/webcomponentsjs#736]
using **webcomponents-es5-loader.js** or **webcomponents-hi-ce-es5.js** with transpiled code from Polymer 2 components results in this message on Firefox and Safari 🤔. 
Any suggestion?
thanks

**Comment by CaptainCodeman** [comment]
See https://github.com/Polymer/polymer/issues/4440#issuecomment-287452735

**Comment by moebiusmania** [comment]
with Polymer 2 **rc3** and Web Components polyfill **rc6** I can't reproduce this issue, so I guess its solved 😄 , you can check this repo that I have created for testing the transpile process **without** the polymer-cli https://github.com/moebiusmania/polymer2-transpile .
