### ISSUE TITLE
Unable to compile due to missing files

### ISSUE THREAD

**Issue by lozohcum** [webcomponents/webcomponentsjs#738]
error:   Uncaught exception: Error: ENOENT: no such file or directory, open 'C:\Users\lozohcum\Documents\Repos\polymer-test\bower_compon                    ents\webcomponentsjs\webcomponents-lite.min.js'
error:   Error: ENOENT: no such file or directory, open 'C:\Users\lozohcum\Documents\Repos\polymer-test\bower_components\webcomponentsjs                    \webcomponents-lite.min.js'

**Comment by azakus** [comment]
There are few problems here:
1) Don't compile files in this repo, they are already compiled
2) `webcomponents-lite.min.js` has been renamed `webcomponents-lite.js`, for the 1.x version, but you still don't need to compile it.
