### ISSUE TITLE
Unable to get property 'ApplyShim' of undefined or null reference

### ISSUE THREAD

**Issue by RevillWeb** [webcomponents/webcomponentsjs#739]
Hi,

Using `webcomponents-es5-loader.js` in IE11 which ultimately loads `webcomponents-lite.js` throws the error:

```
Unable to get property 'ApplyShim' of undefined or null reference
```

Due to line [158](https://github.com/webcomponents/shadycss/blob/master/src/scoping-shim.js#L158) in `scoping-shim.js`:

```
else if (window.ShadyCSS.ApplyShim) {
```

Should perhaps be:

```
else if (window.ShadyCSS && window.ShadyCSS.ApplyShim) {
```

I'd create a pull request but rather people with more in depth knowledge of the code let me know if I'm missing a bigger picture here.

Thanks 👍

**Comment by azakus** [comment]
I think that should already be fixed with https://github.com/webcomponents/shadycss/pull/73, but adding that check is fine.

**Comment by moebiusmania** [comment]
I have encountered this error too, I have applied the solution suggested by @RevillWeb locally and it worked, but I also had to update this line too

```
if (window.ShadyCSS.CustomStyleInterface) {
```

in the same way.
