### ISSUE TITLE
Outer element can't slot child into inner custom element

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/webcomponentsjs#747]
See https://jsbin.com/nehuta/edit?html,output, in which an extremely simple composition of web components fails to render.

The crux of it is that an outer custom element with a slot inside an inner custom element doesn't have its light DOM children appear inside the inner element as expected. If a custom `outer-element` has the following template:

    <template id="outerTemplate">
      <inner-element>
        <slot></slot>
      </inner-element>
    </template>

then

    <outer-element>Hello</outer-element>

shows nothing. The jsbin works in native Shadow DOM in both Blink and WebKit.

The existing of the custom `inner-element` is related to triggering the issue. If that custom element is replaced with a standard HTML element, the `slot` works as expected.

**Comment by notwaldorf** [comment]
This sounds like a Shadow DOM bug, moving it there.

**Comment by notwaldorf** [comment]
This issue was moved to webcomponents/shadydom#116
