### ISSUE TITLE
WebComponentsReady not firing

### ISSUE THREAD

**Issue by arthurevans** [webcomponents/webcomponentsjs#753]
In v1.0.0-rc.6 and later, it appears that WebComponentsReady isn't firing on Firefox, using either `webcomponents-lite.js` or `webcomponents-loader.js`. 

In `webcomponents-loader.js`, it doesn't seem to fire at all in Chrome.

JSBin:
https://jsbin.com/yuyuzayewi/edit?html,console,output

**Comment by azakus** [comment]
Seems not to work with `loader` in rc.7: https://jsbin.com/xiwaden/edit?html,output
but does work with lite `lite`: https://jsbin.com/yulepe/1/edit?html,output

**Comment by azakus** [comment]
Aha, but it _does_ fire when only looking at the "output" frame: https://output.jsbin.com/xiwaden

**Comment by azakus** [comment]
Looks like we need to way for `document.readyState` to be `interactive` at least before firing `WebComponentsReady`
