### ISSUE TITLE
custom element v1 issue "HTMLElementConstructor is not a constructor" in iOS Safari 9.3

### ISSUE THREAD

**Issue by tclzcja** [webcomponents/webcomponentsjs#755]
The element definition is like this:

`window.customElements.define('site-header', class extends HTMLElement {
    constructor() {
        super();
    }
});
`

and I'm using webcomponentsjs#1.0.0-rc.7, webcomponents-hi-ce.js. On iOS/Safari 10+ it works fine, but in iOS 9.3 I keep getting 

>  HTMLElementConstructor is not a constructor (evaluating 'super()')

at CustomElementinternals.js:253

I guess it's sort of related to [this issue](https://github.com/google/traceur-compiler/issues/1709) and I've tried the hack people posted in that issue, but it doesn't work. Just wonder what should I do to make it work, thank you!

**Comment by tclzcja** [comment]
OK I'm closing this issue because my company decided to stop supporting iOS 9.

**Comment by semmel** [comment]
The solution is not to inherit directly form `HTMLElement` but from the derived class `Safari9HTMLElement` which is derived from `HTMLElement` via prototypal inheritance:
```javascript
function setProto(A, B)
{
	A.prototype = Object.create(
		B.prototype,
		{
			constructor: {
				configurable: true,
				writable    : true,
				value       : A
			}
		}
	);
}
function Safari9HTMLElement(self)
{
	self = HTMLElement.call(self || this);
	return self;
}
setProto(Safari9HTMLElement, HTMLElement);

customElements.define(
	"some_name", 
	class extends Safari9HTMLElement {   // just on iOS9, HTMLElement otherwise
		constructor() { super(); /* .. */} 
	}
);
```
