### ISSUE TITLE
Platform.js TypeError: Attempted to assign to readonly property. & Error: Assertion failed

### ISSUE THREAD

**Issue by DelawareConsulting** [webcomponents/webcomponentsjs#76]
Dear,

We are experiencing the following problems with Platform.js 
- TypeError: Attempted to assign to readonly property.
- Error: Assertion failed

On the following lines:
![setting___remsis_admin](https://cloud.githubusercontent.com/assets/2477571/5213907/ce8019a4-7614-11e4-8b1a-0e4e73e2cb0b.png)

Any suggestions? This code is 100% default.

**Comment by janbiasi** [comment]
I also see the Error in the current **Safari 8.0.2**...

```

[Error] TypeError: Attempted to assign to readonly property.
	(anonyme Funktion) (platform.js, line 16)
```

**Comment by KupuJIJI** [comment]
janbiasi , I got same

**Comment by garlicnation** [comment]
@mmocny @janbiasi @KupuJIJI Can you provide a minimal reproduction of this issue? I'll reopen it if I have something more concrete to work on.
