### ISSUE TITLE
webcomponents-loader fails to load `platform` bundle on browser that need it

### ISSUE THREAD

**Issue by sorvell** [webcomponents/webcomponentsjs#761]
Old versions of Chrome pass all the tests for the web-platform bundle but still do not include ES6 features like `Array.from` and `Object.assign`. This can lead to webcomponents code that depends on ES6 failing. 

If `Array.from` is not available, the loader should probably just default to the `lite` bundle.

**Comment by valdrinkoshi** [comment]
Fixed in [v1.0.0-rc.9](https://github.com/webcomponents/webcomponentsjs/releases/tag/v1.0.0-rc.9)
