### ISSUE TITLE
CSS Variables / Custom properties polyfill?

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/webcomponentsjs#764]
Hey,

so IE11 should be supported, but according to http://caniuse.com/#search=variables IE11 does not support css variables. Since shadow dom styling relies partly on css variables, does this mean a polyfill for css variables is shipped? 

I did not see this mentioned in the readme, so if this is the case, it would be quite helpful to include. Thanks for clarifying.

**Comment by seaneking** [comment]
[ShadyCSS](https://github.com/webcomponents/shadycss) covers custom props as well as other WC CSS related stuff (Shady DOM encapsulation, mixins)

**Comment by lukasoppermann** [comment]
Awesome, so on site where I use the web components loader, I can be sure that css custom properties work in IE11 as well?

**Comment by snuggs** [comment]
If you are using a *fill that encapsulates shadyCSS then your statement is correct @lukasoppermann.
