### ISSUE TITLE
Question: minified code without the .min convention?

### ISSUE THREAD

**Issue by straker** [webcomponents/webcomponentsjs#765]
At my company, we run all JS code through a minifier before pushing to production. We prevent a file from running through the minifier if it has a `.min` before the extension (we've run into problems double minifying). 

We are now running into problems with the latest webcomponentjs because they are all minified without the `.min` convention. I was hoping you could elaborate that decision, since if the convention is going away we'll need to adjust our build step.

Thanks.

**Comment by ankon** [comment]
webcomponentsjs used to have a `.min.js` extension. After updating this seems to have been removed, breaking our app in the case the polyfills were needed.

It looks a bit like this `.min.js` got lost in 2ff4e6eb53c4fee5e07c9344255ca34cb543414b.

**Comment by TimvdLippe** [comment]
Sorry for taking so long to respond. I am not sure what the original decision-making here was. However, we can now no longer update the bundle names, as that would be a breaking change. I am unsure what our options are now 😢

**Comment by spacerockzero** [comment]
You could add a .min file, unminify the normal one, and just instruct ppl to use the .min file if they want a minified output

**Comment by web-padawan** [comment]
It would mean that the repo would have to include 2 different loaders, too. Currently, `webcomponents-loader` resolves which bundles to load but they are all minified. And to me it looks like manual transpiling (and sometimes, minifying) of the polyfills might bring in the problems, related to the improperly configured tools, etc.

**Comment by TimvdLippe** [comment]
I have added the label "breaking change" as a reminder that we can make this change in a new major version of the polyfill. However, for the time being we can not make any changes to our naming scheme sadly :cry:
