### ISSUE TITLE
[iOS 8] Error in Object.setPrototypeOf(f, b.prototype) on mobile Safari

### ISSUE THREAD

**Issue by leolabs** [webcomponents/webcomponentsjs#767]
Using the latest webcomponents.js v1.0.0-rc10 in combination with Polymer#2.0.0-rc7, I get the following error when I load the project on mobile Safari on iOS 8 in webcomponents-lite.js:213 and webcomponents-lite.js:1565:

```
TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(f, b.prototype)')
```

I think that Safari in iOS 8 doesn't have support for this `setPrototypeOf` yet. Is iOS 8 still supported and is there a workaround or polyfill that can be used to fix this error?

**Comment by pareshsalunke** [comment]
I am trying to test in browserstack.com for same configuration. I am facing the same issue. Looks like,  It's been resolved in iOS9 though.I am trying to find workaround/ polyfills but if anyone knows solutions to this. Please let me know.

**Comment by alxdnlnko** [comment]
+1. Got the same error on IOS 8.4.

**Comment by csomakk** [comment]
+1

**Comment by pareshsalunke** [comment]
@alxdnlnko and @csomakk : If you are using webpack then installing babel-polyfill and https://babeljs.io/docs/plugins/transform-object-set-prototype-of-to-assign/ helped me get rid of the errors. If not then just polyfill.js should work for you as well.

**Comment by bkawk** [comment]
I also have this issue on ios8 and ios9

<img width="679" alt="screen shot 2017-06-24 at 12 15 48 am" src="https://user-images.githubusercontent.com/14357697/27491778-41f83f9c-5876-11e7-9685-5bd503fa44dc.png">

**Comment by unionthugface** [comment]
+1

**Comment by unionthugface** [comment]
Any news on this?  My app doesn't work on iPhone 6 at all.

**Comment by TimvdLippe** [comment]
We support Safari 9 and above, which means we do not provide active support for iOS 8. For more information see https://github.com/webcomponents/webcomponentsjs#browser-support and https://www.polymer-project.org/3.0/docs/browsers
