### ISSUE TITLE
Disable html import polyfill

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/webcomponentsjs#768]
Hey, since both firefox and safari put html imports on hold, I decided to build my custom elements without html imports.

However, the polyfill is still loaded in safari, using the `loader`. Is there a way to add a config to the loader or something, to stop it from loading the html import polyfill?

Thanks.

**Comment by azakus** [comment]
No, the loader is only configured to load the prebuilt bundles, not each polyfill individually. This is to balance code size vs # of network requests.

I don't think we're quite ready to expand the number of bundles we have, as the current amount is already quite complex to test for 🤹‍♀️.

However, you can always load the polyfills individually, or make a more specialized bundle.
The [bundle entrypointes](https://github.com/webcomponents/webcomponentsjs/tree/master/entrypoints) should be a good starting point for ordering if you decide to go that route.

**Comment by lukasoppermann** [comment]
Ahh, I understand, thanks for clarifying.
