### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by julien** [webcomponents/webcomponentsjs#772]
Hi,

I wanted to know if you are planning to publish the `rc` releases frequently on npm.

I'm currently  using `npm` as my package manager and I'm using the git repo's URL to get the dependency i.e.
 
```shell
npm i  git+ssh://git@github.com:webcomponents/webcomponentsjs.git
```

It would be nice if we could get `1.0.0-rc.11` from npm but I'm assuming this is because it's an `rc` release. 

Could you please confirm this is the case, or tell me the recommended way of using this package to get the latest version.

Thanks

**Comment by moebiusmania** [comment]
I agree with @julien , and since NPM handles release candidates too I don't think this would be a big effort.

**Comment by FluorescentHallucinogen** [comment]
See https://www.npmjs.com/package/@webcomponents/webcomponentsjs 😉

**Comment by FluorescentHallucinogen** [comment]
I think this issue can be closed.

**Comment by julien** [comment]
Thanks, yes I guess since 1.0.0 is on npm this is resolved.
