### ISSUE TITLE
Error when used with GPT (Dfp ads) on FireFox

### ISSUE THREAD

**Issue by CaptainCodeman** [webcomponents/webcomponentsjs#775]
Including the webcomponents loader on FireFox seems to interfere with the Google Publisher Tag script that DoubleClick for Publishers uses:

```
Exception in queued GPT command DOMException [SyntaxError: "'#google_ads_iframe_/ad-unit-id/div-id' is not a valid selector"
code: 12
nsresult: 0x8053000c
location: [domain]/bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js:123]  pubads_impl_115.js:70:577
	Pl.prototype.push https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:70:577
	P/< https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:70:79
	Rl https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:71:84
	P/< https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:70:79
	Ap https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:315:653
	<anonymous> https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:316:300
	<anonymous> https://securepubads.g.doubleclick.net/gpt/pubads_impl_115.js:1:2
```

I'll try and setup an example to reproduce it.

**Comment by CaptainCodeman** [comment]
Here's [a JSBin to demonstrate the issue](http://jsbin.com/biroyebuye/edit?html,console,output)

It's definitely some interaction between GPT and WebComponents polyfill, looks like it starts from `getElementById` that then does some queries.

If I add some code to shim the GPT calls to instead use GPT Light / Glade then it works OK.

**Comment by CaptainCodeman** [comment]
Maybe related, maybe not, but I have hit other issues that only seem to affect FireFox. Having certain scripts on the page with an `async` attribute caused errors with an Angular 1.6 app. Removing the async and having the script load _before_ `webcomponents-loader.js` (or lite) fixed things.

**Comment by TimvdLippe** [comment]
This appears to be fixed now: http://jsbin.com/gucogut/edit?html,console,output
