### ISSUE TITLE
Polyfill working on chrome 51

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/webcomponentsjs#779]
Hey,

so I am working on a project where (currently) chrome 51 is used, so no web components. 😞 
So I would like to know if this polyfill will work in chrome 51. 

Thanks.

**Comment by snuggs** [comment]
Last i checked this is correct @lukasoppermann

**Comment by justinfagnani** [comment]
It should work just fine. Closing unless someone reports an issue.
