### ISSUE TITLE
Webcomponentsloader causing issues with bundlers

### ISSUE THREAD

**Issue by AndreasGalster** [webcomponents/webcomponentsjs#781]
When using webcomponentsloader for the polyfill, bundlers such as Webpack don't know to include the specific polyfills to include, thus it doesn't work and your only option is to choose a specific polyfill. Is there a way to import webcomponentsloader in a way that it automatically includes all the actual polyfills that **might be needed**?

**Comment by justinfagnani** [comment]
I don't quite understand... the point of the loader is that we also don't know which bundles to include. The loader figures that out with client-side feature detection. How would the loader go about "including" all the possible bundles in such a was as to make Webpack happy, but not actually load them all to the browser? IOW, isn't this best solved in the Webpack config?

**Comment by AndreasGalster** [comment]
Afaik webpack (or other bundlers like Meteor) create bundles based on what gets required/imported. In case of Meteor/Webpack, they also create bundles (like fragements in polymer) for individual dynamically imported bundles via import().

I'm not aware of a method in Webpack to say "include this in the bundle" without requiring it. Even if it were so, the file would be something like app.js (or whatever you call your bundle), whereas webcomponents-loader always expects a specific file name like webcomponents-hi-ce.js etc., no?

If I do something like this, how would the bundler be able to know to include the polyfill at all?

```
	import('./bower/@polymer/webcomponentsjs/webcomponents-loader.js').then(() => {
			import('./views/_app-shell.html');
	});
```

The only thing that actually gets bundled is webcomponents-loader, but not the individual polyfills.

What I would expect for the case of the loader, that it somehow tells the bundlers to include them all in the build as fragments/chunks, otherwise it's impossible to load them. Then webcomponents-loader would refer to the correct chunk. After all, with the loader, there's a chance that any of those polyfills will be used in some case based on the browser, so why not create chunks for each of the variations individually and then webcomponents-loader refers to them?

**Comment by CaptainCodeman** [comment]
If you want to bundle the full polyfills then you should add the `webcomponents-lite.js` file to the bundle, not the loader. It's really the wrong way to approach polyfills though and goes against best practices - you are forcing download and evaluation of JS to browsers that simply don't need it.

Some good reading: https://w3ctag.github.io/polyfills/
