### ISSUE TITLE
Publish 1.0 to NPM

### ISSUE THREAD

**Issue by seaneking** [webcomponents/webcomponentsjs#782]
Just saw that 1.0 has officially landed ( 🎉 ), can it be pushed to the `webcomponents.js` NPM package?

**Comment by abdonrd** [comment]
It's already in NPM 😄 

https://www.npmjs.com/package/@webcomponents/webcomponentsjs

**Comment by seaneking** [comment]
Bah, my bad. Didn't realise the package name had changed. Thanks!

**Comment by abdonrd** [comment]
Your welcome! :)
