### ISSUE TITLE
Loader problem, there's no webcomponents-sd.js

### ISSUE THREAD

**Issue by arturparkhisenko** [webcomponents/webcomponentsjs#786]
I'm using hybrid mode with: `window.ShadyDOM = {force: true};`.
I target latest browsers (so I don't need a `ce` polyfill).
Loader generates me: `webcomponents-sd.js` and that's why it isn't working.
The temporary workaround with `webcomponents-sd-ce.js` file https://github.com/webcomponents/webcomponentsjs/issues/786#issuecomment-302118269.

**Comment by notwaldorf** [comment]
There shouldn't be any browsers that have custom element support but not shadow dom support. Just polyfill inn for shadow dom doesn't help you, since you also need to polyfill custom elements to use it

**Comment by arturparkhisenko** [comment]
@notwaldorf but want to use shady-dom in the latest browsers.

**Comment by CaptainCodeman** [comment]
Set `window.ShadyDOM = {force: true};` _before_ the loader script.

**Comment by arturparkhisenko** [comment]
@CaptainCodeman https://github.com/webcomponents/webcomponentsjs/issues/786#issue-229044182 read pls, i've updated to make it easier to understand: 
> Loader generates me: `webcomponents-sd.js` and that's why it isn't working.

**Comment by CaptainCodeman** [comment]
I don't have any problem reading or understanding thank you. Instead of arguing about the answer, have you actually bothered to try it?

Put the code before the loader and it will work as expected because if you read the code for the loader you'll see that it handles the `ShadyDOM` options being set and loads the required script if that is the case. The options need to be set before the script that uses them to decide what to load.

https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-loader.js#L23

**Comment by notwaldorf** [comment]
I think he is trying to force the `ce` polyfill, so you need `window.customElements.forcePolyfill` as per the next line: https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-loader.js#L26

@arturparkhisenko I think the setup should be:
```html
<head>
  <script>
    window.customElements.forcePolyfill = true;
  </script>
  <script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head> 
```

Disclaimer: I haven't actually tried to see if this works.

**Comment by arturparkhisenko** [comment]
@notwaldorf Thanks, it works! (my mistake was that I was trying to set it with `window.customElements = {forcePolyfill: true}`) but not solving the problem of the unneeded polyfill.

@CaptainCodeman I wanted to say the same to you :), and I'm not arguing, please look at this example ([jsbin](https://jsbin.com/puxuhugevo/edit?html)):
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <script>
    window.ShadyDOM = {force: true}; // as you see i really put it before loader ;)
  </script>
  <script src="https://cdn.rawgit.com/webcomponents/webcomponentsjs/cf46d7a0/webcomponents-loader.js"></script>
</head>
<body></body>
</html>
```
And open dev-tools, you'll see this error:
```
webcomponents-sd.js Failed to load resource: the server responded with a status of 404 ()
```

**Comment by CaptainCodeman** [comment]
Strange, I was going off my own recent use of `window.ShadyDOM = {force: true};` while working on a different issue and it was working as expected for me - maybe a different build / version.

Anyway, glad it's sorted.

**Comment by moebiusmania** [comment]
@CaptainCodeman I have to report that using the code provided by @arturparkhisenko I have encountered that problem too. The loader searches for a ```webcomponents-sd.js``` that is not available inside the package. It's just a build problem that for one reason or another that file is not being generated in the latest build. Could you fix that please?

**Comment by AliMd** [comment]
The Same issue
Fixed with `window.customElements.forcePolyfill = true;` Thanks to @notwaldorf
But I think component loader must fix `-sd` suffix and don't load not exited files

**Comment by TimvdLippe** [comment]
This bundle now exists: https://github.com/webcomponents/webcomponentsjs/blob/master/bundles/webcomponents-sd.js
