### ISSUE TITLE
v1.0.0 for bower comes without webcomponentts-*.js

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [webcomponents/webcomponentsjs#787]
when running `bower install webcomponents/webcomponentsjs#1.0.0` no `webcomponentts-*.js` or other code is included. But when running `bower install webcomponents/webcomponentsjs#1.0.0-rc.12` the expected code exists.

**Comment by azakus** [comment]
Hmm, I can't seem to reproduce this. Can you try running `bower cache clean` and see if this is still occurring?

**Comment by BrandiATMuhkuh** [comment]
Thank you `bower cache clean` did the trick.
