### ISSUE TITLE
Ploblems with shadow DOM in old Chrome versions

### ISSUE THREAD

**Issue by lawlietmester** [webcomponents/webcomponentsjs#789]
In my current project, I need the support of Chrome versions starting from 31. Project based on Polymer 2.

In Chrome 43, I am getting error:
element-mixin.html Uncaught TypeError: Cannot read property 'appendChild' of null

It's associated with this code:
`value: function _attachDom(dom) {
          if (this.attachShadow) {
            if (dom) {
              if (!this.shadowRoot) {
                this.attachShadow({ mode: 'open' });
              }
              this.shadowRoot.appendChild(dom);
              return this.shadowRoot;
            }
          } else {
            throw new Error('ShadowDOM not available. ' +
            // TODO(sorvell): move to compile-time conditional when supported
            'Polymer.Element can create dom as children instead of in ' + 'ShadowDOM by setting `this.root = this;\` before \`ready\`.');
          }
        }`

So after this.attachShadow({ mode: 'open' }); - this.shadowRoot still null.
Any ideas how to change source code so it will be working in this version of Chrome? I understand that such errors have very low priority - so the only way to change source code manually.

**Comment by sorvell** [comment]
This issue was moved to webcomponents/shadydom#162
