### ISSUE TITLE
vertx dependency in webcomponents-lite.js

### ISSUE THREAD

**Issue by Hotell** [webcomponents/webcomponentsjs#794]
What is this `vertx` and why is it required in try-catch within `webcomponents-lite.js` ? there is nothing like that in dependencies of this project

https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-lite.js#L94

**Comment by 4esnog** [comment]
Same here. Webpack build fails because it can't resolve this package.

**Comment by espiegel** [comment]
Why is vertx being brought in?

```
WARNING in ./~/@webcomponents/webcomponentsjs/webcomponents-lite.js
Module not found: Error: Can't resolve 'vertx'
```

**Comment by Tschef** [comment]
Are there any news on this issue?
I would like to load webcomponents per SystemJS and it fails out of this reason.

**Comment by valdrinkoshi** [comment]
It comes from the `es-promise` dependency which is bundled into `webcomponents-lite`. This is the line requiring vertx 
https://github.com/stefanpenner/es6-promise/blob/master/lib/es6-promise/asap.js#L100

**Comment by robdodson** [comment]
Does the webpack build fail or does it warn? I think it's safe to ignore the unmet dependency. My (very rough) understanding is that vertx is only loaded as a fallback of some kind... @jakearchibald do you know if we could maybe switch to a different promise polyfill that doesn't have this same vertx issue? I recall us chatting about this over hangouts a long time ago but at the time we didn't come to a great conclusion. Figured it'd be good to discuss on github so there's a record.

**Comment by jakearchibald** [comment]
@robdodson does the fix in https://github.com/stefanpenner/es6-promise/issues/100#issuecomment-95309254 work?

**Comment by Tschef** [comment]
I am not bundling and fixed the issue for _SystemJS_ with
`
System.config({
    map: {
        "vertx": "@empty",
    }
});
`

This is the equivalent to the _Webpack_ fix with the _IgnorePlugin_ 
`
new webpack.IgnorePlugin(/vertx/)
`

Vertx is only used for server side from what i can understand, because it checks if there is a undefined _window_ object at https://github.com/stefanpenner/es6-promise/blob/a5838bd94a76e31ad80ac1685bcd0dbc3d8ce963/lib/es6-promise/asap.js#L116

**Comment by pablohpsilva** [comment]
Still not working guys. Check this [issue](https://github.com/stefanpenner/es6-promise/issues/305) out. 

Is there any other promise polyfill you guys could use?

**Comment by stefanpenner** [comment]
Hey guys, es6-promise maintainer here. I would like to try and ensure using es6-promise is without the pain described above.

I have attempted an isolated reproduction: https://github.com/stefanpenner/test-es6-promise-webpack

Unfortunately, It seems to "just work". But If you could help me come up with an isolated reproduction, I will be able to ensure es6-promise is configured correctly.

---

related es6-promise issue: https://github.com/stefanpenner/es6-promise/issues/305

**Comment by stefanpenner** [comment]
I was able to reproduce, required `--target=node` to my reproduction

**Comment by stefanpenner** [comment]
Unfortunately, it doesn't seem to be possible to configure a modules externals from that module....
Anyways, a workaround: https://github.com/stefanpenner/es6-promise/pull/323

**Comment by ubarevicius** [comment]
I am still getting the warning, I'd like to help somehow, but I'm not sure where this dependency is comming from or what it does.

**Comment by Tim-Erwin** [comment]
I could solve this by ignoring `vertx` in  my `webpack.config.js`:

```
const { IgnorePlugin } = require('webpack');
...
plugins = [
    new IgnorePlugin(/^vertx$/),
    ...
]
```
