### ISSUE TITLE
Script Errors like "SCRIPT1003: Expected" in Internet Explorer 11 when Application is served from apache, not when served from polymer serve

### ISSUE THREAD

**Issue by gnoby** [webcomponents/webcomponentsjs#796]
### Description
We get Script Errors like "SCRIPT1003: Expected" in Internet Explorer 11 when our Application is served fromTomcat, not when the Application is served from polymer serve. It works fine in other browsers. This is reproducable when creating a simple polymer 2 application through polymer init.

#### Steps to Reproduce
1. polymer init 
2. choose polymer-2-application 
3. give any name to the application and the component
4. polymer serve - open 127.0.0.1:<polymerport> in Internet Explorer 11 -> Application works, it displays "Hello..."
5. Copy the whole Application to your webapps/root folder in tomcat 8.x (we don't want to change the absolute paths to make it easy reproducable and don't have to tamper with the application template where the includes from index.html start with /), or do a polymer build and copy it there 
6. Start Tomcat and open 127.0.0.1:<tomcatport>. The Application works in latest firefox and others, but not in Internet Explorer. It is not a path problem. 
7. In the console IE11 displays several Script Errors like SCRIPT1003: Expected

#### Expected Results
Application works when served from polymer and Tomcat and viewed in Internet Explorer 11

#### Actual Results
Application only works when served from polymer, not when served from Tomcat

### Browsers Affected
- [x ] IE 11

### Versions
- Polymer: 2.01
- webcomponents: 1.01

Console Output in IE 11
![2017-06-01 14_22_00-console](https://cloud.githubusercontent.com/assets/13251869/26679530/c269f506-46d5-11e7-9841-b67bb01dfdae.png)

**Comment by gnoby** [comment]
I have found out that serving the application with polymer serve changes the served javascript file on the fly for IE11. For example in webcomponents-lite.js
`var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };`
is added to the beginning of the javascript file when the client Broswer is IE11. I guess this is necessary to make it run on IE11. So I guess this is not a bug.

Is there a way to make it run on another Web Server on IE11?

**Comment by ali27001** [comment]
How did you solve the problem?

**Comment by gnoby** [comment]
@ali27001 We had to enable js compile in the polymer.json 
`  "builds": [
    {
      "name": "default",
      "addServiceWorker": true,
      "bundle": true,
      "js": {"compile": false, "minify": true},
      "css": {"minify": true},
      "html": {"minify": true}
    }`
