### ISSUE TITLE
Resolution order of custom elements within a SPA

### ISSUE THREAD

**Issue by Sylphony** [webcomponents/webcomponentsjs#797]
I'm using custom elements within a SPA and I've been having issues with understanding how the ordering of resolution for custom elements works.

For example, given markup like this:

```html
<element-one>
  <element-two></element-two>
</element-one>
```

In Chrome/Firefox, on load, the initial ordering is:

```
ElementTwo constructor
ElementTwo connectedCallback
ElementOne constructor
ElementOne connectedCallback
```

However, after switching to another view and back (it's a SPA, there is no page refresh), the loading order becomes:

```
ElementOne constructor
ElementTwo constructor
ElementOne connectedCallback
ElementTwo connectedCallback
```

I feel the sudden ordering change might be due to the way I am defining the custom elements.  Are they resolved according to when `customElements.define()` is called or is it something else?

**Comment by TimvdLippe** [comment]
The upgrades happen at the moment of calling `customElements.define`. Therefore if you asyncly load a later definition, the first element will already be created. For more information see https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-define where step 14 looks for all instances of that custom element and step 15 then enqueues a reaction. The actual upgrade will then happen in the next microtask, when all scripts have finished executing.
