### ISSUE TITLE
Import polyfills without <script> tag

### ISSUE THREAD

**Issue by 4esnog** [webcomponents/webcomponentsjs#798]
I'm trying to use polyfills inside one of my JS entry-files, importing them like so:
`import '@webcomponents/webcomponentsjs/webcomponents-loader'`

But I'm getting an error because of this line: 
https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-loader.js#L42
Loader expects that I use <script> tag, but in my case it doesn't exist. `script` variable, which is null, has no `.src` property.

Do I really must include polyfills on page using <script> tag?
Or if it is not critical, could we change this behaviour?

**Comment by ankon** [comment]
A similar issue happens when one "vulcanizes" the `<script>` elements into the main page - the script tag is now gone, and the system is no longer able to import anything.

**Comment by justinfagnani** [comment]
Don't import polyfills into JavaScript, always use a script tag. It's very critical that the loader is in a separate script tag before your application script.

The Bundler (there is no "vulcanize" anymore) on the other hand should handle bundling the index.html for non-client-side-routed apps.
