### ISSUE TITLE
IE & Edge: HTML import with <link rel="stylesheet"> disables other imported <custom-style> styles for the document scope

### ISSUE THREAD

**Issue by platosha** [webcomponents/webcomponentsjs#799]
Once there is a `<link rel="stylesheet">` in an HTML import, all the styles for the document scope declared with `<custom-style></custom-style>` elements inside HTML imports stop working in IE and Edge. Instead, the styles end up inside `<style type="import-placeholder">` elements in the `<head>`.

Not sure if this is an issue with the HTML Imports polyfill or the ShadyCSS polyfill or both of them.

Affected browsers: IE 11, Edge 14.

Impact: `<demo-snippet>` import breaks document styles in IE because of the linked stylesheet from the [prism-element/prism-import.html](https://github.com/PolymerElements/prism-element/blob/master/prism-import.html) dependency.

### Reproduction

import.html:

```html
<link rel="import" href="components/polymer/lib/elements/custom-style.html">

<custom-style>
  <style>
    html {
      --green-color: green;
    }

    body {
      color: var(--green-color);
    }
  </style>
</custom-style>
```

index.html:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <script src="components/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="import.html">
  <link rel="import" href="components/prism-element/prism-import.html">
</head>
<body>
  <h1>This should be green.</h1>
</body>
</html>
```

Expected outcome: the body text is green.

Actual outcome: in IE and Edge, the body text is black. If you remove the `prism-import.html` import, the body text becomes green in IE, as expected.

**Comment by valdrinkoshi** [comment]
Verified. HTMLImports polyfill will move all stylesheets to head if there is one `link rel=stylesheet` -
 [more details on why here](https://github.com/webcomponents/html-imports#imported-stylesheets-in-ieedge).
ShadyCSS wrongly sets the `type` attribute to the style
![screen shot 2017-06-13 at 12 54 50 pm](https://user-images.githubusercontent.com/6173664/27101883-360be080-5038-11e7-94b3-17b9220fc609.png)
@azakus mind taking a look?

**Comment by valdrinkoshi** [comment]
This issue was moved to webcomponents/shadycss#108
