### ISSUE TITLE
allow using the webcomponents-loader.js script inline

### ISSUE THREAD

**Issue by vlukashov** [webcomponents/webcomponentsjs#801]
When optimizing page load performance, as a developer I may want to reduce the number of HTTP round trips required to render a page. The webcomponents-loader script is small and therefore looks like a perfect candidate for inlining. However, as it is currently written, it does not work when inlined (since it tries to find the `<script>` tag that includes itself, and use its `src` url).

Please add an option to support inlining webcomponents-loader.js.

One approach to that could be  that the base URL for dynamically loaded polyfills is set through the global Web Components settings:

```html
<script>
  window.WebComponents = window.WebComponents || {};
  window.WebComponents.base = 'bower_components/webcomponentsjs/';
</script>
<script>
  /* webcomponents-loader.js (with the modifications to check WebComponents.base) */
</script>
```

**Comment by trentmwillis** [comment]
I've opened a PR to fix this at #802.

**Comment by Haprog** [comment]
We're currently using a custom fork of `webcomponentsjs` just because of this, so it would be nice to have the fix merged in, so that we wouldn't have to maintain the fork when `webcomponentsjs` gets updates.

**Comment by vlukashov** [comment]
Google PageSpeed has issues with the webcomponents-loader.js likely due to this same issue (see #806).

A humble reminder to the maintainers (and that seems to be @sorvell currently):

Could you please indicate--as the maintainers of the repo--if you see the ability to inline the loader a useful feature at all? It would improve the compatibility with Google PageSpeed (and will also allow for performance improvements) at the cost of a few extra lines of code.

And if this feature is useful, could you please review the PR and list the missing bits that block it from being merged? (I assume documentation update would be one). I believe the community could help you out implementing this feature if there is a clear understanding of what needs to be done.
