### ISSUE TITLE
Remove duplicated license headers

### ISSUE THREAD

**Issue by stramel** [webcomponents/webcomponentsjs#803]
Any way to remove duplicated license headers in these bundles? 

- `webcomponents-hi-ce.js`
- `webcomponents-hi-sd-ce.js`
- `webcomponents-hi.js`
- `webcomponents-lite.js`
- `webcomponents-sd-ce.js`

![image](https://user-images.githubusercontent.com/855184/27501693-8c256c30-5834-11e7-9f50-6ae46e631689.png)

**Comment by jamrizzi** [comment]
I just submitted a pull request for this #804. I didn't remove ones with different years because I'm not sure of the implications.

**Comment by stramel** [comment]
@jamrizzi Yeah, I'm not sure on how to handle that either. My guess would to be use 2014, since the banner.txt file's commit message says 

> Add license header to builds

[Commit](https://github.com/webcomponents/webcomponentsjs/commit/14192b434cfe456011de542d10bc8fde5833f7e2)

Maybe if the build process could handle this?

**Comment by jamrizzi** [comment]
Since the code is minified, the license was probably introduced through a build process, which probably means manually removing it is not the best approach.

**Comment by stramel** [comment]
@azakus Is there a reason you are maintaining all those license headers in the bundles?

**Comment by TimvdLippe** [comment]
I think we have to keep all licenses there, as they are "unique". This is probably a legal requirement, although we might have to let legal take a look.

**Comment by TimvdLippe** [comment]
We have to keep our licenses in. Even though only the years change, we can not remove the original licenses from our code.
