### ISSUE TITLE
webcomponents-loader.js assumes its name

### ISSUE THREAD

**Issue by CorpulentBrony** [webcomponents/webcomponentsjs#806]
The script for `webcomponents-loader.js` assumes its name will be `webcomponents-loader.js`.  Not only does this present a problem if someone inadvertently changes the name of the file, but it also causes problems with pagespeed if any rewrites are enabled.  Since the script is re-written into HTML in the form of `webcomponents-loader.js.pagespeed.jm.3srszniyEn1aflLxINlB.js` and the script just does a replace for the string `webcomponents-loader.js`, you end up with attempts to load non-existent scripts and 404 errors.

To fix the specific pagespeed issue, you could replace

```javascript
var url = script.src.replace(name, replacement);
```

with something like this

```javascript
var url = script.src.replace(script.src.replace(/^.*[\\\/]/, ''), replacement);
```

This leaves the issue of the developer renaming the script file themselves unresolved, but I'm only personally being affected by the pagespeed issue.

Thanks.

**Comment by TimvdLippe** [comment]
You can now inline the polyfill to get around this. For more information see https://github.com/webcomponents/webcomponentsjs#inlining
