### ISSUE TITLE
Unable to get property '__catchall' of undefined or null reference

### ISSUE THREAD

**Issue by feuerste** [webcomponents/webcomponentsjs#823]
In Edge 40.15063.0.0, I get above error message in webcomponents-hi-sd-ce.js (114,120). I am currently using webcomponentsjs 1.0.6.
Could this be related to webcomponents/shadydom#168?

**Comment by bashmish** [comment]
It is reported here as well as it originates from ShadyDOM polyfill https://github.com/webcomponents/shadydom/issues/168

**Comment by jonmann20** [comment]
Having the same error from `webcomponents-hi-sd-ce.js (114,152)`.  Using v1.0.8

![screenshot_1](https://user-images.githubusercontent.com/2007099/29639163-cd76fef6-8827-11e7-80ef-a72c66ee03ce.png)

**Comment by BorntraegerMarc** [comment]
I'm having the same issue with v1.0.10

**Comment by BorntraegerMarc** [comment]
Can we expect a solution to this soon? It's blocking our upgrade of polymer as we now have to use webcomponentsjs 1.0.1

**Comment by BorntraegerMarc** [comment]
Ah, I think this issue an be closed as it is also here https://github.com/webcomponents/webcomponentsjs/issues/813 and here webcomponents/shadydom#168

**Comment by feuerste** [comment]
Closing it due to webcomponents/shadydom#168
