### ISSUE TITLE
syntax error when loading webcomponentsjs in IE11

### ISSUE THREAD

**Issue by brainmonger** [webcomponents/webcomponentsjs#826]
I'm getting the following error when I view my component in IE11 after loading webcomponents-loader.js. I tried upgrading to use the latest psk, as suggested elsewhere but that didn't seem to resolve the issue. Any ideas??

<img width="1154" alt="screen shot 2017-08-11 at 1 28 23 pm" src="https://user-images.githubusercontent.com/2782809/29231216-38062a3a-7e9b-11e7-8511-fb1157d4d0e2.png">

**Comment by brainmonger** [comment]
With 1.0.8, I'm not longer seeing the issue with the comments error, but still seeing a script error related to ES6 code:

![screen shot 2017-08-15 at 5 28 53 pm](https://user-images.githubusercontent.com/2782809/29342496-ee0a4fd6-81df-11e7-8c8a-6c551a0999f3.png)

**Comment by 007lva** [comment]
Could be because IE11 doesn't support arrow functions.

**Comment by regou** [comment]
Will this get fixed?

**Comment by hyyan** [comment]
Please fix

**Comment by ryanpcmcquen** [comment]
It isn't just arrow functions. They also use the `class` syntax in there ...

**Comment by TimvdLippe** [comment]
This should be fixed now. In any case, if you author your elements with ES6 syntax, you have to transpile to ES5 for IE11.
