### ISSUE TITLE
Broken webcomponentsjs polyfill configuration through global vars

### ISSUE THREAD

**Issue by bashmish** [webcomponents/webcomponentsjs#828]
## Demo

This repository contains all necessary information to reproduce the issue https://github.com/bashmish/bug-webcomponentsjs-config

## Description

This is based on the repository mentioned above.

If you enforce ShadyDOM by configuring polyfill using global vars before importing the polyfill itself like this

    <script>window.ShadyDOM = { force: true };</script>
    <script>window.customElements = { forcePolyfill: true };</script>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>

then `document.createElement('...')` for custom elements does not initialize element correctly.

Check this by installing and running polymer server in this project (polymer-cli assumed installed)

    bower install && polymer serve -o

and you'll get

    my-component.html:18 Uncaught TypeError: Cannot read property 'myLightDomDiv' of undefined
        at HTMLElement.checkLightDom (my-component.html:18)
        at HTMLElement.ready (my-broken-component.html:15)
        at HTMLElement.ready (class.html:217)
        at HTMLElement._enableProperties (property-accessors.html:531)
        at HTMLElement.connectedCallback (element-mixin.html:614)
        at HTMLElement.connectedCallback (legacy-element-mixin.html:90)
        at CustomElementRegistry.Fa.define (style-placeholder.js:36)
        at Function.window.Polymer._polymerFn (polymer-fn.html:43)
        at window.Polymer (boot.html:29)
        at my-broken-component.html:10

If you remove these two lines of configuration and use GET params `?wc-shadydom=true&wc-ce=true` instead, it works OK.

Try it (possible local server address http://127.0.0.1:8081/components/bug-webcomponentsjs-config/?wc-shadydom=true&wc-ce=true) and you'll see in the console

    my-component.html:14 Ready works!
    my-component.html:19 Component LightDOM is initialized!

This works even you leave these lines in the code

    <script>window.ShadyDOM = { force: true };</script>
    <script>window.customElements = { forcePolyfill: true };</script>

so looks like GET params override them anyway.

This bug also exists under Polymer 1.9.x too. And also without `window.customElements` line, having only `<script>window.ShadyDOM = { force: true };</script>`.

**Comment by bashmish** [comment]
I do understand that the way to configure the polyfill in this manner is not officially documented and not likely supported. Although it worked pretty well for me in the past and I'm curious what changed so that now it breaks under certain circumstances. I double checked this file https://github.com/webcomponents/webcomponentsjs/blob/master/src/pre-polyfill.js and recens changes to it and didn't find any relevant answer.

Would be nice if you either say that it was never supposed to work correctly or document in somewhere and fix this bug. I can help in case it is more clear what the expected behavior should be or what is the alternative configuration which can be used instead of GET params.

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadydom#256
