### ISSUE TITLE
WeakMap tied to ShadowDom Polyfill - Chrome 35 issue

### ISSUE THREAD

**Issue by imaffett** [webcomponents/webcomponentsjs#83]
The WeakMap polyfill will only be added when WebComponents.flags.shadow is true.  This causes a problem due to Chrome 35 having proper native Shadow Dom support but native WeakMap not introduced until Chrome 36.   

NodeWebkit 0.10.x series is based off Chrome 35 and we are seeing the issue there.  I know it's an odd edge case.

```
if (WebComponents.flags.shadow) {
  if (typeof WeakMap === "undefined") {
```

**Comment by tomtomau** [comment]
+1 this issue in Chrome 35

**Comment by jmesserly** [comment]
Chrome stable is at 40, right? AFAIK, we don't officially support old versions of evergreen browsers. That said, if there's a non-disruptive way to include support, I'm happy to accept a pull request.

Easiest fix here is probably to include WeakMap polyfill manually in your HTML until NodeWebkit gets updated: https://github.com/webcomponents/webcomponentsjs/blob/master/src/WeakMap/WeakMap.js
```html
<!-- Chrome 35 needs WeakMap polyfill ... adjust path as needed -->
<script src="components/webcomponentsjs/src/WeakMap/WeakMap.js"></script>
```

**Comment by TimvdLippe** [comment]
Closing per above comment. Our browser support is viewable at https://www.polymer-project.org/2.0/docs/browsers
