### ISSUE TITLE
SEO Regression

### ISSUE THREAD

**Issue by TBLOREAL** [webcomponents/webcomponentsjs#831]
@azakus : 
The version v1.0.8 include a regression for SEO (Chrome 41).
The issue solved since the version v1.0.5 is reproduced in the version v1.0.8 : 
https://github.com/webcomponents/custom-elements/pull/107

The version v1.0.7 works fine. The polymer team build it here : 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpolymer-shop.appspot.com%2F

The bug with version 1.0.8 : 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fshop-init.appspot.com%2F

**Reproduce the issue :** 
Build and deploy Polymer Shop 2.0 with ES5 build : 
https://github.com/Polymer/shop

**Fix the issue with webcomponentsjs#v1.0.7:** 
In : 
https://github.com/Polymer/shop/blob/master/bower.json
Add the following dependency : 
"webcomponents/webcomponentsjs": "webcomponents/webcomponentsjs#v1.0.7"

Regards

**Comment by azakus** [comment]
Ah, we transitioned to NPM and it looks like the custom-elements npm releases are out of date.
I'll make a new build, which should have the correct custom-elements version.
