### ISSUE TITLE
V1 attributeChangedCallback is called asynchronously

### ISSUE THREAD

**Issue by tomalec** [webcomponents/webcomponentsjs#832]
In polyfilled browsers `attributeChangedCallback` is called asynchronously, see http://jsbin.com/jizehalomu/1/edit?html,console

Even though in Chrome (native V1 & V0) http://jsbin.com/laguvex/11/edit?html,console and V0 polyfill http://jsbin.com/cesutid/3/edit?html,console it was called synchronousy.

So this is inconsistency between spec & implementation, v0 polyfil & v1 polyfil, what makes it more confusing and problematic.

**Comment by TimvdLippe** [comment]
I think this issue would be resolved by https://github.com/webcomponents/custom-elements/pull/62
