### ISSUE TITLE
Firefox issue: global styles affect shadow elements

### ISSUE THREAD

**Issue by DusanMilko** [webcomponents/webcomponentsjs#833]
Example: 
https://jsfiddle.net/bje7p6u3/5/

**Issue 2**
Firefox: all p tags are blue.
Chrome/Safari(expected behavior): p tag in shadow root is not blue

Expecting global styles to not affect shadow root elements.

Is there a fix to these??

**Comment by dalvarezmartinez1** [comment]
yeap noticed the same thing today, css leaks throgh the shadow root when using the polyfills (FF && IE)

**Comment by gijo-varghese** [comment]
is there any fix for this? Me too having the same issue
