### ISSUE TITLE
CustomStyleInterface not available

### ISSUE THREAD

**Issue by oravecz** [webcomponents/webcomponentsjs#834]
When using `webcomponents-lite.js` 1.0.7, I do not have access to `window.ShadyCSS.CustomStyleInterface`. Is this an oversight, or are the docs on how to apply styles out of date?
https://github.com/webcomponents/shadycss#about-customstyleinterface

**Comment by dnlzglr** [comment]
`CustomStyleInterface` is located in [webcomponents/shadycss](https://github.com/webcomponents/shadycss) as a [separate minified js file](https://github.com/webcomponents/shadycss/blob/master/custom-style-interface.min.js).

You might just require `@webcomponents/shadycss` as a depencency in your project and load it using a separate script tag like `<script src="./node_modules/@webcomponents/shadycss/custom-style-interface.min.js"></script>`. After that, you can use it as `window.ShadyCSS.CustomStyleInterface`.
