### ISSUE TITLE
Window load listeners always ignored in Firefox@55.0.2 on win10 64bits, using ver.1.0.9

### ISSUE THREAD

**Issue by dalvarezmartinez1** [webcomponents/webcomponentsjs#836]
So when using when using webcomponents-hi-sd-ce.js the window load event is swallowed by the custom implementation of addEventListener in [patch-events](https://github.com/webcomponents/shadydom/blob/master/src/patch-events.js) line 355:
```
// prevent non-bubbling events from triggering bubbling handlers on shadowroot, but only if not in capture phase
if (e.eventPhase !== Event.CAPTURING_PHASE && !e.bubbles && e.target !== target) {
        return;
}
```
Firefox always triggers the window load event, with e.eventPhase=2, e.bubbles=false and  e.target = document so the listener is always ignored.

This breaks a lot of libraries which make use of the window load event.

Test:
```
<html>
<head>
  <meta charset="UTF-8">
  <script src="custom-elements-es5-adapter.js"></script>
  <script src="webcomponents-hi-sd-ce.js"></script>
  <script>
    window.addEventListener("load", (e) => console.log("window capture"), true);
    window.addEventListener("load", (e) => console.log("window bubble"), false);
  </script>
</head>
</html>
```

if you remove the webcomponents scripts, all works fine

**Comment by TimvdLippe** [comment]
This seems to be working fine in Firefox now: http://jsbin.com/tikenuy/edit?html,console,output

**Comment by TimvdLippe** [comment]
Oh I incorrectly copied your example and forgot to add the proper full URL. This JSBin reproduces this issue properly: http://jsbin.com/tikenuy/edit?html,console,output
