### ISSUE TITLE
regression: Promise.prototype.catch is undefined in IE11 (v1.0.8+)

### ISSUE THREAD

**Issue by vlukashov** [webcomponents/webcomponentsjs#837]
Starting from the version 1.0.8 of the WebComponents polyfill, the ES6 promise polyfill shipped as a part of webcomponents-lite.js does not define the `Promise.prototype.catch` method. For example, the [app-storage](https://www.webcomponents.org/element/PolymerElements/app-storage) web components break the app in IE11 starting with WebComponents polyfill 1.0.8 (1.0.7 is still OK).

Here is a demo app (broken in IE11): https://github.com/vlukashov/polymer-local-storage.

Most likely, the root cause is [closure-compiler/#2640](https://github.com/google/closure-compiler/issues/2640), but for some reason the issue did not surface with the polyfill versions 1.0.7 and before.

**Workaround**
Pin the version of the WebComponents polyfill to 1.0.7 or less.

**Comment by ChadKillingsworth** [comment]
@azakus Looks like you probably need to manually assign the es6-promise Promise object to window.Promise rather than depend on the auto registration.

Alternatively, just remove the `rewrite_polyfills=false` flag for this case and use the Compiler provided promise polyfill.
