### ISSUE TITLE
webcomponents polyfills break Angular change detection

### ISSUE THREAD

**Issue by nightmare6m** [webcomponents/webcomponentsjs#838]
I have a project that uses Angular and Polymer. I am loading webcomponents-lite.js to polyfill older browsers.

When I include the webcomponents-lite or webcomponents-sd-ce, change detection in Angular does not run. If I include webcomponents-hi-ce, change detection runs fine which leads me to believe the issue is in the Shadow DOM polyfill.

This is reproduceable in IE 11, Edge, and FF. Chrome is fine (probably because it doesn't need the polyfill).

I can force change detection with applicationRef.tick(). However, that seems horribly clunky.

**Comment by robdodson** [comment]
Sounds like it could be this https://github.com/angular/zone.js/issues/782

There's a patch for zone.js that needs to be loaded for the web component
polyfills to work with it

**Comment by nightmare6m** [comment]
Thank you Rob, that is absolutely the issue I was running into. Thanks for pointing me in the right direction.

**Comment by robdodson** [comment]
Sure thing, happy I could help out :)
