### ISSUE TITLE
innerHTML fails to parse markup in IE/Edge/Firefox

### ISSUE THREAD

**Issue by brettpostin** [webcomponents/webcomponentsjs#839]
Introducing the webcomponentsjs v1 polyfills changes the behaviour of setting innerHTML in IE/Edge/Firefox. 

Demo [HERE](http://jsbin.com/bakanul/edit?html,output).

When run in Chrome, you will see the table output as expected. However when run in a polyfilled browser, the markup is stripped when setting tbody.innerHTML.

If you comment out the polyfills, IE/Edge/Firefox render the table as expected.

I'm unsure if this is specific to tbody as I haven't testing any other elements. However this breaks a number of existing 3rd party components within our app. For reference, these same elements were fine with the v0 polyfills.

**Comment by varmentano** [comment]
I too am experiencing this issue.  It is preventing me from using this polyfill for GWT with Polymer.

@brettpostin did you find any workaround?

**Comment by brettpostin** [comment]
Unfortunately not. We are using a 3rd party grid component so cannot control the source. Internally it sets innerHTML for the table rows.

I'm just hoping a fix will come along soon.

**Comment by imcdonagh** [comment]
I have the same issue. Is there a fix planned?

**Comment by azakus** [comment]
Removing the Polymer specific bits, this is clearly a ShadyDOM bug: http://jsbin.com/bumuje/edit?html,output

**Comment by azakus** [comment]
This issue was moved to webcomponents/shadydom#192
