### ISSUE TITLE
V1 polyfill template is not inert on IE11

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#840]
I created a somewhat [simple, standalone page](https://jeff17robbins.github.io/V1-Issues/inert_polyfill.html) that forces use of the polyfill via 

```
    <script type="text/javascript">
        if (window.customElements) window.customElements.forcePolyfill = true;
    </script>
    <script src="webcomponents-lite.js"></script>
```

It works as I expected it on Chrome, Firefox, and MS Edge.  

On IE11, the `<template>` polyfill doesn't seem to treat its content as inert.  Or, rather, the various overridden DOM API calls like `.appendChild()` and `.setAttribute()` don't seem to respect that the root of the tree matters, and if it is a template's documentFragment, they shouldn't go ahead and upgrade or run lifecycle callbacks. 

(Interestingly, the V0 polyfill doesn't seem to suffer from this problem on IE11.  I wonder if it is due to the more performant API hooking strategy that V1 takes vs V0's MutationObserver reliance?)

The code that populates the "inert" template is:

```
        var container = document.createElement('template');
        container.innerHTML = '<x-product data-name="Inert"></x-product>';
```

This screenshot illustrates the issue on IE11:  the first caption under the Python logo isn't supposed to get overwritten, and only does because the `.attributeChangedCallback()` of my supposedly inert element fires on IE11, but not on any of the other browsers shown.

![ie11_non_inert_template](https://user-images.githubusercontent.com/2102919/30232640-1ff2ff2e-94bf-11e7-8157-29de3e001fc9.PNG)

**Comment by azakus** [comment]
Yeah, we can't make the Template polyfill behave correctly for inertness. By the time we can bootstrap the template element to move nodes into the inert content, scripts have already executed.

**Comment by Jeff17Robbins** [comment]
But the V0 polyfill works properly on IE11.  I'm confused about why V1 can't behave properly.

**Comment by Jeff17Robbins** [comment]
@azakus , have you seen this issue https://github.com/webcomponents/template/issues/21.  I show how the V0 polyfill works, the V1 polyfill doesn't, because `"shadydom/src/patch-builtins.js` in https://github.com/webcomponents/shadydom breaks IE11 template polyfill".

I don't think the Template polyfill itself is responsible for the problem I am reporting.
