### ISSUE TITLE
V1 polyfill innerHTML broken when used inside constructor, causes infinite recursion crash

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#841]
Using the [V1 polyfill](https://github.com/webcomponents/webcomponentsjs), I created [an ES5 babel transpilation of the `<x-product>` example](https://jeff17robbins.github.io/V1-Issues/inert_polyfill_innerHTML.html) found at [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements).  

The custom element's constructor essentially wraps an `<img>` element.  The salient code is:

```
                var img = document.createElement('img');
                img.alt = _this.getAttribute('data-name');
                img.src = _this.getAttribute('data-img');
                img.width = '150';
                img.height = '150';
                img.className = 'product-img';
                //_this.appendChild(img);  // this works
                _this.innerHTML = img.outerHTML;  // this creates a recursive loop in the polyfill
```

As shown, if instead of appending the `<img>`  I instead assign to `.innerHTML`, the assignment causes a loop back into constructing `<x-product>`.  And so on until stack crash.

This crash reproduces on Chrome, MS Edge, IE11, and Firefox.

I don't understand why the polyfill's `.innerHTML` apparently re-triggers the upgrade process on the element, but if you are encapsulating a 3rd party library and need to construct something in your constructor, obviously you can't control if the 3rd party chooses to use `.innerHTML`.  

Also, [a native version of this same page](https://jeff17robbins.github.io/V1-Issues/inert_native_innerHTML.html) does not crash.

**Comment by Jeff17Robbins** [comment]
In reading the spec ([custom-element-conformance](https://www.w3.org/TR/custom-elements/#custom-element-conformance)), I see that my code wasn't conforming with this rule:

> The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.

I don't know whether or not to close this issue, because the native version of the page doesn't crash.  But obviously this is much less important than I first thought in my ignorance about the constraints placed on the constructor code.

**Comment by justinfagnani** [comment]
I think we should leave the issue open, but only to fix the crash, not to enable innerHTML in the constructor.

And your code differs critically from the MDN example in that you're not using shadow DOM. If you need to wrap a 3rd party library, give it the shadow root to use innerHTML on.

Also, I think you also might have identified a bug in at least Chrome's custom elements implementation. I _think_ that creating children or setting attributes in the constructor is supposed to throw. @dominiccooney would know better.

**Comment by Jeff17Robbins** [comment]
Thanks @justinfagnani.  As I studiy the [spec](https://html.spec.whatwg.org/multipage/custom-elements.htm), I agree that Chrome seemingly ought to have thrown an error due to my code's non-conformance. The lack of an error actually allowed me to persist in my ignorance longer than I would have otherwise!

I know that my code differs from the MDN example.  I changed the example on purpose because we are currently stuck with IE11, and so have avoided the taking journey first with shadow and then with shady DOM polyfills.  Instead, we've contented ourselves with light DOM children on our custom elements.

Until now, I figured that the "fancier" shadow DOM was simply opt-in, and we could get along with light DOM children.  

I'm still hazy on why a custom element is allowed to populated its shadow root with children in its constructor, but not allowed to (more simply?) populate itself with children.  

What is the crucial difference with the two different kinds of children, wrt the constructor?

Also, in the [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance), I read this:

> In general, the constructor should be used to set up initial state and default values, and to set up event listeners and possibly a shadow root.

That led me to believe that a shadow root is optional.  

Yet over [here](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-api) in the spec, there's this seemingly inconsistent bullet:

> 14. Let upgrade candidates be all elements that are **shadow-including descendants** of document, whose namespace is the HTML namespace and whose local name is localName, in shadow-including tree order. Additionally, if extends is non-null, only include elements whose is value is equal to name.

But can't I have a custom element that wants to enjoy many of the benefits of the upgrade, like `.attributeChangedCallback` and the other lifecycle callbacks, without have a shadow root?  And isn't there a chicken and egg problem whereby the UA has to wait until it calls my constructor to find out if, indeed, the element **has** a shadow root?  

So is bullet 14 above perhaps over-specified?

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/custom-elements#161

**Comment by dominiccooney** [comment]
On Mon, Sep 11, 2017, 11:07 AM Jeff17Robbins <notifications@github.com>
wrote:

> Thanks @justinfagnani <https://github.com/justinfagnani>. As I studiy the
> spec <https://html.spec.whatwg.org/multipage/custom-elements.htm>, I
> agree that Chrome seemingly ought to have thrown an error due to my code's
> non-conformance.
>
A lot can depend on the context the constructor is running in. It would be
useful if you could make a minimal repro and outline the critical steps.

The

> lack of an error actually allowed me to persist in my ignorance longer
> than I would have otherwise!
>
> I know that my code differs from the MDN example. I changed the example on
> purpose because we are currently stuck with IE11, and so have avoided the
> taking journey first with shadow and then with shady DOM polyfills.
> Instead, we've contented ourselves with light DOM children on our custom
> elements.
>
> Until now, I figured that the "fancier" shadow DOM was simply opt-in, and
> we could get along with light DOM children.
>
> I'm still hazy on why a custom element is allowed to populated its shadow
> root with children in its constructor, but not allowed to (more simply?)
> populate itself with children.
>
This too depends on the calling context.

In general the practice is discouraged, and sometimes an outright error,
because no built in elements do this and we wanted to preserve parser
setting children for authors writing markup.

> What is the crucial difference with the two different kinds of children,
> wrt the constructor?
>
> Also, in the spec
> <https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance>,
> I read this:
>
> In general, the constructor should be used to set up initial state and
> default values, and to set up event listeners and possibly a shadow root.
>
> That led me to believe that a shadow root is optional.
>
ShadowRoot is optional.

> Yet over here
> <https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-api>
> in the spec, there's this seemingly inconsistent bullet:
>
>
>    1. Let upgrade candidates be all elements that are *shadow-including
>    descendants* of document, whose namespace is the HTML namespace and
>    whose local name is localName, in shadow-including tree order.
>    Additionally, if extends is non-null, only include elements whose is value
>    is equal to name.
>
> This is unrelated. It just means that elements in Shadow DOM are upgraded.

>
>
> But can't I have a custom element that wants to enjoy many of the benefits
> of the upgrade, like .attributeChangedCallback and the other lifecycle
> callbacks, without have a shadow root?
>
You can.

> And isn't there a chicken and egg problem whereby the UA has to wait until
> it calls my constructor to find out if, indeed, the element *has* a
> shadow root?
>
No. I don't follow where you think the inconsistency is. The system might
be recursive but that is all.

> So is bullet 14 above perhaps over-specified?
>
In what way?
