### ISSUE TITLE
Promise polyfill issues

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/webcomponentsjs#843]
webcomponents-lite.js apparently contains this [Promise polyfill](https://github.com/stefanpenner/es6-promise/blob/master/dist/es6-promise.js).

There are 2 issues with this part of the code:

original src:
```
    var P = local.Promise;

    if (P) {
        var promiseToString = null;
        try {
            promiseToString = Object.prototype.toString.call(P.resolve());
        } catch (e) {
            // silently ignored
        }

        if (promiseToString === '[object Promise]' && !P.cast) {
            return;
        }
    }

    local.Promise = Promise$2;
```

(as shipped in webcomponents-lite.js)
```
            var b = a.Promise;
            if (b) {
                var c = null;
                try {
                    c = Object.prototype.toString.call(b.resolve())
                } catch (d) {}
                if ("[object Promise]" === c && !b.Eb) return
            }
            a.Promise = y
```

Notice what happened to the check for deprecated, legacy `Promise.cast` in the src.  It became a check for an obfuscated `.Eb` which, obviously, changed the semantics of that check.  

This seems to be a failure on the part of the tool used to obfuscate.  That's issue 1.

Issue 2 is that the check for `[object Promise]`.   At first glance, that seems logical.  Let's check if the branded Promise is available.  But...suppose I have **already** polyfilled Promise with my own library that I like better than ES6-Promise?  How can my library pass muster on an older browser like IE11, since I don't see how it can control what `Object.prototype.toString.call()` will return. There's no `[Symbol.toStringTag]` on older browsers, for example.

Summary:  the check `if ("[object Promise]" === c && !b.Eb) return`  by the ES6-Promise polyfill is broken by the obfuscator, and clobbers any preferred Promise polyfill by its overly stringent check for built-in Promise only.

**Comment by azakus** [comment]
This is probably also fixed with https://github.com/webcomponents/webcomponentsjs/pull/844, by making the only check `if (!window.Promise) {}`

**Comment by Jeff17Robbins** [comment]
Yes, that fixed it.  The window.Promise test is much less stringent than
Object.prototype.toString.call(Promise.resolve()) === '[object Promise]',
thanks!

**Comment by Jeff17Robbins** [comment]
The closure compiler would seem to be a bit dangerous if the module isn't written to know about it.  [es6-promise](https://github.com/stefanpenner/es6-promise) checks for `Promise.cast`.  The closure compiler strategy of renaming `.cast` to `.Eb` would be fine if that property were defined also by user code subject to the closure compiler.  But the es6-promise test was trying to test for a property on a browser-native Promise.  

If the author knew about the closure compiler, presumably he or she could code around this "ADVANCED_OPTIMIZATIONS" compilation option.  

https://developers.google.com/closure/compiler/docs/compilation_levels
> To enable this extreme compression, ADVANCED_OPTIMIZATIONS makes strong assumptions about the compiled code. If your code does not conform to those assumptions, ADVANCED_OPTIMIZATIONS will produce code that does not run.

>For example, code compiled with ADVANCED_OPTIMIZATIONS may not work with uncompiled code unless you take special steps to ensure interoperability. If you do not flag external functions and properties referenced in your code, Closure Compiler will inappropriately rename references in your code, causing mismatches between the names in your code and in the external code.

Presumably the author of es6-promise didn't know that his/her library was going to be subject to these ADVANCED_OPTIMIZATIONS?  But `gulpfile.js`  has this in it:

```
  const closureOptions = {
    new_type_inf: true,
    compilation_level: 'ADVANCED',
   ...
```

I think it is not a good idea to pull different modules into `webcomponents-lite.js` if they weren't written to be safe wrt the closure compiler.  The current fix of making a less stringent test is good for other reasons, but the question remains as to what other problems might be lurking.

**Comment by TimvdLippe** [comment]
Closing this per https://github.com/webcomponents/webcomponentsjs/issues/843#issuecomment-328700745 We will remain using the Closure compiler for now.
