### ISSUE TITLE
webcomponents-hi-sd-ce-pf-index.js missing from repo

### ISSUE THREAD

**Issue by mrdevin** [webcomponents/webcomponentsjs#847]
so i am using the `webcomponents-lite.js` and it generates a script tag with `webcomponents-hi-sd-ce-pf-index.js` which doesn't exist in the repo

**Comment by mrdevin** [comment]
my error was coming from a .map file

**Comment by tleite** [comment]
@mrdevin I had the same issue... is there an issue with the map file?
