### ISSUE TITLE
Unable to create customElement

### ISSUE THREAD

**Issue by florianajir** [webcomponents/webcomponentsjs#849]
I followed [this doc](https://webdesign.tutsplus.com/tutorials/how-to-create-a-web-component-for-embedding-youtube-videos--cms-26744) to create a custom HTML element.

Without surprise not working natively with other browser than chrome.

So I tried to use your lib (importing the loader file) to make it working on firefox but got error on initialization.

I made it working with an [other lib from npm](https://www.npmjs.com/package/webcomponentsjs) ([github](https://github.com/dlmma/webcomponentsjs) not maintained since 2 years) but with this lib I need to use the heavy full version, and it's causing conflicts when using jquery.animate function.

Can you help me debugging using your lib please ?

**Comment by robdodson** [comment]
The tutorial you referenced is using the old Custom Elements v0 syntax that only ever shipped in Chrome. Give it a shot with the updated v1 syntax, currently shipping in both Chrome and Safari https://developers.google.com/web/fundamentals/architecture/building-components/customelements

**Comment by florianajir** [comment]
yes! thank you for the explanation, I close the issue :)
