### ISSUE TITLE
webcomponents-lite.js.map missing 

### ISSUE THREAD

**Issue by paladox** [webcomponents/webcomponentsjs#850]
Hi, when i build gerrit with webcomponentsjs 1.0.13 it is showing that this file is missing 

bower_components/webcomponentsjs/webcomponents-lite.js works but this
bower_components/webcomponentsjs/webcomponents-lite.js.map dosen't.

Could this be fixed please?

**Comment by paladox** [comment]
Oh it shows it is empty here

https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-lite.js.map

**Comment by valdrinkoshi** [comment]
Fixed in 1.0.14
