### ISSUE TITLE
Disable htmlimport polyfill

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/webcomponentsjs#852]
Hey,

if I am not mistaken no browser engine apart from blink has included html imports and they probably won't ever. For this reason I am not using them at all in my components. However, using the polyfill html imports are always polyfilled, e.g. in recent safari.

Is there a way to disable this, or could there be some kind of config added, so that html imports are not polyfilled? Otherwise it adds an unnecessary resources and speed penalty even though the browser supports all needed features.

Thanks.

**Comment by azakus** [comment]
For version 1.x of Webcomponents, you could decide which polyfill bundle your app needs and use it directly. `webcomponents-sd-ce.js` will give you the ShadyDOM, ShadyCSS, and CustomElements polyfills, which will probably be all you need.

For the upcoming 2.x of Webcomponents, I'm already working on a branch to remove the HTML Imports polyfill: https://github.com/webcomponents/webcomponentsjs/tree/no-html-imports

**Comment by lukasoppermann** [comment]
Hey @azakus, thanks I looked through the issues but not through the branches. 😬 Awesome, thanks for letting me know.
