### ISSUE TITLE
Error in Firefox: TypeError: c is null

### ISSUE THREAD

**Issue by jogibear9988** [webcomponents/webcomponentsjs#854]
<img width="1452" alt="bildschirmfoto 2017-09-29 um 22 35 59" src="https://user-images.githubusercontent.com/364896/31035025-c1c700e0-a566-11e7-93bc-753124708430.png">

**Comment by valdrinkoshi** [comment]
Can you provide steps to reproduce?

**Comment by jogibear9988** [comment]
when the map file is loaded the error seems to be in line:

https://github.com/webcomponents/shadydom/blob/4c0ef0fd3ef65538d9859412151d6558f140ab6d/src/patch-events.js#L304

**Comment by valdrinkoshi** [comment]
Uhm, so is a shadydom issue. Mind filing the issue in the [shadydom repository](https://github.com/webcomponents/shadydom/) with steps on how to reproduce?

**Comment by jogibear9988** [comment]
with this plunker you can reproduce https://plnkr.co/edit/mggcVPrlbtNZ0PNgtyq6

**Comment by jogibear9988** [comment]
Is anyone working on shady-dom?

**Comment by jogibear9988** [comment]
https://github.com/webcomponents/shadydom/pull/187
