### ISSUE TITLE
Accessing `event.target` on custom element throws TypeError (w/ test case)

### ISSUE THREAD

**Issue by HenrikJoreteg** [webcomponents/webcomponentsjs#857]
Hi! :)

I'm trying to write a simple web component that can make an list of elements sortable and ran into an issue that only appears when polyfilled.

Here's a test case: http://sortable-component.surge.sh
Here's the repo (though you can just as easily view source): https://github.com/HenrikJoreteg/sortable-component

Even trying to read `e.target` [here](https://github.com/HenrikJoreteg/sortable-component/blob/master/sortable-list.js#L101) when dragging a child element throws a `TypeError: a is null` error in FF but works in Safari/Chrome.

This feels like a bug since it works when not polyfilled. Thanks for you work on these awesome polyfills ❤️

**Comment by valdrinkoshi** [comment]
This does look like an issue of shadydom http://jsbin.com/fewosow/1/edit?html,console,output

@HenrikJoreteg in your example you read the EventTarget after a timeout of 300ms for the `mousedown` event. You can fix the issue by storing `e.target` into a variable synchronously instead of inside the timeout:
```js
    _onStart (e) {
      this._down = true
      this.startX = this._getPagePosition(e, 'x')
      this.startY = this._getPagePosition(e, 'y')
      const target = e.target;
      if (this._timer) clearTimeout(this._timer)
      this._timer = setTimeout(() => {
        console.log(target);
```

**Comment by HenrikJoreteg** [comment]
@valdrinkoshi well, now I feel silly that I didn't think to try that :) Anyway, thanks. Should I file a bug somewhere else or what would you suggest?

**Comment by valdrinkoshi** [comment]
I'll move this issue to the shadydom repo 👌
