### ISSUE TITLE
Latest published v1 spec 

### ISSUE THREAD

**Issue by equinusocio** [webcomponents/webcomponentsjs#866]
The readme point to the editor's draft spec. Should it point to the latest published version?
https://www.w3.org/TR/custom-elements/

**Comment by snuggs** [comment]
This is correct @equinusocio. Nice catch!

#ping @ebidel

**Comment by snuggs** [comment]
@equinusocio correction that was in https://github.com/webcomponents/webcomponentsjs/commit/da466620070b314edf83bda64556b148c7d70d4e

My bad Eric 🙏

**Comment by TimvdLippe** [comment]
The README no longer includes this link, so this issue has been resolved.

**Comment by snuggs** [comment]
Copy that @TimvdLippe. Thanks for the cleanup job! 🙏
