### ISSUE TITLE
Timing issue with wecomponents-loader.js firing event before listeners are ready

### ISSUE THREAD

**Issue by jasmith79** [webcomponents/webcomponentsjs#868]
Trying to do a very simple test element with the polyfill loader.

Markup

```html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, minimum-scale=1.0">
</head>
<body>
  <script type="module" src="./test.js"></script>
  <script src="./node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
  <foo-bar data-entry="yuckyuck">
    <span>Yo </span>Whatever
  </foo-bar>
 </body>
</html>
```

JavaScript in `test.js`

```javascript
class FooBar extends HTMLElement {
  constructor () {
    console.log("constructing");
    super();
  }

  connectedCallback () {
    console.log("connecting");
  }

  disconnectedCallback () {
    console.log("disconnecting");
  }
};

window.addEventListener('WebComponentsReady', e => {
  console.log("Ready to componentize");
  customElements.define('foo-bar', FooBar);
});
```

If I use the loader as provided I *always* miss the event on chrome 62 (I realize I don't actually *need* the polyfill for chrome). If I replace the rAF with `setTimeout` of 0 I'm 90% hit in chrome but about roughly 1/10 reloads the event fires too soon and I miss it. Upping the `setTimeout` to 100ms makes my script catch the event 100% of the time but is undesirable from a performance standpoint. I have no trouble catching the event in Firefox (as it's being fired by the loaded polyfill script instead of the loader itself).

If I set both scripts to `async defer` I seem to catch the event in chrome every time without fail, but if that is *required* for using this polyfill the docs should mention that fact (even if it is best practice).

**Comment by TimvdLippe** [comment]
Note that module scripts are always deferring (https://jakearchibald.com/2017/es-modules-in-browsers/#defer-by-default) which means you have to enforce the timing between the two. However, that is an ES modules issue and not an issue with the loader. You can defer both scripts to make sure the scripts execute as you expect.
