### ISSUE TITLE
Polyfills without HTML Import

### ISSUE THREAD

**Issue by CITguy** [webcomponents/webcomponentsjs#870]
I'm not using HTML imports in my custom element library (I build a single JS asset for my custom elements). However, I have no way of excluding the HTML Import polyfill from the loader.

What should I do to get a custom build to exclude HTML import polyfills?

**Comment by web-padawan** [comment]
Consider using `webcomponents-sd-ce.js` bundle. It only loads Custom Elements polyfill and shady DOM shim, as you can see [here](https://github.com/webcomponents/webcomponentsjs/blob/master/entrypoints/webcomponents-sd-ce-index.js).

**Comment by CITguy** [comment]
Thanks, I'll see if that does what I'm expecting.

**Comment by CITguy** [comment]
@web-padawan: Sadly, `webcomponents-sd-ce.js` doesn't include the `<template>` polyfill for IE support.

**Comment by dgt41** [comment]
@CITguy did you found a way around this? I'm facing the same problem as well

**Comment by CITguy** [comment]
@dgt41: It's not optimal, but I built my own loader to exclude the polyfills I know I don't need.

**Comment by web-padawan** [comment]
Should be adressed by #907

**Comment by CITguy** [comment]
Closing. I think #907 with the 2.0.0 release I've got what I need.
