### ISSUE TITLE
Does the ShadowDOM polyfill work without Custom Elements polyfill?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/webcomponentsjs#874]
I see that there's no SD-only build option. Does SD work without the CE polyfill?

For example, if I use the document-register-element CE polyfill, will the SD polyfill here work with it? Why isn't there an SD-only build option? I don't see any build that have SD without CE, so I thought there might be a reason for that.

**Comment by tomalec** [comment]
I could only say from my personal experience with attempts to use https://github.com/WebReflection/document-register-element (as it contains V1 customized build-ins) with WC.js (Shadow DOM) polyfill and it was colliding in some cases in Safari.
Colliding so badly, despite the number of side bugs I've found, managed to report and workaround, I gave up eventually.

**Comment by web-padawan** [comment]
BTW, it seems that FIrefox will implement CE before SD:
- [Intent to implement Custom Elements](https://groups.google.com/forum/#!msg/mozilla.dev.platform/BI3I0U7TDw0/6-W39tXpBAAJ) targets Firefox 59 nightly
- [Intent to implement Shadow DOM](https://groups.google.com/forum/#!msg/mozilla.dev.platform/aJvUlADn-Hk/BYB52MgDBQAJ) targets Firefox 60 nightly

**Comment by justinfagnani** [comment]
@web-padawan we haven't seen that combination in the wild yet, so we'll almost definitely have to do work to support it.

**Comment by web-padawan** [comment]
@justinfagnani FYI: the CE are now shipped in [Firefox Nightly](https://twitter.com/FirefoxNightly/status/951009715584225280) as it was previously announced.

**Comment by justinfagnani** [comment]
cc @azakus

**Comment by trusktr** [comment]
A standalone SD polyfill that I can use with document-register-element would be awesome!

The reason that I asked about this is because it is easy to make a build process that outputs a single file that works in older and modern browser with CE v1.

With `custom-elements-es5-adapter.js`, it is much more difficult to produce a single-file build that works in all browsers because

1. We have to _not_ transpile the adapter code
  - this is difficult because other stuff in the file _does_ need to be transpiled
2. If we include the adapter in a the single-file and run it in an older browser, the older browser has a fit about the syntax
  - We can wrap the code in an `eval`, but this is tricky, and is even more painful if the transpiler is set to transpile other `eval` code.

Basically, trying to compile my library into a single file that can be used in all supported browsers has been just a pain, and it has been by far easier to produce a single-file build using `document-register-element`.

However, `document-register-element` does not have ShadowDOM. It'd be really really great to make the adapter more easy to work with in single-file builds because then I could also use your the CE polyfill along with SD and be done with it.

At the moment, I cannot support browsers that don't have native ShadowDOM because document-register-element doesn't have it, and I haven't found any polyfill that I can just drop in, and the only one I see is the one here.

My original question was (after fixing some typos just now): does SD work by itself at all? Or does it rely on implementation details of the CE polyfill?

**Comment by trusktr** [comment]
Or, maybe I missed how to do it. Do one of you guys have an example of a single-file build that works in both old browsers and new browsers with `class`?

**Comment by azakus** [comment]
Given that Firefox Nightly will be shipping Custom Elements before ShadowDOM, I've update the `no-html-imports` branch to include a ShadyDOM-only bundle.

Tests still need to be configured for this bundle.

**Comment by trusktr** [comment]
I've discovered something interesting:

- I'm compiling my classes to ES5 classes.
- I'm not using the native-shim.
- But my transpiled classes (passed to native `customElements.define`) _are still working_ in modern browsers because I'm using `babel-plugin-transform-builtin-classes`

Let me see if this will work with the SD an CE polyfills...

**Comment by trusktr** [comment]
And....... it works!! Pen:

https://codepen.io/anon/pen/rpvqBV

If you try that in Edge, you'll see green buttons laid out on the screen. The layout is calculated by the custom elements (ignore any errors in the console, those are unrelated).

Without the polyfill, the buttons would be laid out in the middle of the screen.

This shows that the polyfill works using `babel-plugin-transform-builtin-classes`, so library authors can use that rather than requiring the end users to use native-shim.js (and rather than library authors having to painstakingly figure out how to bundle the native-shim).


**_Cool!!!!!!_**

This issue is no longer relevant for me because I no longer need a standalone SD polyfill (if I were to use keep using document-register-element).

**Comment by trusktr** [comment]
I meant

> Without the SD and CE polyfill, the buttons would **not** be laid out in the middle of the screen.

**Comment by dgt41** [comment]
> I've update the no-html-imports branch

@azakus is this branch safe for production?

I want to use it in the Joomla 4 as we don't have a need for Html Imports there:
https://github.com/joomla/joomla-cms/blob/54f2ed05049767880555e990f5bead4c03254193/package.json#L21

**Comment by TimvdLippe** [comment]
This has shipped with https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-hi-sd.js A loader removing HTML imports is being worked on in #907

**Comment by tomalec** [comment]
@TimvdLippe does it mean we can finally make Shadow DOM work without custom element? Like attach shadow root for a single instance of native element (`div`) and make ShadyCSS polyfill work there?

**Comment by TimvdLippe** [comment]
@tomalec That is a good question! That feature is on the roadmap for ShadyCSS v2 (https://github.com/webcomponents/shadycss/issues/134). I suspect @azakus will soon devote time to that refactoring, while also investigating `::part` and `::theme` support

**Comment by tomalec** [comment]
Thanks! you cannot imagine how much I'm looking forward both :)
