### ISSUE TITLE
Using webcomponentsjs with Angular 4?

### ISSUE THREAD

**Issue by sneurlax** [webcomponents/webcomponentsjs#877]
Hi!  I apologize that this isn't strictly an issue with webcomponentsjs, strictly speaking, but I'm curious if anyone else has achieved this nonetheless:

I'm trying to use native view encapsulation in Angular4 for Firefox and was instructed to install webcomponentsjs using `npm install @webcomponents/webcomponentsjs` and then to include `import '@webcomponents/webcomponentsjs/webcomponents-sd-ce.js';` in my polyfills.ts ... this is apparently incomplete advice as it didn't solve my issue.

I am of course importing ViewEncapsulation from @angular/core and setting ViewEncapsulation.Native in the component I'd like to encapsulate.

Any help is much appreciated!  Thank you for reading and sorry again that this isn't an issue with webcomponentsjs itself, strictly speaking.

**Comment by mnemanja** [comment]
Hi @sneurlax, 
have you found a solution to your problem? If so, could you share it here please?
Thanks!

**Comment by sneurlax** [comment]
I got encapsulation to work, yes, but I've moved on from this completely... what do you need help with?  I'm closing the issue but just @sneurlax me.

`polyfills.ts`:
```
/***************************************************************************************************
 * WebComponent JS required for native view encapsulation.
 */
import '@webcomponents/webcomponentsjs/webcomponents-sd-ce.js';



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

In component to use encapsulation,

```
...
import { Component, ViewEncapsulation } from '@angular/core';
...
@Component({
  ...
  encapsulation: ViewEncapsulation.Native,
  ...
})
export class WhateverComponent {
```

**Comment by RezaRahmati** [comment]
I have same issue in angular 6 (and I tried with angular 7), I added the webcomponents to polyfill, and still having the issue

[https://stackblitz.com/edit/angular-webcomponent-polyfill](https://stackblitz.com/edit/angular-webcomponent-polyfill)

**Comment by AndreyBespamyatnov** [comment]
> I have same issue in angular 6 (and I tried with angular 7), I added the webcomponents to polyfill, and still having the issue
> 
> https://stackblitz.com/edit/angular-webcomponent-polyfill

Have you solved it? cause i have the same issue

**Comment by RezaRahmati** [comment]
> > I have same issue in angular 6 (and I tried with angular 7), I added the webcomponents to polyfill, and still having the issue
> > https://stackblitz.com/edit/angular-webcomponent-polyfill
> 
> Have you solved it? cause i have the same issue

Yes, use 
`import '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce';`
