### ISSUE TITLE
Set is not defined on old Chrome 37.

### ISSUE THREAD

**Issue by fanthos** [webcomponents/webcomponentsjs#879]
I am trying to use the polyfill for Chrome 37(lots of third party browsers for Android based on this old version). I got `ReferenceError: Set is not defined` when loading the page. After search through the source code, I can't find usage of `Set`, so it seems the code compiler used Set to minify the code. After polyfill the page with `es6-shim` it mostly work as excepted.
Is this the excepted or should be fixed?

**Comment by jasmith79** [comment]
This has nothing to do with WebComponents. You'll need to load core-js (or possibly a more minimal polyfill).

**Comment by TimvdLippe** [comment]
We do not support Chrome 37, so if you need to support this browser please load the `Set` polyfill yourself.
