### ISSUE TITLE
Add @nocompile to custom-elements-es5-adapter.js

### ISSUE THREAD

**Issue by rictic** [webcomponents/webcomponentsjs#884]
This will tell closure compiler not to touch the file, including not to translate it from es6 to es5.

**Comment by trusktr** [comment]
@rictic There's other things in the file, like `const` statements, that need to be transpiled if you happen to have this in a single build output file that you run in old and new browsers.

How are you using the adapter?

**Comment by justinfagnani** [comment]
The adapter is only for browsers with native ES6 and native Custom Elements. It can not be compiled and still function. It should not be bundled with a compiled app.

**Comment by trusktr** [comment]
I know. But some people want to make a single bundle and run it in all browsers.

Anyways, this is possible using Babel transform-builtin-classes instead of the native-shim adapter. So far I've gotten it to work everywhere except IE11 (errors from ShadyDOM and custom-elements).
