### ISSUE TITLE
Gulp build fails

### ISSUE THREAD

**Issue by flagollet** [webcomponents/webcomponentsjs#887]
Forked and cloned the repo, followed build instruction (`npm install` and `bower install`) but then gulp fails: 

```
node_modules/es6-promise/lib/es6-promise/enumerator.js:28: ERROR - Variable validationError$$module$node_modules$es6_promise$lib$es6_promise$enumerator declared more than once. First occurrence: node_modules/es6-promise/lib/es6-promise/enumerator.js
function validationError() {
         ^^^^^^^^^^^^^^^

1 error(s), 1 warning(s)

(node:83304) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'gulp-google-closure-compiler'
Message:
    Compilation error
``` 

I also get many warnings.

Any idea what's going on?

FYI: `npm version` gives 
```
{ 
 '@webcomponents/webcomponentsjs': '1.0.22',
  npm: '4.1.2',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.0',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.93',
  zlib: '1.2.8' 
}
```

**Comment by FrancoisBeaune** [comment]
I'm working with @flagollet.

Just wanted to add that the error occurs during the minification of the `hi-sd-ce-pf variant`, i.e. during the `closurify-hi-sd-ce-pf` gulp task.

Side questions: What does `pf` stands for? Random guess: Polyfill? What's the difference between `hi-sd-ce` and `hi-sd-ce-pf`?

**Comment by TimvdLippe** [comment]
I am unable to reproduce this. We also switched away from es6-promise, so this issue should no longer occur.

> Side questions: What does pf stands for? Random guess: Polyfill? What's the difference between hi-sd-ce and hi-sd-ce-pf?

That bundle includes more polyfills, including `Symbol` and `Promise`. It is necessary for browsers like IE11.
