### ISSUE TITLE
browser extension breaks when we add webcomponents-lite.js for ShadowDom support

### ISSUE THREAD

**Issue by basherr** [webcomponents/webcomponentsjs#890]
When we add the `webcomponents-sd-ce` to support `ShadowDom` the extension just breaks and doesn't run other scripts. When remove the `webcomponents-lite` from the `JS` list then the `contentscript` does seems to log to the console otherwise it doesn't out put anything.
```
"js": [
        "scripts/webcomponents-sd-ce.js",
        "scripts/contentscript.js"
      ],
```
we are working with `react` app
```
import ShadowDOM from 'react-shadow';

<ShadowDOM include={ browser.extension.getURL('/styles/main.css') }>
            <div>
              {this.currentPanel()}
            </div>
</ShadowDOM>
```
Firefox: 58.0 (32-bit)

**Comment by TimvdLippe** [comment]
Which browser extension is breaking the website? I suspect LastPass; we have a fix in the works for that.

**Comment by basherr** [comment]
The browser extension isn't breaking the website but extension it self breaks. It's our custom extension.

**Comment by basherr** [comment]
We've tried changing `dom.webcomponents.enabled` to `true` in `about:config` section which seems to be fixed but as always it isn't solution to the problem. Could there anything I'm missing with `firefox 58.0`?

**Comment by basherr** [comment]
My apologise as it works with `webcomponents-hi-sd.js`
