### ISSUE TITLE
In strict content security policy this line will fail because of the restriction.

### ISSUE THREAD

**Issue by sz332** [webcomponents/webcomponentsjs#892]
https://github.com/webcomponents/webcomponentsjs/blob/0d285e7df994f99341e45bf2b603a1fdb485baae/src/HTMLImports/parser.js#L307

If there exists a strict content security policy which is not changeable by the user it will prevent the browser to load the javascript. Suggested solution: make it configurable to use script.textContent or any similar solution. A long and detailed description of the problem is available on the following link:

[https://stackoverflow.com/questions/42017052/content-security-policy-webcomponent-script-src-datauri-can-i-override-http-h](url)

**Comment by TimvdLippe** [comment]
We have removed this part in the latest version of the polyfill, so this should no longer be an issue :tada:
