### ISSUE TITLE
Offer a shadow DOM only polyfill

### ISSUE THREAD

**Issue by AndreasGalster** [webcomponents/webcomponentsjs#899]
Firefox is about to ship CE soon, shadow DOM looks like it's at least another 2 months away, maybe even longer. Any chance we can get a shadow DOM only polyfill?

**Comment by TimvdLippe** [comment]
Yes! We have shipped this with https://github.com/webcomponents/webcomponentsjs/blob/master/bundles/webcomponents-sd.js
