### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by adeptues** [webcomponents/webcomponentsjs#900]
What exactly do i need to do to enable ie11 support for webcomponents via the poly fills listed on https://www.webcomponents.org/polyfills/

as adding the following polyfils dont seem to work 
```html
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.1.0/custom-elements-es5-adapter.js" integrity="sha256-/qu9HOoKyajv609iMcx0pqazJeqcpDsBwrBzA5IcPMc=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.1.0/webcomponents-lite.js" integrity="sha256-oN2JNfdNjF2gsa0aRXIgxyAFBQ3JXp2uCWbb76YVw20=" crossorigin="anonymous"></script>
```

in fact they all produce exceptions when loaded on ie11. My code is compiled down from typescript into es5 too

specifically these exceptions are

```
no such interface supported 
File: webcomponents-lite.js, Line: 135, Column: 359
```
and theres an exception with the custom elements es5 pollyfill but further reading seems to state that this can only be used with browsers that support es6 lol

**Comment by justinfagnani** [comment]
The es5 adapter is only needed in browsers with native custom elements. Even though it causes errors on syntax IE11, they're fine to ignore. If you don't want the errors, you'll have to only the script on IE11.

I haven't seen the other error before, do you have a full stack trace?

**Comment by iconexperience** [comment]
When using a simple import on IE11, this error is thrown:

`Object doesn't support this action`

This occurs in <a href="https://github.com/webcomponents/webcomponentsjs/blob/master/src/post-polyfill.js#L61">post-polyfill.js line 61</a>, because `dispatchEvent` does not work as expected in IE11. See <a href="https://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11">this stackoverflow question</a> for details.

In general it seems that IE11/10 for webcomponents is claimed, but not really tested.

**Comment by adeptues** [comment]
So what polyfill should be used to provide customelements on IE11 if the es5 adapter is only for browsers with it already implemented?

**Comment by adeptues** [comment]
Thanks for the clarification. So i add 
```html
 <script src="./node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js"></script>
```
then load my component via
```javascript
window.addEventListener("WebComponentsReady", () => {
    customElements.define("cda-viewer", CDAViewer);
});
```

which produces the following stacktrace in ie11

```"TypeError: Unable to get property 'Ca' of undefined or null reference\n   at cg (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:195:186)\n   at Anonymous function (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:23:304)\n   at d (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:23:69)\n   at Anonymous function (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:23:284)\n   at b (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:23:200)\n   at e (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:23:253)\n   at f (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:23:271)\n   at Anonymous function (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:195:317)\n   at ba (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:123:397)\n   at n.define (http://192.168.100.30:8000/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi-sd-ce.js:122:20)"```

**Comment by CITguy** [comment]
As of `@webcomponents/webcomponents` versions `v1.2.4` and `v2.0.4`, you should be able to do the following:

```html
<head>
  <!-- ... -->
  <link rel="stylesheet" href="path/to/application-styles.css" />

  <script src="path/to/node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>
  <script src="path/to/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
  <!-- polyfills for the current browser get injected here (if needed) -->
</head>
<body>
  <!-- ... -->

  <script src="path/to/application-logic.js"></script>
</body>
```

The adapter (`custom-elements-es5-adapter.js`) doesn't have to be loaded in the `<head>`, but you do need to make sure it's loaded _BEFORE_ any custom elements are loaded.

**Comment by TimvdLippe** [comment]
Closing this issue as both @justinfagnani and @CITguy are spot on. If you require more information, please see https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs
