### ISSUE TITLE
TypeError: observerHandle is null in Firefox

### ISSUE THREAD

**Issue by TrebuhD** [webcomponents/webcomponentsjs#901]
## Description of problem
On firefox (v58.02), I get the following error after I destroy one particular element (when navigating to a different route):

TypeError: observerHandle is null

The element in question contains a list of elements, each of them using `paper-dropdown-menu`. When I delete the `paper-dropdown-menu`, everything works well. If I include `paper-dropdown-menu`, even one without any content, it throws this error.

The error is particularly bad, because after it occurs, half of the website refuses to work.

I _suspect_ this is a **polyfill issue** because it only occurs on Firefox (and because of the stack trace below), but I haven't been able to find the root cause.

I'm using webcomponents-lite.js.

## Live example
Go to [this page](https://next.suttacentral.net/dn1), click the downwards facing arrow on the bottom right and then click the green "Pali" button on the left of the element that opened up. The error will occur.

[Here's the code](https://github.com/suttacentral/next-sc/blob/development/client/elements/suttaplex/sc-parallel-item.html) for the item containing the dropdown (sc-language-menu on line 200).

It seems like the error is actually coming from iron-overlay-behavior.html specifically.
Here's the stack from when I pause the firefox debugger when the error occurs:

`
unobserveNodes@http://localhost/bower_components/polymer/lib/legacy/polymer.dom.html.js:59:7
detached@http://localhost/bower_components/iron-overlay-behavior/iron-overlay-behavior.html.js:196:7
detached@http://localhost/bower_components/polymer/lib/legacy/class.html.js:242:11
detached@http://localhost/bower_components/polymer/lib/legacy/class.html.js:240:9
detached@http://localhost/bower_components/polymer/lib/legacy/class.html.js:240:9
detached@http://localhost/bower_components/polymer/lib/legacy/class.html.js:240:9
disconnectedCallback@http://localhost/bower_components/polymer/lib/legacy/legacy-element-mixin.html.js:106:9
Fd.prototype.disconnectedCallback@http://localhost/bower_components/webcomponentsjs/webcomponents-lite.js:136:317
O@http://localhost/bower_components/webcomponentsjs/webcomponents-lite.js:132:114
we/<@http://localhost/bower_components/webcomponentsjs/webcomponents-lite.js:147:366
__detachInstance@http://localhost/bower_components/polymer/lib/elements/dom-repeat.html.js:576:9
disconnectedCallback@http://localhost/bower_components/polymer/lib/elements/dom-repeat.html.js:300:9
Fd.prototype.disconnectedCallback@http://localhost/bower_components/webcomponentsjs/webcomponents-lite.js:136:317
O@http://localhost/bower_components/webcomponentsjs/webcomponents-lite.js:132:114
we/<@http://localhost/bower_components/webcomponentsjs/webcomponents-lite.js:148:95
__teardownInstance@http://localhost/bower_components/polymer/lib/elements/dom-if.html.js:243:13
__render@http://localhost/bower_components/polymer/lib/elements/dom-if.html.js:147:9
__debounceRender/this.__renderDebouncer<@http://localhost/bower_components/polymer/lib/elements/dom-if.html.js:102:114
setConfig/this._timer<@http://localhost/bower_components/polymer/lib/utils/debounce.html.js:30:9
microtaskFlush@http://localhost/bower_components/polymer/lib/utils/async.html.js:21:11`

**Comment by TimvdLippe** [comment]
Thanks for the issue. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
