### ISSUE TITLE
slotchange event in firefox

### ISSUE THREAD

**Issue by nika-begiashvili** [webcomponents/webcomponentsjs#902]
currently firefox doesn't fire slotchange event, I think this can be polyfilled using MutationObserver

**Comment by TimvdLippe** [comment]
Thanks for the issue.  The slotchange event is implemented, see https://github.com/webcomponents/shadydom/blob/8dadb6f152758c0a1ceeaabd83d86a04c78d13a8/src/attach-shadow.js#L168 Please open a new issue with a jsbin showing the issue such that we can debug the problem.
