### ISSUE TITLE
No Css encapsulation in IExplorer/Edge

### ISSUE THREAD

**Issue by ndesorden** [webcomponents/webcomponentsjs#904]
Is there any way to have css encapsulation in IExplorer  or at least in Edge?
I have a webcomponent using polymer2 and webcomponents polyfills

index.html
```  
<head>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="./components/my-component.html">
  <style>
     h1 {
      color: red;
      text-align: right;
   }
</style>
</head>
<body>
...
  <my-component></my-component>
...
</body>
```

my-component.html

```
<dom-module id="my-component">
<template>
<style>
   h1 {
      color: blue;
      text-align: left;
  }
</style>
     <h1>Bla, bla, bla</h1>
```

In Firefox/Chrome H1 has color blue and align left, but in IE is red and align right....

How can i fix it?

Thanks

**Comment by TimvdLippe** [comment]
This is a known limitation. Shadow dom styling is not polyfilled for styles declared in the main document: https://github.com/webcomponents/shadycss#document-level-styling-is-not-scoped-by-default
