### ISSUE TITLE
Property getters identified by Symbol have wrong value of `this` in Microsoft Edge

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/webcomponentsjs#905]
Inside a property getter identified by a `Symbol`, the superclass implementation is undefined.
```
const prop = Symbol('prop');

class ElementA extends HTMLElement {
  get [prop]() {
    return this;
  }
}

class ElementB extends ElementA {
  get [prop]() {
    // This doesn't return the expected value of `this`, but undefined.
    return super[prop];
  }
}
```

See https://codepen.io/JanMiksovsky/pen/YaGqVO?editors=1010.
Works in Chrome, Safari, Firefox, but not in Edge. Tested with webcomponents 1.1.0.

We make heavy use of Symbol-keyed properties in component mixins to avoid accidental property name collisions. Those mixins need to be able to invoke `super` where appropriate so that all mixins on the prototype chain can perform work. This bug is blocking a number of components from working in Edge.

**Comment by justinfagnani** [comment]
How does this behave on plain classes?

**Comment by justinfagnani** [comment]
I think it's a problem with Babel compilation of getters. See this stackblitz which fails for getters: https://stackblitz.com/edit/super-getter-access?file=index.js

When I run the same code directly in Chrome dev tools, it works.

**Comment by JanMiksovsky** [comment]
Hmm, I see this as broken in Edge itself.

https://codepen.io/JanMiksovsky/pen/OvRXXN?editors=0011 works in Chrome, not in Edge. There's no Babel in this picture. Edge just doesn't seem to understand that `super[symbol]` is a thing.

If you concur, I can file an issue with Edge.

**Comment by justinfagnani** [comment]
Seems like bugs all around. I'd definitely file with Edge

**Comment by JanMiksovsky** [comment]
Filed as https://github.com/Microsoft/ChakraCore/issues/4835.

Many thanks for the quick response!
