### ISSUE TITLE
What does "Indicates the current version of the browser" means?

### ISSUE THREAD

**Issue by flawyte** [webcomponents/webcomponentsjs#908]
Everything is in the title.
I often see this indication: `Indicates the current version of the browser` but which version does *current version* refers to? I mean, these polyfills are obviously compatible (or have been tested) with browsers down to a specific version below which they do not work (or haven't been tested on yet). What is this *minimum/oldest version* which they are garantueed to work on? And why not put that version instead? Cause as you know, *current version* varies among time so it's a bit unclear what it's referring to.
Thanks a lot

**Comment by TimvdLippe** [comment]
It means the version that is currently considered the latest stable version. This means that we do not (officially) support older versions of evergreen browser. It is still highly likely they are working, but we simply do not run our test suites on them and therefore can't give the guarantees that they work.

**Comment by flawyte** [comment]
So if I get right :
- Given that X is the latest stable version of Browser A, you run your test suites on this version only (and no other) for this browser
- If a new stable version X+1 gets released, you'll stop running your test suites on version X and will only test on version X+1, updating the polyfill if needed but without checking for compatibility with now old version X

**Comment by TimvdLippe** [comment]
We rely on Travis for this logic (see https://github.com/webcomponents/webcomponentsjs/blob/760912c085b7283b643ef8effb74444675038491/.travis.yml#L6-L11), but yes that seems the gist of it.

**Comment by flawyte** [comment]
Got it, thanks!
