### ISSUE TITLE
p is not defined

### ISSUE THREAD

**Issue by lastmjs** [webcomponents/webcomponentsjs#909]
In `webcomponents-sd-ce.js`, and probably in a few other files (I believe it is the shadow dom polyfill that is causing the issue), the minified version has two instances of the following:

```javascript
p.Object.defineProperties
```

I'm not sure what the `p` is supposed to be, and the browser sees it as undefined. I assume Object.defineProperties is supposed to be the globally available Object.defineProperties. When I just delete the `p`, my code relying on the polyfills works fine.

**Comment by TimvdLippe** [comment]
With what version of the polyfills did this still work and with what version did it start to break?

**Comment by lastmjs** [comment]
I don't know, it's been a while since I've used the polyfills, I did a fresh install today and it broke. To get around it I'm just using the individual polyfills installed under `@webcomponents` on npm

**Comment by abraham** [comment]
I believe I'm running into the the same issue in an Angular app I'm working on.

```
Uncaught TypeError: Cannot read property 'defineProperties' of undefined
    at webcomponents-sd-ce.js:formatted:3019
    at Object.<anonymous> (webcomponents-sd-ce.js:formatted:1)
    at Object../node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js (webcomponents-sd-ce.js:formatted:1)
    at __webpack_require__ (bootstrap:81)
    at Object../src/polyfills.ts (webcomponents-sd-ce.js:formatted:1)
    at __webpack_require__ (bootstrap:81)
    at Object.1 (webcomponents-sd-ce.js:formatted:1)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)
    at Array.webpackJsonpCallback [as push] (bootstrap:30)
```

The error isn't there in v1.0.1 and appears in v1.0.2.

**Comment by abraham** [comment]
Repo steps with Angular 6:

Install the Angular CLI v6.
```
$ npm i -g @angular/cli@6.0.8
/Users/abraham/.nvm/versions/node/v10.4.0/bin/ng -> /Users/abraham/.nvm/versions/node/v10.4.0/lib/node_modules/@angular/cli/bin/ng

+ @angular/cli@6.0.8
added 1 package from 3 contributors, removed 2 packages and updated 10 packages in 11.695s
```

Generate a new Angular app.
```
$ ng new kitten
CREATE kitten/README.md (1023 bytes)
[snip]
added 1184 packages from 1293 contributors and audited 21885 packages in 34.224s
  [snip]
    Successfully initialized git.
```

From within the new `kitten` directory install the WC polyfill.
```
$ npm i @webcomponents/webcomponentsjs@2.0.2
+ @webcomponents/webcomponentsjs@2.0.2
added 1 package from 1 contributor and audited 21886 packages in 8.349s
  [snip]
```

Import WC at the bottom of `src/polyfill.ts`.
```
import '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce';
```

Start the dev server and open [http://localhost:4200](http://localhost:4200) in Chrome (I used 68.0.3440.42).
```
npm start
```

Open the dev tools and you should see

> Uncaught TypeError: Cannot read property 'defineProperties' of undefined
    at Object.<anonymous> (webcomponents-sd-ce.js:151)
    at Object../node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce.js (webcomponents-sd-ce.js:179)
    at __webpack_require__ (bootstrap:76)
    at Object../src/polyfills.ts (polyfills.ts:1)
    at __webpack_require__ (bootstrap:76)
    at Object.1 (polyfills.ts:81)
    at __webpack_require__ (bootstrap:76)
    at checkDeferredModules (bootstrap:43)
    at Array.webpackJsonpCallback [as push] (bootstrap:30)
    at polyfills.js:1

**Comment by abraham** [comment]
Using my [previous repo steps](https://github.com/webcomponents/webcomponentsjs/issues/909#issuecomment-402320128) but using `yarn add` and `yarn start` I get the same error as before.

**Comment by TimvdLippe** [comment]
@abraham As of right now, you are unable to import the polyfills using `import`. You have to use a script tag. This issue is tracked at https://github.com/webcomponents/webcomponentsjs/issues/891

**Comment by TimvdLippe** [comment]
Closing per above comment. For importing the polyfills using `import`, please see #891
