### ISSUE TITLE
SCRIPT445: Object doesn't support this action IE11

### ISSUE THREAD

**Issue by rthadhani** [webcomponents/webcomponentsjs#911]
Hello All,

I am getting this in the minified version of the custome element that I have written.
Included the webcomponentsjs/webcomponents-lite.js

Thanks inadvance
Please help

**Comment by TimvdLippe** [comment]
Could you please give a reproduction case that shows the issue?

**Comment by TimvdLippe** [comment]
Closing per above comment.
