### ISSUE TITLE
Please remove promise polyfill

### ISSUE THREAD

**Issue by askbeka** [webcomponents/webcomponentsjs#913]
Sorry if I am missing something but I don't get why promise polyfill is included in build.

Since webcmoponents-lite includes promise and it being loaded async.
There is not much flexibility for some that want to use promise before webcomponents-lite is loaded. We can include promise-polyfill ourselves but we will end up with two polyfills.

I think webcomponents polyfills should assume promise is there and document that promise polyfill should be loaded before loader. Or promise polyfill should be loaded into its own loader.
The best would be to make whole thing a babel-plugin:)

As an exmaple, I am buidling a tool that will generate me polyfills bundle like core-js, intl and others.
I need this since projects I am working on are stuck with polymer build,  which is not very flexible. Some polyfills like intl polyfill require a step to conditionally load some parts like webcomponents-loader does but I want to use dynamic import for that using webpack or require.ensure, that need promise to be available. So it is only possible after WebcomponentsReady event.

**Comment by TimvdLippe** [comment]
I do not think we can, at this moment in time, remove the polyfill as that would be a major breaking change. I am not aware of any plans to ship a major version update of this polyfill anytime soon.

**Comment by askbeka** [comment]
@TimvdLippe, Thanks for the response.  Can babel-preset-env be used with babel-polyfill? and it will output Promise polyfill if needed. Should not be a breaking change.

Since Promise is part of JavaScript not WebAPI, it feels like to have it separate will be a better idea.

**Comment by TimvdLippe** [comment]
I dont think we support that right now. Will discuss with the others what
the options are, but for now we will keep the state as-is.

**Comment by abraham** [comment]
v2 was released less than a month after this issue was opened. That would have been the perfect chance to make a breaking change.

**Comment by ruphin** [comment]
The v2 release has several bundles, including ones without the platform polyfills (which contain the Promise polyfill). You can choose to load a bundle that only includes the 'Web Components' polyfills.

The list of different bundles can be found here: https://unpkg.com/@webcomponents/webcomponentsjs@2.0.2/bundles/

The bundles are postfixed `ce` for Custom Elements, `sd` for Shadow DOM, and `pf` for Platform.

**Comment by TimvdLippe** [comment]
We have no plans to remove the polyfill from the current bundles. However, we are considering a "bare" bundle, which we are tracking in #1007.
