### ISSUE TITLE
Polyfills problem on Firefox 58

### ISSUE THREAD

**Issue by luan-cestari** [webcomponents/webcomponentsjs#914]
Hi,

I was trying to reproduce the experiments on different browsers and on Linux using Firefox 58.0.2 (even with webcomponents options enabled) some examples doesn't work. For example http://plnkr.co/edit/3Nz8GL?p=preview and http://plnkr.co/edit/KvBnmE?p=preview

Does this problem have some issue related to polyfills ? I tried to reach people from polymer https://github.com/Polymer/docs/issues/2384#issuecomment-379366253 and we thought to open an issue here

Could you help me please?

Thanks

**Comment by djm158** [comment]
I am also seeing issues using HTML imports in Firefox 59.0.2.

**Comment by TimvdLippe** [comment]
This was likely an issue with the HTML Imports polyfill. We have removed that polyfill in v2 of these polyfills and the issue should therefore no longer occur.
