### ISSUE TITLE
Error: Process spawn error.  Is java in the path?

### ISSUE THREAD

**Issue by Sylphony** [webcomponents/webcomponentsjs#915]
I am trying to manually build the polyfill.  After installing the dependencies and running gulp, I get `Error: Process spawn error.  Is java in the path?` when it starts `closurify-hi`.

How do you fix this?

**Comment by TimvdLippe** [comment]
Closure requires Java to be installed on your system. For more information, see https://www.npmjs.com/package/google-closure-compiler#java-version I will add an extra note for this in the README
