### ISSUE TITLE
webcomponents-loader.js + custom-elements-es5-adapter.js + Firefox does not work

### ISSUE THREAD

**Issue by mortenson** [webcomponents/webcomponentsjs#916]
Using webcomponents-loader.js and custom-elements-es5-adapter.js to polyfill ES5 Web Components does not work with Firefox (version 59.0.2), and leads to the error "Constructor HTMLElement requires 'new'".

You can replicate this error by visiting http://jsbin.com/parugeqico/1/edit?html,js,output in a recent Firefox build. Chrome seems to work fine, and if you use webcomponents-lite.js instead that also works. You can uncomment that script tag in the HTML from JSBin to fix components.

**Comment by TimvdLippe** [comment]
This appears to be working now in Firefox: http://jsbin.com/dokofewaye/edit?html,js,console,output
