### ISSUE TITLE
Use the files field in the package.json

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponentsjs#917]
It would be great to send only the necessary files.

> The optional "files" field is an array of file patterns that describes the entries to be included when your package is installed as a dependency. If the files array is omitted, everything except automatically-excluded files will be included in your publish. If you name a folder in the array, then it will also include the files inside that folder (unless they would be ignored by another rule in this section.).

Reference: https://docs.npmjs.com/files/package.json#files

**Comment by TimvdLippe** [comment]
This was fixed in #929
