### ISSUE TITLE
IE11: webcomponents-bundle.js issue with DOM written into main document.

### ISSUE THREAD

**Issue by sorvell** [webcomponents/webcomponentsjs#920]
The pattern shown [here](https://github.com/Polymer/polymer/blob/3.x/test/unit/custom-style.html#L30) doesn't work in IE11.

**Comment by TimvdLippe** [comment]
This issue lacks a description, but I think we tackled this in https://github.com/Polymer/polymer/commit/8b5803c2937aa63dd0a31c64681e8ba0acbf94eb#diff-5ccfdb2810bc155fcc15b5a27ae88be4 and later also fixed the `template` polyfill in https://github.com/webcomponents/template/issues/40
