### ISSUE TITLE
v2: URL.prototype.search/hash are missing from closure compiler output

### ISSUE THREAD

**Issue by keanulee** [webcomponents/webcomponentsjs#921]
We [have elements](https://github.com/PolymerElements/iron-location/blob/23cbb3d/iron-location.html#L410) that use `url.search` and `url.hash` getters, but unlike other getters (e.g. `url.pathname`) the minified output of the URL polyfill does not have these identifiers:

https://github.com/webcomponents/webcomponentsjs/blob/909e43a/webcomponents-bundle.js#L213

Affects browsers that don't have native `URL` (e.g. IE11).

**Comment by azakus** [comment]
Looks like the externs are up to date in the latest closure-compiler, so I'll update that dependency.

**Comment by azakus** [comment]
Well, just updating to latest seemed to break the Promise polyfill somehow, so I'll try to backport the URL externs for now and fix that later.

**Comment by azakus** [comment]
Wow, this is much more broken than missing externs, which actually exist in the used version of closure compiler. It looks like closure is just eliminating those getters and setters no matter what.

**Comment by azakus** [comment]
OK, found a hack that will work by saying that the URL polyfill `@implements {URL}`

**Comment by azakus** [comment]
Fixed with 2.0.0-beta.2
