### ISSUE TITLE
removedCallback not called when deleting pixi-js from Sandbox

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#94]
<a href="https://github.com/sjmiles"><img src="https://avatars.githubusercontent.com/u/98045?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sjmiles](https://github.com/sjmiles)**
_Thursday May 02, 2013 at 02:15 GMT_
_Originally opened as https://github.com/Polymer/CustomElements/issues/22_

----

**Comment by garlicnation** [comment]
@sjmiles Closing. I can investigate further if you provide a reduced test case.
