### ISSUE TITLE
Add missing elementFromPoint / elementsFromPoint API

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/webcomponentsjs#945]
We're trying to use `shadowRoot.elementsFromPoint` and notice that it's missing from the polyfill. The `elementFromPoint` and `elementsFromPoint` calls are [speced](https://w3c.github.io/webcomponents/spec/shadow/#extensions-to-the-documentorshadowroot-mixin) and implemented in Chrome and Safari.

We're able to make do by simply detecting the absence of these calls on the shadow root, and falling back to `document.elementsFromPoint`. It'd be nice if the polyfill could handle that, and define `ShadyRoot` members that act as aliases for the corresponding methods on `document`.

**Comment by web-padawan** [comment]
Duplicate of webcomponents/shadydom#141

**Comment by JanMiksovsky** [comment]
Thank you.
