### ISSUE TITLE
sourcemaps point to incorrect paths

### ISSUE THREAD

**Issue by coreyfarrell** [webcomponents/webcomponentsjs#947]
sourcemaps in this repo point to incorrect paths in `sources`.  For example the first source mentioned webcomponents-ce.js.map is `"node_modules/@webcomponents/custom-elements/src/Utilities.js"`.  This is incorrect, it should say `"../component-elements/src/Utilities.js"`.  In theory this could be fixed with the `sourcemaps.mapSources` function.  I'm unable to submit a PR as I cannot get 'npm run build' to work on my system (even without making any change).

**Comment by TimvdLippe** [comment]
I think the root issue is that the individual polyfills are not shipped together on this repo. The files therefore link to files that do not exist at all, no matter if you reference them as `../` or as `node_modules`. Not sure how to resolve that situation, other than making the polyfills dependencies and lock their version to make sure the sourcemap references remain valid, even across version upgrades.

**Comment by TimvdLippe** [comment]
@coreyfarrell Thanks for the extensive explanation, the problem is now clear to me! PR up at #954
