### ISSUE TITLE
cdnjs is broken

### ISSUE THREAD

**Issue by ruphin** [webcomponents/webcomponentsjs#953]
CDNJS is missing the `/bundles/` folder introduced in the 2.0 release.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.0.2/webcomponents-loader.js"></script>
```

will cause the following error on a browser that needs to load some polyfills:

```
Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.0.2/bundles/webcomponents-sd-ce.js”.
```

Looking at the [cdnjs page](https://cdnjs.com/libraries/webcomponentsjs) the files are indeed missing.

**Comment by TimvdLippe** [comment]
We do not own cdnjs, so I am not sure what we can do. In our README we point to unpkg which does work: https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/

**Comment by ruphin** [comment]
As far as I know cdnjs is updated by package owners. Someone who owns webcomponentsjs should have the ability to create a pull request to update what files they host.

I didn't think about using unpkg, thanks for the tip :)

**Comment by ruphin** [comment]
Great, I will submit a PR to cdnjs to have it fixed. :)
