### ISSUE TITLE
Ability to use with other javascript frameworks

### ISSUE THREAD

**Issue by amodi00** [webcomponents/webcomponentsjs#956]
Hello,
Is there a way we use this loader to create web components in non-Angular platforms like jQuery, SAPUI5, ExtJS and so on and without using npm?

**Comment by TimvdLippe** [comment]
You can use web components in any context :smile: If you do not want to use npm you can use a CDN like https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/

**Comment by amodi00** [comment]
I am sorry I did not find any examples with webcomponentsjs where angular was not used, hence the question. Any links or documentation will be helpful.
Thanks!
