### ISSUE TITLE
Why the MutationObserver polyfill has been removed?

### ISSUE THREAD

**Issue by thexpand** [webcomponents/webcomponentsjs#959]
It seems that the polyfill has been removed, thus dropping IE9 and IE10 support.
Why would you do that?
https://github.com/webcomponents/webcomponentsjs/commit/ab21a42c01d471bd35c1306f91f6e28cc6c70421

**Comment by TimvdLippe** [comment]
We no longer support IE9 and IE10. We do support IE11. In general, we support the latest version of a browser. You can of course add the polyfill manually yourself to get that support.

**Comment by thexpand** [comment]
@TimvdLippe How am I supposed to add the polyfill?

**Comment by thexpand** [comment]
I ended up using this one: https://github.com/webmodules/mutation-observer
I have tested it down to IE10 and it works fine. Given the fact that these versions of IE are dying slowly and painfully, one happy sunny day this polyfill and many like it will server no purpose.
