### ISSUE TITLE
Element.prototype.querySelectorAll returns Array instead of NodeList in Firefox 61

### ISSUE THREAD

**Issue by Gugic** [webcomponents/webcomponentsjs#967]
Here is the simple jsbin:
http://jsbin.com/hoyecowadu/2/edit?html,console,output

In chrome console output will have NodeList (which is correct according to standards: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll). However in Firefox 61 (ubuntu linux/macos x) it will be simple Array of HtmlElement's

Removing of webcomponents-loader.js from page will make Firefox produce correct results (NodeList)

**Comment by TimvdLippe** [comment]
This is an issue in shadydom: http://jsbin.com/qavaxenoxu/1/edit?html,console,output (you can comment the shadydom force to see the difference)

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadydom#254
