### ISSUE TITLE
Question about waitFor loader + webpack + polymer 3

### ISSUE THREAD

**Issue by quetzalsly** [webcomponents/webcomponentsjs#971]
I am a bit confused as how to use this little bit of code to bootload webcomponents with webpack and polymer 3. I am just trying to get it to work with the polymer shop demo code. I am pretty sure I am doing this wrong, should waitfor be loading all the code in my project? should I be using async and await? should I return await or just return without await. What is most efficient? Would really appreciate some guidance :)

I have something like this:

```
WebComponents.waitFor(async () =>
{
  await import(/* webpackMode: 'lazy' */ './actions/categories.js');
  await import(/* webpackMode: 'lazy' */ './components/shop-list-item.js');
  await import(/* webpackMode: 'lazy' */ './reducers/categories.js');

         await import(/* webpackMode: 'lazy' */ './cart.js');
  return await import(/* webpackMode: 'lazy' */ './store.js');
});
```

**Comment by web-padawan** [comment]
See https://github.com/web-padawan/polymer3-webpack-starter

In short, I recommend using dynamic imports for code splitting per route, as demonstrated in that repo.

**Comment by TimvdLippe** [comment]
@quetzalsly Thanks for your question. I think https://github.com/web-padawan/polymer3-webpack-starter is a great example project on how to organize your application. Feel free to take any advice from there :smile:
