### ISSUE TITLE
Trace viewer not working with v1 polyfills

### ISSUE THREAD

**Issue by agnjunio** [webcomponents/webcomponentsjs#974]
I'm trying to use [catapult's trace viewer](https://github.com/catapult-project/catapult/tree/master/tracing) into my project, which a project that makes hevy use of html imports, shadow dom and custom elements.
Since v2 is not supporting HTML imports anymore, i'm trying to use the wc-v1 tag (1.2.3), but I'm getting the following error:

```
TypeError: document.registerElement is not a function[Learn More] data:
<anonymous> http://localhost:8080/trace_viewer_full.html.js:46:186
<anonymous> http://localhost:8080/trace_viewer_full.html.js:44:123
``` 

I tested it with the `node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js` version and tried to import a big html with `<template>`s, `<dom-module>`s and scripts

I can work on a demo later if more information is needed.
![screenshot from 2018-07-23 11 30 29](https://user-images.githubusercontent.com/13356774/43086692-f8f591c8-8e6b-11e8-8b3e-e6d117496f45.png)

**Comment by TimvdLippe** [comment]
Document.registerelement is the v0 customelements API. They need to update to the v1 API: `customelements.define`
