### ISSUE TITLE
Switch 1.0 to taylorhakes promise polyfill

### ISSUE THREAD

**Issue by aomarks** [webcomponents/webcomponentsjs#975]
We're currently bundling https://github.com/stefanpenner/es6-promise for our Promise polyfill in webcomponents js 1.0, but https://github.com/taylorhakes/promise-polyfill seems to be smaller, and is what we previously used for our now deprecated https://github.com/PolymerLabs/promise-polyfill fork.

**Comment by TimvdLippe** [comment]
@aomarks We have recently switched to that polyfill: https://github.com/webcomponents/webcomponentsjs/blob/master/package.json#L52 and https://github.com/webcomponents/webcomponentsjs/commit/97b6f63d7930aaf59e5ffa3a0825a3e43baf727d Did we miss something?

**Comment by azakus** [comment]
Fixed with #977
