### ISSUE TITLE
webcomponents-bundle.js error in IE 11 ('Reflect' is undefined)

### ISSUE THREAD

**Issue by shystruk** [webcomponents/webcomponentsjs#976]
Hi,

Running "node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js" in IE 11 cause an error.

![image](https://user-images.githubusercontent.com/5999543/43601402-e931e6fa-9641-11e8-9348-ed722a2f7d46.png)

Does someone know how to run webcomponents in IE 11?

Thanks

**Comment by shystruk** [comment]
Webpack with babel-polyfill helps to solve this issue 👍 
vendor: ["babel-polyfill", `${PATHS.modules}/@webcomponents/webcomponentsjs/webcomponents-bundle.js`]

**Comment by alex-ju** [comment]
`babel-polyfill` solves it, but I consider this is still an issue as it should work out of the box
