### ISSUE TITLE
detect "missing" this.super() calls

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponentsjs#98]
<a href="https://github.com/Pomax"><img src="https://avatars.githubusercontent.com/u/177243?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Pomax](https://github.com/Pomax)**
_Tuesday Sep 02, 2014 at 20:01 GMT_
_Originally opened as https://github.com/Polymer/CustomElements/issues/128_

----

I don't think Polymer currently supports this, but we've found that letting people create extending elements (`<polymer-element name="..." extends="...">`) while also letting them define their own `.ready`, `.attached`, `.domReady` etc functions will frequently leave them forgetting to add the crucial `this.super()` calls in their overrides. It would be quite useful if Polymer was able to fire an event or have some other function that could be tapped into to detect when extending custom elements are being loaded that have overrides that do not call `this.super()`, thus potentially ending up isolated from the code they're saying they're extending. The detection is relatively straightforward (a `prot.ready.toString().indexOf("this.super") === -1` will generally be enough) and would make component authoring, and custom component loading, a little more robust

**Comment by garlicnation** [comment]
Extension of custom elements is provided by Polymer, not the polyfills. You should re-file this under Polymer/polymer for consideration.
