### ISSUE TITLE
v2 published to bower does not work

### ISSUE THREAD

**Issue by LarsDenBakker** [webcomponents/webcomponentsjs#980]
We want to use the v2 polyfill, but are still on bower. Unfortunately the bower version does not work, as it tries to import file from 'bundles' which don't exist in the bower distribution.

**Comment by TimvdLippe** [comment]
This was an intentional change in #944 We no longer explicitly publish to `bower`, with the removal of `bundles` as a side-effect. I think maintaining a fork with the checked in bundles in the repository is the best option?

**Comment by TimvdLippe** [comment]
Closing per above comment.
