### ISSUE TITLE
Firefox - WebcomponentsJs breaks angular 6 [(ngModel)]

### ISSUE THREAD

**Issue by davidrot** [webcomponents/webcomponentsjs#981]
Hello,

I noticed, when I import the webcomponents-lite.js to my angular 6 project the [(ngModel)] is not working in Firefox anymore. 

Example:

import webcomponents-lite.js (Version 1.2.3)
https://stackblitz.com/edit/angular-2way-ngmodel-w-lite?file=app%2Fapp.component.ts

import webcomponents-bundle.js (Version 2.0.2)
https://stackblitz.com/edit/angular-2way-ngmodel-w-bundle?file=app/app.component.ts

These are the versions I have tested:

```
Windows 10
Windows 10 & Firefox 58.0.0 (32 bit)
Windows 10 & Mac & Firefox 61.0.2 (64 bit)

@angular/forms 6.1.2

webcomponents-lite.js 1.2.3
webcomponents-bundle.js 2.0.2
```

**Comment by snajo** [comment]
+1

**Comment by ali-nr** [comment]
I'm facing this issue on angular 1.5, my forms don't show at all. Did anyone find a solution to this?

**Comment by snajo** [comment]
https://github.com/angular/zone.js/issues/782

**Comment by TimvdLippe** [comment]
This appears to be resolved per https://github.com/angular/zone.js/issues/782#issuecomment-421100689 I fear that any other updates would require updates on the Angular side. If anyone would be able to create a reproduction case without Angular (e.g. just the polyfills) that is broken, please open a new issue on this repo and we can fix it!
