### ISSUE TITLE
v1.2.5 breaks styling element without shadow dom

### ISSUE THREAD

**Issue by LarsDenBakker** [webcomponents/webcomponentsjs#985]
For performance optimizations, we build some of our polymer elements without shadow dom. These elements export styles which are implemented in the parent's shadow root. For example (pseudocode): 

```
<parent-element>
  #shadowroot
    <style>...parent styles...</style>
    <style>...child styles...</style>

    <child-element>
      <!-- child-element's dom rendered to light dom -->
    </child-element>
</parent-element>
```

Styles inside the child-styles tag are prefixed with child-element, for example:

```
child-element .foo {

}

child-element .bar {

}
```

This works perfectly fine with native shadow dom, and used to work with webcomponentjs polyfill until v1.2.5. On After 1.2.5 it stopped working, because while before the rendered dom look liked this:

```
<parent-element>
    <child-element class="style-scope parent-element">
      <div class="style-scope parent-element child-element"></div>
    </child-element>
</parent-element>
```

but now, it looks like this:

```
<parent-element>
    <child-element class="style-scope parent-element">
      <div class="style-scope child-element"></div>
    </child-element>
</parent-element>
```

It fails because the child-element styles are scoped to the parent-element:
```
  child-element.foo.parent-element {
   
  }

  child-element.bar.parent-element {
   
  }
```

I think the behavior of 1.2.4 was correct, the child-element's content is inside the scope of the parent-element.

**Comment by LarsDenBakker** [comment]
This is a minimal reproduction of the issue: https://jsbin.com/fujijikefi/5/edit?html,css,js,output

It has the correct behavior there, I think 1.2.5 is not available on polygit yet?

**Comment by TimvdLippe** [comment]
I think the culprit is https://github.com/webcomponents/shadycss/pull/176 @LarsDenBakker do you mind adding a test to shadycss and potentially fix the logic in there?

**Comment by LarsDenBakker** [comment]
I will add a test. I have never worked on shady css before, but I will see what I can do.

**Comment by LarsDenBakker** [comment]
I've been working on tests, but I cannot reproduce this issue with vanilla web components. Will dig into it further.

**Comment by LarsDenBakker** [comment]
I did some further digging, and I cannot reproduce using the latest version of polymer and webcomponentjs. So either it didn't work in that specific version, or something was wrong on my end. Either way I'll consider this issue closed

**Comment by TimvdLippe** [comment]
Awesome, thanks for confirming!
