### ISSUE TITLE
Defining window.WebComponents.root causes a script error with call to _batchCustomElements

### ISSUE THREAD

**Issue by jhorback** [webcomponents/webcomponentsjs#991]
The _bachCustomElements function never gets defined if window.WebComponents.root is define.

The culprit:
window.WebComponents = window.WebComponents || {
    ready: false,
    _batchCustomElements: batchCustomElements,
    waitFor: function(waitFn) {
      if (!waitFn) {
        return;
      }
      whenLoadedFns.push(waitFn);
      if (polyfillsLoaded) {
        runWhenLoadedFns();
      }
    }
  };

**Comment by TimvdLippe** [comment]
Oops, thanks for the issue! PR up with a fix in #992
