### ISSUE TITLE
iterator polyfill is causing runtime error

### ISSUE THREAD

**Issue by newyork-anthonyng** [webcomponents/webcomponentsjs#996]
The [iterator polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/Symbol/iterator/polyfill.js) is getting imported [in the symbol.js file](https://github.com/webcomponents/webcomponentsjs/blob/08ca94151cf660831ee3004560b513b5a86eb27a/src/symbol.js#L14).

It is causing the error below:
```
Uncaught TypeError: Cannot redefine property: iterator
```

The [iterator polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/Symbol/iterator/polyfill.js) doesn't check if `Symbol.iterator` already exists. Should we use the [iterator detect](https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/Symbol/iterator/detect.js) to check if the `Symbol.iterator` polyfill is needed?

**Comment by newyork-anthonyng** [comment]
I was bundling `webcomponentsjs` with my code in webpack.

This was causing the error. After removing `webcomponentsjs` from my bundled code, it was working 👍

**Comment by andrewkfiedler** [comment]
Where did you end up bundling webcomponents instead?

**Comment by newyork-anthonyng** [comment]
@andrewkfiedler I included it in the `html` file instead, before the bundled code.

```html
```

**Comment by tirithen** [comment]
I'm having the same problems with webpack build, loading page in Firefox.

Webpack entries (building webcomponents separately):

    entry: {
      app: './index.js',
      webcomponents: './node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js'
    },

**Comment by TimvdLippe** [comment]
This should now be fixed with #1005. Note that you should not bundle the polyfills in your WebPack bundle (see #891 for more info). You can inline the loader if you want to and use the [`root` option](https://github.com/webcomponents/webcomponentsjs#inlining) to tell the loader where your bundles are on the filesystem.
