### ISSUE TITLE
When I use webcomponents-bundle.js, my style tag's id disappeared

### ISSUE THREAD

**Issue by SoloJiang** [webcomponents/webcomponentsjs#999]
### The cause of the bug

My code is:
```html
<dom-module id="a-input">
  <template>
    <style id="style"></style>
      </template>
</dom-module>
<script>
  import { PolymerElement } from 'Element';
  export default class Input extends PolymerElement {
    ready() {
      super.ready();
      this.$.style.innerHTML = `...`
    }
  } 
</script>
```
### Process
However, it throws an error, this.$.style is undefined; When I look at the element rendering, I found the style tag's id disappeared;
### Platform
PC is normal, but there is a problem with the phone. My iphone is ios11.4.

**Comment by SoloJiang** [comment]
...My mistake. PC is normal, because I did not introduce this file on the PC.

**Comment by TimvdLippe** [comment]
Glad you were able to solve your problem :smile:

**Comment by SoloJiang** [comment]
No, I haven't solved the problem, I mean my PC is ok because I only loaded this file on the mobile side.

**Comment by web-padawan** [comment]
@SoloJiang please note that the ShadyDOM polyfill removes the actual `<style>` tags from the DOM and moves the processed styles into the document head, so it is by design.
